### ISSUE TITLE
My IOT gateway is failing to renew LetsEncrypt cert, with "unexpected error: Deserialization error: The following field are required: new_authzr_uri. Skipping."

### ISSUE THREAD

**Issue by dholbert** [mozilla-iot/gateway#1007]
Ever since April 9th[1], it seems my gateway's LetsEncrypt cert renewals have been failing, with error output saying `WARNING:certbot.renewal:Attempting to renew cert from /home/pi/mozilla-iot/etc/renewal/eagle.mozilla-iot.org.conf produced an unexpected error: Deserialization error: The following field are required: new_authzr_uri. Skipping.`  I'm only just noticing this failure this past week, because my last successfully acquired cert has now expired which means I can't access my gateway without SSL-error-page-clickthrough hacks.

Here's a bit more context around that error, from `var/log/letsencrypt.log`, from the first log where this happened:
````2018-04-09 00:00:40,177:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.webroot.Authenticator object at 0x73bd97d0> and installer None
2018-04-09 00:00:40,181:WARNING:certbot.renewal:Attempting to renew cert from /home/pi/mozilla-iot/etc/renewal/eagle.mozilla-iot.org.conf produced an unexpected error: Deserialization error: The following field are required: new_authzr_uri. Skipping.
2018-04-09 00:00:40,194:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/certbot/renewal.py", line 413, in handle_renewal_request
    main.obtain_cert(lineage_config, plugins, renewal_candidate)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 621, in obtain_cert
    le_client = _init_le_client(config, auth, installer)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 399, in _init_le_client
    acc, acme = _determine_account(config)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 360, in _determine_account
    acc = account_storage.load(config.account)
  File "/usr/lib/python2.7/dist-packages/certbot/account.py", line 174, in load
    regr = messages.RegistrationResource.json_loads(regr_file.read())
  File "/usr/lib/python2.7/dist-packages/acme/jose/interfaces.py", line 180, in json_loads
    return cls.from_json(loads)
  File "/usr/lib/python2.7/dist-packages/acme/jose/json_util.py", line 293, in from_json
    return cls(**cls.fields_from_json(jobj))
  File "/usr/lib/python2.7/dist-packages/acme/jose/json_util.py", line 276, in fields_from_json
    cls._check_required(jobj)
  File "/usr/lib/python2.7/dist-packages/acme/jose/json_util.py", line 271, in _check_required
    ','.join(missing)))
DeserializationError: Deserialization error: The following field are required: new_authzr_uri

2018-04-09 00:00:40,195:DEBUG:certbot.main:Exiting abnormally:
````

[1] (For a large chunk of the time since April 9th, my gateway's LetsEncrypt renewals were actually failing due to a more-proximal issue, #1003, but now that issue's been fixed in trunk and I've hacked around it with local edits, so my gateway is now back to failing renewal due to this issue here.)

**Comment by dholbert** [comment]
My (failing) letsencrypt renewal log from today is exactly the same as the 04-09 one that I quoted above, BTW, aside from different timestamps.

This is a gateway that I installed at version 0.3.0 and have updated since then.  It's currently at version 0.4.0.  I haven't manually messed with any files on the system (except for a very recent tweak to work around #1003 ).

I did find some reports of other people running into this issue with their own LetsEncrypt setups:
https://community.letsencrypt.org/t/python-deserialization-error-on-temporary-webserver/9300
https://community.letsencrypt.org/t/deserializationerror/18002/2

In both those cases, it sounded like there was some sort of mysterious corruption involved in the `regr.json` file, resulting in this field being unexpectedly missing there. I can confirm that the field is missing from my `.mozilla-iot/etc/accounts/acme-v01.api.letsencrypt.org/directory/[long-id]/regr.json` file, but the file isn't obviously corrupted besides that json field being missing...

Anyway, I might try backing up & deleting that json file and seeing what happens when my gateway renews tonight...

**Comment by dholbert** [comment]
OK, I found the `mozilla-iot/gateway/tools/renew-certificates.sh` script which seems to be the way to manually trigger cert renewal. Sadly, it seems that renewal script complains if I delete any of the JSON files (I started by deleting the `regr.json` file that's missing the field in question here, but that makes the script complain that the file is missing).

@mrstegeman, I'm guessing maybe you might know what I should do here and/or what might be going wrong, since you implemented the cert renewal system... Is there a straightforward way that I can get back to a good state? (e.g. by manually clobbering my LetsEncrypt state and registering new certs, or by fixing my `regr.json` file somehow)

**Comment by mrstegeman** [comment]
@dholbert I just grepped through my brand new certbot configs and such and I don't see `new_authzr_uri` anywhere.

What certbot version are you using? I'm on 0.23.0.
```bash
certbot --version
```

If you can't get it resolved, you could wipe out your certs and such, then re-register your domain:
```bash
rm -rf ~/.mozilla-iot/etc
rm -rf ~/.mozilla-iot/var
rm -rf ~/.mozilla-iot/ssl
sqlite3 ~/.mozilla-iot/config/db.sqlite3 'DELETE FROM settings WHERE key = "tunneltoken"'
```

After doing this, restart the gateway and you should be presented with the domain registration form. If you input the same email address and domain as before, you should be able to re-register.

**Comment by mrstegeman** [comment]
Yeah, 0.23.0 is on my Mac via Homebrew, as I don't have access to my RPi this week. I believe 0.10.2 is the latest version available in the Raspbian repos.

I will try to dig into this in the morning and see if I can find anything.

**Comment by dholbert** [comment]
Thanks!

**Comment by mrstegeman** [comment]
@dholbert Can you try adding the following field to `regr.json` at the same level as `uri`, please?

```json
"new_authzr_uri": "https://acme-v01.api.letsencrypt.org/acme/new-authz"
```

**Comment by dholbert** [comment]
That got me further! I end up with the following output from `renew_certificates.sh` now (I'm redacting a long random-looking token in the acme-challenge URL, for paranoia/security):
````
$ bash mozilla-iot/gateway/tools/renew-certificates.sh 
Saving debug log to /home/pi/.mozilla-iot/var/log/letsencrypt.log

-------------------------------------------------------------------------------
Processing /home/pi/.mozilla-iot/etc/renewal/eagle.mozilla-iot.org.conf
-------------------------------------------------------------------------------
updating legacy http01_port value
Cert is due for renewal, auto-renewing...
Renewing an existing certificate
Performing the following challenges:
http-01 challenge for eagle.mozilla-iot.org
Waiting for verification...
Cleaning up challenges
Attempting to renew cert from /home/pi/.mozilla-iot/etc/renewal/eagle.mozilla-iot.org.conf produced an unexpected error: Failed authorization procedure. eagle.mozilla-iot.org (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://eagle.mozilla-iot.org/.well-known/acme-challenge/$REDACTED_TOKEN: "<!DOCTYPE html>
<!-- This Source Code Form is subject to the terms of the Mozilla Public
   - License, v. 2.0. If a copy of the ". Skipping.

All renewal attempts failed. The following certs could not be renewed:
  /home/pi/.mozilla-iot/etc/live/eagle.mozilla-iot.org/fullchain.pem (failure)
1 renew failure(s), 0 parse failure(s)

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: eagle.mozilla-iot.org
   Type:   unauthorized
   Detail: Invalid response from
   http://eagle.mozilla-iot.org/.well-known/acme-challenge/$REDACTED_TOKEN:
   "<!DOCTYPE html>
   <!-- This Source Code Form is subject to the terms of the Mozilla
   Public
      - License, v. 2.0. If a copy of the "

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address.
````

**Comment by dholbert** [comment]
If I run `renew_certificates.sh` again, I get the same output with a different random `$REDACTED_TOKEN`.

If I load the acme-challenge/$REDACTED_TOKEN url in a fresh Firefox profile (to simulate LetsEncrypt loading that URL) and I click through the Firefox cert-expired error page), I end up just looking at a login page for my gateway. I think that's the page whose HTML is partially dumped in the quoted output above.

**Comment by mrstegeman** [comment]
Ok, I see where this problem is. This was apparently broken a little while ago. Working on it...

**Comment by dholbert** [comment]
(It wasn't *just* the conf file -- I did still need the manual `new_authzr_uri` JSON hack that you provided to get this far, as evidenced by the fact that I was getting this failure in letsencrypt logs a month before I ever touched my .conf file.) 

Here's my success output:
````
$ bash mozilla-iot/gateway/tools/renew-certificates.sh 
Saving debug log to /home/pi/.mozilla-iot/var/log/letsencrypt.log

-------------------------------------------------------------------------------
Processing /home/pi/.mozilla-iot/etc/renewal/eagle.mozilla-iot.org.conf
-------------------------------------------------------------------------------
updating legacy http01_port value
Cert is due for renewal, auto-renewing...
Renewing an existing certificate
Performing the following challenges:
http-01 challenge for eagle.mozilla-iot.org
Waiting for verification...
Cleaning up challenges
Generating key (2048 bits): /home/pi/.mozilla-iot/etc/keys/0000_key-certbot.pem
Creating CSR: /home/pi/.mozilla-iot/etc/csr/0000_csr-certbot.pem
Running renew-hook command: /home/pi/mozilla-iot/gateway/tools/deploy-certificates.sh
Hook command "/home/pi/mozilla-iot/gateway/tools/deploy-certificates.sh" returned error code 1
Error output from deploy-certificates.sh:
Failed to restart mozilla-iot-gateway.service: The name org.freedesktop.PolicyKit1 was not provided by any .service files
See system logs and 'systemctl status mozilla-iot-gateway.service' for details.


-------------------------------------------------------------------------------
new certificate deployed without reload, fullchain is
/home/pi/.mozilla-iot/etc/live/eagle.mozilla-iot.org/fullchain.pem
-------------------------------------------------------------------------------

Congratulations, all renewals succeeded. The following certs have been renewed:
  /home/pi/.mozilla-iot/etc/live/eagle.mozilla-iot.org/fullchain.pem (success)
````

**Comment by mrstegeman** [comment]
Beautiful! I've got a PR open for the Let's Encrypt library we use to fix the `regr.json` issue, so that should be taken care of soon.

**Comment by mrstegeman** [comment]
This is pending the merge and release of the following: https://git.coolaj86.com/coolaj86/le-store-certbot.js/pulls/1

**Comment by dholbert** [comment]
Thanks! For the record, it looks like the certs I ended up generating via the renewal here are triggering a misconfiguration issue around support/lack-of-support for OCSP stapling -- I filed #1008 on that.
