### ISSUE TITLE
My IOT gateway produces SSL error pages in Firefox, due to generating a cert that supports OCSP must staple, but failing to staple OCSP response

### ISSUE THREAD

**Issue by dholbert** [mozilla-iot/gateway#1008]
I've run into a series of cert renewal issues with my gateway, which I've mostly worked around with help from mozilla-iot devs (thanks!) -- specificlaly #1003 and #1007. Now I've got a renewed cert, but that renewed cert produces an SSL error page in Firefox (not Chrome or Safari, interestingly).

Specifically, Firefox now gives me a "Secure Connection Failed" page with:
````
An error occurred during a connection to eagle.mozilla-iot.org. A required TLS feature is missing. Error code: MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING
````

Some googling got me to https://bugzilla.mozilla.org/show_bug.cgi?id=1278041#c12 which prompted me to run SSL Labs, and indeed, that gives me this warning:
> This server certificate supports OCSP must staple but OCSP response is not stapled
> [...]
> OCSP Must Staple | Supported, OCSP response not stapled

@mrstegeman ran his [working] gateway through SSL Labs, and his says:
> OCSP Must Staple: No

So it seems my gateway has been opted in [perhaps from apt-get dist-upgrade?] to a cert with this new SSL feature, which it then cannot fully deliver on. :(

I can work around this in my Firefox client by toggling security.ssl.enable_ocsp_must_staple to false, BTW.

**Comment by dholbert** [comment]
FWIW, `certbot --version` gives me `certbot 0.10.2`.

I don't know what certbot version this device originally had, but as a shot in the dark, I'm guessing that *maybe* I updated certbot when doing a "apt-get update && apt-get upgrade" at some point, and that this hypothetical update may've been the cause of both #1007 as well as the fact that my certs now say stapling is supported.

If anyone else has a functional gateway handy via SSH and could test their certbot version and report it here (and run https://www.ssllabs.com/ssltest/analyze.html on their site to check OCSP must-staple support), that would be useful to test this theory!

**Comment by mrstegeman** [comment]
PR: https://git.coolaj86.com/coolaj86/le-store-certbot.js/pulls/2

**Comment by dholbert** [comment]
I confirmed that making that change (from @mrstegeman's PR above) locally -- and regenerating certs and rebooting my gateway -- was sufficient to get this working (it gets me new certs that didn't have this issue).
