### ISSUE TITLE
API Authentication

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#102]
As a user I would like the API of my gateway to be authenticated so that only authenticated users can consume it.

Authenticate API calls (e.g. using JSON Web Tokens).

**Comment by lightsofapollo** [comment]
After refreshing my memory about JWT I came up with the following:

The JWT will be issued in the successful login message. The token itself must then be used for all other API calls by placing it in the `Authorization:` header. (Let's leave token management fuzzy for now).

Our JWT is created with an asymmetric encryption algorithm (ES256). The server implementation should take extra care to _discard_ the private key after the JWT is signed. Discarding the private key limits the server to attacks where the data may be leaked but we retain control over the server (i.e. an attacker will not have a valid private key to craft infinite valid JWT tokens).

**Comment by lightsofapollo** [comment]
We totally did this yay.
