### ISSUE TITLE
Support for non-XBee Zigbee dongles

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1042]
On Twitter @asciidisco [expressed](https://twitter.com/asciidisco/status/1001068346996088832) an interest in implementing support for non-XBee Zigbee dongles and more Zigbee clusters.

I suggest discussing with @dhylands. Could be a separate adapter, or an enhancement/refactoring of the current adapter. I know Dave has also previously expressed an interest in re-writing some adapters in Rust!

**Comment by dhylands** [comment]
Provided we can get access to the actual frames, then I suspect that adapting the current adapter would be fairly straight forward.

The AT commands (which are used for configuration of the dongle) are most likely Digi specific.
https://github.com/mozilla-iot/zigbee-adapter/blob/5d9dfefb5728b03889bfd554614a7d3d68bf420d/zb-adapter.js#L204-L222

There are a very small number of places where the actual xbee-api library is used. Even using a different adapter, I think we can still use the xbee-api for doing the frame parsing/making.

**Comment by asciidisco** [comment]
I´d personally like the idea of splitting the adapter into a "core ZigBee" adapter and additional modules/adapters per USB-Stick (or to be more specific, Chip/Firmware combinations).

In Europe, I think we have four other options (aside from the XBee), which unfortunately are very different on the API side of things:

There´s the [Telegesis ETRX3](https://www.silabs.com/products/wireless/mesh-networking/telegesis-modules-gateways/etrx3-zigbee-usb-sticks) which uses an AT command set quite similar to the XBee. Unfortunately it is as pricy & hard to get/buy (from a customers perspective) as the XBee. There´s a commercial version the [Qivicon USB Stick](https://www.amazon.de/Telekom-Smart-Zig-Bee-Home-Base-40291347/dp/B015TCBZIE), which is quite cheap & can be bought from Amazon, but there are no Windows and OSX drivers.

Then there are the [Silicon Labs Ember chip based](http://www.bitronvideo.eu/index.php/produkte/smart-home-produkte/zb-funkstick/) ones, which don't offer an AT style API, are cheap & easy to buy as well, but also suffer from the problem of no OSX & Windows drivers.

Also, there are the quite cheap (seen them for less than $10) [Texas Instruments CC253x](http://www.ti.com/tool/CC2531EMK) based USB sticks. They mostly suffer from the problem that they not come with a pre flashed firmware, which leads to the problem that you also need to buy the CC-Debugger and flash them yourself. No AT command API, but at least there´s somme very good API documentation out there.

Last but not least, there´s the [Dresden Elektronik Conbee](https://www.dresden-elektronik.de/conbee/), which has drivers for all platforms, comes with pre-flashed firmware, is cheap & easy to get from Amazon, but doesn't offer a public API documentation. At least I haven't found one.

I´ve also heard about ZigBee & Z-Wave combi sticks, produced for the US market [liek this one](https://www.gatehousesupplies.com/ProductDetails.asp?ProductCode=HUSBZB-1&click=2&gclid=Cj0KCQjw3v3YBRCOARIsAPkLbK42Zbb_GkpXlF6C4A61tjjCcE7r8zyIld4_mtJR-A7qYW9CVvc-h9caAp5xEALw_wcB), but I wasn't able to get my hands on one of these.

Based on this fragmented ecosystem, I just thought that it might be a good idea to separate things on a repo/adapter level & only install what is needed on the users gateway.

**Comment by dhylands** [comment]
I'd definitely like to add support for more Zigbee dongles, and it shouldn't be too difficult to split the code into core/transport layers.

I'd like to add support for the Raspbee, and have one, just haven't had time to play with it.

On the Digi device we only use the AT commands for doing some of the dongle configuration. After that, we only send/receive zigbee frames using transparent mode with the dongle.

**Comment by asciidisco** [comment]
I do have access to everything except the raspbee (and a wide range of ZigBee devices) & implemented some other home automation protocols in the past, so I’m really happy to help.

**Comment by mrstegeman** [comment]
Moved: mozilla-iot/zigbee-adapter#40
