### ISSUE TITLE
Unchecking local access checkbox should disable mDNS

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1050]
STR:
* Load Domain Settings
* Untick "Local Access" checkbox

Expected:
* mDNS is immediately disabled

Actual:
* If you reload the page the check box is checked again, you actually need to click the "Update host name" button in order for the setting to take effect.

I understand why it was implemented this way (essentially like submitting a form for both settings), but this is inconsistent with other settings in the UI which change immediately when checking a box and the button specifically says "update host name", not "update settings".

It would also be nice to disable the text input and button when the checkbox is unchecked, but that could be a separate issue.

**Comment by nherriot** [comment]
Would you like me to look at this?

**Comment by mrstegeman** [comment]
@nherriot I've almost got it worked out. Feel free to check out #82, #1051, or #1052, though!
