### ISSUE TITLE
Move "Create new local authorization" from "Authorization" to "Developer" settings

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1053]
I'd argue this is really a developer feature. @hobinjk What do you think?

UI mockup below (does the same thing as the current feature, but from developer settings rather than Authorization settings as it isn't really a user-facing feature):

![developer-settings](https://user-images.githubusercontent.com/552417/40841661-1f23d8a6-65a3-11e8-9f43-ba8eeb9a129e.png)

**Comment by hobinjk** [comment]
I agree that this is a good place for it when the section exists
