### ISSUE TITLE
Domain Settings doesn't reflect full mDNS state

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1055]
See https://github.com/mozilla-iot/gateway/pull/1049#issuecomment-393892397

* The default value which appears in the Local Access host name setting does not reflect the "gateway.local" hostname which Avahi is broadcasting
* When the "Local Access" setting is disabled in settings, Avahi is still broadcasting "gateway.local"
* If the user tries to set the local host to "gateway.local", it conflicts with Avahi and gets set to something else instead

**Comment by mrstegeman** [comment]
Maybe the best thing to do here is to let wifi-setup, which runs every time the RPi starts up, shut down the avahi service before it exits. That way, `gateway.local` is present during wifi-setup, but after that, avahi is no longer running so the gateway can broadcast itself properly.

**Comment by benfrancis** [comment]
That could help. But just thinking about edge cases:

It's possible that the user could have changed the mDNS hostname to "foo.local", but then it fails to connect to WiFi on boot so the WiFi setup web server and WiFi hotspot are started and it continues broadcasting gateway.local.

I also wonder what happens if the gateway is connected via both Ethernet and WiFi, but then WiFi fails to connect....

It seems like the least error-prone way to do this would be to have just one mDNS server rather than multiple.

Note that this may be about to get more complicated because I'm designing the Network Settings section which requires configuring WiFi from the gateway web interface. It makes me wonder whether the WiFi configuration UI should be merged into the gateway web interface.

**Comment by mrstegeman** [comment]
In case 1, I don't really see an issue. The WiFi setup server sets up a captive portal, and the user will have to connect to a different network to set things back up anyway. `foo.local` will be broadcast again after wifi is fixed.

Case 2 doesn't seem like a typical use case, but it would be the exact same story as case 1. The gateway won't even be running until wifi is fixed or skipped.

Your suggestion is actually the same as mine. `avahi` can just completely go away if/when we merge the WiFi setup into the gateway.

**Comment by benfrancis** [comment]
@nherriot wrote in #1049:
> Mmmm. I've got quite a few raspberry pi's and I'm using rasbian stretch at the moment. None of them start and broadcast on gateway.local. They start on:
> raspberrypi.local
> What I'm suggesting is that whatever the Mozilla Gateway did to change that could be left as is (i.e let the system come up as raspberrry.pi). So the raspberry pi keeps it's own mDNS name.

We just changed the default hostname from raspberrypi.local to gateway.local for our gateway OS image.

If we have UI for the user to change the hostname broadcast via mDNS then I think it should actually change the hostname broadcast via mDNS, not just add a second broadcast (e.g. for the case of two conflicting gateways broadcasting the same name).

If in future we expose a Thing Description for the gateway as we have previously discussed, that could also result in duplicate web things being discovered.

 mDNS can also create quite a lot of network noise so having duplicate broadcasts seems excessive.

I also do think it's a bit odd if the mDNS broadcast switches between different hostnames in different states or stages of booting.

> The user gets the flexibility of choosing the name of the gateway locally in the Mozilla settings. I thought changing doc's are easy compared to code. :-)
> 
> If you want it to be the only mDNS broadcast then you will have to stop the avahi daemon broadcasting, which i think is a cool way to go if you are wanting to make this platform a nodejs top to bottom. However - you may upset developers who normally want to do:
> /> ssh pi@raspberry.local
> That's a tough one!

Being able to ssh pi@gateway.local seems like a valid use case for developers or power users, e.g. if there's a problem starting the gateway process in node and they don't know the gateway's IP address.

> Or you could have the nodejs app configure the daemon - but I thought the conversation on that topic was bad idea as the gateway needed root privileges ?

We probably need to do other things from the web interface which require root (or sudo) privileges too (e.g. reboot the gateway).

@mrstegeman wrote:
> In case 1, I don't really see an issue. The WiFi setup server sets up a captive portal, and the user will have to connect to a different network to set things back up anyway. foo.local will be broadcast again after wifi is fixed.

Not all operating systems support captive portal (e.g. it doesn't seem to work in Linux). In this case the user will need to manually type the gateway's hostname or IP address as with Ethernet first time setup. Even for operating systems which do support captive portal, it can sometimes be a bit unreliable, it would be good if you could use a the local hostname as a fallback.

> Case 2 doesn't seem like a typical use case, but it would be the exact same story as case 1. The gateway won't even be running until wifi is fixed or skipped.

The gateway's HTTP server won't be running, but other services like SSH might be.

This seems to be pointing towards having the UI configure Avahi rather than having a separate mDNS broadcast in the node process.

If we do merge the WiFi setup application and the main gateway application then that would make switching to an entirely node-based mDNS server more reasonable, I'm just not sure if that's going to happen in 0.5. The only use case that misses would be if the node process fails to start and you want to SSH in, but that's hopefully a rare occurrence!

I'd suggest we either need to switch the web interface to configuring Avahi, or merge the WiFi setup and gateway applications.

**Comment by mrstegeman** [comment]
@benfrancis I like the idea of just configuring `/etc/hostname` appropriately and letting `avahi` handle things. However, this neglects users that are using macOS or Windows, or on Linux without sudo privileges. The nice thing about the current solution is that none of it requires root privileges, and it works anywhere.

Some of our other functionality does require root privileges, i.e. toggling SSH and restarting the system, but mDNS broadcasting _shouldn't_ really need that, so I don't love the idea of requiring it.

**Comment by benfrancis** [comment]
Generally speaking I think we should prioritise the experience while running on the target gateway hardware (which currently means the Raspbian and OpenWrt builds) over the experience running the gateway application on a desktop PC or server (e.g. during development or on a DIY deployment).

That doesn't mean we shouldn't use the NodeJS approach, just that we should prioritise the experience of those builds and ideally not have two duplicate mDNS servers running in that use case.

It seems like the long term solution might be to merge the WiFi setup and gateway applications and use the NodeJS mDNS implementation, but if that isn't going to happen in 0.5 then I'd suggest we either need to switch the implementation to configure Avahi for the 0.5 release, or disable this feature by default.

**Comment by nherriot** [comment]
Just thought I'd throw in my 10 cent worth. ATM we are working with the authentication system and OAuth2 - the token page diligently tells me that my GW is gateway.local even though on my machine I have disabled the avahi service. I'm guessing that it reads from a config file, which was setup on system start and assumes it's running etc... 
However the mDNS approach means that the GW manages that. Other parts of the system can report the actual value with confidence.

I tried working with other libraries - but found this was the simplest and had less dependencies on the underlying system. It goes against the grain - in that I normally take the view to use the parts of Linux subsystem designed to manage this for you. Having used mDNS, i'm now a convert! :-) ...
Looks like it could be set as disabled as default in the short term if it presents an issue for people.

Kind regards, Nicholas.

**Comment by hobinjk** [comment]
@nherriot If you're talking about the local token service the `gateway.localhost` is being used as the url of the oauth client to signify that the gateway will send the token to itself instead of a remote service (e.g. google assistant and IFTTT). I should probably special-case the gateway.localhost value to display as "your Gateway" or equivalent to be clearer.
