### ISSUE TITLE
Certificate Errors after Reboot from Power Outage

### ISSUE THREAD

**Issue by emceeaich** [mozilla-iot/gateway#1060]
This afternoon we had a power outage at home. The Pi hosting the gateway rebooted, but when I attempted to log back into my hub. I got the browser error:

hostname.mozilla-iot.org uses an invalid security certificate. The certificate expired on June 1, 2018, 5:17:03 PM GMT-7. The current time is June 1, 2018, 7:49 PM. Error code: SEC_ERROR_EXPIRED_CERTIFICATE

If I go to gateway.local, I get a similar error but I'm allowed to create an exception, from there I can log into the gateway and control devices.

**Comment by mrstegeman** [comment]
@emceeaich There were several issues recently with certificate renewal. If you copy this file into place and run it, your issues should hopefully be resolved. Place it in: `/home/pi/mozilla-iot/gateway/tools`

https://github.com/mozilla-iot/gateway/blob/master/tools/renew-certificates.sh

**Comment by emceeaich** [comment]
Thank you!
