### ISSUE TITLE
Can't always get back to things screen from thing detail view

### ISSUE THREAD

**Issue by sogaani** [mozilla-iot/gateway#1071]
1. Open browser and access URL `yourgatewaydomain/things/<things-id>` direct.
2. back button does not work.

**Comment by benfrancis** [comment]
It's a bit tricky to know where to go back to.

The thing detail view can be reached either from the things view or the floorplan view so I assume this button uses window.history.back() to go back to whichever page you just came from. If you link to the thing URL directly then it will probably go back to the new tab page!

**Comment by sogaani** [comment]
Oh, I see. It is reasonable behavior. I didn't understand that thing-detail view can be reached from floorplan view.

**Comment by benfrancis** [comment]
I think this is a valid bug report because if you deep link to the detail page there's no way to get back to the main things screen. I'm just not sure what the fix is.

**Comment by dhylands** [comment]
Perhaps store a hidden field on the page which has the needed information?

**Comment by benfrancis** [comment]
Yeah. If you start on that page though, where should you go back to?

Perhaps it should default to going back to the main things screen, unless there's a query string or something which tells it the referrer was the floorplan page.
