### ISSUE TITLE
VoltageProperty

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1078]
As a developer I want the gateway UI to show the current voltage being used by my device.

Thing Description example:
```
{
  "name": "My Thing",
  "@context": "https://iot.mozilla.org/schemas",
  "properties": {
    "voltage": {
      "name": "Voltage",
      "@type": "VoltageProperty",
      "type": "number",
      "unit": "voltage"
    }
  }
}
```

UI mockup:
![voltageproperty](https://user-images.githubusercontent.com/552417/40998223-f8e1e3b8-68fe-11e8-977d-ab5fb887b967.png)

**Comment by benfrancis** [comment]
@mrstegeman I just realised that this says the unit is "voltage", but the [SI unit](https://en.wikipedia.org/wiki/International_System_of_Units#Derived_units) is actually "volt". I'm not sure whether that's something that we actually string match vs. just display as is, but something may need changing?

**Comment by mrstegeman** [comment]
@benfrancis I implemented it using `volt`, and I believe all of the adapters do as well. If we do find something that uses `voltage` as the unit, we can just add it to [this function](https://github.com/mozilla-iot/gateway/blob/master/static/js/utils.js#L118) and all will be well.

**Comment by dhylands** [comment]
Aside: I find it amusing that the units use the singular, which means that they're only correct when the number is 1. For any other number (the vast majority of the cases) the units should be pluralized (i.e. volts, amps (or amperes), watts, etc.

**Comment by mrstegeman** [comment]
@dhylands They end up being abbreviated in the UI anyway, but yes, they should probably be pluralized.

**Comment by benfrancis** [comment]
It is a bit odd. The important thing is that SI is a widely accepted standard that we can follow in the Thing Description (although even that is not very easy to reference from a W3C specification, and JSON Schema technically doesn't support defining units). We can display whatever we want in the UI.
