### ISSUE TITLE
Removing and adding a thing back to gateway is not working

### ISSUE THREAD

**Issue by tsathishkumar** [mozilla-iot/gateway#1108]
I have a web-thing running locally. I first added it, then removed it from gateway.

But when I tried to add it again, it shows "_Web thing already added_"

Log says:
`2018-06-20 12:51:23.426 Web thing already added http---localhost-8888-0`

Note: I'm adding the thing using web thing url.

**Comment by benfrancis** [comment]
I'm not sure why this is happening, but if you go to Menu -> Settings -> Add-ons -> thing-url-adapter -> Configure. Do you see any URLs listed there. If so, try removing it and see what happens.

**Comment by tsathishkumar** [comment]
Ok, after retrying it works fine. I think the first time I removed and added back, there was error in thing api (properties endpoint was not working). Since there was error, the thing was not displayed in Things tab, and I tried to add again. That is when I got the issue. Guess the issue can be closed.
