### ISSUE TITLE
Settings - Location

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/gateway#1113]
For #562 we need a section of the settings to allow the user to specify their location and optionally timezone. What I have in mind is:
"Location: [around here](link to external map) [Get]()"
"Timezone: EDT" (with drop-down for manually setting an alternative)
@benfrancis Do you have the time to mock this up? If not I can just implement it and post screenshots on the PR.

**Comment by hobinjk** [comment]
There's an existing Firefox icon for location which makes things a bit easier:
[Location.svg.zip](https://github.com/mozilla-iot/gateway/files/2121168/Location.svg.zip)

**Comment by benfrancis** [comment]
@hobinjk If the sunrise/sunset feature depends on a new location/timezone settings feature then let's get that into the backlog to do first and I'll create a UX spec, but FWIW I'd be fine with dropping this feature for 0.5. Location & timezone features usually end up being more complex than first thought, especially if we're dependent on any third party services.

FWIW I used the sunrise/sunset feature of SmartThings for over a year and in the end I switched to fixed times that I tweak myself because sunset was always a bit too late and sunrise always a bit too early for turning lights on and off!

**Comment by hobinjk** [comment]
Yeah, I agree that this has the potential to explode in complexity. I think it's worth taking the time to make sure we get it right. It's also only useful for sunrise/sunset and daylight savings time so it's not too critical

**Comment by dhylands** [comment]
I like to be able to use a offset added to sunset. i.e. turn lights on 30 minutes before suset). I wound up writing an external script which does what I want.

**Comment by rzr** [comment]
If unset, TZ should be set to UTC

**Comment by kgiori** [comment]
I currently use several add-ons where I have had to copy/paste lat and lon into the config. If I could put lat/lon into a gateway setting, to be my default for add-on configs, that would be quite useful. For now, data could be configured on an additional settings page: 

**Settings > Localization**
Latitude
Longitude
Time Zone
Address (for later, since country might help in some regulatory use cases)
Language (for later)
Theme (for later)

**Comment by dhylands** [comment]
We should be setting the country for Wifi to make sure that the correct channels are being used.

**Comment by benfrancis** [comment]
Initial ideas:
![location_settings](https://user-images.githubusercontent.com/552417/66952351-5c6bd280-f054-11e9-832e-0157a77b0250.png)

Notes:
- Wow, there are a lot of different possible ways of grouping this!
- This would cover the very basics of [Location Settings](https://github.com/mozilla-iot/gateway/issues/1113), [Language Settings](https://github.com/mozilla-iot/gateway/issues/2125), [Time Settings](https://github.com/mozilla-iot/gateway/issues/1530) and [Unit Settings](https://github.com/mozilla-iot/gateway/issues/1523). They don't have to all be implemented at the same time, they could be implemented separately.
- Any setting that can't get set on the current OS would have its form element disabled
- Setting the unit for temperature would be reflected in all `TemperatureProperty` and `TargetTemperatureProperty` representations, which probably touches quite a few bits of UI across the Things UI, rules engine and logs where the value would need to be converted and a different unit displayed.
- I haven't included a way to set the current time, but I'm not sure how essential that is given the Pi will usually set its own time via NTP
- 

Questions:
- Are these enough settings to get started with? Other unit settings I can think of include data and time format for Logs, but given that's still an off-by-default experiment that doesn't feel as high priority.
- Does Raspbian and/or NodeJS provide a list of countries, timezones and/or languages, or do we need to source those from somewhere? Note that lists of countries can be quite controversial, and can change over time. If the OS or NodeJS doesn't provide a list we should maybe look at what Firefox uses, or what npm modules exist.
- Should we have a button to save the settings? It doesn't feel necessary but there are some other areas of settings where we do use a button.
- Any feedback?

**Comment by mrstegeman** [comment]
I like that you have all these settings grouped together. It makes sense that way.

> * I haven't included a way to set the current time, but I'm not sure how essential that is given the Pi will usually set its own time via NTP

I don't think we need to. NTP should be sufficient, at least for now. I just wish the Pi had an RTC.

> * Should we have a button to save the settings? It doesn't feel necessary but there are some other areas of settings where we do use a button.

No, I like instant save.

My biggest comment on this is... why select a country? That can be useful for setting wi-fi channels, but otherwise, it probably tells very little about your location. What would be more useful is to allow users to enter their latitude/longitude, which is already used by quite a few add-ons. I understand that there are potential privacy issues around that (even though user's must choose to enter those details), but for any meaningful location-based rules/adapters/etc., country-level is insufficient.

**Comment by JSkier21** [comment]
chrony works well on my pi devices: https://chrony.tuxfamily.org/

@mrstegeman, there are addon modules for an RTC. 

Regarding location, geoclue has potential: https://gitlab.freedesktop.org/geoclue/geoclue/wikis/home

I agree with lon/lat input; this would work well for weather and sun rise/set functions.

Looking forward to time and temperature updates, thank you for working on this. I'm happy to test anything if needed.

**Comment by mrstegeman** [comment]
@benfrancis It seems to me that the top-level menu item should be "Localization", rather than "Location". Would you agree?

**Comment by dhylands** [comment]
Using NTP is only an option if you're connected to the internet. Its possible (like one user recently reported) that it may take some time after a power failure before their internet came up, so having a way to manually set the date/time might still be useful.

If there is an RTC module, the user will need to do some setup and could presumably set the time from the command line while doing their setup.

**Comment by mrstegeman** [comment]
Without NTP, the user will have to manually set the time. Without an RTC, the user would have to do it after every single boot. The only way time-based rules are helpful is if there is an accurate clock, so we should probably either expect users to use one of those 2 solutions, or switch to a board with a proper RTC.

**Comment by benfrancis** [comment]
@mrstegeman wrote:
> why select a country? That can be useful for setting wi-fi channels, but otherwise, it probably tells very little about your location.

Setting Wi-Fi channels is the main reason (as per Dave's comment earlier). It could also make it easier to pick a timezone if we filtered the timezone field by country.

>  What would be more useful is to allow users to enter their latitude/longitude, which is already used by quite a few add-ons.

Ah, OK. Is there a way to do this without relying on a third party service though? For example, you could use Google Maps to pick your location, but then we'd need an API key, which I'm not sure we could share between all gateways, and would need to share the user's location with Google. Short of just manually typing in longitude and latitude I'm not sure how to achieve this. Any ideas?

we do have the [Mozilla Location Service](https://location.services.mozilla.com/) which can use Wi-Fi and Bluetooth to approximate your location. Is that any help? It appears that GeoClue (suggested by @JSkier21), uses this service for Wi-Fi based geolocation.

I don't think storing your location in the gateway is a privacy issue in itself, as you're not sharing that information with Mozilla. But making that information available to add-ons without some kind of user consent could be an issue.

> It seems to me that the top-level menu item should be "Localization", rather than "Location". Would you agree?

Erm, yeah I guess that makes sense.

@dhylands wrote:
> Using NTP is only an option if you're connected to the internet... having a way to manually set the date/time might still be useful.

This is true. But I also agree with Mike that this is a bit pointless on the Raspberry Pi if you have to do it on every boot.

I see supporting local usage of the gateway as slightly different to supporting offline usage. Supporting a configuration where the web interface is only accessible locally is important. If you're gateway is completely offline (disconnected from the Internet), then lots of things are not going to work (e.g. software updates, smart assistant, many add-ons).

So let's prioritise setting the timezone in 0.10 and file a follow up issue for setting the time, which will be more useful once we port to production hardware with a RTC.

**Comment by mrstegeman** [comment]
> @mrstegeman wrote:
> 
> > why select a country? That can be useful for setting wi-fi channels, but otherwise, it probably tells very little about your location.
> 
> Setting Wi-Fi channels is the main reason (as per Dave's comment earlier). It could also make it easier to pick a timezone if we filtered the timezone field by country.

Ok, that's fine. I'll do the country picker.

> > What would be more useful is to allow users to enter their latitude/longitude, which is already used by quite a few add-ons.
> 
> Ah, OK. Is there a way to do this without relying on a third party service though? For example, you could use Google Maps to pick your location, but then we'd need an API key, which I'm not sure we could share between all gateways, and would need to share the user's location with Google. Short of just manually typing in longitude and latitude I'm not sure how to achieve this. Any ideas?
> 
> we do have the [Mozilla Location Service](https://location.services.mozilla.com/) which can use Wi-Fi and Bluetooth to approximate your location. Is that any help? It appears that GeoClue (suggested by @JSkier21), uses this service for Wi-Fi based geolocation.
> 
> I don't think storing your location in the gateway is a privacy issue in itself, as you're not sharing that information with Mozilla. But making that information available to add-ons without some kind of user consent could be an issue.

Several add-ons have latitude/longitude in their configuration, and users just have to manually enter values.

If we want to support setting this globally, we could have manual inputs and maybe an "Estimate" button which uses the [Geolocation API](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API). That would be the most webby thing.

However, we may actually want to hold off on this for a bit, or maybe not do it at all. Entering this globally would automatically give location access to every add-on, which is potentially undesirable.

I think for now, we should actually just stick with a country picker for setting wi-fi channels.

> > It seems to me that the top-level menu item should be "Localization", rather than "Location". Would you agree?
> 
> Erm, yeah I guess that makes sense.

Ok, will do. Can I get an icon for the menu item? It should be the only one I need.

> @dhylands wrote:
> 
> > Using NTP is only an option if you're connected to the internet... having a way to manually set the date/time might still be useful.
> 
> This is true. But I also agree with Mike that this is a bit pointless on the Raspberry Pi if you have to do it on every boot.
> 
> I see supporting local usage of the gateway as slightly different to supporting offline usage. Supporting a configuration where the web interface is only accessible locally is important. If you're gateway is completely offline (disconnected from the Internet), then lots of things are not going to work (e.g. software updates, smart assistant, many add-ons).
> 
> So let's prioritise setting the timezone in 0.10 and file a follow up issue for setting the time, which will be more useful once we port to production hardware with a RTC.

I agree with this.

**Comment by benfrancis** [comment]
[Menu icon](https://drive.google.com/file/d/1v4N_p_KwidRQuqAm-FNehXgEN0xhC81j/view?usp=sharing)

**Comment by benfrancis** [comment]
> If we want to support setting this globally, we could have manual inputs and maybe an "Estimate" button which uses the Geolocation API. That would be the most webby thing.

I like that idea, though that is the location of the client, not necessarily the gateway. Probably works in most cases.

> I think for now, we should actually just stick with a country picker for setting wi-fi channels.

Agreed.
