### ISSUE TITLE
Would like to be able to retrieve the git hash that a version of the gateway is based on.

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#1117]
It would be useful to be able to determine the git hash that a particular running instance of the gateway is based off of.

I'd also like to see this extended to add-ons.

It would be ideal if this information was available in the UI someplace, but I'd be happy even if it was just in the filesystem.

**Comment by mrstegeman** [comment]
I assume this is primarily developer-focused, as the release version number is in the UI.

**Comment by dhylands** [comment]
Sure - but for example, I'm working on the OpenWRT release which I know is 0.4 but I don't know if its based on the same 0.4 hash as our gateway release is.

Because its mostly developer focused, that's why I'd be happy if the information was just in a file.

**Comment by benfrancis** [comment]
This could possibly go in Developer Settings, but a file would be a good starting point.
