### ISSUE TITLE
Mozilla logo,  Button and Checkbox is layered  in Authorization Screen.

### ISSUE THREAD

**Issue by sogaani** [mozilla-iot/gateway#1124]
![screenshot_20180624-130756](https://user-images.githubusercontent.com/20137651/41815807-6cb6e56c-77b0-11e8-8d79-737a4be4537c.png)

I guess that placing Mozilla logo bottom of screen is better rather than floating, when using mobile phone.

**Comment by benfrancis** [comment]
There are a couple of places where we actually hide the logo, or hide it only on small screens using a media query, so we could do that.

The logo causes quite a lot of layout problems like this so I've been considering moving it to the main menu instead (and using the Things Gateway wordmark). What do people think of that?

![main_menu-wordmark](https://user-images.githubusercontent.com/552417/41855031-8aaea3fa-7889-11e8-81e8-13a177f1c7cb.png)

**Comment by mrstegeman** [comment]
@benfrancis I like that a lot.

**Comment by sogaani** [comment]
👍

**Comment by benfrancis** [comment]
I've filed #1138
