### ISSUE TITLE
Icon is broken on Things view with Chrome.

### ISSUE THREAD

**Issue by sogaani** [mozilla-iot/gateway#1125]
![image](https://user-images.githubusercontent.com/20137651/41816299-57295598-77bc-11e8-92fb-530eff1d3585.png)

Windows 10
Chrome: Version: 67.0.3396.87（Official Build） （64 bit）

**Comment by mrstegeman** [comment]
@sogaani Is this happening with all icons, or only the bulb icon?

**Comment by sogaani** [comment]
@mrstegeman Yes, it happen with all icons. It seems to be caused by overlaying detail links with `float: right;`.  Disabling `float: right;` get correct icon.
![image](https://user-images.githubusercontent.com/20137651/41819685-9e4d89e2-77ff-11e8-963b-e4b14473d007.png)

Furthermore, Smart plug have wrong size`132 x 128`, it cutting off right side.
![image](https://user-images.githubusercontent.com/20137651/41819673-6fb63c3c-77ff-11e8-9346-d02963835525.png)

**Comment by mrstegeman** [comment]
Ok, I'll take a look tomorrow and try to reproduce. Thanks for reporting!
