### ISSUE TITLE
MaxListenersExceededWarnings

### ISSUE THREAD

**Issue by freaktechnik** [mozilla-iot/gateway#1128]
I'm getting some warnings from the node EventEmitter when running the gateway with a couple of devices set up:
```
(node:7883) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 propertyChanged listeners added. Use emitter.setMaxListeners() to increase limit
(node:7883) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 actionStatus listeners added. Use emitter.setMaxListeners() to increase limit
```

**Comment by mrstegeman** [comment]
Duplicate of #561

**Comment by sogaani** [comment]
@mrstegeman This is not same as #561.
#561 is issue about client side memory leak. This is about server side issue.
`EventEmitter` has limitation for listening event and report warning when over limitation. However it is just warning and not errors. We can use `setMaxListeners` API to avoid this warning.

**Comment by sogaani** [comment]
Default `setMaxListeners`  is 10. If an user has more than 10 devices, he get warning even if fixed client side issue. 
Perhaps we need https://github.com/mozilla-iot/gateway/issues/947 too.

**Comment by mrstegeman** [comment]
That's true. We should increase the number of listeners as well. I'll re-open this issue for that purpose.

**Comment by rzr** [comment]
Observed this too, I suspect this is also slowing down on startup.

**Comment by flatsiedatsie** [comment]
I come across this 'issue' too in my logs.

```
2019-05-09 19:16:38.004 ERROR  : (node:27104) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 actionStatus listeners added. Use emitter.setMaxListeners() to increase limit
```

**Comment by flatsiedatsie** [comment]
And it's here too: https://forum.mysensors.org/topic/10435/mysensors-add-on-crashed/5

**Comment by mrstegeman** [comment]
Increasing the number of listeners just seems pointless. Somebody will always hit the max, regardless of what we set.
