### ISSUE TITLE
Create a serial port manager

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#1133]
Currently, it is the responsibility of each adapter to determine which serial port to open. This can be problematic as it may be difficult, if not impossible for an adapter to determine which serial port to use.

For example, on the Raspberry Pi, /dev/ttyAMA0 (which corresponds to the builtin logic level serial port available on the GPIO headers) could be used for a zwave adapter like the [RaZberry](https://z-wave.me/products/razberry/) or a zigbee adapter like the [RaspBee](https://www.dresden-elektronik.de/raspbee/), or it could be connected to other devices.

Even with USB devices, often the VID/PID can be used but this also isn't always the case. The Digi ZigBee dongle that we uses presents using the FTDI VID & PID. More generic configurations like a [UARTSBee](https://www.seeedstudio.com/UartSBee-V5-p-1752.html) with an XBee module programmed as a Zigbee coordinator (same firmware as what runs in the dongle) also presents as an FTDI serial adapter.

Many Arduino boards use FTDI adapters.

I'd like to propose that the gateway have a centralized serial port manager which allows particular serial ports to be assigned to a particular adapter. The serial port manager should try to automate this as much as possible, but the user should be able to override the automatic decisions.

The selection process should use filters (like VID/PID/other USB attributes) as much as possible to allow for devices being plugged-in in a different order.

**Comment by benfrancis** [comment]
I'm reluctant to add any complexity to the main gateway user interface to manage serial ports, because in a consumer gateway this is simply not something the user should be expected to do (in most cases all the radio adapters will be built-in).

For the DIY use cases with the Raspberry Pi, could manual overrides of serial ports for adapters be exposed through add-on configuration?

Relatedly, so far in practice we still seem to have a 1:1 correlation between add-ons and adapters in the UI and adapter configuration happens within the add-on UI. I'm still not convinced that separation is actually necessary.

**Comment by dhylands** [comment]
We really need a central serial port manager that all of the adapters share. Making each adapter determine the correct serial port leads to conflicts and we'd need to implement it in each language that the adapters are written in.

**Comment by benfrancis** [comment]
OK, I understand.

How much of this actually requires user intervention?

**Comment by dhylands** [comment]
The amount of user intervention depends on what's plugged in. For well defined USB devices, no user intervention should be required (most ZWave dongles). For other devices which have generic USB-to-serial front ends (like the pixel wall, microblocks, serial-arduino devices, some zigbee adapters) then the user will need to select the adapter that a given serial port should be assigned to.

We would create profiles which do as much as possible in an automated fashion, and the user would need to assign the rest.

**Comment by mrstegeman** [comment]
@dhylands Should we close this now that we have [serial-prober-node](https://github.com/mozilla-iot/serial-prober-node)?

**Comment by dhylands** [comment]
Yeah - I think we can. That combined with configuration would allow custom configs to be added
