### ISSUE TITLE
MultiLevelSensor gets confused with multiple LevelProperties with different units

### ISSUE THREAD

**Issue by freaktechnik** [mozilla-iot/gateway#1148]
If a `MultiLevelSensor` thing has multiple `LevelProperty` properties, it adapts the last updated value as its current main value. It does however not adapt the unit of the updated property, so the center of the thing will contain a number with the wrong unit.

**Comment by freaktechnik** [comment]
Best case scenario the user can choose what property is displayed as primary value. I'm thinking of the weather station here, where some may want to quickly see the temperature, while other may want to see CO2 concentration or humidity etc.

**Comment by mrstegeman** [comment]
As the capability system matures, we should start to gain things like `TemperatureProperty`, `HumidityProperty`, etc. When that happens, our selection of high-level icons will grow as well.

I want to keep this issue open, though, for cases where there will continue to be 2 of the exact same property type.

**Comment by benfrancis** [comment]
Hmm, I didn't think of that.

For the time being can we get the UI to just pick one of the `LevelProperty`s, probably the first one, and only display that property's value changes in the main Things screen?

I agree in this use case it would be nice if the user could choose, but in the meantime we should at least not switch between different properties and display the wrong unit.

It would definitely be preferable that you don't have to leave off semantic annotations just to tell our UI which value to show.

**Comment by mrstegeman** [comment]
@benfrancis The problem with picking the "first one" is that it's a JSON object, so "first" is indeterminate. We could try to sort the property names, but that is not necessarily what the developer intended either.

What @dhylands and I decided to do in the case of the dual-outlet smart plug was to set one to the `OnOffProperty` and the other as `BooleanProperty`. The 2 will have different property details, but at least the capability icon will be consistent.

**Comment by mrstegeman** [comment]
The same thing also occurs when you have a smart plug with a light on it. It will need to have an `OnOffProperty` for both the `SmartPlug` and the `Light`, and if you include `OnOffSwitch`, things get even worse.

**Comment by rzr** [comment]
Unsure if related but I have observed UI issues when a thing contains 2 properties of same types (ie onoff switch)

**Comment by mrstegeman** [comment]
Yes, that's the exact same issue.

**Comment by rzr** [comment]
Feedback welcome I only made the fix for switch prop then this can be replicated to other components if  solution is acceptable.

ps: Gz for @mrstegeman .fork() !

**Comment by rzr** [comment]
Can you please try linked patches from:
https://github.com/TizenTeam/gateway/tree/sandbox/rzr/devel/master

It worked for me on this "in progress" thing:

![ARTIK05x](https://pbs.twimg.com/media/DjqoJVAW4AEw5J4.jpg)

**Comment by rzr** [comment]
I confirm this UI  issue is affecting latest release,

I can share a code for ARTIK or RPi to reproduce and verify pending change at:

https://github.com/mozilla-iot/gateway/pull/1249

![artik-720](https://camo.githubusercontent.com/b1ceaf9d50e7b614fe95e6cd35ef08d1d177241c/68747470733a2f2f7062732e7477696d672e636f6d2f6d656469612f446b513362394d58734141413368752e6a7067)

**Comment by rzr** [comment]
@mrstegeman said { Yes, that's the exact same issue. }

May I ask you @freaktechnik  to test my patch and report if it does not make situation worse ;)

**Comment by freaktechnik** [comment]
> May I ask you @freaktechnik to test my patch and report if it does not make situation worse ;)

I _think_ it fixes it even, but it's hard to reproduce for me, without going through the paces and building a custom virtual thing that happens to trigger this. I had encountered this randomly in the wild...
