### ISSUE TITLE
Switch to npm use package.json lockfile

### ISSUE THREAD

**Issue by lightsofapollo** [mozilla-iot/gateway#115]
NPM is a great resource but has had a number of bugs over time. Many of those are fixed relatively well (i.e. a better lock format, etc...). YARN by comparison was built for FB by experts who had built many other package manager systems (cargo, bundler, etc...) and has an excellent lock format.

https://yarnpkg.com/blog/

The lock format itself is so important because it will ensure that our packages do not magically have their contents changed (cache corruption, npm bugs, implicit semver). YARN hashes the contents (the tar) of the packages themselves to ensure that each install has the right bits.

**Comment by hobinjk** [comment]
Is there a reason to use yarn over npm 5's package-lock.json?

**Comment by lightsofapollo** [comment]
@hobinjk I honestly was very skeptical that npm@5 was reliable/deterministic/fast but after tying it out just now on react-native/npm (some test cases where npm was originally 2-5x slower) I am impressed. It was faster in both cases and it looks like aside from the terrible diffs of package.json-lock npm5 seems strictly better (https://yarnpkg.com/blog/2017/05/31/determinism/).

**Comment by lightsofapollo** [comment]
I have been using npm5 for a few hours now and I hit some weird issues with use with the lockfile...

In one case I got asn1 instead of asn1.js ( I have a hard time reproducing this exactly) in another babel-eslint was missing...

**Comment by benfrancis** [comment]
I think this is fixed now @lightsofapollo ?
