### ISSUE TITLE
what are some cool projects implemented using mozilla-iot gateway?

### ISSUE THREAD

**Issue by amrithmmh** [mozilla-iot/gateway#1203]

**Comment by hobinjk** [comment]
http://www.twobraids.com/ and https://twitter.com/RzrFreeFr/status/1002686608469123080 are some particularly nice projects

**Comment by rzr** [comment]
Thx for mentioning it,

Is this an issue ? or maybe related to:

https://discourse.mozilla.org/t/send-us-photos-of-your-things-gateway-in-action/26177/

I like http://www.twobraids.com/2018/05/things-gateway-monitoring-solar-panels.html
I know also that my friend @nledez has deployed it home...

You can even also get inspiration from "World 1st smart orchid" :

https://twitter.com/TizenHelper/status/1017436150053654528

Part of code is upstreamed at:

https://github.com/mozilla-iot/webthing-arduino/tree/master/examples/LevelSensor

**Comment by benfrancis** [comment]
Feel free to continue the discussion on Discourse! https://discourse.mozilla.org/c/iot
