### ISSUE TITLE
Uncaught error within stm_web

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/gateway#1208]
`Fetch error: ReferenceError: "error is not defined"` appears to happen if it doesn't hear anything? It's not entirely clear. Notably it doesn't update the UI and the STM object gets poisoned

**Comment by sogaani** [comment]
I found a stm_web issue that does not back to `ready` state, if an error occurs.
[My pull request](https://github.com/mozilla/speaktome-web/pull/16) will fix it and report errors.

I think useful to show a message something error occur with avater, when stm_web reports error.

**Comment by hobinjk** [comment]
Thanks for the pr to STM! Fixed in c68a8fc2a2074c64ce12f25efc190eee0c932a14
