### ISSUE TITLE
Add page titles to Assistant and Things screens

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1211]
Kathy pointed out that some pages have titles and others don't.

Let's try adding titles to the Assistant and Things screens and see how well it works. The title should scroll off the page though, rather than have the content disappear behind an invisible line beneath it.

We could also try adding a title to the floorplan page, but it might need a dropshadow to account for white backgrounds, so the icon probably wouldn't work.

May require some experimentation.

**Comment by mrstegeman** [comment]
We decided this wasn't a great idea. See #1323 for discussion.
