### ISSUE TITLE
Use WebSpeech API when available

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/gateway#1215]
Later, polyfill the WebSpeech API with references to our local solution.

**Comment by andrenatal** [comment]
That's not a smart move. It better to use the Mozilla's stm API when on environments that's not chrome, otherwise it's the same as giving free data to google since we don't retain the samples.

**Comment by hobinjk** [comment]
The point about giving data to google is a reasonable concern.

My reason for creating this issue is that I think we eventually want to use the WebSpeech API on all supported platforms since it's the "standard web API" way of doing things.

**Comment by andrenatal** [comment]
Yes, but seems they don't care too much about standards when they want to privilege and promote their platform and browser: https://www.reddit.com/r/programming/comments/91i0mc/youtube_page_load_is_5x_slower_in_firefox_and/

In addition to that, Mozilla needs data to train their own speech models, that was the whole point of Common Voice and etc.. and having a mozilla's web property that favor google and not us is not a smart business decision

**Comment by benfrancis** [comment]
Using the web standard is the right thing to do, it gives the end user the choice of who gets their data.

UA sniffing Chrome to prevent it using the Web Speech API in some kind of tit-for-tat war against Google is just wrong. It should be up to the user to choose who gets their speech data, not us.
