### ISSUE TITLE
Web component scaling issue on Linux

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1224]
Note that on the smart bulb and multi-level switch icons the text looks larger and there's less padding inside the circle.

![screen shot 2018-07-30 at 18 32 30](https://user-images.githubusercontent.com/552417/43413448-fd368bfe-9427-11e8-9dff-eaf978e226e2.png)

This is Firefox 61.0.1 on Ubuntu 18.04. I can't tell if this is a font issue (related to #1112) or it's a strange difference in the rendering engine on Linux.

**Comment by benfrancis** [comment]
Same view rendered in Firefox on Mac OS:

![screen shot 2018-07-30 at 18 42 47](https://user-images.githubusercontent.com/552417/43413608-71e1eb60-9428-11e8-9dcf-bec0bae440a5.png)

**Comment by benfrancis** [comment]
I think this is a text rendering issue. Everything else has exactly the same dimensions in pixels.

**Comment by benfrancis** [comment]
It looks like this is a font rendering issue specific to Gecko on Linux. Renders fine on MacOS and on Chrome on Linux. We may need to file a bug against Firefox and leave this one.

**Comment by benfrancis** [comment]
This is actually even worse on the things screen.

Mac:
Uploading...

Linux:
![screen shot 2018-08-01 at 16 51 01](https://user-images.githubusercontent.com/552417/43532933-863bcc5a-95ab-11e8-8d4a-4bfd42557ec9.png)

@hobinjk I don't supposed you have any ideas how to work around this?

**Comment by benfrancis** [comment]
Oh actually, this is fixed in Firefox Nightly on Linux....
![screen shot 2018-08-01 at 17 05 33](https://user-images.githubusercontent.com/552417/43533658-3c93a97c-95ad-11e8-8b78-81ff251a4f96.png)

**Comment by benfrancis** [comment]
Broken for me on Firefox stable on Mac:
![screen shot 2018-08-01 at 17 13 19](https://user-images.githubusercontent.com/552417/43534075-5a600d14-95ae-11e8-8f25-f654918f2dd7.png)

So it appears to be a Firefox vs. Firefox Nightly thing, probably a bug that has been fixed or web components feature that has been implemented and needs to ride the trains.

**Comment by hobinjk** [comment]
Sorry, I completely misread this issue the first time I checked it out. I can develop a fix for this soon
