### ISSUE TITLE
Error in image/add-gateway.sh script

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/gateway#1225]
Running this in a VM which might be contributing to the issues:
```
Unzipping './gateway-0.5.0-pre1-base.img.zip' to './gateway-0.5.0-pre1.img.img'
read error, sector 0
read error, sector 1
read error, sector 29
/dev/mapper/loop
read error, sector 0
read error, sector 1
read error, sector 29
Loop mounts created successfully
mount: /home/hobinjk/tmp/rpi-boot: special device /dev/mapper/loop does not exist.
Failed to mount boot partition
Removing boot mountpoint rpi-boot
Removing loop mounts
loop deleted : /dev/loop7
```

@dhylands any idea what could be going on here?

**Comment by dhylands** [comment]
The uncompressed size of that image is 3.6 Gb (plus 1.1 Gb for the zipfile).

**Comment by hobinjk** [comment]
Thanks for the tips! I was running the add-gateway script inside one of the VM's shared folders which apparently confused everything. It worked after a simple `cp -r`
