### ISSUE TITLE
Thing icons no longer vertically centered

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1231]
0.5-pre3

![screen shot 2018-07-31 at 21 47 09](https://user-images.githubusercontent.com/552417/43486293-61e6844e-950b-11e8-9577-d141d36b1b52.png)

Likely another regression from #1222

**Comment by sunilkumarvalmiki** [comment]
can i take this task...

**Comment by hobinjk** [comment]
Sorry, there's already a fix in-progress in PR #1233. Thanks for asking though!

**Comment by benfrancis** [comment]
I think this is already fixed in https://github.com/mozilla-iot/gateway/pull/1233, but feel free to take another one!
