### ISSUE TITLE
Error running prepare-base.sh

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#1241]
I just finished building a base image and saw this error:
```
Now using node v8.11.3 (npm v5.6.0)
Creating default alias: default -> lts/carbon (-> v8.11.3 *)
Now using node v8.11.3 (npm v5.6.0)
hostapd.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable hostapd
Synchronizing state of dnsmasq.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable dnsmasq
cp: cannot stat 'config/hostapd.conf': No such file or directory
```

That comes from: https://github.com/mozilla-iot/gateway/blob/6724d401cee3ca278b5f448c9d5adcfccd1910b3/image/prepare-base-root.sh#L23

Those files originated from here:
https://github.com/mozilla-iot/gateway-wifi-setup/tree/master/config

So I think that they might need to relocated if we're using a merged gateway/wifi-setup

**Comment by hobinjk** [comment]
Sorry, thought that prepare-base-root ran in the image directory, not the gateway directory. The path should now be correct

**Comment by dhylands** [comment]
Yeah - prepare-base.sh is copied to the home directory by make-prep.sh.
I updated my PR to use HERE documents and removed the copies of the files.
Testing now...
