### ISSUE TITLE
Remove -> add -> remove loop can conflict and fail

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/gateway#1252]
The root cause is that the add/remove mechanism in src/addon-manager.js uses only one Deferred for each under the hood. This can cause weird timeouts and unexpected failures.

Easy but potentially adapter-incompatible solution: enable add and remove to overlap
Hard but definitely workable solution: Add feedback and logic to the UI to properly inform the user when add/remove are conflicting and improve the add cancellation logic to be less glitchy

**Comment by dhylands** [comment]
At least with zwave, the add and remove can't overlap.
