### ISSUE TITLE
Add web app manifest so gateway can be pinned to home screen

### ISSUE THREAD

**Issue by freaktechnik** [mozilla-iot/gateway#1253]
It'd be nice if the gateway could be pinned to the home screen as "PWA" by having a web app manifest.

**Comment by benfrancis** [comment]
It already has one! :)

**Comment by freaktechnik** [comment]
Then the bug is "make it so Firefox for Android detects it" I guess?

**Comment by benfrancis** [comment]
It works for me. What version of Firefox are you using?

![screenshot_20180803-180704](https://user-images.githubusercontent.com/552417/43655870-32cf29a6-9748-11e8-9623-98761d6e4a73.png)

**Comment by freaktechnik** [comment]
I'm using nightly. And I use the gateway via "hostname" DNS of my router instead of mDNS or an external URL (though that shouldn't matter, based on what's in the manifest).

**Comment by benfrancis** [comment]
I think Firefox requires a manifest to be served over HTTPS before it will show the add to home button, I'm guessing your local domain isn't using SSL?

**Comment by freaktechnik** [comment]
It isn't yes, good point.
