### ISSUE TITLE
"THING" text is truncated on rules view SVG thing-icon, on Linux; looks like "[HIN("

### ISSUE THREAD

**Issue by dholbert** [mozilla-iot/gateway#1256]
STR:
 1. View this SVG image, over a dark background (it has white text):
https://github.com/mozilla-iot/gateway/blob/master/static/optimized-images/rule-icons/thing.svg

(For me, this icon shows up in my gateway's Rules view, for now-invalid rules associated with some virtual devices which I've removed by virtue of having deactivated the virtual-devices addon)

EXPECTED RESULTS:
The icon should look reasonable.

ACTUAL RESULTS, on Linux:
The first and last letter are truncated, so it looks kinda bizarre/hard-to-understand/broken. Screenshot (from my gateway's rules view):
![selection_027](https://user-images.githubusercontent.com/426803/43688453-01af0a42-989e-11e8-9775-068ed64c95f2.png)

This probably depends on the platform and the fonts available. It looks like this icon is simply comprised of "real" text (not paths), rendered with whatever font the system would like to use, with the request for "Open Sans Bold" (but my system does not have Open Sans Bold so it uses DejaVu Sans Bold which is a bit wider than the space available).

**Comment by dholbert** [comment]
Some possible solutions:
 - "flatten" the text to paths in InkScape, so that it renders reliably regardless of fonts available.
 - Use a monospace font, which may have a more predictable width regardless of actual font choice, and allow a bit more extra space in case of an unexpectedly wide local font.

**Comment by dholbert** [comment]
CC @hobinjk who's got edit history for this icon.
Here's a standalone data URI testcase, using the SVG image hosted by my own gateway:
data:text/html,<img style="background:black" src="https://eagle.mozilla-iot.org/optimized-images/rule-icons/thing.svg">
For me, that ^^ testcase looks like this:
![selection_028](https://user-images.githubusercontent.com/426803/43688511-120fcb8c-989f-11e8-8e92-bf5add6abb0d.png)

I'm using Firefox Nightly on Ubuntu 18.04, FWIW.  It's similarly clipped in Chrome on the same machine (not quite as severely, but still somewhat clipped).

**Comment by jaller94** [comment]
Implying the font should stay the same:
As mentioned, converting the texts to paths would be a good option.
How to preserve the original SVG? Outside of the repository or in a different folder?

Should there be a building step when adding or changing an SVG?
This would require an SVG manipulator and Open Sans (Bold) to be installed on the build system.
For Inkscape: `inkscape input.svg --export-plain-svg=output.svg --export-text-to-path`

Are other SVG graphics affected?

**Comment by jaller94** [comment]
I just noticed that the svgs already get processed and the originals are included in the repo.

Originals: [`gateway/static/images`](https://github.com/mozilla-iot/gateway/tree/master/static/images)
Optimized: [`gateway/static/optimized-images`](https://github.com/mozilla-iot/gateway/tree/master/static/optimized-images)

The build steps are here: [`gateway/tools/optimize-images.js`](https://github.com/mozilla-iot/gateway/tools/optimize-images.js)

The tool SVGO is already used, however, it does not seem to support the conversion of text, which is not a simple shape, to paths. [Link to parameters](https://github.com/svg/svgo#what-it-can-do)

**Comment by dholbert** [comment]
> Are other SVG graphics affected?

None that I've seen, in my usage of the gateway.

And `grep` says that there are only two files in optimized-images that contain the string `<text`:
 - the SVG icon being discussed here in optimized-images/rule-icons/thing.svg
 - another icon also called "thing.svg" but in the in the "thing-icons" directory, rather than the "rule-icons" directory.  e.g. here using my gateway's copy of that one:
`data:text/html,<img style="background:black" src="https://eagle.mozilla-iot.org/optimized-images/thing-icons/thing.svg">`
That other one has more space around the text, so there's no clipping (though it's "affected" in the sense of requesting & not getting Open Sans)

**Comment by hobinjk** [comment]
Thanks for the report! A while back I (or Ben, not exactly sure) went through and flattened all the uses of `<text>` into paths due to this exact issue popping up. I missed the introduction of these new `<text>` uses but will apply the same flattening to these miscreants

**Comment by hobinjk** [comment]
In this case I'm not too sad about losing the original in-repo svgs since they're both very simple but an ideal solution would preserve them

**Comment by benfrancis** [comment]
Just to note: This is kind of a shame from an accessibility point of view (assuming screen readers can read SVG text).

As a longer term solution I'm wondering if it's possible to use the .woff fonts we're already hosting on the gateway in SVG via CSS?

**Comment by dholbert** [comment]
> Just to note: This is kind of a shame from an accessibility point of view (assuming screen readers can read SVG text).

Agreed in spirit, though in this case, I don't think screen readers had access to the text anyway, because the gateway software is displaying the SVG content via `<img src="...svg">`.

(I don't think we have any API for digging into imagelib and exposing the text inside images that happen to really be SVG.  If we were referencing this SVG content in a "document-flavored" context -- i.e. with its `<svg>`, `<text>`, etc. DOM nodes being actual nodes in the top-level document or in an iframe -- then screen readers would have access, I think.)

The best bet for making this image accessible would be to add alt-text via the `alt` attr, I think -- which we don't seem to use here right now.  The image markup looks like:
  `<img class="rule-part-icon" src="/optimized-images/rule-icons/thing.svg">`

That's fodder for another issue, though. Thanks for fixing this one!

**Comment by dholbert** [comment]
> As a longer term solution I'm wondering if it's possible to use
> the .woff fonts we're already hosting on the gateway in SVG via CSS?

Unfortunately that won't work as easily as you might hope -- `<img>` elements aren't allowed to reference external resources.

I think we'd have to encode the .woff files as a data URI and reference it from inside the SVG content that way (so that it's not "external").

Alternately [but probably less-good], we could use `<embed>` (which is kinda iframey and is allowed to load external resources) instead of `<img>`.  But that also would foil some image-rasterization-caching optimizations that we've got.  So the data URI solution is probably best -- that, or just throwing up our hands and treating the SVG file as a vector graphic which happens to represent text, like we're doing now, and try to accompany it (and other images) with alt-text to help out a11y folks.

**Comment by benfrancis** [comment]
.woff files as data URLs are going to be huge!

Of course the other consideration is localisation. Every time we turn text into a path we make that harder.

I'll keep thinking.
