### ISSUE TITLE
Visual feedback of command success

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/gateway#1259]
As a user I want visual feedback to indicate my command was successful

For example, the message box containing "Okay, turning on the kitchen light" would get the kitchen light's webcomponent plonked into it.

**Comment by benfrancis** [comment]
Thanks for adding this after our discussion today. FWIW, I'm not 100% convinced about this idea yet.

**Comment by hobinjk** [comment]
Oh, I thought you'd be 110% convinced since it's similar to your mockups where there's a device icon prefacing each reply:
![](https://user-images.githubusercontent.com/552417/39375342-f2b32e66-4a45-11e8-8ce6-b591ff7c8b66.png)

I do acknowledge that the current component views might not be ideal for this purpose

**Comment by benfrancis** [comment]
I've morphed this into a general "visual feedback" user story and we can figure out the UI design later.
