### ISSUE TITLE
Read-only properties

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1261]
As a user I would like to be able to tell whether a property can be modified or whether it is read-only information so that I don't try to set a read-only property

Depends on https://github.com/mozilla-iot/wot/issues/38

**Comment by webwurst** [comment]
I have a fridge connected to a TP-Link switch to measure power consumption. But I don't want to accidentally switch it off. So it would be nice if a user could edit a thing in the user interface and set a property to read-only although the device accepts different values.

**Comment by benfrancis** [comment]
> I have a fridge connected to a TP-Link switch to measure power consumption. But I don't want to accidentally switch it off. So it would be nice if a user could edit a thing in the user interface and set a property to read-only although the device accepts different values.

That might be better addressed through [permissions](https://github.com/mozilla-iot/gateway/issues/787). Perhaps if the current user can't write to a property then then writable should be set to false in the Thing Description.

**Comment by benfrancis** [comment]
https://github.com/w3c/wot-thing-description/issues/209#issuecomment-420537155 seems to indicate that the W3C spec will be updated from `writable` to `readOnly`, but I'm not 100% confident that is going to happen.

I'm going to leave it up to @mrstegeman to keep an eye on the situation and make a call one way or another while I'm on PTO (personally I think just going ahead and implementing `readOnly` is probably the the least bad option).
