### ISSUE TITLE
Proposal: production shouldn't run webpack at all

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/gateway#1273]
When running in production go directly to `node build/gateway.js`, skipping webpack. On the Pi, only bundle the production `node_modules`

Pros:
- Reduces node_modules size significantly (currently 500M)
- Will boot almost instantly
Cons:
- Makes local development require running `yarn` and some kind of flag to get the systemd service out of production mode

**Comment by hobinjk** [comment]
Another interesting approach is flattening all the dependencies which gets us down to ~250M but will likely cause bugs due to api changes between dependency versions

**Comment by benfrancis** [comment]
This sounds right to me because I wouldn't have thought we should need to build on every boot, but I really don't know enough about webpack to know how it's intended to be used in production.

They do have documentation around production builds but we may already be doing a lot of this https://webpack.js.org/guides/production/

**Comment by hobinjk** [comment]
Unfortunately, the main benefit of not running webpack at all is that we don't have to pull in all of the support modules that webpack needs to function. For example, just the top-level babel dependency we use to turn our fancy JS into JS that even IE could understand is 67MB. We can also take out the test support infrastructure and leave only the smallest set of runtime dependencies.

As far as I can tell the main benefit of production mode is that webpack runs additional optimizations passes on the output files which would have the opposite of the desired effect, but could be a nice way to eke out a couple more percentage points of performance.

**Comment by mrstegeman** [comment]
I believe this is now done. See e66fe3b8136be1c99410d937fa1b7e90f0c0d285.
