### ISSUE TITLE
Paired devices get out of sync

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#1275]
When you remove a device from the gateway, it first asks the adapter to unpair the device, and then removes the device from the device list whether it was unpaired or not.

In the event that the device doesn't unpair, the gateway now has no way to re-add the device, since the device is still paired, but the gateway has no way to know about it since it doesn't show up in the device list.

The device should only be removed from the device list if it was successfully unpaired. This may also mean that the adapter needs a mechanism to indicate whether it was successfully unpaired or not. Due to delays, this should probably be an async mechanism (from the adapter to the gateway) and not rely on a timeout.

For example, with zigbee devices, some devices don't support the "leave network" command at all. Others may reply, but it may takes 10's of seconds or even minutes before the response is received.

With zwave devices, the user may not press the button on a device, and thus the device doesn't become unpaired.

**Comment by benfrancis** [comment]
I think we need to re-consider the user interface for un-pairing and consider separating "remove" from "unpair" so that we can better represent the actual state to the user.

**Comment by benfrancis** [comment]
See also #1334

**Comment by mrstegeman** [comment]
We've decided to leave this clean up to individual adapters, now that they receive a list of saved devices (#2143).
