### ISSUE TITLE
DoorSensor Capability

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1276]
As a device developer I want to tell the gateway that my device acts as a door (or window) sensor.

Proposed UI design:
![door_sensor](https://user-images.githubusercontent.com/552417/44285514-988f8180-a25d-11e8-84c6-eaf43e4e92da.png)

![door_sensor-closed](https://user-images.githubusercontent.com/552417/44285578-c7a5f300-a25d-11e8-9501-c6dfc21975ed.png)

![door_sensor-open](https://user-images.githubusercontent.com/552417/44285583-cc6aa700-a25d-11e8-826b-617629b78974.png)

Depends on defining a new DoorSensor capability schema.

**Comment by dhylands** [comment]
Is a door sensor any different from a window sensor? How would the user specify how the sensor is being used?

**Comment by benfrancis** [comment]
Some are sold as "door sensors" and some are sold as "window sensors", they're the same thing, the difference is purely semantic. 

Users can specify how the sensor is being used by giving it a different name like "Lounge Window" or "Cat Flap"!

Is it really worth defining a separate WindowSensor capability? DoorOrWindowSensor is a bit clunky! Another possibility I considered was calling the capability ContactSensor which covers both, but at the UI level this is probably harder for users to understand as the products tend to be sold as either a "door sensor" or "window sensor".

We could use different terms at the API level and the UI level, but if there's not a 1:1 mapping that's going to make things complicated.

**Comment by benfrancis** [comment]
See https://github.com/mozilla-iot/schemas/issues/10 for discussion around the schema.

**Comment by dhylands** [comment]
I agree that the difference is purely a semantic one. I think that as long as the user can select an appropriate icon (maybe this is even already implemented) then I think it should be fine.

**Comment by dhylands** [comment]
The zigbee spec allows for devices like these to report "restore" events or not. i.e. some devices will only report an "open" event and some devices will report an "open" and "close" event. For the ones which only report "open" then you're supposed to use a timeout to generate the close event if you need it. The timeout should probably be configurable (another example of a per-device configuration option). Maybe this is just a case of adding a property to allow the timeout to be set.

**Comment by benfrancis** [comment]
> For the ones which only report "open" then you're supposed to use a timeout to generate the close event if you need it.

That sounds bad. Is there not a queryable open/closed state? If you just assume the door has closed itself, we could be reporting that a door is closed when the door is in fact open.

> The timeout should probably be configurable (another example of a per-device configuration option). Maybe this is just a case of adding a property to allow the timeout to be set.

I think you're right this an example of per-device configuration. It doesn't represent any state in the real world, just an internal configuration. We still don't have a good solution to that.

**Comment by dhylands** [comment]
> For the ones which only report "open" then you're supposed to use a timeout to generate the close event if you need it.
> 
> That sounds bad. Is there not a queryable open/closed state? If you just assume the door has closed itself, we could be reporting that a door is closed when the door is in fact open.

Battery sensors can't be queried (in general). The only time you can talk to them is when they decide to talk to your. So while you can query the state, it might not happen for some time. There is a bit that tells whether it reports "restore" events or not. So far, the only place I've seen this is for motion sensors,

**Comment by benfrancis** [comment]
> The only time you can talk to them is when they decide to talk to you. So while you can query the state, it might not happen for some time.

Presumably this is something we should handle at the adapter level by caching state though? Fundamentally the web layer has the concept of properties that can be read, the state doesn't necessarily have to be 100% up to date, just the last known state.

I can understand if a motion sensor has a timeout, but door sensors are either open or they're closed. Have you seen any contact sensors which don't report a transition to a closed state?

**Comment by dhylands** [comment]
The adapter currently caches the state and persists it to disk, so it will have the last know state even if the gateway restarts.

I'm not aware of any contact sensors which don't report a transition to closed, just saying that the spec allows for it.

**Comment by mrstegeman** [comment]
Icons, please.

**Comment by benfrancis** [comment]
mini icon with circle: https://drive.google.com/file/d/1VU5iwqsAkFKIg_YHJwitioWAl5i4KGYI/view?usp=sharing

Icon without circle (open, white): https://drive.google.com/file/d/17r2Scjo1x_lRLNA1Wz07fcs2dGpJ4whL/view?usp=sharing

Icon without circle (open, blue): https://drive.google.com/file/d/1rqiYRzRTjSxliNx8CokUJYisQC3XgBG5/view?usp=sharing

Icon without circle (closed, white): https://drive.google.com/file/d/1Elj99XvYEzpxXiHJ9IW22o_uAbnCBnh0/view?usp=sharing
