### ISSUE TITLE
MotionSensor Capability

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1277]
As a device developer I want to tell the gateway that my device acts as a motion sensor.

Proposed UI design:
![motion_sensor](https://user-images.githubusercontent.com/552417/44285641-105dac00-a25e-11e8-82a9-6c35bb95c299.png)

![motion_sensor-no_motion](https://user-images.githubusercontent.com/552417/44285673-35eab580-a25e-11e8-93b4-3330c27ce530.png)

![motion_sensor-motion](https://user-images.githubusercontent.com/552417/44285682-3c792d00-a25e-11e8-8b6a-8b8090998307.png)

Depends on defining a new MotionSensor capability schema.

**Comment by benfrancis** [comment]
See https://github.com/mozilla-iot/schemas/issues/9 for discussion around the schema.

**Comment by kgiori** [comment]
For motion/PIR sensors, I've seen device vendors signify the use case with an icon of a [stick person walking](https://www.instructables.com/id/Motion-Sensor-Arduino/) with some sort of motion lines, or a stick person walking with shadows to reflect movement. This image of a dot with motion lines on each side is more like the representation of a standard "wireless signal". Of course the text "motion" and "no motion" helps clarify. :)

**Comment by benfrancis** [comment]
Yeah I've struggled a bit with this icon design, I had the same concern as you about it looking like a wireless transmitter of some kind.

Quite a common icon seems to be a person running with (( )) marks around them to indicate motion:

![](https://monnit.azureedge.net/content/product_images/profiles/Motion.jpg)

For some reason this didn't seem to fit very well with the general icon theme (I didn't like having the stick man), but maybe I'll try again.

**Comment by mrstegeman** [comment]
Icons, please.

**Comment by benfrancis** [comment]
Revised icon design:
![motion_sensor](https://user-images.githubusercontent.com/552417/44801953-61e92d80-abb2-11e8-94c9-46671c912bd5.png)
![motion_sensor-no_motion](https://user-images.githubusercontent.com/552417/44801967-67df0e80-abb2-11e8-89e1-135e9491893b.png)
![motion_sensor-motion](https://user-images.githubusercontent.com/552417/44801975-6ca3c280-abb2-11e8-9004-72e19b681063.png)

@mrstegeman What assets are needed exactly? Just the image part of the icon? Full size and mini versions? With or without the circle?

**Comment by dhylands** [comment]
Shouldn't the "No Motion" icon just have the man without the curved lines which indicate motion?

**Comment by benfrancis** [comment]
I tried that, but then it looks like a person walking, which is confusing. So I could make the person stand still but then it just looks like a sign for the toilet/restroom ;)

<img width="100" src="https://user-images.githubusercontent.com/552417/44803155-8397e400-abb5-11e8-8e6e-11ee79644553.png">

**Comment by benfrancis** [comment]
What do other people think? Is this not confusing on its own?

![motion_sensor-no_motion2](https://user-images.githubusercontent.com/552417/44803500-8d6e1700-abb6-11e8-9b0f-a4d4058232ba.png)

**Comment by mrstegeman** [comment]
@benfrancis Yes, we'll need the capability icons, with and without circle.

**Comment by benfrancis** [comment]
How about this?

![motion_sensor2](https://user-images.githubusercontent.com/552417/44805000-f48dca80-abba-11e8-85d7-f3cca12283a9.png)

FWIW the reason I didn't use a person in the icon in the first place was because a stick figure of a person on its own doesn't really tell you the device is a motion sensor.

**Comment by benfrancis** [comment]
Icons:

Motion sensor mini icon (with circle): https://drive.google.com/file/d/10U7AauHt4PpnKX28-0SGGDsUOBRXBM10/view?usp=sharing

Motion sensor - no motion: https://drive.google.com/file/d/19g6IR92bjHJX8QPbP1TgL00admF4wWo9/view?usp=sharing

Motion sensor - motion: https://drive.google.com/file/d/1eZ1vYmzXfzML1NJXt__jXRQC5Dkf9jGM/view?usp=sharing
