### ISSUE TITLE
PushButton Capability

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1278]
As a device developer I want to tell the gateway that my device acts as a push button.

Proposed UI design:
![push_button](https://user-images.githubusercontent.com/552417/44285785-a72a6880-a25e-11e8-912b-378d27274a80.png)

![push_button-not_pressed](https://user-images.githubusercontent.com/552417/44285793-adb8e000-a25e-11e8-8d22-b0a2b766ef9b.png)

![push_button-pressed](https://user-images.githubusercontent.com/552417/44285798-b3162a80-a25e-11e8-8514-65cef0c3340a.png)

Depends on defining a new PushButton capability schema.

**Comment by dhylands** [comment]
Some buttons also support multi-click detection and reporting. The xiaomi one I've been playing with does. For the xiaomi one, the simplest way was to add a separate multiClick property which indicated the number of clicks (2-5).

**Comment by twobraids** [comment]
In a conversation from Slack, I noted that I never experienced a non-mouse physical button in the real world that required a double click. @dhylands comment does remind me of a push button that responded differently to multiple clicks.  It is used in a wretched user interface to control features of a vaping pen.  Now I must to concede, multi-click button pushes (even beyond double click) are a legitimate use of a PushButton.  If a device is capable of detecting it, we ought to support it.  Does that mean that we ought to simulate support for momentary push buttons not natively capable?

**Comment by benfrancis** [comment]
As discussed on Slack, we may have events for different types of button press (e.g. long press, double click). We should probably discuss the schema separately though (I'll file issues in the schema repo), as events don't show up in this UI.

**Comment by benfrancis** [comment]
See https://github.com/mozilla-iot/schemas/issues/8 for discussion around the schema.

**Comment by kgiori** [comment]
I think that similar to the motion sensor and door/window detector, it might help to add TEXT to these icon images, especially in preparation for complex presses. 
- pressed
- not pressed
- double click
- long press
- hold

**Comment by kgiori** [comment]
I think that similar to the motion sensor and door/window detector, it might help to add TEXT to these icon images, especially in preparation for complex presses. 
- pressed
- not pressed
- double click
- long press
- hold

**Comment by dhylands** [comment]
If we decide to make something like the sylvania button look like a pushbutton (if this even turns out to be possible), it only generates high level events. So you'll only get one event per press/release.

**Comment by benfrancis** [comment]
What do you mean by "high level events"? I would describe just a pushed event and a released event as "low level events".

> So you'll only get one event per press/release.

One event for a press and one event for a release, or one event per press & release combination (i.e. a "click")?

**Comment by benfrancis** [comment]
> 
    pressed
    not pressed
    double click
    long press
    hold
If we include double click and long press in the schema they will be events rather than properties so I don't think we should display them on the button, because they only apply for an instant in time, they are not a state as such.

I experimented with putting text on the button but the challenge (the same as with the ambiguity people have commented about with the on/off icon) is that usually text on buttons is a label telling you what a button does, not telling you its current state.

I do think this icon design is a bit abstract though so I'll revisit it.

**Comment by dhylands** [comment]
> What do you mean by "high level events"? I would describe just a pushed event and a released event as "low level events".
> 
> So you'll only get one event per press/release.
> 
> One event for a press and one event for a release, or one event per press & release combination (i.e. a "click")?

One event for a press & release. For something like the sylvania 4-button device it will probably be something like a toggle command being broadcast. Since the button can also be used for dimming, it will probably send a toggle on a press/release and send level-controls on a press/hold.

**Comment by mrstegeman** [comment]
Icons, please.

**Comment by benfrancis** [comment]
Revised icon design:
![push_button](https://user-images.githubusercontent.com/552417/44802124-d02df000-abb2-11e8-94bf-e4340aadca5f.png)
![push_button-not_pressed](https://user-images.githubusercontent.com/552417/44802190-f6539000-abb2-11e8-8452-63f5db00978d.png)
![push_button-pressed](https://user-images.githubusercontent.com/552417/44802153-dcb24880-abb2-11e8-9ffd-56636229d54b.png)

**Comment by benfrancis** [comment]
@twobraids wrote:
> That's a confusing set of icons - the repetition of labeling and use of the property name in the domain of the property value does not promote clarity.

It's tricky to reconcile @kgiori's feedback that there should be text on the button with your feedback that there's too much repetition of labeling.

I agree the detail view looks confusing. Part of that is the fact that it's a detail view for a device which only has one property. We didn't used to bother expanding out devices with only one property, but when we added edit and remove functions to the detail view and links from the floorplan it required having a detail view for every device.

I suppose for specific schemas we could just not show a bubble for a single property if all the information is communicated by the main icon. I'm not sure if that inconsistency might get confusing if a sensor has additional properties though, like a door sensor which also happens to have a temperature sensor in it.

**Comment by twobraids** [comment]
I think the confusion is almost entirely from the name of the property and its domain of values, not idea that it is an expansion of a thing with only one property.

This simple rule could clear things up: if saying out loud what shows in the UI about the relationship between the property and its value leads to an absurd sentence, then the naming is problematic.  "Pushed is Not Pushed" makes no sense.  However, "Status is Not Pushed" or "Pushed is False" makes sense.  

What makes sense to the user is not necessarily the same as to what makes sense to the programmer.  In the UI, making sense to the user is more important than making sense to the programmer. 

If the domain of a property is an enumeration of strings, then the property name should be generic and not a selection from the domain: status ← one of {"pushed", "not pushed"}.  If the property name implies a boolean state, the domain should be boolean:  pushed ← one of {True, False}.

**Comment by benfrancis** [comment]
> I think the confusion is almost entirely from the name of the property and its domain of values, not the idea that it is an expansion of a thing with only one property.

Ah OK, well if the issue is the label on the property bubble then that's not really fixed by the UI design, it can be specified by the web thing author. They could use "Status" rather than "Pushed" in their Thing Description for example. (The reason I try to avoid generic terms like status is because it quickly breaks down with multiple properties).

I understand your point though, I suppose we might want to put more thought into what labels our own adapters use.

So apart from the label on the property bubble, is this still confusing? Is the repetition of the PUSHED/NOT PUSHED text too much? If so then I can remove it from the button again. Or even try removing the property bubble entirely.

**Comment by mrstegeman** [comment]
Let's not go down the path of selectively removing property bubbles again. If you have a multi-sensor device, you'll absolutely want all properties shown.

**Comment by twobraids** [comment]
Feedback from my partner looking at these images, he expresses confusion over the value the property repeated in both the property and the central bubble.  In fact, he finds that confusing even when there are multiple properties.  When the thing icon is not expanded, that text is active.  When the thing icon is expanded, that text is no longer active, but there is no visual feedback to indicate that.

Perhaps just leave off the text in the central icon in expanded mode?  That way one would be less lured into trying to click it and the repetition with a property wouldn't be a source of confusion.

**Comment by benfrancis** [comment]
> Let's not go down the path of selectively removing property bubbles again. If you have a multi-sensor device, you'll absolutely want all properties shown.

I tend to agree. All my motion sensors and door sensors also have temperature sensors, which makes it a bit less confusing because there are multiple properties.

**Comment by twobraids** [comment]
@benfrancis, you are right regarding my statement about the central icon being clickable ("active" in my previous post).  Not sure why I thought is was not.  I have a recollection of clicking one and it doing nothing, but I cannot reproduce that behavior.

> Was your assumption that you would be able to click the virtual button as well?
Actually, yes.  As I am currently working on writing a virtual on/off button, my thought process was influenced by that.  I understand that for a physical button, it must be read-only because a physical button may have a literal physical indication of state.

**Comment by benfrancis** [comment]
> I have a recollection of clicking one and it doing nothing, but I cannot reproduce that behavior.

I think it may have been that way before the web components refactor in 0.5.

**Comment by benfrancis** [comment]
Thanks to @mrstegeman for the suggestion of a side profile of the button.

![push_button](https://user-images.githubusercontent.com/552417/44918496-0c885a00-ad33-11e8-9fe3-9120694fb421.png)

![push_button-not_pressed](https://user-images.githubusercontent.com/552417/44918507-13af6800-ad33-11e8-97d1-1639a1d39f12.png)

![push_button-pressed](https://user-images.githubusercontent.com/552417/44918525-1d38d000-ad33-11e8-9676-209e46b4953b.png)

Is that better?

**Comment by mrstegeman** [comment]
I personally find this to be much more understandable.

**Comment by mrstegeman** [comment]
@benfrancis I still think it would be fine to include "PUSHED" and "NOT PUSHED", just so that it's more in line with our other icons.

**Comment by benfrancis** [comment]
OK, final version:
![push_button](https://user-images.githubusercontent.com/552417/44920218-4196ab80-ad37-11e8-8d7a-4978dc55da92.png)

![push_button-not_pushed](https://user-images.githubusercontent.com/552417/44920886-f7aec500-ad38-11e8-9a4c-eb63380ceb88.png)

![push_button-pushed](https://user-images.githubusercontent.com/552417/44920237-4eb39a80-ad37-11e8-98ee-e0da4816e690.png)

**Icons**
* [Push button - mini icon with circle](https://drive.google.com/file/d/1jdotdt4kq-xGEEsVajSloNUNJWN5rF7b/view?usp=sharing)
* [Push button - not pushed](https://drive.google.com/file/d/14368oyztdwDEcvg6KymgYpYOMpuidjXr/view?usp=sharing)
* [Push button - pushed](https://drive.google.com/file/d/1XNnrD-PgjNkTYMrmFgfngIYXNh0IaMbh/view?usp=sharing)

@twobraids Note that the developer can use whatever label they like for the property. I'm personally struggling to think of a better name than "Pushed" or "Pushed/Not pushed" which still works when there are multiple properties.
