### ISSUE TITLE
Full author support in package.json

### ISSUE THREAD

**Issue by blackfyre** [mozilla-iot/gateway#1289]
Currently the Gateway's Add-ons menu only supports the simple `author` value of the package.json file:

```json
{
  "author": "John Doe",
}
```

Ideally the complex version should be supported as well:

```json
{
  "author": {
    "name": "Galicz Miklós",
    "email": "gnick666@gmail.com",
    "url": "https://blackfyre.ninja/"
  }
}
```

If there's a complex `author` field, the Add-ons list outputs `[object Object]` instead.
![image](https://user-images.githubusercontent.com/1991410/44483957-ba697980-a64c-11e8-82ae-9c7bae765d87.png)

**Comment by benfrancis** [comment]
Note that you can now provide a homepage and license URL

See https://github.com/mozilla-iot/addon-list/blob/master/list.json for examples
