### ISSUE TITLE
Settings scrolling issues

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1290]
I've noticed some bugs which are probably regressions from #1270.

STR:
* Enter responsive mode with a small screen size (e.g. 320x480)
* Go to Settings
* Scroll down
* Select an option

Expected:
* The relevant setting screen opens in the start position (not scrolled)

Actual:
* The UI elements are scrolled off the screen
* In some cases the + button is not fixed at the bottom of the screen

Basically I think each setting needs to be a separate scrollable element. I'm pretty sure this used to work so I'm not sure what we broke :(

**Comment by hobinjk** [comment]
I know what I broke and will have a fix out soon.

**Comment by hobinjk** [comment]
(It's just going to require rewriting every single settings title)

**Comment by benfrancis** [comment]
My bad, I should have tested more thoroughly in review!

I have noticed that re-using the title element across settings is a bit laggy, the text visibly changes before the icon updates. If the fix could improve that it would be an added bonus!
