### ISSUE TITLE
Smart Assistant says "Sorry, I didn't understand that" when unable to complete a command

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/gateway#1297]
- Connect a tp-link bulb
- Turn off the bulb so that any attempt by the gateway to interact with it fails
- Give the command "Turn the bulb red"
- Smart assistant replies "Sorry, I didn't understand that"

The assistant should instead reply with "I'm sorry ${username}, I'm afraid I can't do that"

**Comment by benfrancis** [comment]
> The assistant should instead reply with "I'm sorry ${username}, I'm afraid I can't do that"

LMAO. Yes.
