### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1299]
As a user I want to log data from my sensors so I can see trends in data over time.

**Comment by benfrancis** [comment]
Some very rough early thoughts on UI design:
![logging](https://user-images.githubusercontent.com/552417/44597693-700d0780-a7c8-11e8-83f4-daff99ee80ce.png)

**Comment by kgiori** [comment]
In addition to how long to keep data, I think that the log options page (middle screen) should have a frequency option. For temp I might only want once every 4 hours. For power maybe once a minute. If we implement rrd (round robin database) format then how long you keep it is irrelevant. The dB stays the same size but older data is smoothed out.

**Comment by mrstegeman** [comment]
Requires #173

**Comment by benfrancis** [comment]
@kgiori wrote:
> In addition to how long to keep data, I think that the log options page (middle screen) should have a frequency option. For temp I might only want once every 4 hours. For power maybe once a minute.

That would work well for continuous values like temperature, but not so well for discrete values like open/closed. In the latter case I probably want to log every change in state.

**Comment by benfrancis** [comment]
I've made some more progress on designing the logging screen.

![logging2](https://user-images.githubusercontent.com/552417/45228364-ea568500-b2ba-11e8-86dc-b1e2851efce6.png)

I'm starting to realise that even these basic logging features are probably too much work to fit into the 0.6 release.

@hobinjk what do you think? Should we be punting this to the next release so we can do it justice?

**Comment by hobinjk** [comment]
Sorry for not replying to this earlier. I think this looks mostly good. For navigating the graphs I think it makes more sense to expose standard graph controls (drag to move around, scroll wheel to zoom in/out) and do away with the global time drop-down. Any range selection would then propagate between the graphs. There's also no way to reorder graphs.

I should be able to hack something together in d3 with my existing prometheus work. I think this is way too ambitious for the current 0.6 cutoff of Friday but might work well as an experiment.

**Comment by flatsiedatsie** [comment]
A lot of existing smart home solutions allow you to see graphs for a specific device. This makes comparisons an analysis difficult. For example, how do temperature and humidity relate? How long after switching on the heater does the temperature start to rise?

A useful feature is to be able to overlay graphs, or at least put related ones together and give that 'view' a name.

One example of a system that in my professional opinion does this well is Homey. Here's a video of how they did it:
https://youtu.be/bB6-vYxi924?t=14

**Comment by flatsiedatsie** [comment]
In my experience having a 'day/month' button is very useful, as it allows you to quickly reset the graph to a certain length.

Another nice feature is to be able to select a certain part of the graph, and have it zoom into that selection. That way you can quickly explore an anomaly.

If there was a more advanced grouping feature ([mocked up in this issue](https://github.com/mozilla-iot/gateway/issues/1383)), then these groups could also be the UX for selecting which graphs would be shown close together (or even overlayed).

![group-datalog](https://user-images.githubusercontent.com/805405/51533126-e0808900-1e39-11e9-9d21-1dc59666b136.png)

**Comment by rzr** [comment]
I am wondering how can time series can be exported or queried

**Comment by hobinjk** [comment]
The endpoints I'm currently using are
`/logs/things/${thingId}/property/${propertyName}` for an array of a property's values over time
`/logs/things/${thingId}/` for an object containing arrays of all the thing's property's values over time
`/logs/` for an even bigger object containing all the things

All of these endpoints will take a `start` and `end` query parameter so you can do `/logs/?start=${Date.now() - 60 * 1000}&end=${Date.now()}` for the last minute of information

I'm interested if you think there are other useful features/endpoints that logging could provide (e.g. if streaming seems useful)

**Comment by hobinjk** [comment]
@benfrancis Could I get svg files for the logs icon? I've been using the rules icon as a placeholder for so long that I almost forgot. It would also be nice to get icons for reset zoom (up arrow might be good) and expand into View Individual Log (maybe like the fullscreen on https://design.firefox.com/icons/viewer/# or one with all four corners).

I also would like to add a feature where pressing a button copies the start and end of a zoomed in log to all other logs for which I can't think of proper iconography (up and down arrows might do it but are still less than clear)

**Comment by benfrancis** [comment]
@hobinjk logs icon: https://drive.google.com/file/d/1eG9bYhrj7uSF48-_uqq5JxwahZIgPWoP/view?usp=sharing

**Comment by benfrancis** [comment]
> It would also be nice to get icons for reset zoom (up arrow might be good) and expand into View Individual Log (maybe like the fullscreen on https://design.firefox.com/icons/viewer/# or one with all four corners).

The idea I had in mind was that clicking on the log's icon (not yet implemented) would navigate to a detail view which displays only that log. The detail view would have its own URL and an overflow menu with edit and delete options.

> I also would like to add a feature where pressing a button copies the start and end of a zoomed in log to all other logs for which I can't think of proper iconography (up and down arrows might do it but are still less than clear)

The idea of the dropdown in the mockups would be that the x-axis scale would apply to all graphs simultaneously. I understand you've gone for another design, which I'll discuss in the PR.

**Comment by hobinjk** [comment]
Oh right, sorry for not talking about the dropdown in the mockups. I think that has the issue that it doesn't seem to support focusing on a specific point in time (i.e. two nights ago the refrigerator stopped drawing power between 01:00 and 06:00, did its internal temperature rise above safe levels during that window?)

**Comment by corradopetrelli** [comment]
I am also interested to this feature.
+1

**Comment by mrstegeman** [comment]
@corradopetrelli this feature has been available for the last few releases.

**Comment by benfrancis** [comment]
@kphanipavan Technically they are already stored in a file on the gateway, called logs.sqlite3 😉

If you want to save them in JSON you could use the REST API and pipe the output to a file, e.g. with curl,

`curl http://gateway.local/logs --header "Accept: application/json" --header "Authorization: Bearer {JWT}" -o logs.json`

(replacing {JWT} with a valid JSON Web Token for your gateway, which you can generate in Settings -> Developer -> Create Local Authorisation)

This should save the logs in a file called logs.json

Hope this helps
