### ISSUE TITLE
Default precision of number properties

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1318]
How precise should various number properties be in the UI by default?

The current approach appears to be zero decimal points for power, voltage and frequency but one decimal point for current for example.

Would a significant figures approach work better? E.g. 3 significant figures by default?

**Comment by mrstegeman** [comment]
Alternatively, we could switch units as necessary. For example, instead of showing `0.0310 A`, we could show `31.0 mA`.

**Comment by twobraids** [comment]
I support dynamically switching the units for scale so that the display field can generally show 3 digits (or a configurable number) plus a decimal point.

**Comment by freaktechnik** [comment]
I'm not convinced the current default of three decimal digits is a great default, maybe a way for the device to declare accuracy would be a good idea. This would allow the gateway UI to scale to what it can expect from the property. My suggestion would be a property that can have any value between 1 and 0 (including 1, excluding 0). If it is unset, infinite precision is assumed.

Properties with the integer type should get no decimal digits, currently they get the same as a number type. So integers would have a precision of "1".

**Comment by flatsiedatsie** [comment]
> maybe a way for the device to declare accuracy would be a good idea

That would be great to have. That being said, in [some cases](https://github.com/mozilla-iot/gateway/issues/1809#issuecomment-486695028) it's not possible for the device to already suggest how many decimals will be required.


I've spotted some off things around this issue.

First, I have a temperature sensor that has one decimal of precision, but the Gateway always truncates it to remove the decimal? And no, I haven't set it to 'integer'.

```
# Adding temperature property
                    self._type.append('MultiLevelSensor')
                    self.properties[targetPropertyID] = MySensorsProperty(
                        self,
                        targetPropertyID,
                        {
                            '@type': 'TemperatureProperty',
                            'label': new_description,
                            'type': 'number',
                            'unit': 'degree celsius',
                            'readOnly': True,
                        },
                    new_value, new_node_id, new_child_id, new_sub_type)
```

Results in:

![temp-no-decimal](https://user-images.githubusercontent.com/805405/56744476-22d2a280-6768-11e9-9628-407491df0676.png)



On the other side of the spectrum, properties that are initiated without an official type/property (I have a lot of those..) get trailing zeros if they are floats:

![co2-thing](https://user-images.githubusercontent.com/805405/56744822-bb692280-6768-11e9-9d1f-c1a5923ecb27.png)


The code that initiates it:

```
            elif child.type == 22:                      # Air quality
                if new_sub_type == 37: # V_LEVEL
                    if prefix != '':
                        self.properties[targetPropertyID] = MySensorsProperty(
                            self,
                            targetPropertyID,
                            {
                                'label': new_description,
                                'type': 'number',
                                'unit': prefix,
                                'readOnly': True,
                            },
                            new_value, new_node_id, new_child_id, new_sub_type)
                    else:
                        self.properties[targetPropertyID] = MySensorsProperty(
                            self,
                            targetPropertyID,
                            {
                                'label': new_description,
                                'type': 'number',
                                'readOnly': True,
                            },
                            new_value, new_node_id, new_child_id, new_sub_type)
```

**Comment by freaktechnik** [comment]
I guess the case where there is no know precision could also be neatly handled with [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat) where you can define minimum and maximum precision, allowing the number to be as short as required but only so long it still fits within the gateway's UI.

**Comment by flatsiedatsie** [comment]
One way of handling this would be to base it on what the sensor is sending?

- If it sends a zero or one, show it as a boolean in the UX.
- If it (then suddenly) sends integers, show an integer in the UX.
- If it (then suddenly) sends one decimal, show one decimal from then on.
- If it sends a two decimal value, from then on show two decimals, etc.

**Comment by tim-hellhake** [comment]
Why not just add a precision field to the properties of a device?
The adapter knows best which precision makes sense for a sensor.

**Comment by mrstegeman** [comment]
We could potentially use [`multipleOf`](https://json-schema.org/latest/json-schema-validation.html#rfc.section.6.2.1), which is already part of the JSON Schema spec.

For instance, if we want 2 decimal points, we could use `"multipleOf": 0.01`.

**Comment by tim-hellhake** [comment]
Even better!

**Comment by benfrancis** [comment]
I was thinking that there's currently no way to define precision using a Thing Description/JSON Schema, but multipleOf is potentially a clever idea. We just have to be careful about how we display that in the UI, didn't we also previously use that as the step size for a range input?

**Comment by mrstegeman** [comment]
Yes, but those shouldn't conflict. In fact, that makes perfect sense, given that this issue is discussing read-only properties, and we currently just use `multiipleOf` for writable properties.

**Comment by IGx89** [comment]
Reading through this thread, is it correct to say that a decision has been made and you're simply waiting for PRs now? Or is more discussion/requirements planning needed first? I ask because it's been a bit painful for me having temperature data ~1/20th as precise in WebThings as I had in SmartThings (losing a decimal and losing Fahrenheit)
