### ISSUE TITLE
integration of my custom web of thing with mozila iot gateway

### ISSUE THREAD

**Issue by prasenjeetgupta** [mozilla-iot/gateway#1331]
I am new for mozila iot gateway can not understand how my java based web of thing integrate with mozila iot gateway and add url. I am already setup the mozila gateway in Raspberry pi and make single thing for demo purpose but confused how to deploy the Things i created. so that anyone can add this thing from mozila gateway htmlpage( UI )

Please anyone help me by complete process and with example...

thanks in advance...

**Comment by mrstegeman** [comment]
Discusson at mozilla-iot/webthing-java#22
