### ISSUE TITLE
Rule output displays "on" when set to "off"

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1341]
STR:
* Create a rule with a smart plug or light as an output
* Set the rule to turn the device off (e.g. at a certain time of day)
* Save the rule
* Edit the rule

Expected:
* Output shows "off"

Actual:
* Text description says "off" but drop-down on output shows "on"

**Comment by freaktechnik** [comment]
Additionally the rule description text always says "turn off" as action, even when on is selected (actively selected)
