### ISSUE TITLE
gateway.local fails to load after re-install

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1343]
I forgot to file this before and can't find it filed anywhere...

STR:
* Set up a gateway and access it via gateway.local using HTTPS
* Re-flash your SD card
* Set up again

Expected:
* Loading gateway.local loads the gateway's web interface

Actual:
* "Problem connecting" to gateway.local

I think this is a caching issue as it works in a private browsing window and if you add port 8080 to the end of the URL.

**Comment by mrstegeman** [comment]
I've seen this before, I believe. I think the browser caches the redirect from gateway.local to the subdomain.

**Comment by benfrancis** [comment]
> I've seen this before, I believe. I think the browser caches the redirect from gateway.local to the subdomain.

It's definitely something like that. The question is, how to we prevent it? There are related issues trying to access the gateway locally via gateway.local after an external domain has been registered during first time setup.
