### ISSUE TITLE
Update from 0.4.1 fails

### ISSUE THREAD

**Issue by rei-vilo** [mozilla-iot/gateway#1347]
Hi!

I went through the menu **≡ > Settings > Updates** and clicked on **Update**.

Unfortunately, the procedure freezes on **Restarting**, with no indication on what's going on.

<img width="581" alt="capture 2018-09-10 a 15 55 30" src="https://user-images.githubusercontent.com/951776/45301879-23d4fd80-b512-11e8-8436-ab1e6329331e.png">

How to update using a standard package manager?

Thank you!

**Comment by benfrancis** [comment]
It probably hasn't frozen. It may take up to 50 minutes to update depending on your connection speed and CPU speed.

Usually this happens automatically overnight, if you trigger it manually you need to give it time to complete.

Try giving it a bit longer and report back if it still doesn't work.

**Comment by benfrancis** [comment]
Note:
1. You can follow the system logs using `tail -f /var/log/syslog` to see what it's doing and `top` to see what's running
2. Updates after 0.5.2 should be much faster
3. We're working on improving the UI

**Comment by rei-vilo** [comment]
Thanks for the answer. Here is the log with a final error:

```
tail -f /var/log/syslog
Sep 10 15:59:00 myPiMozilla check-for-update.sh[1372]: tar: node_modules/babel-register/node_modules/babel-runtime/node_modules/core-js/library/fn/string/virtual/sub.js: Cannot open: No such file or directory
Sep 10 15:59:00 myPiMozilla check-for-update.sh[1372]: tar: node_modules/babel-register/node_modules/babel-runtime/node_modules/core-js/library: Cannot mkdir: No space left on device
Sep 10 15:59:00 myPiMozilla check-for-update.sh[1372]: tar: node_modules/babel-register/node_modules/babel-runtime/node_modules/core-js/library/fn/string/virtual/italics.js: Cannot open: No such file or directory
Sep 10 15:59:00 myPiMozilla check-for-update.sh[1372]: tar: node_modules/babel-register/node_modules/babel-runtime/node_modules/core-js/library: Cannot mkdir: No space left on device
Sep 10 15:59:00 myPiMozilla check-for-update.sh[1372]: tar: node_modules/babel-register/node_modules/babel-runtime/node_modules/core-js/library/fn/string/virtual/big.js: Cannot open: No such file or directory
Sep 10 15:59:00 myPiMozilla check-for-update.sh[1372]: tar: node_modules/babel-register/node_modules/babel-runtime/node_modules/core-js/library: Cannot mkdir: No space left on device
Sep 10 15:59:00 myPiMozilla check-for-update.sh[1372]: tar: node_modules/babel-register/node_modules/babel-runtime/node_modules/core-js/library/fn/string/virtual/blink.js: Cannot open: No such file or directory
Sep 10 15:59:00 myPiMozilla check-for-update.sh[1372]: tar: node_modules/babel-register/node_modules/babel-runtime/node_modules/core-js/library: Cannot mkdir: No space left on device
Sep 10 15:59:00 myPiMozilla check-for-update.sh[1372]: tar: node_modules/babel-register/node_modules/babel-runtime/node_modules/core-js/library/fn/string/virtual/pad-end.js: Cannot open: No such file or directory
Sep 10 16:17:01 myPiMozilla CRON[1701]: (CRON) error (create tmpfile)
```

**Comment by benfrancis** [comment]
How big is your microSD card? It sounds like you may have run out of space.

**Comment by rei-vilo** [comment]
The micro-SD is the default 4 GB provided with the kit.

```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root       3.6G  3.0G  527M  85% /
devtmpfs        460M     0  460M   0% /dev
tmpfs           464M     0  464M   0% /dev/shm
tmpfs           464M   12M  452M   3% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           464M     0  464M   0% /sys/fs/cgroup
/dev/mmcblk0p1   41M   22M   20M  54% /boot
tmpfs            93M     0   93M   0% /run/user/1000
```

**Comment by rei-vilo** [comment]
Finally, I decided to perform a clean install on an 8 GB micro-SD card.

#1345 will be welcomed!

**Comment by rei-vilo** [comment]
The main page [Build Your Own Web of Things Gateway](https://iot.mozilla.org/gateway/) doesn't specify the minimum size for the micro-SD card.

The more detailed procedure [How to build your own private smart home with a Raspberry Pi and Mozilla’s Things Gateway](https://hacks.mozilla.org/2018/02/how-to-build-your-own-private-smart-home-with-a-raspberry-pi-and-mozillas-things-gateway/) reads

> You’ll also need a microSD card to flash the software onto! We recommend at least 4GB.

Maybe recommending a larger micro-SD card, _ca._ 8 GB, would suit the large downloaded packages for the update.

**Comment by benfrancis** [comment]
I'm not sure what "kit" you're referring to, but you're correct. We previously recommended a minimum of 4GB. It seems that with the 0.5 release that isn't quite enough space to perform an OTA update.

The good news is that after 0.5.2 OTA updates will require far less space. The bad news is that to upgrade from 0.4.1 to 0.5 will always require more space.

Thanks for highlighting this issue.
