### ISSUE TITLE
Use SQLite instead of a flat file to store tunneltoken and notoken 

### ISSUE THREAD

**Issue by andrenatal** [mozilla-iot/gateway#137]

**Comment by andrenatal** [comment]
@mrstegeman could you please take this one?

**Comment by benfrancis** [comment]
Note: We stopped using node-persist because it was unreliable. Most data is now stored in SQLite.

**Comment by mrstegeman** [comment]
So should we store the token data in the SQLite db, then?

**Comment by benfrancis** [comment]
That seems reasonable. @hobinjk do you think this should live in the settings table?

**Comment by hobinjk** [comment]
Yes, the settings table would be the easiest place to put it (using `src/models/Settings.js`)

**Comment by hobinjk** [comment]
The follow-up problem is then how to extract the information in the `tools/manual-renew-certificates` script, but the way I see it that script is a temporary solution for gateways running a specific revision that would have the current-style storage

**Comment by mrstegeman** [comment]
I will add it to the settings table. @hobinjk yes, that's only a stopgap solution for <= 0.2.1 images, so they would be unaffected.
