### ISSUE TITLE
Process to manually update?

### ISSUE THREAD

**Issue by che-wf** [mozilla-iot/gateway#1373]
## Issue
I'm running Gateway (0.5.1) on a Raspberry Pi. I am trying to update Gateway since it says I have an update. However, whenever I click "Update", the button text changes to say "In Progress". When I refresh, it reverts back to "Update". I check a day later, and it still says "Update".  I ran the command to checkout the `syslog`.  Here's my output:
```
Sep 25 04:50:02 home-dash dhcpcd[365]: wlan0: dhcp_envoption 13.0/1: missing embedded option
Sep 25 04:50:02 home-dash dhcpcd[365]: wlan0: dhcp_envoption 13.0/1: missing embedded option
Sep 25 04:50:48 home-dash dbus[313]: [system] Activating via systemd: service name='org.freedesktop.PackageKit' unit='packagekit.service'
Sep 25 04:50:48 home-dash systemd[1]: Starting PackageKit Daemon...
Sep 25 04:50:48 home-dash PackageKit: daemon start
Sep 25 04:50:48 home-dash dbus[313]: [system] Successfully activated service 'org.freedesktop.PackageKit'
Sep 25 04:50:48 home-dash systemd[1]: Started PackageKit Daemon.
Sep 25 04:58:31 home-dash dhcpcd[365]: wlan0: dhcp_envoption 13.0/1: missing embedded option
Sep 25 04:58:31 home-dash dhcpcd[365]: wlan0: dhcp_envoption 13.0/1: missing embedded option
```

So, my question is "do I need to try something different or can I manually upgrade?"

## Images
Update Available:
![image](https://user-images.githubusercontent.com/1719239/46012923-833d1c80-c07f-11e8-9e1a-fc8cb68012bc.png)

In Progress:
![image](https://user-images.githubusercontent.com/1719239/46012966-9e0f9100-c07f-11e8-8bda-33bf5da13a9e.png)

## System Info:
  **System:**
    OS: Linux 4.14 Raspbian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: arm ARMv7 Processor rev 4 (v7l)
    Memory: 45.90 MB / 927.19 MB
    Storage: 5.7GB / 64GB
    Container: Yes
    Shell: 4.4.12 - /bin/bash

  **Binaries:**
    Node: 8.12.0 - /usr/bin/node
    Yarn: 1.9.4 - /usr/bin/yarn
    npm: 6.4.1 - /usr/bin/npm

  **Utilities:**
    Make: 4.1 - /usr/bin/make
    GCC: 6.3.0 - /usr/bin/gcc
    Git: 2.11.0 - /usr/bin/git

  **IDEs:**
    Nano: 2.7.4 - /bin/nano

  **Languages:**
    Bash: 4.4.12 - /bin/bash
    Java: 1.8.0 - /usr/bin/javac
    Perl: 5.24.1 - /usr/bin/perl
    Python: 2.7.13 - /usr/bin/python
    Ruby: 2.3.3 - /usr/bin/ruby

**Comment by benfrancis** [comment]
> do I need to try something different or can I manually upgrade?

No, clicking the upgrade button should be sufficient, it just takes a long time to update (we have an [issue](https://github.com/mozilla-iot/gateway/issues/1345) open to improve the UI). But your gateway should also automatically check for updates once a day and update itself overnight.

Is your gateway still on 0.5.1? It should have updated itself to 0.5.3 by now.

**Comment by che-wf** [comment]
> Is your gateway still on 0.5.1? It should have updated itself to 0.5.3 by now.

Yeah, it's still on 0.5.1.

**Comment by benfrancis** [comment]
@hobinjk Is there any additional log information that @che-wf can provide to help explain why his gateway is not updating? Hopefully this is not a widespread problem.

**Comment by hwine** [comment]
> Hopefully this is not a widespread problem.

I have a similar problem going from 0.5.3 (where I started with a fresh flash load) to 0.6.0 ☹️ 

Only a smidgen worse -- the gateway becomes unusable (server not running). Fortunately, I had ssh enabled, so the following got me going again:
- manually (re) installed npm (no idea how that got messed up)
- ``cd mozilla-iot/gateway``
- run ``npm start``

Once the Gateway was back online, I tried the manual update as above. It does not succeed, and the server process died again.

Now that I've figured out how to get my gateway back online, I'm happy to leave it on 0.5.3 and provide any debug information you need. Let me know.

**Comment by benfrancis** [comment]
@hobinjk Which logs would help debug this?

In the past I've seen useful output on `tail -f /var/log/syslog` during an OTA update.

run-app.log might also be useful (which you can access via the web interface in Settings -> Developer -> View Logs, but only while the web interface is running, after which you'll need to find it on the command line).

**Comment by hobinjk** [comment]
I just realized that there's a simple way to get debug output and I don't need to write up a page long guide about what I look for in htop. The best place to get debug output is by running `node tools/check-for-update.js` from the command line in the gateway directory which should produce an error to investigate. It's also possible to check out `sudo systemctl stop mozilla-iot-gateway; ./gateway_failed/run_app.sh` if the OTA update progresses far enough to download the 0.6 gateway

Finally, if none of that has results, creating a temporary directory and downloading the OTA bundles manually might give a bit more insight. This would look like:
```
mkdir gateway_ota_test
cd gateway_ota_test
curl https://github.com/mozilla-iot/gateway/releases/download/0.6.0/gateway-6eb2648c21c95b20c09f44cc81b8a85c40a4f6a19489490746a3ec407d70b78d.tar.gz | tar xzv
ls # hopefully the directory is called gateway 
cd gateway
curl https://github.com/mozilla-iot/gateway/releases/download/0.6.0/node_modules-86e06abc0ec781c5bffb27aab368d6455e054b33aab5eeaa1c54ae6cb1ba94c6.tar.gz | tar xzv

node build/gateway.js
```

**Comment by hwine** [comment]
@hobinjk -  First - you want a "-L" option in the curl command above. GitHub does like to redirect to the CDN.

I think I've discovered the problem. I'm running from a flashed image -- so 4GB. That leaves only:
```bash
pi@gateway:~ $ df -lh
Filesystem      Size  Used Avail Use% Mounted on
/dev/root       3.6G  3.2G  292M  92% /
devtmpfs        213M     0  213M   0% /dev
tmpfs           217M     0  217M   0% /dev/shm
tmpfs           217M  3.1M  214M   2% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           217M     0  217M   0% /sys/fs/cgroup
/dev/mmcblk0p1   43M   22M   21M  52% /boot
tmpfs            44M     0   44M   0% /run/user/1000
```

The 6.0 node module package expands to 506MB, which equals "no space on device" before the unpack finishes.

Q.E.D.

_/me goes to read up on expanding partitions - it's been a while_

**Comment by benfrancis** [comment]
Ah, recent releases are supposed to automatically expand the partition on first boot. 4GB is unfortunately no longer enough space, as you've discovered.

**Comment by che-wf** [comment]
I'm still left hanging. I have 64GB. So, I have no problems there. When I run `npm tools/check-for-update.js`, it just runs with no output or returning to prompt. 

I ran `tail -f /var/log/syslog` and this is the result:
```
Oct 25 00:28:28 home-dash dhcpcd[357]: wlan0: dhcp_envoption 13.0/1: missing embedded option
Oct 25 00:35:47 home-dash dhcpcd[357]: wlan0: dhcp_envoption 13.0/1: missing embedded option
Oct 25 00:35:47 home-dash dhcpcd[357]: wlan0: dhcp_envoption 13.0/1: missing embedded option
Oct 25 00:36:44 home-dash systemd[1]: Started Session c2 of user pi.
Oct 25 00:40:18 home-dash dhcpcd[357]: wlan0: dhcp_envoption 13.0/1: missing embedded option
Oct 25 00:40:18 home-dash dhcpcd[357]: wlan0: dhcp_envoption 13.0/1: missing embedded option
Oct 25 00:46:54 home-dash dhcpcd[357]: wlan0: dhcp_envoption 13.0/1: missing embedded option
Oct 25 00:46:54 home-dash dhcpcd[357]: wlan0: dhcp_envoption 13.0/1: missing embedded option
Oct 25 00:56:40 home-dash dhcpcd[357]: wlan0: dhcp_envoption 13.0/1: missing embedded option
Oct 25 00:56:40 home-dash dhcpcd[357]: wlan0: dhcp_envoption 13.0/1: missing embedded option
Oct 25 01:02:41 home-dash dhcpcd[357]: wlan0: dhcp_envoption 13.0/1: missing embedded option
Oct 25 01:02:41 home-dash dhcpcd[357]: wlan0: dhcp_envoption 13.0/1: missing embedded option
```
I don't think any of that is related. 

I even tried the manual OTA update. It's not letting me download due to the redirects.

**Comment by hwine** [comment]
> I even tried the manual OTA update. It's not letting me download due to the redirects.

@che-wf add a '-L' option, and curl should handle the redirects just fine (edited from [above](https://github.com/mozilla-iot/gateway/issues/1373#issuecomment-431848067)):
```bash
mkdir gateway_ota_test
cd gateway_ota_test
curl -L https://github.com/mozilla-iot/gateway/releases/download/0.6.0/gateway-6eb2648c21c95b20c09f44cc81b8a85c40a4f6a19489490746a3ec407d70b78d.tar.gz | tar xzv
ls # hopefully the directory is called gateway 
cd gateway
curl -L https://github.com/mozilla-iot/gateway/releases/download/0.6.0/node_modules-86e06abc0ec781c5bffb27aab368d6455e054b33aab5eeaa1c54ae6cb1ba94c6.tar.gz | tar xzv

node build/gateway.js
```

**Comment by che-wf** [comment]
Thanks, everyone! I got it manually updated. Everything is looking good so far.

**Comment by che-wf** [comment]
So, it looks like there is a new update. My instance hasn't updated once again. I'm wondering if it is happening because I installed it on Raspberry Pi instead of using the image. I'm wanting to update it manually, but I also want to see if I can resolve this if it is a real issue.

**Comment by mrstegeman** [comment]
#1510 could help in adding the systemd services outside of our prebuilt images.

**Comment by che-wf** [comment]
For what's it's worth if anyone finds this useful, I wrote a bash script gist that will perform the actions above in order to update quickly. 
https://gist.github.com/che-wf/3fd241f78fa4a802ec5fdb7e1da0d97d
