### ISSUE TITLE
Support MySensors

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#1375]
The MySensors Arduino library/stack is a popular way to create and connect DIY devices and sensors.

https://www.mysensors.org

[Existing open source controllers](https://www.mysensors.org/controller) like OpenHab, Home Assistant and Domoticz all support MySensors, in various degrees. It would be great if this project could as well!

**Comment by flatsiedatsie** [comment]
Seems like someone in the community has taken a shot at it already:
https://forum.mysensors.org/topic/9455/api-first-controller-with-ota-support-also-exposes-webofthings-apis-for-sensors

It would be great it Mozilla devs could help out.

I personally only have MySensors devices in my home, and plan to keep it that way for privacy, security and transparency reasons (as well as being fun to make and much cheaper than commercial products).

**Comment by flatsiedatsie** [comment]
Good news: the add-on seems to be working on the Raspberry Pi now (arm7 at least).

**Comment by mrstegeman** [comment]
That's excellent. Would you care to [publish it](https://github.com/mozilla-iot/addon-list)?

**Comment by tsathishkumar** [comment]
@mrstegeman It is not an add on. It is written as a Web thing. We had a discussion about making it as an add on, but gave it up as Web thing route was better.

[Here](https://github.com/tsathishkumar/MySController-rs) is the project for your reference.

**Comment by mrstegeman** [comment]
Oh, awesome! Since this is working now and it doesn't require any changes to the gateway or a new add-on, I'll go ahead and close this issue.
