### ISSUE TITLE
Rule edit display: icon out of sync with reality

### ISSUE THREAD

**Issue by hwine** [mozilla-iot/gateway#1382]
_[edit: system version 0.5.3, installed Sat 2018-09-30]_
As a n00b, I was confused for a while by the icon not matching the text. Since the icon has a lot more visual weight, I kept thinking it represented "truth", and I hadn't properly saved the rule. See:

![image](https://user-images.githubusercontent.com/132412/46384748-e70da980-c66c-11e8-9b43-88ec364accc6.png)

The text is correct - the rule turns the lights off. But the icon displays the light as "on", which is confusing.

When a rule changes the level, the icon state matches the text state:
![image](https://user-images.githubusercontent.com/132412/46384862-921e6300-c66d-11e8-8fb1-1bb61471d28b.png)

**Comment by benfrancis** [comment]
Hi @hwine, thanks for this feedback.

The icons used here are currently just a static representation of the device type. The level icon does not change if you change the level in the rule for example.

Are you suggesting that the appearance of the icon should always reflect the value of the form field next to it? It's a cool idea, but it would be very tricky to represent all the possible states of all possible device types in the constrained space of the icon. How far would we take it? Would the clock icon also show the correct time for a timer rule for example?

**Comment by hwine** [comment]
My experience is different - let me see if I can explain better. I'll use iPhone images this time. Below are two different shots showing that the icon matches the text w.r.t. percentage:
<div style="float:left">
<img src="https://user-images.githubusercontent.com/132412/46566045-a4e2a300-c8cc-11e8-8f12-1d0642c030bb.PNG" width="40%" />
<img src="https://user-images.githubusercontent.com/132412/46566055-bf1c8100-c8cc-11e8-80f1-b22600fb896a.png" width="40%" />
</div>


The "bug" is that the text for the "Off" action has an icon which shows "On":

<img src="https://user-images.githubusercontent.com/132412/46566166-4caca080-c8ce-11e8-9809-73622782f7f8.PNG" width="40%"/>

**Comment by mrstegeman** [comment]
Yeah, it is shown that way because the property name is "on". I do agree that it could be confusing, though.

**Comment by hobinjk** [comment]
It's an actual bug, the selected value should be "Off". I may have reintroduced this bug in a recent change to the property selection logic.

**Comment by benfrancis** [comment]
@hobinjk Is this fixed now?

**Comment by hobinjk** [comment]
It's fixed but now there's a different issue since a bunch of things had their "On" property name changed to "On/Off"

**Comment by mrstegeman** [comment]
I believe this was fixed a couple releases ago.

**Comment by hwine** [comment]
Working correctly in `0.10.0` for sure.
