### ISSUE TITLE
Autostart gateway as a service

### ISSUE THREAD

**Issue by thanhtantran** [mozilla-iot/gateway#1384]
Hello,

I have install Gateway success on my Orange Pi zero with Armbian

Now i want to Gateway auto start every time i boot the Pi Zero

I try to create a service file as 
`sudo nano /etc/systemd/system/mozilla-iot.service`

 then add the servcice like this

```
[Unit]
Description=Mozilla IOT
After=network-online.target

[Service]
Type=simple
User=%i
ExecStart=cd /home/admin/gateway/run-app.sh

[Install]
WantedBy=multi-user.target
```

But when i start the service after

```
sudo systemctl --system daemon-reload
sudo systemctl enable mozilla-iot
sudo systemctl start mozilla-iot
```

the service is not running

**Comment by hobinjk** [comment]
The ExecStart should drop the `cd` and be `/home/admin/gateway/run-app.sh`.

The image's service file's definition of this is https://github.com/mozilla-iot/gateway/blob/master/image/prepare-base.sh#L95

**Comment by ssbarnea** [comment]
I think that as long there is no single command to install it as service, this bug should be kept open. Having a run-app.sh script does not mean we have a service.

**Comment by mrstegeman** [comment]
@ssbarnea Our service files are here: https://github.com/mozilla-iot/gateway/tree/master/image/etc/systemd/system

Those are Raspbian-specific, but they're easy to adopt for other repos. For instance, I copied them for the AUR package and modified them as necessary: https://github.com/mozilla-iot/gateway-aur
