### ISSUE TITLE
Smart assistant requests microphone permission every time it is used

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1388]
STR:
* (Add gateway to homescreen from Firefox using ambient badge (the add button in the URL bar))
* Enable the smart assistant
* Tap the microphone icon on the smart assistant page
* Grant microphone permission
* Issue a voice command
* Tap the microphone icon again

Expected:
* Permission is remembered and microphone is used

Actual:
* Permission is requested every time the microphone is accessed

**Comment by mrstegeman** [comment]
You have to click "Remember this decision" in order for the browser to keep the permission.

From MDN:
> As an API that may involve significant privacy concerns, getUserMedia() is held by the specification to very specific requirements for user notification and permission management. First, getUserMedia() must always get user permission before opening any media gathering input such as a webcam or microphone. Browsers may offer a once-per-domain permission feature, but they must ask at least the first time, and the user must specifically grant ongoing permission if they choose to do so.

**Comment by benfrancis** [comment]
Unfortunately Firefox doesn't offer that option.

![screenshot_20181012-095035](https://user-images.githubusercontent.com/552417/46859101-bbc15200-ce04-11e8-9c99-bd53dbfaf79d.png)

It looks like Chrome remembers the permission, so maybe this is a bug report/feature request for Firefox. At least for installed PWAs...

**Comment by mrstegeman** [comment]
Interesting! I get an option to remember on Firefox desktop, so I'd say this is probably a Fennec issue.
