### ISSUE TITLE
Can't access REST API

### ISSUE THREAD

**Issue by laibulle** [mozilla-iot/gateway#1390]
Hello, I am trying to access web API via curl but it doesn't work.

```
curl -X POST \
  https://192.168.1.75/login/ \
  -H 'Content-Type: application/json' \
  -d '{
	"email": "xxxxx@gmail.com",
	"password": "xxxxx"
}'
```

the response is

```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /login</pre>
</body>
</html>
```

The same thing append when I use a JWT token agains /things

Am I missing something ?

Best regards

**Comment by benfrancis** [comment]
It may be that you need to set

`Accept: application/json`

in the request to get JSON rather than HTML.

Not sure logging in will work from curl though...

**Comment by hobinjk** [comment]
dhylands wrote a script for logging in and retrieving the user's JWT: https://github.com/mozilla-iot/curl-examples/blob/master/login.sh

**Comment by laibulle** [comment]
The add of 'Accept: application/json' did the trick.
```
curl -X POST \
  https://192.168.1.75/login \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
	"email": "xxxx@gmail.com",
	"password": "xxx"
}'
``` 

```
{
    "jwt": "eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjI1MTM4NzdmLWRiNDQtNDgwZS1hOWQ4LTIwMzNmNjQxNzA3ZSJ9.eyJyb2xlIjoidXNlcl90b2tlbiIsImlhdCI6MTUzODg0MTY5OX0.9yoYVDoYkM-Fsf5NOdl7eU86igXIO7c2El_3PjuneQoVyMu2d5WVlQZsBKLprteGhug7mNgU_KAgFmeDxFhNAw"
}
```
