### ISSUE TITLE
Digi XStick Supplier

### ISSUE THREAD

**Issue by who93** [mozilla-iot/gateway#1391]
Hi,
Where can I order the Digi XStick in Europe? The USB Dongle is not any more in stock at Mouser.
Cheers

**Comment by benfrancis** [comment]
It looks like Mouser have ordered some more stock which should be available shortly. You can also try enquiring with [Solid State Supplies](https://www.sssltd.com/products/xbee-zigbee-series-1/) who [according to Digi](https://www.digi.com/products/models/xu-z11) currently have 63 in stock.
