### ISSUE TITLE
Event rules are triggered too often

### ISSUE THREAD

**Issue by freaktechnik** [mozilla-iot/gateway#1406]
I have the following rule:
![image](https://user-images.githubusercontent.com/640949/46876478-b680f900-ce3e-11e8-9b8e-85bf3145c07a.png)

Besides it not turning on the light when clicking the button, it does not let me turn it off anymore, which makes me think that the rule is true after the event was triggered, but the event tirggering itself doesn't execute the rule.

I'd expect the rule is evaluated exactly once every time the event is fired, however.

The turn off counterpart of it (even with this rule disabled) doesn't seem to work at all, unless I switch to while, which makes both rules behave like this - completely ignoring the event requirement.

**Comment by benfrancis** [comment]
@hobinjk I haven't played with events as inputs yet, any idea what's going on here?

**Comment by hobinjk** [comment]
For context: events used the old time trigger style where the trigger would remain "on" permanently. The PR updated the event trigger to function as a more intuitive momentary pulse

**Comment by freaktechnik** [comment]
I'd ask for this to be reopened, as the flickers still happen, the only difference is that they stop after the code resets the event "on" state.

This however still leads to flicker for a pair of "toggle" rules, one turning a light on and one turning a light off, based on the state of the light and when the event happens. I realize that this would be fixed if there was a toggle action for on/off devices, as tracked in a separate bug, but I don't think this is how events are expected to behave with rules.

So what's happening is that the two rules trigger each other while the event is "on", since they change the on state of the light, which is part of their conditions. However I'd only expect the rules to be ran that were true on the leading edge of the event, and not during the whole event, since an event normally has no duration, else it'd be a property.
