### ISSUE TITLE
Events aren't shown in the device event log

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#1414]
If I have a device which generates events, then the events aren't shown when you go into the splat menu and click on "event log". It only shows property changes.

**Comment by mrstegeman** [comment]
Seems to be working ok for me, at least with the virtual things adapter.
![screenshot_2018-10-16 things gateway](https://user-images.githubusercontent.com/457381/47048794-f02d6900-d18a-11e8-9b4b-0749c6d40ce9.png)

**Comment by dhylands** [comment]
Seems to be working for me as well. Not sure why it wasn't working.
