### ISSUE TITLE
SmartThings Button gets detected as a "Binary Sensor" and is "active" 100% of the time (pushing the button has no noticeable effect in the gateway web ui)

### ISSUE THREAD

**Issue by dholbert** [mozilla-iot/gateway#1416]
https://hacks.mozilla.org/2018/10/home-monitoring-with-things-gateway-0-6/ says "We’ve also added support for push buttons, like the [SmartThings Button](https://www.samsung.com/us/smart-home/smartthings/buttons/samsung-smartthings-button-gp-u999sjvleaa/)", and the screenshot shows a "push button" image:
https://hacks.mozilla.org/files/2018/10/Screen-Shot-2018-10-09-at-16.02.14.png

I bought a SmartThings Button ([from Amazon, here](https://www.amazon.com/gp/product/B07F8ZFFQK/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1)) but my Gateway (version 0.6, on Raspberry Pi 3 Model B) detects it as a "Binary Sensor", not as a "push-button" as shown in the blog post (with a checkbox-image icon, rather than a press-button icon).  And after I add the device (as a Binary Sensor), it shows up as "Active" all of the time, and I can't seem to get it to trigger actions in any rules.  Physically pressing the button doesn't seem to have any effect. So I think it's being detected/configured wrong.

**Comment by dholbert** [comment]
Here's a screenshot of the SmartThings Button on my gateway, in case it helps.  Note the checkbox icon (for binary-sensor).  Also: nothing about this page changes at all when I physically press the button.
![image](https://user-images.githubusercontent.com/426803/47062546-895c7f80-d18b-11e8-88a3-98927a4faa5a.png)

**Comment by dhylands** [comment]
The SmartThings button only generates "pressed" events and never generates "released" events.

The current approach that I'm taking is this:
1 - Advertise as a "THING" until such time as something better is available
2 - It will wind up having the following properties: Voltage, Temperature, and Low Battery
3 - It will generate the following events: pressed, doublePressed, and held

I have the above working in a development branch, but the rules engine isn't cooperating fully, so I'm currently investigating why the rules engine doesn't always trigger properly.

**Comment by benfrancis** [comment]
If the `PushedProperty` never gets set to true (because we don't know when to set it to false again), I'm not sure what we should do with the UI.

Should we flash the icon white when it's pressed? Flash twice for double press and flash longer for a long press?

**Comment by dhylands** [comment]
It might make sense to do something generic, like have a type which indicates that its primarily event driven. All of our current types assume that there is some primary property and reflect the value of that property.

If a device has an @type of 'EventDriven' then perhaps it should flash briefly each time an event is received (any event), or perhaps it could have an EventCounter property which reflects the number of events which have been received.

**Comment by mrstegeman** [comment]
@dhylands Fixed?

**Comment by dhylands** [comment]
Currently, it looks like this:
![screenshot from 2018-10-17 13-24-04](https://user-images.githubusercontent.com/127500/47191380-c182d000-d2fb-11e8-8abd-216d739eed93.png)
and generates the following events:
* pressed
* doublePressed
* longPressed

There are no properties to reflect the state of the button (which is why the ... shows in the middle icon).

**Comment by dholbert** [comment]
Thanks! I got an update and the button seems to be detected correctly now, and I do see events being reported as little popups on the button's page, but they don't seem to trigger rules correctly, so I filed #1431 on that.
