### ISSUE TITLE
Allow users to visualise data to analyse and compare trends

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#1423]
Most smart home systems have a way of showing graphs. For example, a user may want to see trends in electricity use, or analyze the temperature fluctuations that a thermostat is causing.

A lot of existing smart home solutions allow you to see graphs for a specific device. This makes comparisions an analysis difficult. For example, how do temperature and humidity relate? How long after switching on the heater does the temperature start to rise?

One example of a system that in my professional opinion does this well is Homey. Here's a video of how they did it:
https://youtu.be/bB6-vYxi924?t=14

**Comment by mrstegeman** [comment]
This is somewhat of an extension of #1299

**Comment by flatsiedatsie** [comment]
Somewhat is putting it mildly. I'll close this :-)
