### ISSUE TITLE
Adding custom devices. Please help noob.

### ISSUE THREAD

**Issue by abalashov78** [mozilla-iot/gateway#1426]
I have Pi at my cottage and i want to
1. get Temp form local sensor vie Adafruit driver from GPIO 11 port.
like "/home/pi/AdafruitDHT.py 11 20"

2. Temp from 2 ESP modules via WiFi like "curl -GET http://192.168.1.68/TemperatureC 
15.0"

3. Also I control the heaters via BLE

It all works on my python and shell scripts. 
Because I don't have access to web-server to Pi vie multiple NATs i  have telegram bot.
But now I want to add my 3 sensors and 4 switches to the Mozilla's web interface.

A. I think that this is possible through like virtual devices and update Temp via curl. But VirtualThings is ReadOnly. How add my devices to Gateway?

B. How I can run my shell or python script for BLE-command from RULES to control the heaters? It look like VirtualSwitch.

**Comment by mrstegeman** [comment]
It sounds like you've already got some scripts and such to control your devices. That being the case, I'd recommend just turning your scripts into web things.

See [this blog post](https://hacks.mozilla.org/2018/05/creating-web-things-with-python-node-js-and-java/) for more information.

If you go this route, you don't have to build your own adapter or anything, you just add them as native web things.

**Comment by abalashov78** [comment]
Thanks!
