### ISSUE TITLE
Provide Update Feed-Back

### ISSUE THREAD

**Issue by rei-vilo** [mozilla-iot/gateway#1430]
I'm updating from `0.5.2` to `0.6` and the **Updates** page provides no feed-back on the process.

<img width="1225" alt="capture 2018-10-19 a 19 33 00" src="https://user-images.githubusercontent.com/951776/47234354-df246800-d3d5-11e8-9bd5-74ad19a6c8b0.png">

- How long the update is going to take?
- Do I have enough time for a coffee only, or for a cup of tea with a piece of cake?
- How to know the update process has frozen the RapsBerry Pi?

**Comment by benfrancis** [comment]
See also: https://github.com/mozilla-iot/gateway/issues/1345
