### ISSUE TITLE
SmartThings Button pressed/doublePressed events (after the first one) don't seem to trigger rules

### ISSUE THREAD

**Issue by dholbert** [mozilla-iot/gateway#1431]
CC @dhylands:

Following up #1416: my SmartThings Button (zigbee) now is detected correctly (with Zigbee Add-on updated to 0.6.1 last night), and the button does generate events when I press or double-press it -- but rules don't seem to be correctly triggered by those events.  The first press triggers a rule as I expect, but subsequent presses do not (though they do get reported as "pressed" when I'm viewing the button's page on the gateway).

In particular, I set up two rules as follows:
Rule (1): If button event "pressed" occurs, turn bulb on
Rule (2): If button event "doublePressed" occurs, turn bulb off

If I disable + reenable these rules (with the slider toggle on the rules view), then the first button-press successfully turns on the bulb, and the first double-press successfully turns off the bulb. But subsequent presses don't have any effect on the bulb.

**Comment by dholbert** [comment]
(I'm hoping you can reproduce, but in case you can't: I'm happy to try things out & gather more diagnostic info etc. later on. This setup is at my home & I'm not near it right now, though I do have access to the web interface of course.)

**Comment by dholbert** [comment]
Thanks! I'll keep an eye out for the next point release.

**Comment by mrstegeman** [comment]
I'm going to call this fixed. @dholbert please reopen this issue if you have problems after our next release.

**Comment by dhylands** [comment]
I just created another update (0.6.3) that fixed some regressions I introduced. Can you see if that fixes things for you?

I've had issues with the 2016 versions of the SmartThings sensors, and the 2018 versions of the sensors have been working well. See https://github.com/mozilla-iot/wiki/wiki/Supported-Hardware for links to both versions and you should be able to tell from the pictures which ones you have.

**Comment by dholbert** [comment]
I installed the zigbee addon update (to 0.6.3) and removed & re-paired my motion sensor and switch.

My smartthings motion sensor (2018 version) does seem to register motion correctly now, but my sylvana dimmer switch is still in a broken state. It seems to be permanently "on" at 52%, regardless of short /long presses of either of its buttons.

**Comment by dholbert** [comment]
> There was an update made to the rules engine, which you probably don't have that will correct this.
In particular #1421 is the PR which fixed the problem.

Following up: I can confirm that my SmartThings button is correctly registering pushes & triggering rules, now that I've got iot-gateway release version 0.6.1.
