### ISSUE TITLE
Problem with Eve Motion sensor

### ISSUE THREAD

**Issue by krystiansliwa** [mozilla-iot/gateway#1435]
Hi, 
I have a problem when connecting to Eve Motion sensor. Gateway detects it but it is viewed as "Custom thing" and in Rules creator I cannot browse any "properties". How can I fix it?

**Comment by mrstegeman** [comment]
What version of the gateway are you running?

**Comment by krystiansliwa** [comment]
It was 0.6.0 version

**Comment by mrstegeman** [comment]
If you open the expanded view for the sensor, are any properties at all shown, or do you only have the central "THING" icon?

This is how mine shows up:
![screenshot_2018-10-23 things gateway](https://user-images.githubusercontent.com/457381/47366487-4e97a180-d6cd-11e8-8823-e5937756dd30.png)

**Comment by mrstegeman** [comment]
This should hopefully be fixed in the v0.3.1 HomeKit adapter version (just released). Can you try the following:
1. Navigate to _Settings->Add-ons_
2. Update "Web Thing", if installed.
3. Click "Configure" for "Web Thing", ensure that "bluetoothEnabled" is unchecked, then click "Apply".
4. Update "HomeKit".
5. Navigate back to "Things" and reload.

Let me know if your sensor is still having issues after that.

**Comment by krystiansliwa** [comment]
Hi, I have only central Thing icon, nothing more. I have tried your solution but it didn't work. Now I can't pair with my device - got Incorrect Pin error. 

Maybe I can share some logs?

**Comment by mrstegeman** [comment]
Yes, logs would be helpful. Can you first remove the motion sensor via the UI, then reset it by holding the reset button on the back for 10 seconds until it flashes red?

After that, restart the gateway (so we can get a clean log), then try to pair again and upload `~/.mozilla-iot/log/run-app.log`.

If you don't have command line access, you can download the log from the UI via _Settings -> Developer -> View Logs_.

**Comment by krystiansliwa** [comment]
Here you can find a log
[run-app.log](https://github.com/mozilla-iot/gateway/files/2514475/run-app.log)

**Comment by krystiansliwa** [comment]
New log with bluetoothEnabled unchecked
[run-app.log](https://github.com/mozilla-iot/gateway/files/2517919/run-app.log)

**Comment by krystiansliwa** [comment]
New log with removed add-ons for WebThing, Z-Wave etc. Only with HomeKit adapter
[run-app.log](https://github.com/mozilla-iot/gateway/files/2517935/run-app.log)

**Comment by mrstegeman** [comment]
Well, that's unfortunate. I was having very similar pairing issues with my Eve Motion Sensor, but mine went away after those fixes. The only thing I can suggest is to try resetting the sensor again via the reset button.

**Comment by krystiansliwa** [comment]
I tried that many times. Pin code is ok because I can correctly pair with Apple Home app and with Eve app. 
I will try to grab new image for my RPi and try again from scratch after weekend.

Thanks for help ;)

**Comment by mrstegeman** [comment]
Sorry I couldn't be of more help! Please let me know if you have any luck after flashing a new image.

**Comment by krystiansliwa** [comment]
Maybe I will try to run some debug mode and try to investigate it. Where I can find manual for developing/debugging add-ons?

**Comment by mrstegeman** [comment]
Primarily, you can just clone the [homekit-adapter repo](https://github.com/mozilla-iot/homekit-adapter) into `/home/pi/.mozilla-iot/addons/` (remove the old one first). Then, the easiest thing to do is to debug via `console.log`, as the add-ons all run in separate processes, but the logs all go to the same place.

Here are some good resources:
* https://hacks.mozilla.org/2018/02/creating-an-add-on-for-the-project-things-gateway/
    * There are a lot more resources listed at the end of this post.
* https://hacks.mozilla.org/2018/02/making-a-clap-sensing-web-thing/

**Comment by mrstegeman** [comment]
@krystiansliwa @ idahuang-temboo What Raspberry Pi model are you each using?

**Comment by krystiansliwa** [comment]
I am using Raspberry Pi Zero W

**Comment by mrstegeman** [comment]
@krystiansliwa @idahuang-temboo I just released a new version of the HomeKit adapter, v0.3.2. Could you try updating and see if that fixes your issues?

If not, I also added some additional debug logging which should help me diagnose, so please attach new logs if things are still broken.

**Comment by idahuang-temboo** [comment]
I am using Raspberry Pi Model 3 B Vi2

**Comment by mrstegeman** [comment]
Any luck with the new version? Your HomeKit add-on should be at version 0.3.3 now.

**Comment by krystiansliwa** [comment]
Hi @mrstegeman I will look at it in the next week and let you know ;)

**Comment by mrstegeman** [comment]
Closing this issue. Please open a new issue in the [homekit-adapter](https://github.com/mozilla-iot/homekit-adapter) repo if you continue to have problems.
