### ISSUE TITLE
BT device is busy when gateway is running

### ISSUE THREAD

**Issue by abalashov78** [mozilla-iot/gateway#1437]
I need to use BT controller by other scripts.
But when gateway is running BT is busy

```
root@raspberrypi:~/bt# ./status.sh C5:AF:CA:9B:81:1B
Characteristic Write Request failed: Request attribute has encountered an unlikely error
Characteristic Write Request failed: Request attribute has encountered an unlikely error
connect: Device or resource busy (16)

when gateway is stopped all is OK

root@raspberrypi:~/bt# ./status.sh C5:AF:CA:9B:81:1B
OFF
root@raspberrypi:~/bt# ./status.sh C6:07:4C:94:B7:FA
OFF
root@raspberrypi:~/bt# sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)
root@raspberrypi:~/bt# sudo setcap cap_net_raw+eip $(eval readlink -f `which python3`)
```
 

or how make gateway without BT support? 

or possibly to use BLE-protocol with customers payloads and hanlders like this https://github.comPimenovAlexander/r4s-bluetooth

**Comment by mrstegeman** [comment]
`thing-url-adapter`, which is an add-on installed by default, uses BLE. Bluetooth adapters have turned out to be finicky, as processes cannot seem to share them nicely.

**Comment by mrstegeman** [comment]
You can disable the add-on in the UI via _Settings->Add-ons_. The add-on will appear as "Web Thing".

**Comment by abalashov78** [comment]
Nope. 
just for clarity - I need to use WebThing Add-On for connect to other devices on my network by webhong servers (ESPs). And at same time i need to use BLE-adapter on my Pi.

**Comment by mrstegeman** [comment]
Currently, there's not a way to selectively disable the Bluetooth functionality. I'm beginning to think we need that option, though, as I'm also having issues with another Bluetooth adapter.

**Comment by abalashov78** [comment]
So I think i can try to use noble instead gatttool (python BLE tool).
Tell me please in whis module in JS i can try it? webthing-node for nodejs?

**Comment by mrstegeman** [comment]
The other Bluetooth adapter I'm using also uses noble, but it seems like multiple instances of noble may not play well together. I'll add a feature to thing-url-adapter to allow disabling Bluetooth scanning. Then, you should be able to keep your current code.
