### ISSUE TITLE
Update recommended SD Card Size

### ISSUE THREAD

**Issue by hwine** [mozilla-iot/gateway#1447]
Current [hacks page](https://hacks.mozilla.org/2018/02/how-to-build-your-own-private-smart-home-with-a-raspberry-pi-and-mozillas-things-gateway/) recommends:
> You’ll also need a microSD card to flash the software onto! We recommend at least 4GB

Per [this comment](https://github.com/mozilla-iot/gateway/issues/1373#issuecomment-432600024), 4GB is no longer enough.

**Comment by hobinjk** [comment]
@benfrancis ^

**Comment by benfrancis** [comment]
@hwine That is true, and we're currently working on an online user guide which we will keep up to date with the latest requirements. I don't think we can keep going back end editing this blog post every time something changes (it was correct at the time of publication), but if you spot the 4GB requirement documented anywhere else (e.g. the README or wiki) then please feel free to update it or let us know.
