### ISSUE TITLE
Push button rules only fire once

### ISSUE THREAD

**Issue by nyergler** [mozilla-iot/gateway#1458]
I have a Samsung Smartthing Button ("Kitchen Switch") and an Aeotec Smart Switch ("Kitchen") added to my Things Gateway. My goal is to have the button control the switch. I have two rules defined:

* If Kitchen Switch event "pressed" occurs, turn Kitchen on
* If Kitchen Switch event "doublePressed" occurs, turn Kitchen off

After defining the rules, I can turn the switch on, and then off, once. After that the rule no longer fires (although I can see the press and double press events in the button's event log). Interestingly, if I go into the rule editor and then back out (presumably re-saving the rule?) the rule will fire again. This makes me wonder if it's something similar to #1247 (maybe the rule is storing state that's incorrect after the other rule fires?).

**Comment by hobinjk** [comment]
This is issue #1431 which will be fixed on Monday in the 0.6.1 release which your gateway will automatically update to as long as it has an internet connection. If you don't want to wait there's a prerelease image available [on the release page](https://github.com/mozilla-iot/gateway/releases/tag/0.6.1)
