### ISSUE TITLE
Gateway pings 224.0.0.251:5353 on startup

### ISSUE THREAD

**Issue by tdawson** [mozilla-iot/gateway#1466]
Whenever gateway is started, it's pinging 224.0.0.251:5353.
I've checked and it doesn't matter if we are using our own certificate or not.
The issue was commented on in https://github.com/mozilla-iot/gateway/issues/1401
When this ping was blocked, gateway would crash.  The crash was fixed, but there is no reason for the ping.
224.0.0.251:5353 is the default ip address and port of dnssd.
dnssd is called by src/mdns-server.js in DNSserviceDiscovery.
It certainly looks like we are setting an IP and Port in that function, but for some reason, those settings are not being passed to dnssd.

I'm sorry I don't have a patch to fix this.  This was about as far as my nodejs skills could take me.  But could we please get this fixed.
I'm very concerned that people will see this ping happening everytime they start their gateway and think that we're "phoning home" or something like that.

Until this is fixed, we  need to update the Fedora firewall instructions, adding
  firewall-cmd --zone=public --add-port=5353/udp --permanent

**Comment by dhylands** [comment]
224.0.0.251 is the multicast IP address and port 5353 and is used by mDNS to advertise the IP address of the raspberry pi.

**Comment by mrstegeman** [comment]
I assume this is part of the UDP multicast protocol that mDNS uses, so there's nothing to really fix here.

**Comment by dhylands** [comment]
I don't think that you should need to do anything to the firewall. Packets sent to multicast IP address shouldn't leave the local network.

**Comment by nullr0ute** [comment]
@dhylands but they will leave the localhost so if it's a local outbound firewall it might need adjustment.

**Comment by dhylands** [comment]
@nullr0ute right - if the firewall is running on the same machine as the gateway.

The mDNS stuff is only used to advertise the IP address of the gateway (so that we can resolve the gateway using gateway.local). If you already know the IP address of the firewall/gateway then you don't need to let those broadcasts out. You can just browse to the IP address directly.

**Comment by tdawson** [comment]
So, the takeaway is that this is a known thing.
By default, Fedora machines have their firewall turned on.  So I guess the only thing that needs to change is the README to add an extra line to the Fedora firewall setting.
