### ISSUE TITLE
Missing support of integer in https://iot.mozilla.org/schemas

### ISSUE THREAD

**Issue by tomasy** [mozilla-iot/gateway#1467]
In https://iot.mozilla.org/wot/ the property type could be one of (null, boolean, object, array, number, integer or string) but in https://iot.mozilla.org/schemas there are no support for integer just number. I think most of the properties in schemas that have `type: number` could be `type: number/integer`. 

Perhaps not correct place to bug report for schemas. But I was told to create issues where I found missing use of `type: integer`

A comment:
The schemas use only `boolean`and `number`.  No one of the other defined types. Perhaps more needs to be used. Example for `enum`. In a thing define a `LevelProperty` `type: enum`  with values "High", "Medium" or "Low".

**Comment by mrstegeman** [comment]
Moved to mozilla-iot/schemas#16 and mozilla-iot/schemas#17

We also don't support object or array types well right now, but we've not yet found a great use case to actually play around with.
