### ISSUE TITLE
readOnly strings and enums look the same as writable ones

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#1471]
Currently a readOnly enum looks exactly like a writable one. It has the dropdown arrow, and clicking on it does nothing.

Currently a readOnly string looks exactly like a writable one.

I think that a readOnly enum should look like a readOnly string, and that a readOnly string should look something like a voltage (i.e. background color same as the property bubble).

**Comment by benfrancis** [comment]
Sounds good to me.
