### ISSUE TITLE
Upgrade of addons shall also reload devices

### ISSUE THREAD

**Issue by tomasy** [mozilla-iot/gateway#1479]
As a user who upgrade an addon shall also get the devices upgraded at the same time.

Today when a user upgrade an addon and a device have new properties the user must remove the old device and then add it again. If this is not done the new properties are not visible.

**Comment by mrstegeman** [comment]
When add-ons are updated, they are restarted. Once started, they should find and report their things back to the gateway, which should handle the new thing description just fine. That was fixed in #1335. You may have to reload the UI, though.

**Comment by tomasy** [comment]
You are right. When I reloaded the page they are visible. 

I close this bug but perhaps a user shall not be needed to reload the page.
