### ISSUE TITLE
Rolling log Files & removing old log files

### ISSUE THREAD

**Issue by tomasy** [mozilla-iot/gateway#1498]
As a user I do not want to run out of disk space due to very large log files.

Problem:
Today the `run-app.log` is created when the gateway starts and it will growth until it run out of disk or the gateway is restarted. If the OS run out of disk it will stop to work.

Proposal:
1. Add rolling log functionality to log files that works for Linux and other OS.
OR
2. For Linux use `journalctl`, change the `View Logs` to use `journalctl` and make it possible to turn of the `run-app.log`

**Comment by mrstegeman** [comment]
Log rotation has already been implemented. It will be present in 0.7.

See #1420
