### ISSUE TITLE
Extension Add-ons

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1505]
As a developer I want to write an add-on which extends the user interface of the Things Gateway.

This might include:
* Collections of web components to represent third party device schemas
* Adding top level menu entries to add a whole new section to the UI

Questions:
* How would these add-ons be packaged?
* What can we learn from Web Extensions here?
* How can we do this safely?

**Comment by benfrancis** [comment]
I should mention that we do already have an [add-ons system](https://github.com/mozilla-iot/wiki/wiki/Add-On-System-Design) for "adapter add-ons" which use Node packages. a GitHub repository to list them and checksums to verify their integrity.

This issue is about adding a new type of add-ons which modify the gateway's UI.

**Comment by flatsiedatsie** [comment]
Good point :-D

**Comment by flatsiedatsie** [comment]
I had some fun doodling. Some of them are pretty far out.

A detail page for an add-on could look like this:
![mozilla-device-support-page](https://user-images.githubusercontent.com/805405/49964768-3563e200-ff13-11e8-9343-c72f92a9f1c0.png)

Add-ons settings pages could help users manage settings, and even help users get an idea of which devices they govern. Here's an example of a MySensors add-on. Users can use this to easily upload code to Arduino's that they attach to the Raspberry Pi.
![mozilla-device-support-page](https://user-images.githubusercontent.com/805405/49965102-2893be00-ff14-11e8-9ae9-323ddf2f7310.png)

Add-ons could offer things like wizards to help on-board new devices.
![mozilla-device-support-mysensors-wizard](https://user-images.githubusercontent.com/805405/49965015-e79ba980-ff13-11e8-9cb6-e807e255f79c.png)

Here's another example for a 433Mhz cloning add-on:
![mozilla-page-433mhz](https://user-images.githubusercontent.com/805405/49965673-c471f980-ff15-11e8-83b7-a7e7f3f839c1.png)

With a similar wizard:
![mozilla-page-433mhz-wizard](https://user-images.githubusercontent.com/805405/49965710-dc497d80-ff15-11e8-8b87-3b313d2e5832.png)

Not all add-ons are about adding things to the system. Some could focus more on creating software functionality, and could perhaps be called apps instead. Perhaps technically they are the same thing.
![mozilla-page-apps](https://user-images.githubusercontent.com/805405/49964572-bcfd2100-ff12-11e8-8059-a44a09443f8c.png)

![mozilla-page-installed](https://user-images.githubusercontent.com/805405/49964594-cdad9700-ff12-11e8-9b06-1d6016cf70c4.png)

Here's the settings page of an "app" that adds photo frame functionality:
![mozilla-app-picture_frame-settings](https://user-images.githubusercontent.com/805405/49965862-537f1180-ff16-11e8-968a-7d86350cb9a5.png)

But I could imaging all kinds of apps that try to wrangle the available functionality into larger types of over-arching functionality.

**Comment by createcandle** [comment]
Here's a practical example of an interface I'd like to incorporate into the Mozilla Gateway somehow:
https://github.com/createcandle/Candle-manager

**Comment by flatsiedatsie** [comment]
Here's another mockup.


The idea would be:

![mozilla-gateway-apps](https://user-images.githubusercontent.com/805405/51531575-bfb63480-1e35-11e9-9c7c-a9b3672c4f60.png)


- Apps can have a display page. Once started, 'apps' can take up the entire screen. The side menu would always be on top of any 'app'. This would allow for, for example, a photo display app.
- Apps can bring along a settings page. This could be made to preferentially conform to the Gateway's CSS, but still allow for custom JS. Settings pages allow for the launch of settings wizards that aid users in the generation of new devices / recording of new signals, etc.
- Apps can bring along 'widgets'. These are tiny templates for data display. They have 'slots' where users can add existing data sources. This could allow them to overlay simple graphs, create a list of toggle buttons, create a widget optimised for weather forecasts, home energy usage, car charging status, etc. These widgets could become a marketplace all of themselves. In my experience it's really useful if people can mix and match existing data into new display constellations. They often want to bring disparate sensors from different devices together [in one view/widget](https://www.pineapplejazz.com/public/domoticz/aurora/compact.png).

Here's a quick bad mockup of what that could look like. In reality these widgets could be made to be more in one style if some useful ready made widgets are bundled with the Mozilla Gateway.

![mozilla-gateway-dashboard-mockup](https://user-images.githubusercontent.com/805405/51531693-1459af80-1e36-11e9-9e2e-78a43337e950.png)

**Comment by flatsiedatsie** [comment]
I was thinking: what if the add-on settings page is expanded a little bit as follows:

- The jason schema is still transformed into a basic HTML form, as it is now.
- That form is now a html page that is inside an iframe.
- An add-on can add javascript to that html page, so that the basic form can be transformed into more advanced interfaces (wizards, fancy selectors, etc). The iFrame would limit the reach of that javascript.
- The javascript could interact with the add-on in a very basic way to pull/poll updated data from it. For example, in the case of the presence detection add-on, a list of found devices on the wireless network could be updated by the add-on. The javascript could pull in the updated list and display it inside a textarea. This textarea has another bit of javascript code to turn it into a fancy selector tool. The user can then select which device on the wireless network they want to add as a thing, and send this knowledge back to the add-on, which then only presents those devices as things.
- The add-on settings page could, perhaps through a checkbox, gain a shortcut inside the main menu. That way it could become more like an 'app'.

**Comment by flatsiedatsie** [comment]
Perhaps as an interesting example I'm currently working on an add-on that needs a complex interface. The add-on now creates a thing with an "alt" link. If you click on it it opens a new page in a new tab. This page is served by the Flask webserver (on a different port) that the add-on launches and manages.

![candle_manager_sneak_preview](https://user-images.githubusercontent.com/805405/59334627-71bda280-8cea-11e9-9fed-d09284e7a458.png)
It will allow users to upload code to Arduino's that they attach using a wizard.

**Comment by mrstegeman** [comment]
I'm going to close this issue now that we can build extensions. Any additional extension points that we want can be filed in their own issues.
