### ISSUE TITLE
Nice to have: picture frame screensaver

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#1506]
Nowadays a lot of people have old or cheap tablets (of phones). They will likely often be used as permanent remote controls and data displays for the Mozilla Gateway.

Some of these may be mounted to walls, some have cases that allow them to be propped up on a cabinet, others may simply find a home in the living room.

Currently, these tablets may permanently show the interface so that people can see things like temperature, weather forecast, etc at a glance, or toggle actuators.

However, users may prefer to hide the interface most of the time, and have the tablet function as a picture frame until it is tapped/moved.

PRACTICAL
- The user can choose to enable "picture frame screensaver" from settings. Optionally, there is also a 'wait X minutes before going into screensaver mode" slider here.
- The gateway reveals a 1Gb SMB drive that shows up in the users network. 
- If users place pictures on that drive they will be used for the picture frame screensaver. Other files than pictures are ignored/deleted.
- If the user has selected the picture frame option, and the web interface has not been interacted with for X amount of minutes, then the slideshow starts.
- If the user touches the screen, the slideshow stops.
- If the user has created an automation that requires something being shown on the screen, then the slideshow stops.

OPTIONAL
- Create a "go fullscreen" (and close fullscreen) button in the interface, so that the UX is shown full screen. This is a feature that would still be useful even if the picture frame feature is not implemented. At the start of the photo display the browser could go fullscreen. If the browser was originally not in fullscreen mode, the browser could disable fullscreen mode when the slideshow is stopped by a touch event.
- Allow videos to be uploaded as well.
- Create more settings, like "show in black and white", "use ken burns effect", "show videos in slow motion".

ALTERNATIVE
- A SMB drive is not created, but a web-based photo upload is used instead.

ADVANTAGES
- Increased privacy: data from the system is not immediately visible to visitors of the home.
- Security by obscurity: visitors do not immediately see that he tablet is a control surface.
- Technically relatively easy to implement.
- A [popular feature](https://www.theverge.com/2018/10/22/18005724/google-home-hub-digital-photo-frame-review-specs-features-price) that is still rarely implemented.

OPPORTUNITIES
- If the gateway has an internet connection, then it could show pictures from online photography resources.

**Comment by benfrancis** [comment]
This would probably work better as a feature for a [Things Controller](https://github.com/mozilla-iot/things-controller) rather than the Things Gateway.

**Comment by flatsiedatsie** [comment]
Interesting, I didn't know about the Android app. That would definitely make sense.

building it into the gateway (or better yet, building the add-on system in a way that would allow a third party to create this feature) would also create it for the Android app. From the UI slides:

"loads the gateway web app as its home screen inside a webview"

**Comment by mrstegeman** [comment]
See discussion here: mozilla-iot/things-controller#10
