### ISSUE TITLE
Split systemd service files out of image builder script

### ISSUE THREAD

**Issue by mrstegeman** [mozilla-iot/gateway#1510]
This would allow for easier packaging and such outside of the Raspberry Pi image.

**Comment by dhylands** [comment]
The primary motivation for having them be here documents is that then only a single file needs to be copied to the Pi when creating the base image.

I'm not opposed to splitting them out, but perhaps ww can write a helper script to bundle all of the files together into a tarball or self extracting script for installing onto the Pi

**Comment by che-wf** [comment]
Is there a possibility that we could rely on the Debian package manager for those who have installed it on the Pi (not via Gateway image)?
