### ISSUE TITLE
WebThing properties not getting updated

### ISSUE THREAD

**Issue by atirage** [mozilla-iot/gateway#1511]
I have a webThing based on webthing-python-0.8.1 and a Gateway running version 0.6.1, the webThing is linked to the Gateway with the thingURLAdapter v0.2.5. I recently noticed that the GUI is not showing the correct/actual values of my things's properties. Accordingly, if I make a GET directly on the thing, I'm getting the latest values, but not if I make a GET through the Gateway, like:
http://raspi0.local:8888/properties =>
{"motion": 0, "light": 6.7, "pressure": 0.97, "temperature": 18.0}

https://atirage.mozilla-iot.org/things/http---raspi0.local-8888-/properties/ => {"light":0.2,"pressure":0.97,"temperature":17.3,"motion":false}  

My understanding is that the Gateway should get the property changes through WS and this should be reflected on the REST API also.

**Comment by atirage** [comment]
Any luck tracking down this issue?
I did some additional trials and I could identify 2 scenarios by running  journalctl -u mozilla-iot-gateway.service -f in parallel:
1. journalctl shows the property updates, but the UI doesn't
2. both journalctl and the UI are not showing the property updates, although, as mentioned in my previous comment, the webthing is responsive on a different WS - seems an issue with the WS connection between the GW and the webthing

**Comment by mrstegeman** [comment]
I've had a test running for ~12 hours now and never see properties stop updating. Please re-open if this occurs again and is reproducible.

**Comment by RitvikSardana** [comment]
I am unable to make changes in the UI ,can anyone tell me how to do changes in the UI?
