### ISSUE TITLE
Home screen doesn't work in Nightly (65)

### ISSUE THREAD

**Issue by janodvarko** [mozilla-iot/gateway#1512]
When loading my gateway's home screen from http://*.mozilla-iot.org it's almost empty and not interactive. It happens in Nightly (65), Firefox release (63) works just fine.

I am seeing the following errors in the (DevTools) Console panel:
* TypeError: this.listeners.onopen is not a function index:55
* Get things failed TypeError: this.ws.addEventListener is not a function gateway-modael.js:152

... and other (also related to WebSocket API)

Honza

![image](https://user-images.githubusercontent.com/37785/49006013-68af1e80-f168-11e8-8b59-af2c046df0e0.png)

**Comment by benfrancis** [comment]
Thanks for the bug report. This is working for me on Nightly (65) on Mac OS with Things Gateway 0.6.1. What OS are you using and what version is your gateway on?

Have you checked to see if a hard reload makes any difference?

**Comment by janodvarko** [comment]
I am on Win10, running Gateway 0.6.1, not even hard reload helps.

But, one thing to note. Downloaded Nightly works fine, the problem is on my m-c build.

My .mozconfig doesn't have anything special:
mk_add_options AUTOCLOBBER=1
ac_add_options --enable-artifact-builds
ac_add_options --enable-debug-js-modules

Honza
