### ISSUE TITLE
replace npm-run-all with concurrently 

### ISSUE THREAD

**Issue by nullr0ute** [mozilla-iot/gateway#1513]
event-stream has a vulnerability: dominictarr/event-stream#116 and appears to be somewhat unmaintained.

It seems one way to fix this, done by a few sites, is it replace the use of npm-run-all with concurrently. One example is https://github.com/BBC-News/simorgh/commit/71eb5e27b38b70137130b27726affef82e2f5ae9

**Comment by mrstegeman** [comment]
Luckily, our event-stream dependency is set to 3.3.4 in our lock files, but yes, we could also replace `npm-run-all`.

**Comment by nullr0ute** [comment]
It seems more maintained (at least at this moment in time) so it might be worth considering.
