### ISSUE TITLE
LeakSensor Capability UI

### ISSUE THREAD

**Issue by mrstegeman** [mozilla-iot/gateway#1514]
As a user, I want to see if a leak has been detected.

**Comment by benfrancis** [comment]
How's this?

![leak_sensor_capability](https://user-images.githubusercontent.com/552417/50845049-e9665a80-1363-11e9-9df3-495f071bf511.png)

**Comment by mrstegeman** [comment]
Works for me. Icons, please?

**Comment by benfrancis** [comment]
Icons:
- [Leak sensor (with circle)](https://drive.google.com/file/d/1njx-x5nKVluOncyWB_VtHyoWCcGrmKM-/view?usp=sharing)
- [Leak sensor - dry](https://drive.google.com/file/d/1C6m0cifjeX6oEeYLdTy0U17C17yRxL4V/view?usp=sharing)
- [Leak sensor - leak](https://drive.google.com/file/d/1AZGuDWZU5gM0Xgb-DQEBI2nLNTjE5n2a/view?usp=sharing)

Let me know if these don't work for any reason.

Thanks

**Comment by mrstegeman** [comment]
@benfrancis Thanks. Just missing the rules icon.

**Comment by benfrancis** [comment]
- [leak sensor (rule icon)](https://drive.google.com/file/d/1XStVbRVqQxkrZcTCcLfeIJB8Vk4Snpy7/view?usp=sharing)
