### ISSUE TITLE
TemperatureSensor Capability UI

### ISSUE THREAD

**Issue by mrstegeman** [mozilla-iot/gateway#1515]
As a user, I want to see the temperature.

**Comment by benfrancis** [comment]
@mrstegeman 

![temperature_sensor_capability](https://user-images.githubusercontent.com/552417/50911872-ade19400-1428-11e9-85d9-7ef7a6c0150e.png)

- [Leak sensor (with circle)](https://drive.google.com/file/d/1AVVDiLPLR1mEXbAhkegSMEuBjejxVTtS/view?usp=sharing)
- [Leak sensor (without circle)](https://drive.google.com/file/d/1WXo2lxcyfM_pNHDaLcZv4UQEQ0mSkGPA/view?usp=sharing)
- [Temperature sensor (rule icon)](https://drive.google.com/file/d/11Ud5HgkezVUlvxJsV_p8tX10EfHtBBEl/view?usp=sharing)

**Comment by benfrancis** [comment]
Note: This UI design is assuming read only. If we have a writable temperature property (e.g. for a thermostat set point) we will need an alternative UI with an editable number field.

**Comment by mrstegeman** [comment]
Awesome, I'll get this done today. Thanks!
