### ISSUE TITLE
Python communication

### ISSUE THREAD

**Issue by mrproton** [mozilla-iot/gateway#1516]
Hi there,
I successfully installed the mozilla-iot gateway and I am able to control my Hue light using the webinterface. However, it would be nice to switch on my bulb using Python. Is this possible? I found the Webthing API - can I use Python to connect over the webthing api to my mozilla-iot gateway and turn on my bulbs? Is there a tutorial for that?
Thank you! :)

**Comment by dhylands** [comment]
The gateway advertises itself using a REST API. You can definitely connect to the REST API and turn on your bulb.

If you look in this repository, you will find some bash scripts which use curl: https://github.com/mozilla-iot/curl-examples

You need to login (which will grab a jwt and save it) and then you can enumerate the devices and then control a property using the set-property.sh script.

Under python this would be done using the requests module. I also have a crude command line program written in python that I've hacking on: https://github.com/mozilla-iot/cli

The https://github.com/mozilla-iot/cli/blob/master/cli/gateway.py has a login method that logs into the gateway and retrieves the JWT. I don't think I have a command for setting a property, but that would be easy to add.

Lars has several blog posts here: http://www.twobraids.com/ in particular this one: http://www.twobraids.com/2018/10/the-things-gateway-pythonic-rule-system.html which may do what you want.
