### ISSUE TITLE
Scrollbar is missing in Firefox Android

### ISSUE THREAD

**Issue by tomasy** [mozilla-iot/gateway#1527]
Browser: Firefox Android 65.0a1
Gateway: 2018-11-28
In rules there is no scrollbar for a device properties. So when a user add an input/output device it will only show the first x property choices.

In chrome-browser the properties is in a list with scrollbars and works well.

**Comment by mrstegeman** [comment]
This was fixed in #1485

**Comment by tomasy** [comment]
Sorry I think you misunderstood.  #1485 is about integers but this is issue is about the ui for Firefox Android browser.
I checked this with gateway from  2018-11-28 and your fix is 22 days old.

Screenshot below is from Firefox for LInux and it contains scrollbar (right to "Sunset") but Firefox for Android lacks this scrollbar. Perhaps it is a bug in Firefox for Android.
![screenshot from 2018-12-01 18-30-31](https://user-images.githubusercontent.com/21138866/49331042-664d2a00-f597-11e8-8c07-2780478d310b.png)

**Comment by mrstegeman** [comment]
Ah, the CSS fix that added the scroll bar was in that PR, but there may be something specific to Firefox for Android.

**Comment by mrstegeman** [comment]
I'm unable to reproduce this. Using Firefox 63.0.2 on Android, no scroll bar is displayed (as is usual on Android), but the list scrolls just fine with a touch/swipe.

**Comment by tomasy** [comment]
I think it is related to browser cache. If I upgrade the browser, I use Firefox Nightly builds, the scroll is not working with touch/swipe. But if I then reload the page everything works.
