### ISSUE TITLE
Settings - Time

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#1530]
It seems the gateway currently [supplies the wrong time](https://github.com/tsathishkumar/MySController-rs/issues/8) (if I understand correctly).

There is no option in the UX for setting the time / clock.

I don't know if [setting a location](https://github.com/mozilla-iot/gateway/issues/1113) / timezone would be a better / enough of a solution.

The issue of Europe stepping away from summer/wintertime is also coming in the median future.

See also:
https://github.com/mozilla-iot/gateway/issues/1113
https://github.com/mozilla-iot/gateway/issues/1428

**Comment by tsathishkumar** [comment]
@flatsiedatsie , I think gateway is not the right owner for this issue. The controller(MySController-rs) is the one currently responds to time request from sensors.

**Comment by hobinjk** [comment]
I believe #1113 is the best way of solving the time problem but I agree that there are benefits to being able to manually adjust the gateway's time

**Comment by edwoody** [comment]
![Mozilla iot gateway time](https://user-images.githubusercontent.com/44067243/54590819-53078280-49ff-11e9-8756-65f15bbb203e.jpg)
I can't get date/time to behave.  I set the time zone EST5EDT (east coast us).  Then sudo raspi_config US/NewYork.  It was set for somewhere in europe.  Nothing changed though.  Still somethings wrong.  Sunrise is says was at 2019-03-18 20:09:59.548290-04:00  8 hours ago.  It's 4:30am here.  Still dark. Sunrise will be at 07:35.  Nearly a 12 hour difference. Mozilla gateway "things" says it's not dark.

**Comment by mrstegeman** [comment]
@edwoody The date-time adapter is actually a third-party adapter, unrelated to this issue.

However, I'm guessing what happened is that you didn't configure the latitude and longitude properly for the add-on. The sunrise and sunset are calculated based on that, not the time zone.

**Comment by edwoody** [comment]
Hi Michael,
Thanks for replying.  This is ver 070, the latest.  What strikes me as odd is how close it is to being exactly backward.  Sunrise is sunset and sunset is sunrise.  11 hours and some minutes apart. The values here, latitude and longitude. are what I found on the net for Greenville SC  US.  Although I wanted to be sure of the time zone, region etc.  And Thanks in advance.  It’s a head scratcher for sure.



Sent from Mail for Windows 10

**Comment by mrstegeman** [comment]
Can you take a screenshot of your date-time-adapter config from the UI? If you don't want to post it here for privacy reasons, you can send it to me directly at mstegeman@mozilla.com.

**Comment by edwoody** [comment]
there's a display of date/time when keying in "date" in the pi.  Just not in the gateway software.  Mine is about 6 min slow. A way to view time or set time would be nice.

**Comment by flatsiedatsie** [comment]
I'm running into this again as well.

The MySensors adapter uses a library that has a built in feature to tell the nodes in the network the time. it simply sends the Unix time from the Pi to the nodes. I use this, for example, for an alarm clock. It requests the time from the controller.

As the Pi is on UTC, this means my alarm clock displays a time that is two hours behind the actual time.

I could try to hack/modify the library to override it with a shifted time somehow. But even then this would require the WebThings Gateway to tell the adapter what the user's actual timezone/time difference is.

**Comment by tim-hellhake** [comment]
> As the Pi is on UTC
Unix time is per definition UTC.
Showing the correct local time is a matter of localization and should be done by the ui/display itself.
> the user's actual timezone/time
But which user? As I understand it an addon is installed per system not per user.

**Comment by flatsiedatsie** [comment]
@tim-hellhake You're right, I meant to say a timestamp in Unix format.

"As I understand it an addon is installed per system not per user."

Great! A system has a physical location, and that is always in a timezone. Setting a system time is a great place to start.

**Comment by dhylands** [comment]
There are probably a number of ways to deal with this.

One way is to run raspi-config and set the timezone. Then when you ask for the localtime it will give you the proper local time.

We should probably make setting the timezone part of the first-time setup.

**Comment by flatsiedatsie** [comment]
"One way is to run raspi-config and set the timezone."

The problem is that the logs don't work properly anymore if the system is not on UTC.

**Comment by tim-hellhake** [comment]
> The problem is that the logs don't work properly anymore if the system is not on UTC.

Then maybe we should fix this ;-)

**Comment by flatsiedatsie** [comment]
I really ran into this issue while creating the Voco add-on. One of it's features is that it allows users to say things like "set an alarm for 8 o'clock".

Currently the add-on has to deal with 3 different times:
- The local time according to Raspbian. In my test case, this was set to London time (+1) out of the box.
- UTC standard time. This can be derived from the above, and is used internally for time delta calculations.
- The time zone that the user is actually in. Currently, the user has to set this in the add-ons settings. E.g. in Paris the difference to UTC is +2 hours, or 7200 seconds.

It's.. a lot of operations, which could be avoided if the WebThings Gateway could be relied on to have the actual local time of the user.

More importantly, it's fragile. The problem is that when the user says "set an alarm for 8 o'clock", Snips will internally deduce when the next 8 o' clock is based on the internal clock.

This leads to weird situation. E.g. imagine that the user's is in Paris at 20:15 and they say "set an alarm for 8 o'clock". For them 20h has passed, and the next 8 o'clock will be in the morning. But Snips, which is operating in London time, will return "20h" as the desired time, since according to it the next "8 o'clock" is just 45 minutes away.

There are a few solutions:
- The user could SSH into the device and set the time and locale using raspi_config. That goes completely against the wonderful usability of the rest of the gateway.
- The add-on could force a new timezone for the entire device. (I haven't looked into if this is actually possible). But then you get the issue of multiple add-ons all overriding each other all repeating this code.

Ideally, a user sets their local time/zone in the Gateway UI.

**Comment by flatsiedatsie** [comment]
As far as I can tell from the new code, it allows a user to set the time zone, but not the actual time? So the system is still dependent on a third party service for that? Which means the system is still regularly "phoning home" to some unknown party?

**Comment by mrstegeman** [comment]
It is only "phoning home" in the sense that it is pulling the current time periodically via [NTP](https://tools.ietf.org/html/rfc5905) from the [NTP pool](https://www.pool.ntp.org/en/). NTP request packets don't have anything sensitive in them.

Our reasoning for still using NTP versus having the user manually set the clock is discussed [here](https://github.com/mozilla-iot/gateway/issues/1113). However, the user can still use the gateway completely offline, which means NTP wouldn't be used. In that case, they'd have to handle the clock on their own.

**Comment by createcandle** [comment]
>  NTP request packets don't have anything sensitive in them.

They do. Your IP address is considered personal data.

On top of that, privacy invasion isn't just about the content of the packet. It's just as much about observing behavioural patterns.

Nothing is free. Is Mozilla paying the NTP server pool? Do you have a subscription to it? If not, it means they are making money some other way. From what I can tell, anyone can add their server to the NTP pool, meaning you can't be sure who is getting the ping from your system. It might be Facebook, Google, etc.

On top of that, any intermediary server along the route could find out that this IP address requested the time. A whole string of servers is informed that my IP address is connected to the internet, and that I just booted up a system.

In the data economy, any signal is useful. If there is data, it will be fed into algorithms that derive and infer new data from it. The best way to protect privacy and enhance security is to not emanate any signal in the first place.

https://resources.infosecinstitute.com/network-time-protocol-ntp-threats-countermeasures/
