### ISSUE TITLE
Allow adapters to prompt user to take action when pairing

### ISSUE THREAD

**Issue by mrstegeman** [mozilla-iot/gateway#1541]
Some adapters, such as Z-Wave, require the user to push a button on the device during the discovery process, but there is currently no way to tell the user about that.

Other adapters can discover devices, but cannot pair unless the user pushes a button or something similar.

**Comment by flatsiedatsie** [comment]
This feels related to https://github.com/mozilla-iot/gateway/issues/1505

**Comment by freaktechnik** [comment]
Not really. The goal here is that the adapter can just say "here's a device that can't quite be added as it is right now, but I found it!". This shouldn't need arbitrary UI modification.

**Comment by flatsiedatsie** [comment]
Ah I see. I thought that the UX to be presented would depend on the type of device (Zigbee, MySensors, etc), and thus on which add-on is responsible.

Are you saying onboarding will be a single unified interface? Perhaps like an 'inbox' for new devices?

**Comment by freaktechnik** [comment]
My suggested solution would be to have an option to display a string in the pairing screen to show further pairing instructions, similar to how pin auth for pairing devices works. However I do not know the full range of pairing solutions that should be covered. Either way, this is something that should be surfaced in the pairing screen (the plus in the bottom right of the device overview).
