### ISSUE TITLE
Discovery using  Bluetooth Eddystone beacon not working on 0.6.1 installed from the stock image

### ISSUE THREAD

**Issue by andrenatal** [mozilla-iot/gateway#1546]
Steps to reproduce:

1 - Flash a new sd card with the 0.6.1 image
2 - Start a rpi with it
3 - Navigate to the gateway's wifi setup and skip it
4 - Wait for the message below to be displayed
` Note that gateway.local may take some time to become active. The gateway can also be accessed directly via its local IP address or discovered using a Bluetooth Eddystone beacon scanner. `
5 - Try to discover the beacon using any compatible phone. On Android Oreo, pull the settings window and touch `Nearby` and the beacon won't be displayed

**Comment by mrstegeman** [comment]
Could be due to this: https://android-developers.googleblog.com/2018/10/discontinuing-support-for-android.html

**Comment by andrenatal** [comment]
Yeah, fast pair would be a way better option

https://android-developers.googleblog.com/2017/10/announcing-fast-pair-effortless.html?m=1

**Comment by mrstegeman** [comment]
We're not using it for pairing purposes, though, just advertisement.

**Comment by mrstegeman** [comment]
Obsolete. We're no longer advertising an Eddystone beacon.
