### ISSUE TITLE
Some sliders don't display properly

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#1551]
In particular the level slider in the Virtual Multi-Level Switch
![virt-multi-level](https://user-images.githubusercontent.com/127500/50302769-f0263f80-043f-11e9-9877-ce10b5f47e71.png)

and the brightness slider in the Virtual Dimmable Color Light
![virt-dim-color](https://user-images.githubusercontent.com/127500/50302796-092ef080-0440-11e9-9cba-9acd08c5df8c.png)

These were both displayed in Firefox 64 under Linux.

**Comment by mrstegeman** [comment]
Hmmm... I can reproduce, but only on Linux.

**Comment by mrstegeman** [comment]
This appears to be a Firefox bug, rather than ours, as a generic slider on MDN displays incorrectly as well: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range

**Comment by mrstegeman** [comment]
I've opened https://bugzilla.mozilla.org/show_bug.cgi?id=1515713
