### ISSUE TITLE
Automatic dependency updates

### ISSUE THREAD

**Issue by mrstegeman** [mozilla-iot/gateway#1553]
Should we use something like [Dependabot](https://dependabot.com/) to auto-update our dependencies?

**Comment by hobinjk** [comment]
I don't think any sort of auto-updating is good outside of reacting to critical security vulnerabilities. While having the david-dm badges means that there's a visual indicator of when we're not on the latest and greatest versions of dependencies I don't think it's worth the potential of a malicious dependency update. If there's a way to get dependabot to only do security-related updates then I'm all for it.
