### ISSUE TITLE
Date/Time device

### ISSUE THREAD

**Issue by edwoody** [mozilla-iot/gateway#1554]
Thanks for the Date/Time device.  Unfortunately either I don't understand it, or it's a work in progress.  The menu has 12 adjustable possibilities?  But finding "sunrise" in the drop down is impossible.  The menu is too long for the screen to display all the possibilities.  Especially on a computer, but even on a tablet you just can't see all the selections.  If this is me not understanding something please advise.  BTW, I'm probably overdue for a Christmas gift to you guys. Weekend, not weekend, sunrise, sunset I get.  Then adjust with submenu.  But 12 selections.  Thanks

**Comment by mrstegeman** [comment]
Thanks for the bug report! I’ve actually already fixed this. The fix will be present in our upcoming 0.7 release in January.
