### ISSUE TITLE
Email verification fails on new regisration

### ISSUE THREAD

**Issue by mewt666** [mozilla-iot/gateway#1556]
Having setup my gateway, I received an email to confirm my email address. Upon clicking the link or following the provided URL, an SSL error is presented to the user:

![image](https://user-images.githubusercontent.com/3087944/50454038-3817fb80-0945-11e9-8242-d467f99a23c4.png)

**Comment by mrstegeman** [comment]
Duplicate of 
https://github.com/mozilla-iot/registration_server/issues/77
