### ISSUE TITLE
Rule does not always properly activate/deactivate a device

### ISSUE THREAD

**Issue by trink** [mozilla-iot/gateway#1560]
I am using the Pulse add-on to create a timer for a switch and have a Rule like this
'While PumpTimer is on, turn Circulation Pump on'

When testing this rule with a virtual device it always works as expected.  However, when using it with a Eufy smart plug it occasionally fails in various ways.
1. Activating the timer does not activate the plug
1. When the timer deactivates the plug is not turned off

I also tried a pair of `If` rules instead but have had similar issues.  Latest release 0.6.1

![screenshot_2019-01-02 things gateway](https://user-images.githubusercontent.com/795988/50602154-66c53300-0e6b-11e9-88da-bad77f5dfa0d.png)

**Comment by trink** [comment]
Note: In the cases where it fails there is a generic error in the log: `2019-01-03 03:05:51.337 Unhandled Rejection`.  A retry mechanism would be useful to prevent the device from being left on forever.  Also, more detailed logging (device/rule/user) the error is associated with as it is unclear when there are multiple simultaneous interactions taking place.

**Comment by hobinjk** [comment]
I'm adding one retry to every time a rule sets a property and some logging which should be better than Unhandled Rejection
