### ISSUE TITLE
x86-64 or x86 Ubuntu/Debian Linux: libpng version

### ISSUE THREAD

**Issue by rhyspowell** [mozilla-iot/gateway#1589]
While working through the document, getting to this point failed for me on Ubuntu 18.04.

it appears the requirement for this version is
libpng16-16

While I would raise a PR normally, not sure how you would like to handle the documenting of the difference in the version across OS versions

**Comment by mrstegeman** [comment]
It appears that `libpng16-16` also exists in Raspbian Stretch and Ubuntu 16.04, so we can just update the README. Do you want to submit a PR?

**Comment by rhyspowell** [comment]
will do, give me a few minutes

**Comment by rhyspowell** [comment]
https://github.com/mozilla-iot/gateway/pull/1590
