### ISSUE TITLE
Feature request: dashboard

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#1597]
Many home automation applications have a dashboard functionality. This offers a customisable overview of current system status.. and much more.

Is this something the Mozilla Gateway strives to implement as well?

A dashboard is different from a datalog page. A datalog page's goal is to help a user gain insights by carefully studying data patterns. A dashboard is more about quickly showing current values. Still, if a dashboard widget can show a simple graph, then there could be a small overlap in functionality. (By the way, isn't 'insights' a better name than the technology focused 'datalog'?)

A dashboard page is different from a things page. Currently the things page is not equiped to give a glanceable overview of a thing's many properties. It can only show one. Besides this, a dashboard is about showing more than things status, as it can also show data such as the weather report or a calendar-for-today view.

![mozilla-gateway-dashboard-mockup](https://user-images.githubusercontent.com/805405/51535253-d6fa1f80-1e3f-11e9-8e1a-c44c55032b56.png)

Sticking to the circular interface of the things page is, in my opinion, too limiting. Square items can contain more information. Perhaps users could select how much real estate a widget can have. For example:
- small (1 square)
- wide (2 squares side by side)
- tall (2 squares on top of each other)
- big (4 squares in a 2x2 formation).

Perhaps widgets could be based on schema. But I suspect many devices will not conform to them. Often schema are based on single things (one toggle button), while a widget may want to show a list of toggle buttons. Also, a single universal schema might not conform to everyone's preference. It could be very interesting if there was some kind of market for widgets. These widgets would have empty slots that users can place values from all over their system into.

![thermostat-control-example](https://user-images.githubusercontent.com/805405/51536180-a667b500-1e42-11e9-9e86-b61c86f13942.png)

**Comment by benfrancis** [comment]
I like the idea of a dashboard, and the idea of installable widgets.

However, to provide enough flexibility to create the kinds of examples you've mocked up we'd need quite a sophisticated system for packaging, discovering, installing and rendering what are essentially mini web applications embedded in a web page, hosted by the gateway's web server. Not all of them are even related to the smart home itself (e.g. the stock ticker, or calendar widgets) so would need to be able to communicate with arbitrary web services. Security would be a particular challenge.

Similar things have been done quite a few times before. Remember [Google Gadgets](https://en.wikipedia.org/wiki/Google_Gadgets)? There was even a [W3C spec for widgets](https://www.w3.org/TR/widgets/), but it is now considered obsolete.

We could potentially make widgets a type of add-on, but there's a lot involved to make that possible.

A simpler approach would be to have a set of pre-defined smart home widgets you can configure and add to the dashboard, for example to show a particular set of property values all in one place, a graph of a particular property over time, quick access to an action, show a group of devices or a trigger a scene. That wouldn't have anywhere near the kind of flexibility displayed by your mockups, but could be easier to implement.

**Comment by flatsiedatsie** [comment]
Cool. Just adding what you describe as the simple approach would already be fantastic.

In the theme I made for Domoticz I added the ability to add (a URL that creates) an iFrame. Then it's up to the user to find / community to build / scrape small widgets. It turned out to be quite useful, also for adding things like non-standard webcams outputs.

**Comment by flatsiedatsie** [comment]
I was toying about today:
![mozilla-remixed-things](https://user-images.githubusercontent.com/805405/52427541-0a9f9f80-2af8-11e9-8545-36c83d4a0305.png)

**Comment by flatsiedatsie** [comment]
Just thinking out loud, here's an idea for a much simpler (first) version.

Step 1.

On a thing detail page a user can select which _properties_ are their favourites.

![select_favourites](https://user-images.githubusercontent.com/805405/56762062-77891400-678e-11e9-8333-e9a4fe540482.png)

Step 2.

There is a dashboard page where all the favourite properties swarm together.

![old-screenshot](https://user-images.githubusercontent.com/805405/56762080-81127c00-678e-11e9-9542-e738db617114.png)
_Please imagine this is a swarm of properties instead of things._

Perhaps with some indication which thing they came from (still has the thing name in the name), and/or with a button that leads 'back' to thing overview page. This would have the advantage of letting users quickly remove things from the dashboard: go back to the thing overview and un-star it.

Like on the things page, they can drag the properties to new locations, allowing for a rudimentary grouping.

Step 3.

There is no step 3.


Step 4.

In a later version this dashboard page could offer some basic grouping functionality. For example, if a user drag-and-drops a property onto another property, those two properties now get a little border around them. They are clumped together. A user could drag properties out of the group. If there are two left, and one is dragged out, this removes the group.

![old-screenshot-property-groups](https://user-images.githubusercontent.com/805405/56762826-4c072900-6790-11e9-89f8-6575206570ca.png)
_A very rough sketch of a group of properties on the dashboard_

**Comment by flatsiedatsie** [comment]
@benfrancis I'm curious what you think of the 'dashboard of properties' idea. The more I think about it, the mode I think it could be a good and relatively simple solution for getting the buttons and values you actually want to see at a glance on one page.

**Comment by benfrancis** [comment]
I like the idea of a dashboard you can populate with widgets, including individual properties. This could be a good first use case for an [Extension Add-ons](https://github.com/mozilla-iot/gateway/issues/1505), once we support those, as a way to prototype a dashboard.

**Comment by flatsiedatsie** [comment]
That's a great idea. Focus on a good API, and then like with Domoticz and other similar software users could step up and create all kinds of dashboards.

**Comment by mrstegeman** [comment]
Going to leave this to an extension.
