### ISSUE TITLE
I cant connect to my host via mozilla-iot.org 

### ISSUE THREAD

**Issue by abalashov78** [mozilla-iot/gateway#1599]
Today i can't connect to my IOT GW
I have error "Content Distortion Error or Redirection State" 
In Mozilla Firefox console "Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. bundle.js:3811"
reboot don't help for it.  my host is online.

**Comment by mrstegeman** [comment]
Just FYI, you can still access your gateway locally at https://gateway.local:4443 until this is resolved.

**Comment by abalashov78** [comment]
Hi!
So. I know problem - ssl certificate was expired yesterday. 
Period for certificate 3 months after installation. 
Closed.
