### ISSUE TITLE
Feature request: if-then-but-only-if style conditionality in automations

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#1607]
The current automation system is great (creating the human readable sentence is great), but rudimentary.

If I could suggest an expansion, it would be to create an "if.. then.. but only if" style system. The 'but only if' part gives user just a tad more complexity to play with, without making it too much. That's my opinion of course, but many other similar systems seem to be moving in that direction.

For example, this uses an "if..then..unless" style system:
https://youtu.be/a-Xw72ItHsc

This example does conditionality in reverse: it adds "but only if".
https://youtu.be/fs0y5xc03EA?list=PLbIEwfYFMhVktBWMEghujReM6z8A6qdPJ&t=37

**Comment by rzr** [comment]
Hi,
Can't you do that with booleans ops on input conditions ? 

eg: if this and that then do stuff ?

about more evolved conditions I made a couple of suggestions by introducing function bock to wire the logic see, my comments in: https://github.com/mozilla-iot/gateway/issues/805

**Comment by hobinjk** [comment]
Both of the systems from the videos appear to be designed around separating event triggers from property triggers, i.e. from the first one "[when this event happens] [then do this action] [if this condition is met]" 

In my opinion this is an unnecessary distinction and it's more natural to group together the instantaneous event triggers and continuous property conditions. This does require the user to consider the difference between instantaneous and continuous but allows for a wider variety of rules and a simpler overall UI. An example of the subtle differences permitted by the simplification is "if front door is open and back door is open then turn on light" and "if front door is opened and back door is opened then turn on light". The first is the continuous "if at any point both doors are open then turn on the light" and the second is the simultaneous "if both doors are opened within the same short time period then turn on the light"

Notably, any rule in the format "when event then action but only if condition" is expressible as "if [condition or event] then [action]"

**Comment by benfrancis** [comment]
I agree with @hobinjk
