### ISSUE TITLE
Not possible to set the name of a Property by using title

### ISSUE THREAD

**Issue by tomasy** [mozilla-iot/gateway#1618]
The rename of 'label' to 'title' is not working as expected. 
If only 'text' is set in the description of a Property the name of the Property will be to the id for most of the types except for LevelProperty. In that case it will be set to 'Level'.

If 'level' is set it is working as expected.

**Comment by benfrancis** [comment]
@mrstegeman Is this a bug or a missing feature?

**Comment by mrstegeman** [comment]
@tomasy I'm not fully understanding the issue. Can you give me a test case?

**Comment by tomasy** [comment]
I thought 'label' is deprecated and 'title' was the correct for a Property. 
Example for  Property Minute in the image below. When I create it and set the description to
`{'title': 'Minute', '@type': 'LevelProperty',...` the title will not be Minute in the image it will be 'Level'
![screenshot from 2019-02-05 22-56-26](https://user-images.githubusercontent.com/21138866/52306899-761f2b00-2999-11e9-9029-9b15eb46e881.png)
But it i create it with `{'title': 'Minute', 'label': 'Minute', '@type': 'LevelProperty',..` the title will be 'Minute'

![screenshot from 2019-02-05 22-38-32](https://user-images.githubusercontent.com/21138866/52306090-25a6ce00-2997-11e9-863b-e574ccf7562e.png)

**Comment by mrstegeman** [comment]
@tomasy Is this with the official Raspberry Pi image, or a gateway you built yourself?

**Comment by tomasy** [comment]
@mrstegeman You are right. My `gateway-addon-python` was not updated. I close this
