### ISSUE TITLE
Rules race condition

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1620]
I have two rules defined to use a smart button to toggle some lights on and off.

They basically say "if the light is on, turn it off" and "if the light is off, turn it on".

![screen shot 2019-02-05 at 12 39 38](https://user-images.githubusercontent.com/552417/52273912-201f9880-2943-11e9-9a4d-e5b6e6d84da7.png)
![screen shot 2019-02-05 at 12 39 26](https://user-images.githubusercontent.com/552417/52273916-21e95c00-2943-11e9-9a68-ef711acf3468.png)

The light being used in the conditional is an IKEA colour bulb.

When I press the button, half the time it works as expected but half the time the rules interact with each other and the lights with will turn off then immediately back on, or on then immediately back off. I have to keep pressing the button until it does what I intended.

I would guess that there's a race condition going on where the two rules are interacting with each other. By the time the second rule is evaluated, the output of the first rule has already taken effect, which changes the result of the conditional and they get stuck in a loop.

@hobinjk Can you guess what is causing this and whether we can make it behave a bit more sanely?

**Comment by benfrancis** [comment]
Could be related to #1619

**Comment by benfrancis** [comment]
Also note "undefined" in the human readable sentence at the top.

**Comment by hobinjk** [comment]
This is unrelated to #1619 as far as I can tell, but using the debugging I was doing for that I determined the issue here to be that the way I translated events to the rules engine will cause both rules to be firing for half a second

**Comment by hobinjk** [comment]
Upon rereading, #1619 is probably the same thing as this unless zigbee property sets take longer than 500ms. I thought that there were different buttons for on/off in #1619
