### ISSUE TITLE
Router First Time Setup

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1622]
As a user I want to configure my gateway as a router when I first set it up, so I can use it as the main router for my home rather than connecting to another wireless network.

**Comment by benfrancis** [comment]
Here my initial ideas for router first time setup.

![router_first_time_setup](https://user-images.githubusercontent.com/552417/52438491-498e1f00-2b11-11e9-9b1e-8051734129a1.png)

I'm trying to use terms non-technical users will understand rather than "WiFi Access Point" vs. "Wi-Fi router" vs. "Wi-Fi client". The user is presented with two options:

1. Connect to an existing Wi-Fi network - continues with the usual first time setup
2. Create new Wi-Fi network - prompts for an SSID and password for the access point

By default, the access point option will have DHCP turned on, but it can be turned off in network settings (see #423).

To be honest, in a final router product I'm not sure any of this is actually necessary. Each router could be pre-configured with a unique SSID and password which is printed on a card in the box. The user would then just connect with those credentials and do the rest of the setup from there.

But for now we're in a bit of an awkward in-between stage where we need to support these two configurations (smart home hub vs. smart home router).

What do you think?

**Comment by dhylands** [comment]
Shouldn't we be able to automate the "Connect to gateway.local" by using captive portal?

**Comment by dhylands** [comment]
I was surprised to find out that the turris ships with WiFi disable by default. See https://github.com/mozilla-iot/wiki/wiki/Setting-up-the-Turris-Omnia-Router for the current steps to setup the turris.

**Comment by kgiori** [comment]
The proposed images look nice.. Just a few suggested tweaks to the setup experience.
UX steps:
1. user connects to SSID "Mozilla IoT Gateway 84c721" (append last 6 digits of MAC addr to SSID)
2. captive portal shows UI option "existing" or "new" (your page 1)
3a. if they choose existing, show scan of existing APs and follow current setup to become wi-fi client
3b. if they choose new, show SSID and password page (your page 2), but show it already filled in with current settings (filled in SSID but blank password) -- let user edit it and save
4a. ideally, the router would test the Wi-Fi AP connection and if successful, redirect the browser to its new IP address on the local LAN. if not successful, revert to Wi-Fi scan page so user can try again
4b. assuming user enters a password and optionally changes SSID, warn user to reconnect to new SSID/pass after a few seconds. 
5a. assuming user browser was redirected to gateway's IP address, and knowing wi-fi setup is complete, show subdomain page
5b. redo captive portal redirect when they connect to new ssid/pass, and because wi-fi setup is complete, show subdomain page 
6. continue setup...

**Comment by benfrancis** [comment]
@dhylands wrote:
> Shouldn't we be able to automate the "Connect to gateway.local" by using captive portal?

That's a good idea, although it wouldn't work on Android. Maybe in this case we could use captive portal with the gateway's IP address instead?

@kgiori wrote:
> The proposed images look nice.. Just a few suggested tweaks to the setup experience.
UX steps:
> 
>     1. user connects to SSID "Mozilla IoT Gateway 84c721" (append last 6 digits of MAC addr to SSID)
> 
>     2. captive portal shows UI option "existing" or "new" (your page 1)
>        3a. if they choose existing, show scan of existing APs and follow current setup to become wi-fi client
>        3b. if they choose new, show SSID and password page (your page 2), but show it already filled in with current settings (filled in SSID but blank password) -- let user edit it and save
>        4a. ideally, the router would test the Wi-Fi AP connection and if successful, redirect the browser to its new IP address on the local LAN. if not successful, revert to Wi-Fi scan page so user can try again
>        4b. assuming user enters a password and optionally changes SSID, warn user to reconnect to new SSID/pass after a few seconds.
>        5a. assuming user browser was redirected to gateway's IP address, and knowing wi-fi setup is complete, show subdomain page
>        5b. redo captive portal redirect when they connect to new ssid/pass, and because wi-fi setup is complete, show subdomain page
> 
>     3. continue setup...

I agree with all of this, I'll try to make sure this is covered in the spec.

**Comment by benfrancis** [comment]
> > Shouldn't we be able to automate the "Connect to gateway.local" by using captive portal?

> That's a good idea, although it wouldn't work on Android. Maybe in this case we could use captive portal with the gateway's IP address instead?

I've realised that at some point we need the user to exit the captive portal window (which is often a special type of window) and load the web interface in their browser.

Can captive portal open a new browser window, or should we ask them to navigate to gateway.local manually at this stage instead?

**Comment by dhylands** [comment]
It seems like most hotels redirect you to their hotel page after you get through the captive portal, so it seems like it should be possible. I think that they screw it up sometimes when you ask for https and they try to serve up http (or something like that) but otherwise it seems doable.

**Comment by benfrancis** [comment]
See [slides 3-10](https://docs.google.com/presentation/d/1rMeg6hep8JQflqwbiNIbhSoK9StCeVZ2npphmQHKda4/edit#slide=id.g221d7d7c9f_0_0) for the WiFi first time setup UX specification.

**Comment by benfrancis** [comment]
OK, after further team discussions I've re-designed the Wi-Fi first time setup to have a separate UI for Raspbian (acts as a client) and OpenWrt (acts as a router) builds. This greatly simplifies the first time setup flow, see the UX spec [here](https://docs.google.com/presentation/d/1rMeg6hep8JQflqwbiNIbhSoK9StCeVZ2npphmQHKda4/edit?usp=sharing).
