### ISSUE TITLE
OpenWrt Build System

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1623]
As a user I want to build an OpenWrt image of the gateway so that I can flash it onto router hardware.

(This will need breaking down into smaller tasks).

**Comment by jernst** [comment]
It would be nice if this was reusable, as much as possible, for other distros, such as UBOS, then everybody's maintenance costs go down and the likelihood of timely releases goes up. Our current work in progress is here: https://github.com/uboslinux/ubos-mozilla-iot-gateway

**Comment by tonyho** [comment]
This would be useful. And Can the gateway package run on performance limitation ARM linux OpenWRT router? Like a ARM9 300MHz SoC based router, or Cortex-A7 800M Hz? 
Or the minimal SoC performance requirement ?

**Comment by dhylands** [comment]
I'm not sure without testing. Most of the gateway isn't CPU intensive. The big thing is that its running node and needs lots of RAM (512 MB) and flash (1 Gb). Most performance limited CPUs are also memory limited.
