### ISSUE TITLE
Lock Capability UI

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1630]
As a user I want to lock/unlock and see the status of my smart locks

**Comment by benfrancis** [comment]
See also: https://github.com/mozilla-iot/schemas/issues/11

**Comment by benfrancis** [comment]
Fun insight into the design process, here are my initial ideas for the Lock UI. I'm not really happy with any of these yet but number 7 is probably my favourite from a simplicity point of view, which is unfortunate because it's based on having two separate "Lock" and "Unlock" actions rather than a single TargetLocked property (I'm still not 100% sure we made the right call on the [schema](https://github.com/mozilla-iot/schemas/issues/11)).

![lock_ui](https://user-images.githubusercontent.com/552417/66589659-ea444b00-eb86-11e9-9542-5993af25840a.png)

No. 8 could work, but those tiny buttons are a bit fiddly. I will keep designing, but feedback welcome.

**Comment by mrstegeman** [comment]
Thoughts:
* I like the padlock icons the best.
* A generic switch (as in 1 and 2) is not very clear about which is locked and which is unlocked.
* I like having 2 buttons. I think it would probably be easiest right now from an engineering perspective to do both buttons in one bubble.
* With the 2 buttons, I wonder if we should disable the lock button if it’s already locked, and vice versa?

**Comment by benfrancis** [comment]
Thanks for the feedback.

Updated mockups:
![lock_ui2](https://user-images.githubusercontent.com/552417/66763207-5c76a180-ee9f-11e9-96a4-76d9b90932e9.png)

 9. Increases the touch target size of the two buttons, but more consistent with the presentation style of properties rather than actions (the highlighted button in the second screen shows the active state of the button)
10. Breaking the mould a bit with a slightly more skeuomorphic representation of a [key fob](https://www.google.com/search?q=car+key+fob&client=ubuntu&hs=7AQ&channel=fs&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjXsNrUiJzlAhWluXEKHbptBgEQ_AUIESgB&biw=1280&bih=922), with lock and unlock buttons that have more obvious visual affordances that you can click them
11. Two separate buttons representing actions rather than a single property

To be honest I think that 11 is probably the best, but to maintain consistency that would require changing the capability schema to use actions rather than a `TargetLockedProperty`.

If @mrstegeman and @dhylands still think we shouldn't do that then we could go with 9 or 10.

What do you think?

P.S. Regarding physically locking/unlocking triggering a change in `TargetLockedProperty`, I'd say that might depend on whether the user action physically unlocks the lock (in which case they're changing `LockedProperty` directly) or presses a physical button which digitally requests the lock to physically unlock (in which case it's more like setting the `TargetLockedProperty` in the web UI.

**Comment by mrstegeman** [comment]
The more I think about the UI and the weird interplay between TargetLockedProperty and LockedProperty, the more it makes sense to me to have lock/unlock actions. My only real hesitation is if there end up being more target states at some point, although I can't immediately think of any. A lock is inherently a binary object, is it not?

So, if we go the actions route, I like 11. If we stick with properties, I like 9 (I actually _really_ like this UI).

**Comment by benfrancis** [comment]
> The more I think about the UI and the weird interplay between TargetLockedProperty and LockedProperty, the more it makes sense to me to have lock/unlock actions.

I agree, I think we should probably make them actions.

>  My only real hesitation is if there end up being more target states at some point, although I can't immediately think of any. A lock is inherently a binary object, is it not?

I think it probably is, yes. Sometimes on a car you press the lock button again to arm the security system - but that's arguably separate to the lock state. You could have a door with both a lock and a deadbolt (like in a hotel room), but they are arguably two separate lock states and only one of them is likely to be a smart lock.

**Comment by mrstegeman** [comment]
> Sometimes on a car you press the lock button again to arm the security system - but that's arguably separate to the lock state.

Agreed, this would be a separate property.

> You could have a door with both a lock and a deadbolt (like in a hotel room), but they are arguably two separate lock states and only one of them is likely to be a smart lock.

Yes, this would be two separate locks. In the physical world, I have to take 2 actions to lock both locks (which are physically separate, and could have different keys), so the electronic representation should probably match that.

**Comment by benfrancis** [comment]
I think a clue that we should be using actions here rather than properties is that we've ended up using verbs in the UI rather adjectives.

I've filed https://github.com/mozilla-iot/schemas/issues/60 to switch to actions, so file any objections there before I get around to updating it tomorrow!

Otherwise, I think we should go with no. 11 as the final UI design.

**Comment by mrstegeman** [comment]
@benfrancis Icons, please.
* Thing icon
* Padlock open (blue + white)
* Padlock closed (blue + white)
* Padlock jammed

**Comment by tim-hellhake** [comment]
> The more I think about the UI and the weird interplay between TargetLockedProperty and LockedProperty, the more it makes sense to me to have lock/unlock actions

It becomes even weirder when the target state is `locked`, but the current state is `unlocked` because the user unlocked it manually.
You would have to change the target state to `unlocked` and then back to `locked` to trigger a change.

**Comment by mrstegeman** [comment]
@tim-hellhake That's exactly the state I was thinking of.

**Comment by benfrancis** [comment]
Icons:
* [Thing icon](https://drive.google.com/file/d/1lXisAkJH-o7Qk3tXfKF6O-KT2W_8g_ea/view?usp=sharing)
* Padlock open ([blue](https://drive.google.com/file/d/1HCyJaj-zhemYk8Myxq9AZrVBQ80Z6f-m/view?usp=sharing) + [white](https://drive.google.com/file/d/1RbthDJ6CXNO8zoU4-I77g1rvwf2sK97N/view?usp=sharing))
* Padlock closed ([blue](https://drive.google.com/file/d/1x-bIMrwIiJNTMQGWqnZNbZoC2YCmqvyJ/view?usp=sharing) + [white](https://drive.google.com/file/d/1GUxuIuc03_12y3BGKG9OAJ32_FwI_08O/view?usp=sharing))
* [Padlock jammed](https://drive.google.com/file/d/1lXisAkJH-o7Qk3tXfKF6O-KT2W_8g_ea/view?usp=sharing)

**Comment by benfrancis** [comment]
Note: In the mockups the small padlock icons are about 24px high and the large ones are about 48px high, but the SVGs have some padding in them to keep everything centered (overall height 32px, padlock 24px), so you may need to fiddle around with them a bit to make everything look right.

**Comment by flatsiedatsie** [comment]
For now I've decided not to implement this functionality in the MySensors add-on. For two reasons

1. Loss of functionality when compared to the existing situation.
The change means the central bubble can no longer be used as a quick way to lock or unlock the door. Users will now have to go into the octopus, click the lock/unlock button, and then exit the octopus.

2. Increase in complexity.
This is about both in the code required to support it (including in the Voco voice add-on), as well as the number of extra properties it results in visually:

![lock_working](https://user-images.githubusercontent.com/805405/68589515-f8d29a80-0483-11ea-9fe8-ead6bbbdbb80.png)
_If I were to add the actions for the second lock, it would add yet two more bubbles._

I could solve this on my end, for example by splitting/cloning devices with two electric locks into two separate things. But this would create other complications because of all the duplicated properties, create a lot of work, and would in the end not really result in significantly better usability.
