### ISSUE TITLE
Need to figure out how retrieve log files under openwrt

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#1635]
Currently, under OpenWRT, the log files are sent to logd and show up in /var/log/messages. This means that they aren't accessible via Settings->Developer->View Logs.

**Comment by mrstegeman** [comment]
I _believe_ this should start working properly with 0.7. The problem is that the OpenWrt package just calls `npm start`, rather than using the `run-app.sh` script. With 0.6 and below, that script was responsible for creating the log file. With 0.7+, `winston` does it for us.

**Comment by dhylands** [comment]
Yep - I have a raspberry pi openwrt image with 0.7 on it and I can see a log file in the /.mozilla-iot/log directory.

**Comment by mrstegeman** [comment]
Perfect. Gonna close this.
