### ISSUE TITLE
[OpenWRT] Port 8080 should redirect to port 4443

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#1636]
Currently, when you browse to http://ip-address/ on the Turris Omnia it shows a link to get to the gateway. This is basically a link to http://ip-address:8080

The gateway redirects to https://ip-address/ which is the same page. It should really redirect to https://ip-address:4443

**Comment by benfrancis** [comment]
Question: If someone is intentionally accessing the gateway locally via its local IP or .local domain, is there actually much benefit in redirecting them from port 80/8080 to 443/4443 and showing the certificate warning, rather than just using plain HTTP?

**Comment by dhylands** [comment]
The issue isn't the certificate warning, it's that http://ip-address:80 is currently the main page for the turris omnia router. When the gateway software is installed, it looks like this:
![turris-home](https://user-images.githubusercontent.com/127500/52433712-87178b80-2ac2-11e9-8f92-c7a33c918bf4.png)

So when you click on the gateway if it redirects back to port 80 then you wind up back on the home screen above.

**Comment by benfrancis** [comment]
Yes, sorry I understood what you mean I was just asking a more general related question about where we should actually redirect to.

But this is obviously a bug.

**Comment by dhylands** [comment]
> Question: If someone is intentionally accessing the gateway locally via its local IP or .local domain, is there actually much benefit in redirecting them from port 80/8080 to 443/4443 and showing the certificate warning, rather than just using plain HTTP?

Presumably the reason the use is connecting to to the local address is because the internet is down or the tunnel isn't otherwise working. In that light, it probably makes sense to stay on port 8080.

Perhaps http://gateway.local:8080 should not redirect?
And https://gateway.local:8080 should redirect to http://gateway.local:8080

Although, logically, it only makes sense to use https with the tunnel.

Once the tunnel is registered, we should probably rewrite the file that causes the gateway to show up in the photo about to use the tunnel URL.

**Comment by mrstegeman** [comment]
All we should need to do for this is set the `behindForwarding` config flag to `false`.
