### ISSUE TITLE
Wi-Fi scan fails if localhost name was changed (no longer gateway.local)

### ISSUE THREAD

**Issue by kgiori** [mozilla-iot/gateway#1645]
If a gateway was set up on one Wi-Fi network, given a subdomain, and the local host name was changed (no longer gateway.local but for example subdomain.local), then if you change to a new AP, and re-associate with "Mozilla IoT Gateway" to change the SSID that it is associated with, the "scan" of Wi-Fi access points fails. The screen will be blank and the only option is to "Skip" the Wi-Fi setup or gain access to the console to change wpa_supplicant.conf directly.

<img width="896" alt="screen shot 2019-02-12 at 10 39 22 am" src="https://user-images.githubusercontent.com/9487286/52660137-df300280-2eb3-11e9-80e7-34dbba1102d9.png">

**Comment by hobinjk** [comment]
I'm unable to reproduce following these steps:
1. Have happy gateway named gateway.local connected to wifi network
2. rename gateway by changing the contents of /etc/hostname to 'lateway'
3. Rename wifi network to get everything to disconnect
4. Reboot lateway, verify that it has hostname lateway.local on the console
5. lateway advertises Mozilla IoT Gateway network
6. Connect to Mozilla IoT Gateway network
7. Captive portal popup lists all expected networks (*isn't blank*)

Could you give me the output of these commands on your renamed gateway the next time you get a blank screen?
`wpa_cli -iwlan0 status`
`sudo ~/mozilla-iot/gateway/src/wifi-setup/platforms/scan.py`
