### ISSUE TITLE
Localisation (L10n)

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1647]
As a user I would like to use the gateway in my native language so that I can use it without knowing English.

**Comment by benfrancis** [comment]
See also: Issue on localizing the website https://github.com/mozilla-iot/mozilla-iot.github.io/issues/18

> Tools Suggestion: [Fluent](https://github.com/projectfluent/fluent.js) for your front-end library, and [Pontoon](https://pontoon.mozilla.org/) for your community translation tool.

**Comment by mrstegeman** [comment]
We'll need to extend this to add-ons as well, for property titles, configuration descriptions, etc.

**Comment by jaller94** [comment]
Is localization a consideration in the Web of Things API?
The things come with labels and descriptions, as do properties, events and actions.

Besides vendors of things providing these, it would be cool to have an open data collection of translations for languages that the vendors didn’t support. I imagine this similar to TypeScript where one can create a repository of type definitions for frameworks that do not ship type definitions themselves.

**Comment by benfrancis** [comment]
@jaller94 wrote:
> Is localization a consideration in the Web of Things API?

I've filed https://github.com/mozilla-iot/wot/issues/127 for this. My recommendation is to use HTTP Accept-Language headers.

**Comment by kgiori** [comment]
It would be nice to see some initial "scaffolding" implemented to support Fluent. With example Fluent framework added to the "Things" and "Rules" pages, that might be enough to enable the community to step in and help on remaining pages. Once we have even just a few of the structural elements in place, we can contact friends of Mozilla (language translators) who will likely be willing to help make this happen.

**Comment by wtigga** [comment]
Hi there. I would really love to contribute to WebThings i18n part. I have published three translations of Mozilla IoT-related articles in Russian  ([Gateway user guide](https://habr.com/ru/post/448654/), [Gateway - Getting Started](https://habr.com/ru/post/448652/), [Empowering User Privacy](https://habr.com/ru/post/452412/)), and I see people are very curious about the project, but the lack of language support is a bummer for the majority of users.

Please let the community know once we can start the translation process. Cheers.

**Comment by mrstegeman** [comment]
Resources:
* https://www.npmjs.com/package/fluent
* https://projectfluent.org/
* https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Internationalization

**Comment by mrstegeman** [comment]
This is doe, as of 0.10. At some point, add-ons will need localization as well, but that can be a separate issue.
