### ISSUE TITLE
The gateway should proxy images and videos of external web things

### ISSUE THREAD

**Issue by jaller94** [mozilla-iot/gateway#1664]
### Issue
With the current implementation, web things with an ImageProperty need to satisfy the following in order for the image to show up:
* not provide full URLs, not absolute or relative links, because the gateway will not prepend the web thing’s IP/ domain (described below)
* serve the image via HTTPS, because would complain about mixed content with other protocols like HTTP.
* serve with a permissive CORS setting, because browsers would refuse to load the image when it comes from a different source.

### Steps to reproduce
1. Write a webthing with a `Camera` capability and an ImageProperty with the following links:
```
[
    {
      rel: 'alternate',
      href: '/static/image.png',
      mediaType: 'image/jpeg',
    }
  ]
```
2. Connect it to your gateway.
3. Preview the image.

### Expected
The image from the web thing shows up.

### Actual
The image cannot be loaded, because the gateway does not change the URL and the client will think that the gateway hosts the image.

### Solution I would like to propose
The gateway should proxy the `alternate` links of ImageProperties (download it and serve it from their own domain).
This also affects VideoProperties.
While this might add additional load to the gateway’s system, it can be used for other useful "gateway"-y features like conversions to common or faster file formats, codecs  and resolution. Controllers could benefit from this, when it enables them to show pictures or videos they would usually not be able to display.
Converters could be addons and configured in the settings.

**Comment by mrstegeman** [comment]
This should already be possible in 0.7, with thing-url-adapter version 0.2.7. The proxying was done by the following commits:

https://github.com/mozilla-iot/thing-url-adapter/pull/65
https://github.com/mozilla-iot/thing-url-adapter/pull/66
https://github.com/mozilla-iot/gateway/pull/1592

I tested with: https://github.com/mrstegeman/photo-cycler-webthing

**Comment by jaller94** [comment]
Thanks for pointing me at this.
The add-on seems to be installed on my Gateway. I will need some more time to investigate what's going on with the URLs.

**Comment by mrstegeman** [comment]
@jaller94 I'm going to close this for now. If you continue seeing issues, please reopen so we can take a look.
