### ISSUE TITLE
Current IP Address

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1674]
As a user I would like to find out the current IP address of my gateway if it was automatically assigned.

- When connected as a DHCP client via  WiFi network
- When connected as a DHCP client via Ethernet
- Public IP when connected to the Internet via a WAN port

**Comment by dhylands** [comment]
Note that its possible to have 2 IP addresses, one for WiFi and one for ethernet and they may or may not be on the same network (this is true on the RPi). On the Turris you can have an IP address for the WAN side and one for the LAN side.

**Comment by benfrancis** [comment]
Yes, the three different types of IP address I listed are not mutually exclusive.
