### ISSUE TITLE
Allow wifi country to be set

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#1676]
Configuring the country (in the wpa_supplicant.conf file) causes different sets of channels to be enabled.

There was some discussion in this bug: https://github.com/mozilla-iot/gateway/issues/618

raspi-config includes the ability to configure the country. It uses:
```
cat /usr/share/zoneinfo/iso3166.tab | tail -n +26 | tr '\t' '/'
```
to get a list of countries.

And here's the routine they use for updating the country:
https://github.com/RPi-Distro/raspi-config/blob/9895c6cfc897339887a471b8ee891d606c3ed79b/raspi-config#L426-L456

**Comment by benfrancis** [comment]
This may be handled by #1113

**Comment by kgiori** [comment]
For commercial Wi-Fi router products, enabling the end-user to modify the country is not allowed. To pass regulatory body (FCC, ETSI, etc.) "certification" requirements the product vendors have to build and distribute regulatory-specific skus. There's no "one size fits all" router product, with respect to Wi-Fi frequencies and power level allowances.

**Comment by mrstegeman** [comment]
This is done now.
