### ISSUE TITLE
gateway doesn't show up door sensor icon

### ISSUE THREAD

**Issue by ramachandrann** [mozilla-iot/gateway#1679]
I'm very enthusiastic about wot.  i'm trying out the Current version:
0.7.0 of gateway.
i tried flashing my esp8266 to act as a door sensor with a magnetic
reed attached to PIN 2 and ground.

When I flash with the below code, it comes up as a 'Custom Thing' and
not 'Door Sensor' with a door icon on the gateway. This code works
well, when I go into detail view it shows the Open with a checkbox
kind of UI. I would like to see the Door Open and Close. Pls advise
where am I going wrong. 
Thanks
Gopal

```cpp
#include <Thing.h>
#include <WebThingAdapter.h>

const char* ssid = "xxxx";
const char* password = "xxxx";

#define MAGNETIC_REED_PIN 2 //pin gpio 12 in sensor

#ifdef ESP32
ESP32WebThingAdapter adapter("esp32");
#endif
#ifdef ESP8266
ESP8266WebThingAdapter adapter("esp8266");
#endif

ThingDevice door("door", "Garage Door", "DoorSensor");
ThingProperty doorOpen("open", "Whether the door is open", BOOLEAN);
ThingPropertyValue openValue;

void setup(void){
  pinMode(MAGNETIC_REED_PIN, INPUT);
  Serial.begin(115200);
  WiFi.mode(WIFI_STA);
  WiFi.begin(ssid, password);
  Serial.println("");

  // Wait for connection
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  Serial.println("");
  Serial.print("Connected to ");
  Serial.println(ssid);
  Serial.print("IP address: ");
  Serial.println(WiFi.localIP());

  door.addProperty(&doorOpen);
  adapter.addDevice(&door);
  adapter.begin();
  Serial.println("HTTP server started");
}

void loop(void){
  adapter.update();

  if (digitalRead(MAGNETIC_REED_PIN)==HIGH) {
    openValue.boolean = true;
    Serial.println("Your Door is Open");
  }
  else {
    openValue.boolean = false;
    Serial.println("Your Door is Closed");
  }
  doorOpen.setValue(openValue);

}
```

**Comment by mrstegeman** [comment]
I think you probably need to change:

```cpp
ThingDevice door("door", "Garage Door", "DoorSensor");
ThingProperty doorOpen("open", "Whether the door is open", BOOLEAN);
```

to:

```cpp
const char* deviceTypes[] = {"DoorSensor", nullptr};
ThingDevice door("door", "Garage Door", deviceTypes);
ThingProperty doorOpen("open", "Whether the door is open", BOOLEAN, "OpenProperty");
```

**Comment by ramachandrann** [comment]
> I think you probably need to change:
> 
> ```c++
> ThingDevice door("door", "Garage Door", "DoorSensor");
> ThingProperty doorOpen("open", "Whether the door is open", BOOLEAN);
> ```
> 
> to:
> 
> ```c++
> const char* deviceTypes[] = {"DoorSensor", nullptr};
> ThingDevice door("door", "Garage Door", deviceTypes);
> ThingProperty doorOpen("open", "Whether the door is open", BOOLEAN, "OpenProperty");
> ```

Tried it out. It didn't work :(
Thanks for the prompt response though. Unfortunately ThingDevice/ThingProperty doesn't seem to support the signature. I'm using the master.
https://github.com/mozilla-iot/webthing-arduino/blob/master/Thing.h

If its a quick fix, kindly point me to some sample sources and I will try modifying the local arduino libraries and test it out :) and can do a pull request. Does it need a lot of understanding of the architecture if the fix is not small? if yes, pls point me to any tech docs .
