### ISSUE TITLE
Add voice commands for new capabilities

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/gateway#1703]
(also requires logging)

- How much energy are my devices using?
- How much energy did my devices use over the past month?

For motion, door, and leak:
- Is there motion detected? Is thing detecting motion?
- When's the last time there was motion detected?
- How long has motion been detected? (how long has this been leaking?)

- What temperature is it?
- How cold did it get yesterday?
- How hot did it get last week?
- How much is my current temperature data proving the existence of climate change?

Fancy things that would require device/assistant-specific support so probably not part of this:
- Show me what the security camera is seeing

**Comment by flatsiedatsie** [comment]
A small question: (how) will this also work for things that are added via add-ons? Is there anything they should do to be 'targetable'? For example, I could imagine that the thing and property names should be well known English words?

Could I, for example, ask: `Is the fireplace on?` if a thing is named 'fireplace' and has an on/off capability/property? Could I ask "what moisture level does the livingroom climate thing indicate", if there is a thing named "livingroom climate" with a property named "humidity"?

**Comment by hobinjk** [comment]
The first one would work since it uses the name and a capability. The second one wouldn't since there's no "HumidityProperty" capability and the "humidty" property isn't being referred to by name. On the other hand, "What is the humidity of the living room climate thing?" is intended to work.

**Comment by flatsiedatsie** [comment]
@hobinjk Thanks! Great to hear.
