### ISSUE TITLE
rule understands OFF but calls ON undefined

### ISSUE THREAD

**Issue by twobraids** [mozilla-iot/gateway#1710]
When trying to debug why a light wasn't coming on at the right time, I noted the sentence at the top of the rule didn't understand the `on` property, but it did understand `off`.  See the attachments:

![Screenshot_20190316_094357](https://user-images.githubusercontent.com/581227/54478600-266e2380-47d1-11e9-8ed6-e46616415d43.png)

![Screenshot_20190316_095442](https://user-images.githubusercontent.com/581227/54478639-a72d1f80-47d1-11e9-8ae6-1db879a04360.png)

The bulb is a IKEA warm white.  It works normally when turning on and off on the "Things" page.

**Comment by mrstegeman** [comment]
@hobinjk This was fixed post-release, right?

**Comment by hobinjk** [comment]
Yes, this was fixed in c58ce6e2e55e33d71c1c344e13da83c2751092a7
