### ISSUE TITLE
Forgot subdomain

### ISSUE THREAD

**Issue by decode-dev** [mozilla-iot/gateway#1711]
Can we have a link under the login page with "Forgot Subdomain". As we are only mapping the email -> sub-domain it would be easier and also helps to know how many sub-domains a person has in case they forget

**Comment by benfrancis** [comment]
Can you explain in a bit more depth the problem you are trying to solve? Is it if a user has registered a subdomain against their email address but have forgotten what the subdomain was?

The subdomains are registered with a [registration server](https://github.com/mozilla-iot/registration_server) in the cloud which provides the secure tunnelling service. We are considering creating a web interface which you can log into using your email address (possibly attached to a Firefox Account) where you can manage your registered subdomains (e.g. list them, change them, un-register them).

Would that solve the problem you've identified?

**Comment by raidnet-ms** [comment]
Hi Ben,
Actually i got the same problem. I registered a subdomain on first attempt but now i can't remember it.
How to connect my gateway to the same subdomain again?

thanks

**Comment by mrstegeman** [comment]
Browse to https://gateway.local or https://&lt;ip-address-of-gateway&gt; on your local network. You'll have to accept the certificate error, but then you can log in and navigate to _Settings -> Domain_ to see your subdomain.

**Comment by raidnet-ms** [comment]
I mean the subdomain for remote access registerd on first installation wizard

**Comment by mrstegeman** [comment]
In the "Remote Access" box on that settings page will be your full URL, like `https://raidnet-ms.mozilla-iot.org`.

**Comment by raidnet-ms** [comment]
For some strange reason i get  "not-set". I'm sure I registered it on some previous test (v 0.3 of the gateway).

**Comment by mrstegeman** [comment]
Currently, the only way to get your domain back is to start fresh with a new install and reclaim it during the setup process.

**Comment by raidnet-ms** [comment]
I see, but i won't be able to use the same domain i set previously, right?

**Comment by mrstegeman** [comment]
Yes, you will. You must enter the same domain/email address combo you originally used. After doing so, the setup process will offer you the option of reclaiming your domain.

**Comment by raidnet-ms** [comment]
Great thank you. Will be possible to get the list of domain associated with my email in future?

**Comment by mrstegeman** [comment]
Yes, hopefully. If you need to know before we implement that feature, send an email to iot@mozilla.com and we can help you out.

**Comment by mrstegeman** [comment]
See #1699
