### ISSUE TITLE
Plugins should have online documentation available

### ISSUE THREAD

**Issue by a2sheppy** [mozilla-iot/gateway#1716]
Currently, there is a detachment between the addons and the documentation (if there even is any for them). This should be addressed by having option URLs in the manifest for an addon that let you specify the URL of documentation for installing/configuring the add-on (things you have to do just to get it to work) and thing configuration using the add-on. This would help a lot with the ease of use during the initial setup process and during ongoing adjustments to configuration of things.

**Comment by mrstegeman** [comment]
We actually already support this, but it's not super intuitive. When adding new add-ons, or after adding one, you can click on the name of the author and it will take you to the homepage of that add-on. Typically, that's the GitHub repo's README or something.

![Screenshot_2019-03-18 Things Gateway](https://user-images.githubusercontent.com/457381/54573896-c2f01b80-49b3-11e9-9bc1-7856824f9f13.png)
