### ISSUE TITLE
Server Configuration

### ISSUE THREAD

**Issue by eanmikale** [mozilla-iot/gateway#1722]
We have a question that may be simple. When I build the gateway at home, and take the build to the office, we find that the build does not function. Do we have to build gateway at the location, and connected to the final network of installation for it to work? Thank you for your time? 

Regards, 

EM

**Comment by mrstegeman** [comment]
1. What do you mean by "build the gateway"? Are you just referring to flashing the SD card with our Raspbian image?
2. What doesn't work, exactly?

**Comment by dhylands** [comment]
And when you say "take the build to the office" what exactly are you taking?

**Comment by eanmikale** [comment]
By building the gateway, we mean compiling the source code. We have had issues taking successfully connected and operational gateways from my home office, and bringing them to the lab to hook up to the Internet at the office. Must be z-wave and gateway packages be compiled at the final destination of installation? Or can I compile from source code at home, and bring into the office and change wpa_suppicant file or via the wifi tab on the Raspbian desktop to configure to our network? I guess mobility of the IoT Gateway upon successful sourcecode compilation and configuration is the question. Thanks. 

Ean Mikale, J.D.

Chief Innovation Officer

Infinite 8 Institute, L3C

ean@infinite8institute.com

www.infinite8institute.com





U.S. Federal Contractor




---- On Wed, 27 Mar 2019 11:25:15 -0500 notifications@github.com wrote ----


What do you mean by "build the gateway"? Are you just referring to flashing the SD card with our Raspbian image?
What doesn't work, exactly?

**Comment by dhylands** [comment]
So you're just bringing the sdcard from Raspberry Pi created at home and botting it on the Raspbery Pi in the office? Or are you transferring the entire Raspberry Pi? Are you also transferring the zigbee/zwave dongles and the devices?

Are both Raspberry Pi's the exact same?

The zwave and zigbee adapters don't need to be recompiled, however, the devices are paired with a particular dongle.

So once you've paired devices with a dongle, you really need to move the devices with the dongle together. The IDs for the devices are stored in the databas on the sdcard, so if you move the sdcard to a device with a different dongle then there will alo be issues.

**Comment by eanmikale** [comment]
You are correct. I am taking the same Pi and same z-wave dongle, removing it from my home office and taking it to our company lab at a different location, to connect to a new network. We wanted to know if we need to recompile the z-wave and/or the gateway packages at each new location of installation, noting that the Pi and dongle remain the same, or if they should work at a new site as along as the Pi, IoT device, and dongle are the same? I forgot to mention, we have different IoT connected devices at home, as opposed to at the office. I am not taking a z-wave standard LED bulb from home and placing that same bulb in a socket at the office. So if the IoT connected devices must also be the same at each location of installation , then that would make sense. Thank you for your time.

Warm Regards,

Ean Mikale, J.D.

Chief Innovation Officer

Infinite 8 Institute, L3C

ean@infinite8institute.com

www.infinite8institute.com





U.S. Federal Contractor




---- On Thu, 28 Mar 2019 12:52:10 -0500 notifications@github.com wrote ----



So you're just bringing the sdcard from Raspberry Pi created at home and botting it on the Raspbery Pi in the office? Or are you transferring the entire Raspberry Pi? Are you also transferring the zigbee/zwave dongles and the devices?

Are both Raspberry Pi's the exact same?

The zwave and zigbee adapters don't need to be recompiled, however, the devices are paired with a particular dongle.

So once you've paired devices with a dongle, you really need to move the devices with the dongle together. The IDs for the devices are stored in the databas on the sdcard, so if you move the sdcard to a device with a different dongle then there will alo be issues.

**Comment by dhylands** [comment]
That should till work. But when at home, you'll only be able to talk to the devices that you paired while at home and while in the office you'll only be able to talk to the devices which were paired at the office.

If left at one location for an extended period time, the dongle will typically mark the missing devices as "Failed".

You definitely don't need to recompile anyting.

If you're using a wireless WiFi connection from the Pi, then you'll need to manually edit the /etc/wpa_supplicant/wpa_supplicant.conf file to add the credentials for whichever site wasn't the one you entered the SSID and password at.

We pretty much do what you're doing when we go to a trade show.

So now it boils down to what do you mean by "does not function".

**Comment by eanmikale** [comment]
Dave,
You answered my questions spot on. We do not move the gateway often, and so it is likely that the missing nodes dropped of as you suggested, and need to be paired again after prolonged stints without connectivity. In other instances we may have paired a device, but left it unconnected for a long period, and unsuccessfully attempted to reconnect, without reproducing the initial pairing steps. I feel comfortable we can close this one out. Thank you for your time. 

Regards, 




Ean Mikale, J.D.

Chief Innovation Officer

Infinite 8 Institute, L3C

mailto:ean@infinite8institute.com

http://www.infinite8institute.com





U.S. Federal Contractor









---- On Thu, 28 Mar 2019 16:06:43 -0500 Dave Hylands <mailto:notifications@github.com> wrote ----



That should till work. But when at home, you'll only be able to talk to the devices that you paired while at home and while in the office you'll only be able to talk to the devices which were paired at the office.

If left at one location for an extended period time, the dongle will typically mark the missing devices as "Failed".

You definitely don't need to recompile anyting.

If you're using a wireless WiFi connection from the Pi, then you'll need to manually edit the /etc/wpa_supplicant/wpa_supplicant.conf file to add the credentials for whichever site wasn't the one you entered the SSID and password at.

We pretty much do what you're doing when we go to a trade show.

So now it boils down to what do you mean by "does not function".
