### ISSUE TITLE
Notifier Add-ons

### ISSUE THREAD

**Issue by mrstegeman** [mozilla-iot/gateway#1758]
As a developer, I want to write an add-on which can be used to notify a user of something via a rule.

Right now, we have several add-ons that represent notifiers as things, such as:
* activitypub-adapter
* email-sender-adapter
* twilio-adapter

While this is functional, it seems a bit clunky, since these are not really _things_.

Instead, I propose a new type of add-on that presents a simple "Notifier", rather than an "Adapter". The Notifier would probably just need one primary method, `notify`, which would accept a string.

Add-ons would be able to create multiple notifiers, as well. For instance, a user might want to configure a "Slack Notifier Add-on" with multiple channels. Each notifier instance could then be used for different rules.

The existing add-on configuration UI could still be used.

**Comment by kgiori** [comment]
Would the user then be offered a list of configurable notification "channels" in the configuration page of this over-arching notifier add-on? And then the rules engine "notification" block would send the alert to all configured channels? I'm trying to imagine the user experience.

**Comment by benfrancis** [comment]
I imagine it would be a type of add-on, there would be multiple Notifier add-ons which expose a particular kind of notification mechanism (e.g. An SMS add-on or an email add-on). It would make sense for those notification mechanisms to then be used as outputs in the rules engine, yes.

**Comment by mrstegeman** [comment]
The initial back-end for this is done now. We'll need some UI design for the rules engine.

**Comment by mrstegeman** [comment]
This issue is essentially done. Follow up work is in #1973 and #1974.
