### ISSUE TITLE
Intermittent Test Failure: Test suite failed to run

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/gateway#1759]
This ends around 90% of test runs with no actual output from the failing test.

Current investigation has been trying to get output from the test but nothing is working so far. This includes approaches from `beforeAll(console.log)` to putting console.log at the beginning of every included file.

The next area for looking at this is the internals of jest itself since it should be at least including the test file at some point. This may turn into poking random parts of our test setup until something works.

So far the only approach that has reduced the intermittent test failures is to want the test run to fail for debugging purposes which is not scalable.

**Comment by mrstegeman** [comment]
Some of my attempts (check out the various force-pushes): https://github.com/mozilla-iot/gateway/pull/1696

**Comment by mrstegeman** [comment]
@hobinjk Fixed now, right?

**Comment by hobinjk** [comment]
Definitely maybe

**Comment by mrstegeman** [comment]
Gonna call it good. Let's re-open if things regress again.
