### ISSUE TITLE
Add wordmark to Wi-Fi first time setup

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1771]
![connect_wifi](https://user-images.githubusercontent.com/552417/55889008-47dfe680-5ba8-11e9-839f-89cc82d3738c.png)

I suggest adding the WebThings Gateway wordmark to the bottom left of the Wi-Fi first time setup screen, as this is the first screen that users will see. (It's already shown on the later parts of first time setup). Unless there is a graphical reason this doesn't work well?

**Comment by mrstegeman** [comment]
Hmmm... That's weird. It's supposed to be there.

https://github.com/mozilla-iot/gateway/blob/master/src/views/wifi-setup.handlebars#L299
