### ISSUE TITLE
"Undefined" message after 0.8 -> 0.7 -> 0.8 upgrade path

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1793]
STR:
* Upgrade from 0.7 to 0.8
* Load gateway web interface

Expected:
* Everything looks normal

Actual:
* "Undefined" message appears as a toast and can't be dismissed
* Source map errors in the console

This can be fixed with a hard reload, but it would be great to get the bottom of the cause because every user will probably see this and not everyone will be able to figure out how to fix it.

**Comment by hobinjk** [comment]
I haven't been able to reproduce this yet but I believe that the most likely cause is https://github.com/mozilla-iot/gateway/blob/v0.7.0/static/js/app.js#L128 which means that I just need to add a no-op websocket listener to the Logs controller

**Comment by hobinjk** [comment]
or rather get it to be a no-op if it's 0.7 listening instead of 0.8

**Comment by hobinjk** [comment]
Thinking this through, this behavior will only happen if someone enables logging, has log data, then downgrades to 0.7 so it won't actually happen to normal users. Any objection to closing this?

**Comment by hobinjk** [comment]
After #1794 this will only happen if someone does 0.8 -> 0.7 -> 0.8 and will not happen during the normal 0.7 -> 0.8 so I'm closing this for now
