### ISSUE TITLE
Suggested improvement for first time setup (OpenWrt)

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#1798]
Currently, after configuring the Wifi, you need to browse to gateway.local in order to enter the domain/email.

It occurred to me that we could do this using captive portal, and then the user doesn't need to browse anywhere.

The only wrinkle in this suggestion is that doing domain reclamation doesn't work since you need to change wireless networks to get to your email and get the token, and when you come back you have to generate another reclamation token.

With some changes I think that this would work well.

I'd also like to see the reclamation process just have a button to click on and then have the reclamation happen automagically without having to copy/paste the code.

**Comment by kgiori** [comment]
I think this would be hugely valuable to the first time setup process. Getting to gateway.local after the Wi-Fi setup can still be a big problem for some people. I think keeping the user in the same captive portal process would be very helpful to them.

**Comment by benfrancis** [comment]
I think this would be a great improvement for the router first time setup, maybe not so much the client version.

For the router it could use captive portal on 192.168.2.1, Internet could still be accessible via Ethernet (WAN) for domain registration and the user need never use mDNS at all (though we probably want that as a fallback for devices which don't support captive portal).

**Comment by benfrancis** [comment]
When I set up an OpenWrt build I noticed that the first time I connected to the Wi-Fi access point Captive Portal didn't activate. When I disconnected and re-connected it worked the second time. I wonder whether at the same time as looking at this, it might be possible to look at whether we can make that more reliable?

**Comment by dhylands** [comment]
Not sure without knowing why it didn't work.

**Comment by dhylands** [comment]
When you say that you disconnected and reconnected, what exactly do you mean?

**Comment by benfrancis** [comment]
> When you say that you disconnected and reconnected, what exactly do you mean?
On my MacBook Pro I disabled Wi-Fi, re-enabled Wi-Fi and re-connected to the Wi-Fi access point.

**Comment by dhylands** [comment]
Hmm. The gateway doesn't know that the client disconnected and reconnected.

I wonder if there is a race or something, perhaps the Wifi was setup before the DNS or something like that and the initial connection got in before one of the other things was setup.

**Comment by benfrancis** [comment]
Yes, I suspect that's what's happening. The Wi-Fi Access Point comes up before everything is ready for Captive Portal to work.

Are you able to reproduce it?

**Comment by dhylands** [comment]
I haven't tried yet. I don't recall running into the problem, but I was watching logs and stuff when testing, so I might have been waiting longer.

**Comment by flatsiedatsie** [comment]
Some time in the future I would like to create an image of the Gateway that can operate without ever connecting to the internet or even the local network. It would have the add-ons I need pre-loaded.

In this situation I'd like to run the Raspberry Pi as a 'stand alone' WiFi hot-spot indefinitely. Acting as a captive portal that immediately brings the user to the interface when they connect to the hotspot would be very nice.

Could this functionality allow for that / accommodate that?

**Comment by dhylands** [comment]
You can definitely preload the addons. We do that to populate the zigbee, zwave, and thing-url addons in the this script: https://github.com/mozilla-iot/gateway/blob/f96ef8ca6be94350d276cb999c53e14d2741988c/image/add-gateway.sh#L189-L206

I don't think you need to connect the internet or local network if your addons are already installed.

I don't see why the "always on" captive portal couldn't be done as some type of option.

**Comment by flatsiedatsie** [comment]
@dhylands I was thinking I could try to create an add-on that 'forces' this 'island mode'. Any suggestions on how to accomplish that? What settings would need to change for the Gateway to stay in captive portal mode but actually be in normal operation state?

**Comment by dhylands** [comment]
With the code that's currently there, I'm not sure that this could be done from an addon, since I'm pretty sure that the addons aren't loaded until after the wifi setup.

The code which does the AP mode is found in src/wifi_setup.js

I'm not familiar enough with the code without figuring it out again.

I know that we use hostapd for the AP mode, and that the captive portal is done by having a DNS server which serves up the IP address of the gateway for every DNS request.

**Comment by flatsiedatsie** [comment]
@dhylands Thanks, that helps a lot. Now I know what to look for. Perhaps the add-on could make some changes and then require a reboot to take full effect.

**Comment by mrstegeman** [comment]
I've opened #1993 for this. The secondary portal works, in that it successfully redirects the user to the setup page. However, registration fails, as the portal captures the traffic intended for the registration server.

**Comment by dhylands** [comment]
The captive portal doesn't intercept any data, it's just redirecting using DNS. So we might be able to add something to allow the letsencrypt DNS requests to return the right data.

We might also be able to do something where we only satisfy DNS requests received from the LAN side.

What's the exact flow again?
I know it sets up an AP to get the Wifi information and then gets up the user-supplied SSID and password.
IIRC the user then connects to the new AP and we redirect to the tunnel setup. We should be able to disable the captive portal once we've gotten the request that we then redirect to the tunnel setup.

**Comment by mrstegeman** [comment]
https://github.com/mozilla-iot/registration_server/blob/master/doc/flow.md

**Comment by mrstegeman** [comment]
The gateway will need to communicate with the registration server (right now, one of 2 IPs) and Let's Encrypt.

The flow is:
1. Start open AP + captive portal
2. Set up wi-fi network
3. Take down open AP + captive portal
4. Start up user-defined network + new captive portal
5. Tunnel setup (see flow in previous comment)
6. Take down captive portal
7. Redirect to tunneled domain
8. User setup

**Comment by dhylands** [comment]
We might be able to do something like the following:
- before setting up the captive portal, lookup the IP addresses of the few addresses we want. For this example, I'll suppose that we want letsencypt.com and that it has an IP address of 1.2.3.4.

Currently we set the address to /#/192.168.2.1 which says to redirect all DNS requests to the IP address 192.168.2.1.

We might be able to set address to /letsencrypt.com/1.2.3.4, /#/192.168.2.1 which would then allow the letsencrypt lookup to return the correct IP address and redirect everything else.

**Comment by dhylands** [comment]
The other approach would be to take down the captive portal just before or just after serving up the tunnel setup page. The portal has done it's work by then. Then when the user clicks submit (or whatever the button is labelled) the captive portal has been taken down and the let's encrypt traffic goes to its intended location, as does the redirection to the tunnel name (hostname.mozilla-iot.org)

**Comment by mrstegeman** [comment]
The problem with the second approach is that the user could end up lost if they accidentally close their tab or something before finishing setup.

I can try the DNS approach and see where I get.

**Comment by mrstegeman** [comment]
Awesome, that worked. Please review.
