### ISSUE TITLE
Multi-factor authentication

### ISSUE THREAD

**Issue by arfrater** [mozilla-iot/gateway#1801]
At login an extra layer of security adding 2 step authentication to the login page as an option [https://en.wikipedia.org/wiki/Multi-factor_authentication](url)

**Comment by arfrater** [comment]
![01](https://user-images.githubusercontent.com/49191109/56862219-de573900-69eb-11e9-87b0-626d638817b0.png)

**Comment by mrstegeman** [comment]
Fixed by #2456.
