### ISSUE TITLE
Musings on new capabilities

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#1809]
While working on a [MySensors](https://www.mysensors.org/) add-on for the Mozilla Gateway I had some trouble integrating the capabilties from both projects.

Perhaps there is some inspiration for more capabilties when looking at the MySensors list of possible data types? In general it has may more sensor types.
https://www.mysensors.org/download/serial_api_20

I'm not saying differentiation between that many (sensor) types is really useful. In general I like how the Mozilla Gateway has a more interface centric focus, and steers clear of making a capability for every single type of sensor in existence. I think that's a smart move. On top of that, I suspect that instead of building this into the Gateway, add-ons could provide the proper labels for sensors, such as "mm", "ppm", "kpah" and the hundreds of environmental variables that can be measured nowadays.

That being said, there are some specific capabilities that I'd love are:
- Support for text strings. An example would be a simple LED display that can only display text. It would be great if that text could be set from the Gateway interface. This text capability could have many subtypes. For example, I have a door lock that require users to input a password and phonenumber. It does not have a web interface, so setting it via the Mozilla UX would be great.
- Some kind of 'quality' setting, where the UX can show a sensor value in certain colours depending on what its current level. For example, a CO2 sensor value could shift from green to orange to red if the level of CO2 reaches certain thresholds. A device could tell the Gateway which colours go with which levels.

Both the labels for sensor values as well as the quality level values feel more like 'metadata' that an add-on could provide.

Other interesting ones:
- Percentage (as a sensor, multiLevelSensor probably covers this in practice)
- GPS coordinates

In general, MySensors devices can be complex amalgamations of sensors and actuators, which often do not fit in the strict categories you find in commercial devices. For example, a thermostat and a dust sensor might be jammed into one device. It'll be interesting to see how the Gateway's capabilities system handles these Frankenstein devices. I'm exploring whether the add-on could split complex MySensors devices into multiple devices, which would then be better represented in the Gateway UX. How does the Gateway currently aim to handle unforeseen constellations and capabilties? I did notice the 'custom' capabilty. Is that the best option here?

**Comment by mrstegeman** [comment]
* For units, we try to stick with SI units, such as `degree celsius`, and then abbreviate them in the UI via [this code](https://github.com/mozilla-iot/gateway/blob/master/static/js/utils.js#L127-L197). So, it should be pretty easy to add support for things like `mm` and `ppm`. Add-ons should supply a `"unit"` for each property, where applicable.
* Text strings are already supported. If you have a property with `"type": "string"` (and not `"readOnly": true`), it will be rendered with a text input.
* Percentage is already covered. You just need to set `"unit": "percent"` for the property.
* The gateway already handles devices with multiple capabilities properly. The top-level thing can define multiple capabilities it supports, such as `"@type": ["OnOffSwitch", "SmartPlug", "EnergyMonitor"]`. When adding that device, the user can select which capability they want as the primary, which is what the main icon is drawn for. All of the properties are created on an ad-hoc basis, so they will all be drawn. A generic UI will be generated if we don't have anything more specific for a given capability.

**Comment by flatsiedatsie** [comment]
So much awesome! Thanks for the insights! Now I understand what that dropdown is for!

Building an adapter really gives me a lot of respect for the awesome and professional work that you guys are doing. Very cool. I just got my first value to show up in the interface.

**Comment by flatsiedatsie** [comment]
If I may ask a few more questions:
- About displaying a string property: [which property](https://iot.mozilla.org/schemas/#LevelProperty) should be chosen with that? None of then seem commensurate? (And is there a capability related to it? Does it matter if a property does not have a capability?)
- What does 'fire and forget' do? I didn't find any explanation online.
- If I choose 'read only' the interface becomes read-only, which is great for sensor values. But I also can no longer update the value from the adapter? I get the error "Read-only property" when I try to update it.
- How can I make the temperature value show a decimal?

Less important:
- Are their plans to add a barometer property?

**Comment by mrstegeman** [comment]
* String property: You don't have to use a `@type` for a property (or a thing). If you just omit it and set `type` to `string`, a generic UI will be drawn.
* CO2 sensor: Ditto. Just add a property with an `integer` or `number` `type`. Include a `unit` if you want.
* Fire and forget: I don't really know. I think that's really only used by one or two adapters. You can ignore.
* Read only: If you have a `readOnly` property, you can still update it internally with `setCachedValue()`.
* Decimal: Use `number` rather than `integer`.
* Barometer: See https://github.com/mozilla-iot/schemas/issues/39. Generally speaking, that repo is where we file issues concerning new capabilities.

**Comment by flatsiedatsie** [comment]
It's coming together quite well, thanks for the help!

Now I have yet another question: is it possible to force a property to be shown in the center of the device?

Right now I have a CO2 sensor:
![co2-device](https://user-images.githubusercontent.com/805405/56720418-5397e500-6732-11e9-9798-5b826039a4ed.png)

I have tried setting it to use the multi value property. If I understand correctly this toggle should determine what gets center stage?
![co2-settings](https://user-images.githubusercontent.com/805405/56720500-86da7400-6732-11e9-9c12-c5658bfd7473.png)

However, it doesn't change anything. It keeps showing '0' in the middle of the device.

I don't even understand where the 'custom' option comes from, as the device only has one property.

This is the code that generates it:

```
            elif child.type == 22:                      # Air quality
                if new_sub_type == 37: # V_LEVEL
                    self._type.append('MultiLevelSensor')
                    if prefix != '':
                        self.properties[targetPropertyID] = MySensorsProperty(
                            self,
                            targetPropertyID,
                            {
                                'label': new_description,
                                'type': 'number',
                                'unit': prefix,
                                'readOnly': True,
                            },
                            new_value, new_node_id, new_child_id, new_sub_type)
                    else:
                        self.properties[targetPropertyID] = MySensorsProperty(
                            self,
                            targetPropertyID,
                            {
                                'label': new_description,
                                'type': 'number',
                                'readOnly': True,
                            },
                            new_value, new_node_id, new_child_id, new_sub_type)
```

I have noticed similar behaviour in a weather station device, where changing the dropdown option doesn't change anything. The humidity value keeps being center stage.

(I'm also trying to figure out how I can make it remove the unnecessary trailing 0's without changing the property from 'number' to 'integer')

**Comment by mrstegeman** [comment]
For a `MultiLevelSensor`, the `LevelProperty` will be shown in the center. So, you need to assign `'@type': 'LevelProperty'` to your properties in that code. You need to adhere to the [schema](https://iot.mozilla.org/schemas) for the icons to work properly. If, however, you have a `MultiLevelSensor` with multiple `LevelProperty`s, you'll need to remove the `@type` from whichever one you **don't** want to show up in the center icon.

The "Custom" option essentially just allows you to set a custom icon, rather than one of our predefined ones.

For the number precision issue, you're looking for #1318.

**Comment by flatsiedatsie** [comment]
Ah, I see. I will have to remove the MultiLevelSensor from it.

The thing is, a `LevelProperty` requires that I set an expected minimum and maximum. But in many of these cases I have no clue what they will be. It depends on what users build / which situations they put the sensors in. For example, sometimes air quality will be measured in micrograms per cubic meter, sometimes in parts per million.

If I only add properties without specifying __type.append_ or `'@type':` options, then they don't seem to get  any value in the center at all.

My original suggestion to create an official, universal 'fallback' type that can handle pretty much anything thrown at it would be very handy here. Alternatively, an option for the user to just select which of the properties they want in the center, based on name, would be equally handy.

**Comment by mrstegeman** [comment]
The high-level icons with numbers/symbols and such are declared based on the capabilities in our schema repository.

I do like the idea of being able to pick which thing to show in the center, so that may be a good thing to pursue.

Right now, the "universal fallback" is drawing generic property bubbles and allowing the user to select an image file to place in the center icon.

**Comment by flatsiedatsie** [comment]
Great to hear!

While selecting an icon is great, nothing beats getting some actual values :-)

As a side note: the beta version of the adapter/add-on (still don't know the difference) can be found here:
https://github.com/createcandle/Webthings-mysensors-adapter
I just compiled it, and it works!

**Comment by mrstegeman** [comment]
Awesome! Please submit a PR to [mozilla-iot/addon-list](https://github.com/mozilla-iot/addon-list) when it's ready so others can use it as well.

**Comment by flatsiedatsie** [comment]
Done.

Shall I close this issue and perhaps create a feature request somewhere for being able to manually select which property gets center stage?

**Comment by mrstegeman** [comment]
That would probably be best. Thanks!
