### ISSUE TITLE
Repeatedly submitting register subdomain not handled gracefully

### ISSUE THREAD

**Issue by ssendev** [mozilla-iot/gateway#1813]
While registering a subdomain the message was `Processing...` but it seemed to be stuck pressing the button again resulted in an instant domain already taken error. After the third domain i was preeety sure that one wasn't already taken so i looked around and found 3 confirmation mails in my spam. which means even the first one worked. i can't remember if i just had to reload the page or if i rebooted but then it had taken the last domain (which of course was the ugliest one (i know i could reflash and reclaim the domain (at least i have read somewhere it should be possible) but it's still annoying))

Possibly related to #358 then it could just say `keep calm i'm still processing...` instead of trying to register a second domain.

**Comment by benfrancis** [comment]
@ssendev Thanks for reporting this. We've been experiencing some intermittent problems registering and re-claiming domains from our API server recently and we're trying to figure out how to reliably reproduce the problem, so if you have any other information then do let us know.

We can also have a think about how to handle the failures a bit more gracefully!
