### ISSUE TITLE
Allow to hide things in Thing view

### ISSUE THREAD

**Issue by ssendev** [mozilla-iot/gateway#1814]
i used a pulse to turn a gpio back off since it shouldn't stay on for longer than a second but now i basically have the same button twice.

it would be great if things could be hidden or grouped

**Comment by flatsiedatsie** [comment]
I have a similar scenario where I have some buttons that I rarely need to use. For example, a button that triggers the addition of a new device. 

One solution would be to create a dashboard where you can add your 'favourites' /  only the devices you actually care about. See: https://github.com/mozilla-iot/gateway/issues/1597

Another, in my case, is to let Add-ons create their own interface pages, so that the 'thing as a button to start the inclusion proces for an add-on' hack is no longer necessary. See: https://github.com/mozilla-iot/gateway/issues/1505

**Comment by mrstegeman** [comment]
I'm not sure we'd want to have _hidden_ things. How would you get them back? What dictates where they _should_ be visible?

I do, however, support the concept of groups. See #1191

Perhaps if we add support for groups, we can allow groups to be collapsed, rather than fully hidden.

**Comment by ssendev** [comment]
they could either hide in the + at the bottom where they would probably need to be specially marked since they should still be visible in rules or a new bottom icon `…` next to the +

**Comment by freaktechnik** [comment]
Note that you can re-order things in the view by dragging them by their name (dropping them to the new position is a bit finicky, I find, since you have to hit the correct area pretty precisely).

**Comment by ssendev** [comment]
i know. having useless stuff at the end still lets my ocd senses tingling.

But that brought another ui idea. Having a `below the fold` `"thing"` that will hide all things that come after it and when there are items that are hidden ads a `…` or `show all` button at the bottom

**Comment by flatsiedatsie** [comment]
From my experience it's quite useful and common to have two views, where one is user curated, and the other gives access to everything.

- Domoticz: dashboard vs categories
- Android: home screen / app drawer
- Windows: desktop / start menu
etc

**Comment by benfrancis** [comment]
There kind of already are two views:

1. The add device screen lists devices which are connected to a network adapter but not added to the gateway database
2. The things screen shows devices that have been added to the gateway database

I tend to agree with @mrstegeman in that this is probably sufficient.

**Comment by flatsiedatsie** [comment]
I don't really agree those things are comparable. The 'add device' screen does now allow you to really look at values from those devices, and they are not available for automations. They are not 'my things'. In this metaphor, the 'add devices' screen would be like the big stack of floppy disks on the table. Available to become part of the system, sure, but they are not part of it yet.

**Comment by benfrancis** [comment]
Maybe rather than hiding devices from the Things view, another approach is to have a curated [dashboard](https://github.com/mozilla-iot/gateway/issues/1597) view which shows exactly what you want to show (e.g. a subset of devices, logging graphs, scenes etc.)?

**Comment by flatsiedatsie** [comment]
Yes, that would be my preference as well.

**Comment by ssendev** [comment]
A dashboard view could probably solve this too.

In the meantime I have tried to implement a hide-things thing which is available at https://github.com/ssendev/gateway which as i think works rather nicely (Beware of the implementation. Also i haven't added a new device and instead corrupted the OnOffSwitch).

**Comment by benfrancis** [comment]
Closing in favour of dashboard view.

**Comment by djangobits** [comment]
+1 for customizable dashboard view
