### ISSUE TITLE
Gateway sending > 50 QPS of GET to '/' to device

### ISSUE THREAD

**Issue by joshgc** [mozilla-iot/gateway#1817]
I have a RPi3B+ serving as a gateway (flashed from the image). When I bring up the single-things example on second device (PiZeroW), it does connect and I do get data as expected back on the Gateway UI. However I'm also getting an excessive amount of GET requests from the gateway IP to either '/' or '/0'.

Has anyone experienced this? A request ever 10-20 milliseconds is sufficient to load the second device so cannot multi-task very well now. Let me know how I can debug, or if you have a pointer so I can "RTFM".

**Comment by mrstegeman** [comment]
Have you been switching between the single-thing and multiple-things examples? Sometimes, that’s not handled super well. If you enable and disable the Web Thing add-on in Settings, this should go away.

**Comment by joshgc** [comment]
That did the trick! Do we want to track the underlying issue? I'd imagine switching between single- and multiple-things is a common onboarding experiences

**Comment by mrstegeman** [comment]
I'm trying to reproduce this to see if I can fix the underlying issue, but I can't seem to. Do you have a set of steps to reproduce?
