### ISSUE TITLE
Kiosk mode on

### ISSUE THREAD

**Issue by raidnet-ms** [mozilla-iot/gateway#1818]
What about simplifing the process to set the Kiosk mode on?
It is very useful when a gateway is connected to a touchscreen.
I found a [guide](https://www.youtube.com/watch?v=I2laR5G5FFo) to set the kiosk mode on raspbian using chromium, i was wondering if we can manage to do the same with FireFox and simplify the process with a flag in the gateway settings.

**Comment by benfrancis** [comment]
@raidnet-ms What do you mean by Kiosk Mode exactly?

Note that the Raspbian build is built on Raspbian lite which is a headless server with no front end.

This use case might be better addressed by the Things Controller https://github.com/mozilla-iot/things-controller

**Comment by flatsiedatsie** [comment]
One option would be a 'go fullscreen' button somewhere. That way, on a tablet, you could quickly turn it into a fullscreen controller for your home.

**Comment by raidnet-ms** [comment]
Hi Ben,
that's true, actually the ISO is based on Raspbian lite but it is also possible to install the IOT gateway on the complete version of raspbian.

What I imagine is something like [Amazon Echo Show](https://www.google.it/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwjZ7dOSre3hAhVJx4UKHURHAVoQjRx6BAgBEAU&url=https%3A%2F%2Fwww.ishopping.pk%2Famazon-echo-show-white-price-in-pakistan.html&psig=AOvVaw1IABEJXDs9IDirMWfC1-2i&ust=1556354106283090) or [Google Home Hub](https://www.google.it/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwjGyo-_re3hAhVN1hoKHdTjCzYQjRx6BAgBEAU&url=https%3A%2F%2Fwww.bestbuy.com%2Fsite%2Fgoogle-home-hub-with-google-assistant-chalk%2F6290313.p%3FskuId%3D6290313&psig=AOvVaw2H8GS-hXu0u8ttcaNqPCUK&ust=1556354235778273).

There's a lot of freeware hardware you can use to make something similar with [mozilla IOT](https://www.google.it/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=2ahUKEwil3IeBru3hAhUPThoKHZsdBJkQjRx6BAgBEAU&url=https%3A%2F%2Fraspi.tv%2F2015%2Fnew-official-raspberry-pi-dsi-screen-launches&psig=AOvVaw3m5BldW6qyWHsWf1SEWuCN&ust=1556354369492541)

There are two main way to use Mozilla iot: a "soft-ware way" where the gateway is implemented in a router or a Nas and you access the settings with any client but It's more oriented to skilled user (IMHO).  

I think we should not miss the potential of a DIY "ready-to-go home device" for less skilled users.

**Comment by raidnet-ms** [comment]
> @raidnet-ms What do you mean by Kiosk Mode exactly?

> This use case might be better addressed by the Things Controller https://github.com/mozilla-iot/things-controller

Interesting but in part seems to be redundant to me.

**Comment by benfrancis** [comment]
> Interesting but in part seems to be redundant to me, you are already developing a gui for the gateway.
> The future is PWA, why we should mess with Android and double the work?

This touches on a popular topic of debate, but let me explain my thinking.

The web interface of the WebThings Gateway is a PWA. The WebThings Gateway is the server which serves the PWA, the WebThings Controller is a client which renders it.

WebThings Gateway will soon run on OpenWrt, aimed at headless wireless router hardware like the Turris Omnia (with hardware optimised for networking) and running a web server with Node.js. WebThings Controller runs on Android Things, aimed at smart displays and smart speakers (with hardware optimised for human interaction), using GeckoView to render the web interface.

This model allows for multiple smart display & smart speaker clients around the home connecting a central router acting as a server.

Whilst it is technically possible to combine the client and server into a single device, there is currently no hardware or software stack which does a good job of both and it would make for a very expensive and impractical product.

What might make sense in future is for multiple client devices (speakers and displays) to act as nodes in (Wi-Fi/Zigbee/Z-Wave/Bluetooth) mesh networks to extend the range of wireless networks around the home. But the home only needs one router and one server.

**Comment by raidnet-ms** [comment]
I see and is pretty clear, I'm just wondering if a router has enough computing power to manage data log from a multitude of things. Did you see how Qnap is working on this side of their IOT platform? They use the power of the nas to computational work and drive speed for data logging. I'm worried about limits of a common router, specially if we plan to manage video resource (Onvif).

Node server has high resource needs (compared to a router CPU performance).
Am i wrong?

**Comment by raidnet-ms** [comment]
> but let me explain my thinking.

I'm really interested in your view. Do you have any draft of the possible roadmaps?

**Comment by benfrancis** [comment]
You're not wrong. But we are really targeting a new generation of smart routers rather than traditional wireless routers which just shift network packets around. Think of it as like the difference between feature phones and smartphones.

The Turris Omnia for example has a dual core 1.6GHz processor and up to 2GB RAM. Future chipsets will be even more advanced and may even have things like dedicated hardware (GPUs) for machine learning. It's true that storage may be an issue, as the flash storage commonly found in routers is not really designed for a lot of writing.

> I'm really interested in your view. Do you have any draft of the possible roadmaps?

Only what is published on our blog https://hacks.mozilla.org/category/web-of-things/

**Comment by benfrancis** [comment]
I'm going to close this issue because I think a full screen button is probably better suited as a client-side feature of browser chrome rather than part of the web app itself.

**Comment by raidnet-ms** [comment]
> The Turris Omnia for example has a dual core 1.6GHz processor and up to 2GB RAM. Future chipsets will be even more advanced and may even have things like dedicated hardware (GPUs) for machine learning. It's true that storage may be an issue, as the flash storage commonly found in routers is not really designed for a lot of writing.

This is what I mean for futuristic vision :-)
