### ISSUE TITLE
unique property/event/action ids for new things

### ISSUE THREAD

**Issue by gabrielruiu** [mozilla-iot/gateway#1824]
This is a question regarding the `Thing` model. 

Looking through the `src/models/thing.js` file, I can see that a thing is instantiated with an id and a device description. Throughout the instantiation process, the properties, events and actions are copied into the Thing instance. 

My question is: during the  instantiation process, would it make sense to assign a unique instance id to each entity (property, event, action) ?

This would have the following advantages:
1. Each of these entities could be referenced independent of the Thing itself.

2. API calls simplification; there would be one less id required in payloads

instead of 
```
{
  messageType: 'setProperty',
  data: {
    pluginId: 'pluginId-string',
    adapterId: 'adapterId-string',
    deviceId: 'device-id',
    propertyName: 'name-of-property',
    propertyValue: new-value,
  },
}
```

it could just be 
```
{
  messageType: 'setProperty',
  data: {
    pluginId: 'pluginId-string',
    adapterId: 'adapterId-string',
    propertyId: 'id-of-property', <--was 'propertyName'
    propertyValue: new-value,
  },
}
```

The `deviceId` is gone, because the instance id of the property refers to a specific property of a specific device/thing.

3. The entities could be cached independently of the parent object (the Thing).

**Comment by tim-hellhake** [comment]
I think the problem is the ids are generated by the addon.
Two addons could generate the same propertyId.

**Comment by gabrielruiu** [comment]
Aren't API calls scoped to a specific addon? That would mean the ids need to stay unique only in the addon context.

**Comment by tim-hellhake** [comment]
Sounds plausible.
But every addon would have to guarantee that the property ids are unique.
As the ids should be reproducible this might lead to ids like 'deviceId/propertyName'.
I don't if this is really better.

**Comment by mrstegeman** [comment]
Properties, actions, and events belong to a thing, not to the gateway, so they only need to be unique to the thing. The change you're suggesting would be a large amount of work for essentially no gain.

**Comment by gabrielruiu** [comment]
Ok, thank you for the insight
