### ISSUE TITLE
Theming support?

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#1827]
This is a far-out idea, and not at all important. But I'd be curious what the position is on this.

I had some fun looking at the html that the gateway generates today.
![thing-overview-css](https://user-images.githubusercontent.com/805405/56760885-ac479c00-678b-11e9-9a9c-8c064b912b18.png)

**Comment by flatsiedatsie** [comment]
Just a thought:

What if themes would basically be add-ons/adapters that can only do one thing: add a single CSS file.

Just modifying CSS could already allow for a lot of fun, like a 'night mode' theme, different colors and fonts, or a theme that uses space a bit more effectively on small screens, etc.

**Comment by mrstegeman** [comment]
This is really a subset of #1505.

**Comment by flatsiedatsie** [comment]
Now that making themes is theoretically possible using the extension add-on functionality, I wonder if it would be wise/useful to create a "theme" type for add-ons. Even if under the hood it's just a normal extension add-on, it might be useful to somehow label it 'theme' so users can find themes easily in the add-on list.

Perhaps this could even include a screenshot somehow.

User story:
As a user I would like to be able to find cool themes easily.

**Comment by mrstegeman** [comment]
I don't have a strong opinion on this either way. @benfrancis?

**Comment by benfrancis** [comment]
I like the idea of theme add-ons, but if we create a special type of add-on for that purpose I really think they should have a more explicit theming API, rather than just having extensions which inject their own CSS.

Without an explicit API or at least a subset of theme able CSS classes which we can aim to keep stable, theme add-ons are likely to be very brittle and experience breakage every time we modify the CSS of the gateway.

**Comment by benfrancis** [comment]
I've filed https://github.com/mozilla-iot/gateway/issues/2225

**Comment by raidnet-ms** [comment]
If you are going to support UIkit i could help on theming.

**Comment by mrstegeman** [comment]
We don't currently use any UI frameworks and don't have any plans to.
