### ISSUE TITLE
Don't update addons if they are not compatible with the gateway

### ISSUE THREAD

**Issue by tim-hellhake** [mozilla-iot/gateway#1828]
Currently addons are auto-updated to the latest version.
If they are not compatible with the gateway they will stop working.
How about adding a property to the addons list which defines which minimum version of the gateway is required?
The gateway can then ignore the update and continue to run with the latest working version.

**Comment by mrstegeman** [comment]
We have an API version which is checked before updating. If the API version is incompatible, it won't be updated. That's what the `api` field is for in the `package.json`. We don't really bump the gateway's API version, though, unless there is major API breakage.

In this case, there is a new API which you can check for at run-time, so not a breaking change.

If we were to bump the gateway's API level every time something changed in that library, half of our add-ons would constantly be in a broken state.

**Comment by tim-hellhake** [comment]
Okay, I didn't knew that.
I suppose the API is defined by the message protocol used between gateway and addon.
What i'm worried about is if something is added to the `gateway-addon-node` there is a breaking change although the api might not have changed at all.
As long as the `gateway-addon-node` is tightly coupled to the `gateway` releases every addon which uses the new functionality depends on that `gateway` version.
Currently it's not possible to detect that other than by a manual review.
So I came up with the idea that the addon states on which `gateway` version it depends.

But i wonder why the `gateway-addon-node` and the `gateway` have to be coupled.
Shouldn't the api version be the only coupling between `gateway-addon-node` and `gateway`?
Maybe it's possible to give `gateway-addon-node` its own version.
Then client would have a stable version to rely on.

**Comment by mrstegeman** [comment]
This should all be solved now with separate versioning of the libraries and the new manifest format.
