### ISSUE TITLE
Router setup allowed an empty password.

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#1835]
When using the router setup, you get presented with a screen to enter an SSID and password. 

It considers an empty password to be valid, but goes ahead and stores it as a psk2 password, which isn't valid (psk2 requires at least 8 characters IIRC).

So we either need to reject invalid passwords or use allow different encryptions (like open).

**Comment by mrstegeman** [comment]
Well, that's weird that the UI allowed it. The field has a `minlength` set to 8.
