### ISSUE TITLE
Links in Welcome to Mozilla WebThings Gateway message don't work.

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#1839]
I registered a new domain and got the following email:
```
Hello,

Welcome to your Mozilla WebThings Gateway! To confirm your email address, navigate to http://api.mozilla-iot.org/verifyemail?s=56a9b67f-674f-4775-98c9-47140ef677c8.

Your gateway can be accessed at ...
```
If I click on the above link then I get an error page titled "Secure Connection Failed"
```
An error occurred during a connection to api.mozilla-iot.org. Peer received a valid certificate, but access was denied. Error code: SSL_ERROR_ACCESS_DENIED_ALERT

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```

**Comment by mrstegeman** [comment]
As is typically the case when @benfrancis reports this, the link works perfectly fine for me. We used to have a misconfiguration with a hard redirect, and your browser could still have that cached. It always works in a private browsing session with no cache.

**Comment by dhylands** [comment]
I tried in Chrome and got a similar error. In both Firefox and Chrome it was trying to redirect from the http: url included in the email to an https url.

Although, the second time I tried to do the verify, I get "An error happened while verifying your email." when I've already verified.

I tried the 2 URLS various times (from the 2 domains I registered), and even in Private Browsing and/or incognito mode I still get certificate errors sometimes. Once I got:

400 Bad Request
The plain HTTP request was sent to HTTPS port

**Comment by haydnnewport** [comment]
Hi, I've just run into this as well - I managed to successfully verify using `curl`, but I noticed that it was getting a redirect from the webserver, shown below:
```
< HTTP/1.1 301 Moved Permanently
< Server: nginx/1.14.1
< Date: Sun, 28 Apr 2019 06:43:12 GMT
< Content-Type: text/html
< Content-Length: 185
< Connection: keep-alive
< Location: https://api.mozilla-iot.org:8443/verifyemail?s=<redacted>
```
whereas when I visit that page in my browser, it's actually showing a `307 Internal Redirect` with HSTS as the reason, so it's trying to connect to the same url as it had, but on port 443, which does not answer.

![2019-04-28_LI](https://user-images.githubusercontent.com/2024554/56860125-01331e80-69e7-11e9-94a6-3c84948dbab0.jpg)

**Comment by mrstegeman** [comment]
Huh. I'm still unable to reproduce that. However, I've disabled HSTS on the registration server for now. Hopefully that resolves things.
