### ISSUE TITLE
Network Map View

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1842]
As a user I want to see a map of my home network so I can see how devices are connected and diagnose connectivity issues.

E.g. a graphical representation of Zigbee/Z-Wave/Wi-Fi mesh networks and which nodes are connected to which.

Just an idea. More of a power user feature but may be quite useful for a smart router.

Could split the Things view into Things (list of icons), Network (network topology map) and Floorplan (spatial view).

**Comment by raidnet-ms** [comment]
First of all we should define if the final user is a tech fan or a normal low-skilled user (to make it simple if they are apple fan or android fan :-)).

My impression is that until Mozilla IOT won't complete this sperimental stage, we will have a platform more addressed to developers. If we don't start thinking about less skilled users, we may risk that the beta version won't be final-user-friendly and not complex enough to be a business solution.

The second meditation is about the user interaction with the gateway: there is a moment to set up things and a moment to control them. A skilled user may find useful a technical view to see if everything is alright. A common user may care only for important notifications and never deepen the tech view.
