### ISSUE TITLE
Play multimedia content from DLNA server

### ISSUE THREAD

**Issue by raidnet-ms** [mozilla-iot/gateway#1847]
Hello,
I was wondering what could be the best practice to develope an adapter to cast multimedia content from a DLNA server to a client using specified rules from the gateway (eg. click a fisical button to play \\nas\automationvideo\Welcome_home.avi on Chromecast or miracast or webos).

I found the thing adapter for Chromecast but this let only direct already playing content (play/pause, stop, volume set).

Could you lead me through a proper way to send specified files from the dlna server through the Chromecast adapter?

May an adapter for DLNAcast https://github.com/xat/dlnacast do this job?

thank you.

**Comment by mrstegeman** [comment]
I think there are a couple problems and/or things to figure out with this.

1. Transcoding. Is this something the gateway should really be handling?
2. Browsing media. Is the media stored on the gateway? How would the user select a file?

**Comment by raidnet-ms** [comment]
1) Usually the DLNA server is transcoding the video (sometimes a NAS or a game console like PS4 or XBOX). If the transcoding is not supported (rare occasion) then the file is sent to the client without transcoding it (it may happen that if the TV hasn't the proper codec then the video cannot be played).
But in most common case the DLNA server do its job.

2) DLNA supports browsing media in the lan with UPnP (you set the media directories in the DLNA server).

2.1) Yeah actually how the user could select the file is my main doubt. Should the user select the file from the rule or should he set the file/playlist from the adapter settings?
The first solution could be more flexible but the gUI doesn't fit this possibility. :-/

**Comment by mrstegeman** [comment]
This might be better served as a web thing, rather than an adapter. For example, I turned MPD (music player daemon) into a web thing here: https://github.com/mrstegeman/mpd-webthing

I think you can be a lot more flexible about things that way, as the user can configure things how they'd like in whatever way you want (command line args, config file, etc.).

**Comment by mrstegeman** [comment]
I like it!
