### ISSUE TITLE
Network Settings (OpenWrt) - WAN & LAN IP addresses

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1848]
- As a user I want to know whether my gateway is connected to the Internet
- As a user I want to know the IP address of my gateway on the Internet
- As a user I want to know the IP address of my gateway on the local network

Note: This is all covered in [slide 129](https://docs.google.com/presentation/d/1rMeg6hep8JQflqwbiNIbhSoK9StCeVZ2npphmQHKda4/edit#slide=id.g5094b10cb0_2_123) of the UX spec, but these features haven't been implemented yet.

**Comment by benfrancis** [comment]
This was previously #1674, which may have been closed in error?

**Comment by mrstegeman** [comment]
This was implemented, but something may be broken:
https://github.com/mozilla-iot/gateway/blob/master/static/js/views/settings.js#L1029-L1046

**Comment by mrstegeman** [comment]
This is returning:

```json
{
  "wan": "",
  "lan": "",
  "wlan": {
    "ip": "",
    "ssid":"WebThings Gateway"
  }
}
```

**Comment by benfrancis** [comment]
I'm currently still not setting a IP address for Internet (WAN) when I connect it to my router via DHCP. Is this still broken?

**Comment by mrstegeman** [comment]
Is this on the RPi? If so, that makes sense, because we only have a LAN port, not WAN.

**Comment by benfrancis** [comment]
@mrstegeman Sorry, I missed this question. Yes, this is on Raspberry Pi.

My understanding is that on OpenWrt the Ethernet port is configured as a WAN port, which Wi-Fi clients route their traffic through. My expectation is that the WAN section of Network Settings therefore shows the current IP address the WAN interface has been assigned. When connecting it to my existing router with NAT enabled this would be a local IP address, but I assume it could also be a public IP assigned by an ISP if plugged into a cable modem for example.

**Comment by benfrancis** [comment]
(This is separate from the IP address in the LAN section, which would be statically defined as 192.168.2.1 by default)

**Comment by mrstegeman** [comment]
Should we hide the LAN section on the Pi, then?

**Comment by benfrancis** [comment]
No, I don't think so. As I understand it a router has two IP addresses, one on the network it is routing from and one on the network it is routing to.

When the Raspberry Pi's Ethernet port is configured as a WAN port it has no Ethernet LAN ports, but the WLAN interface shares the same IP address (The Wi-Fi settings section is just for configuring the SSID and password, the IP configuration is set in the "Home Network (LAN)" section). By default the IP of the WAN side is assigned externally via DHCP and the IP on the LAN side is assigned statically set to 192.168.2.1. The former should be displayed under "Internet (WAN)" and the latter should be displayed under "Home Network (WAN)" in the [Network Settings UI](https://github.com/mozilla-iot/gateway/issues/423#issuecomment-467508688).

Unless I'm missing something?

**Comment by mrstegeman** [comment]
That's not really true. Pretty much every router has at least 2 ethernet ports. One serves the WAN side and has a public IP, and the other serves the LAN side and has a private IP (192.168.2.1). The router handles the routing between the two interfaces. In that case, the WLAN port doesn't actually get an IP address. It just bridges the LAN and the WLAN interfaces.

On the Pi, however, there is no actual LAN interface, so what we do is give the WLAN interface an IP address, rather than bridging it to the LAN port.

It seems like what you're wanting is to show the private IP address in the LAN section, regardless of the hardware (i.e. even if there is no physical LAN port). Is that right?

**Comment by benfrancis** [comment]
> It seems like what you're wanting is to show the private IP address in the LAN section, regardless of the hardware (i.e. even if there is no physical LAN port). Is that right?

Yes, that's right. It's really the "Home Network" section. The title "Home Network (LAN)" makes sense on router hardware with actual LAN ports (where as you say, WLAN is bridged to LAN). I agree it's a bit strange on the Raspberry Pi where there are no LAN ports and you're really configuring WLAN directly. We could move the IP & DHCP configuration out of "Home Network (LAN)" into "Wi-Fi (WLAN)" just for the Raspberry Pi, but it seems simpler to leave it where it is. (The Raspberry Pi is really the edge case).

What do you think?

**Comment by benfrancis** [comment]
(Note that currently the space in the "Wi-Fi (WLAN)" menu item where the IP address would go is currently taken up by the SSID).

**Comment by dhylands** [comment]
Just to clarify. Under Raspbian, the ethernet cable and Wifi are just treated as 2 separate network interfaces and no routing occurs between them. If both are connected, then each one will get an IP address (probably from the same DHCP server).

Under OpenWRT, the ethernet port is the WAN port and by default gets its IP address by DHCP. There is a "lan network" called br-lan which gets assigned a static address 192.168.2.1, and the wifi interface is a member of the br-lan. Routing between br-lan and the WAN occurs automatically.

**Comment by tim-hellhake** [comment]
> As a user I want to know whether my gateway is connected to the Internet

Do you mean _directly connected_ or _has access to the internet_?

**Comment by tim-hellhake** [comment]
> As a user I want to know the IP address of my gateway on the Internet

What should be shown if the gateway is behind a NAT?

**Comment by tim-hellhake** [comment]
> On the Pi, however, there is no actual LAN interface

What about the Ethernet Port?

**Comment by mrstegeman** [comment]
@tim-hellhake this is all for OpenWrt, when the gateway is running in router mode. For our normal Raspbian builds, the gateway is just a client.
