### ISSUE TITLE
Network Settings (OpenWrt) - Pre-populate SSID

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1849]
I suggest pre-populating the Network name (SSID) field in Wi-Fi settings with the current SSID.

Should we pre-populate the password field as well?

**Comment by mrstegeman** [comment]
This should also be done already:
https://github.com/mozilla-iot/gateway/blob/master/static/js/views/settings.js#L1029-L1046

**Comment by mrstegeman** [comment]
This is returning:

```json
{
  "enabled": true,
  "mode": "ap",
  "options": {
    "device": "radio0",
    "network": "lan",
    "ssid": "WebThings Gateway",
    "key": "Something",
    "encryption": "psk2"
  }
}
```
