### ISSUE TITLE
gateway.local mDNS broadcast not working

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1850]
On OpenWrt build

**Comment by mrstegeman** [comment]
@dhylands None of the available mDNS services are installed. We need to add one of the following to the image:
* mdnsd
* avahi-daemon
* mDNSResponder

**Comment by dhylands** [comment]
I was able to install the avahi daemon and get ping openwrt.local to work on the LAN side. I'll see about adding this to the next build.

**Comment by benfrancis** [comment]
> I was able to install the avahi daemon and get ping openwrt.local to work on the LAN side.

To be clear, the hostname should be gateway.local

**Comment by benfrancis** [comment]
This appears to be working now \o/
