### ISSUE TITLE
Lastpass icon can be seen when adding new thing

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#1851]
When adding a new device, the Lastpass icon can be seen. This usually only appears inside html input fields, suggesting there is a hidden one somewhere.

![lastpass-icon](https://user-images.githubusercontent.com/805405/56977698-4e3cff00-6b65-11e9-8412-e13c9260cfb6.png)

**Comment by mrstegeman** [comment]
There's a hidden password field for devices that require pairing (e.g. HomeKit).

**Comment by flatsiedatsie** [comment]
This device does not require pairing though?

I noticed this only happens when a device does not have any capabilities (which the MySensors devices rarely have). In other words, it only appears when 'custom' is selected in the dropdown (and the 'save' button is clicked).

**Comment by flatsiedatsie** [comment]
Hmm, although the screenshot above seems to dispel that idea.

**Comment by mrstegeman** [comment]
The password field is still in the HTML, just not displayed.
