### ISSUE TITLE
NFC thing to open door, best practice to query user DB in gateway?

### ISSUE THREAD

**Issue by raidnet-ms** [mozilla-iot/gateway#1858]
Hello,

I was working on this project made by Edo
https://github.com/edovio/RFIDThing/blob/master/RFID_SKETCH/RFID_THING.ino

This sketch hardcodes the NFC key ID allowed to access while I would like to use a variable and read from the Gateway User DB or even better, to query if any user has the ID read on the NFC. If present then retun username to the thing and authorize.

Any reccomendation or best practices?

**Comment by tim-hellhake** [comment]
I see a`idCurrent` property in the code.
I'm not sure about the user DB but you could at least verify the id in a rule in the gateway.
If you need the status on the thing you could write to the `authCurrent` property.

**Comment by raidnet-ms** [comment]
Actually idcurrent is used to send the nfc key id to the gateway only for reading purpouse. The thing is veryfing the authorization itself while i think it should be the gateway to approve the access.
I don't think that creating a rule for each key is a good solution. The rule could determinate what to do when an access is approved but should not store all the keys allowed to access. In many circumstances each user has a personal key so we might have a huge amount of rules if we need to store them there.

The thing could use authcurrent property to show the feedback on a monitor or to open the door but Opening the door might be achieved by a different thing (usually a relay) with the rules.
