### ISSUE TITLE
request error for  api.mozilla-iot.org

### ISSUE THREAD

**Issue by vincentserpoul** [mozilla-iot/gateway#1860]
2019-05-06 22:36:09.925 INFO   : Failed to ping registration server: { FetchError: request to https://api.mozilla-iot.org:8443/ping?token=xxx failed, reason: getaddrinfo EAI_AGAIN api.mozilla-iot.org:8443 |

**Comment by mrstegeman** [comment]
This happens when the gateway doesn’t have an internet connection.

Is your network blocking outbound traffic to port 8443?

**Comment by hobinjk** [comment]
@mrstegeman api.mozilla-iot.org is down (I'm guessing slack ate the message notification)

**Comment by vincentserpoul** [comment]
That explains :).
I'm just trialing mozilla iot for now, so it's ok, but in case, my home depends on it, is there any SLA on the gateway? Should I look into an alternative?

**Comment by mrstegeman** [comment]
Server is coming back up now, sorry for the downtime.

There is a 2 part answer to your question.
1. The SLA of the gateway is truly dependent on your local gateway's uptime. All processing is done there, all storage is kept there, etc. As long as your physical gateway is up and running, you can access it locally via http://gateway.local.
2. If you're asking about the tunneling service in particular, i.e. accessing &lt;host>.mozilla-iot.org, we don't have a defined SLA. Our engineering team is a total of 4 people, so we don't have someone constantly monitoring everything.

**Comment by vincentserpoul** [comment]
1. Yes, makes total sense.

2. Thank you! I was not trying to blame anyone, just wanted to know how reliable it was and have a second way of accessing my gateway if that fails, like today.
