### ISSUE TITLE
TemperatureProperty always shown as integer?

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#1870]
I have a temperature sensor that sends data over with one decimal:

`payload: 21.0`

However, in the UX, a temperature value is always shown as an integer.

- It is initiated as a number:

```
            elif child.type == 6:                       # Temperature
                if new_sub_type == 0: # V_TEMP
                    self._type.append('MultiLevelSensor')
                    self.properties[targetPropertyID] = MySensorsProperty(
                        self,
                        targetPropertyID,
                        {
                            '@type': 'TemperatureProperty',
                            'label': new_description,
                            'type': 'number',
                            'unit': 'degree celsius',
                            'readOnly': True,
                        },
                    new_value, new_node_id, new_child_id, new_sub_type)
```

- Other values with decimals that are not set as a temperature type do show decimals in the UX. In fact, they are padded with extra zeros until they have three decimals, but that's another issue.

**Comment by flatsiedatsie** [comment]
Perhaps the issue is that a Math.round is applied?
https://github.com/mozilla-iot/gateway/commit/c5d91f118ded755e04b7ca483ba00031f7ddd6f4#diff-e4eeba55b041f12325de3a5848b845d5R86

**Comment by mrstegeman** [comment]
Yes. This is yet another case of not knowing what precision to use. See #1318

**Comment by flatsiedatsie** [comment]
That is an issue. But I don't agree it's blocking a fix here.

Since this variable is defined as a `number`, rounding it down to a state without decimals (aka an integer) is going too far, regardless. A number should, at the very least, always have/allow for one decimal?

**Comment by mrstegeman** [comment]
Right, but what's the _proper_ precision here if it's a `number`? That's still the question.

**Comment by flatsiedatsie** [comment]
I understand.

Could we, until all that is figured out, remove the round from the temperature value? Perhaps set it to use 2 decimals as a temporary solution?

**Comment by mrstegeman** [comment]
@benfrancis What do you think? I think 1 decimal would probably be sufficient for a `number`, personally.

**Comment by benfrancis** [comment]
I think it's really impossible to pick a general rule which is appropriate for all numbers. Various approaches have been discussed in #1318

As far as temperature sensors go, many smart home temperature sensors are only rated to be accurate to within about ±2 degrees, in which case an integer seems fine. (There are of course more accurate sensors on the market).

There could be a difference between the precision exposed by the Web Thing API and what is displayed in the gateway UI. We could even show a more precise value in the detail view, or hover to show the original value.

**Comment by Nca78** [comment]
If a number is used and not an integer then we should at least have one decimal on the home page, it's really frustrating at the moment to see 28°C and not know if it's 27.5 or 28.4. One decimal on the homepage would give enough precision for temperature but also for many other cases (battery voltage, power, ...) for checking things with a click glance a the screen, without any click, scroll, ...
Regarding precision I'm using custom made sensors with si7021 and typical precision on temperature is +/-0.3°C, even cheap 10$ xiaomi sensors have a similar precision so having a decimal makes perfect sense.

**Comment by flatsiedatsie** [comment]
@benfrancis I believe the main issue here is this:

Properties can currently be set to either "integer" or "number".
- if a property is set to "integer" it should not show any decimals. But...
- If a property is set to "number", then it _should_ have at least one decimal. Otherwise the integer option would have been chosen.

In other words: a float should be displayed as a float, an integer as an integer.

This already works like this in most of the interface, where is a 'number' display is chosen the value is shown with 3 decimals (which is overkill, but that's another issue). It's just that if a TemperatureSensors capability is used, then a float is suddenly displayed as an int.

In the long run there could be a system to decide the optimal number of decimals to show for a float, instead of three. But for now I would take 3 decimals over no decimals any day.

**Comment by benfrancis** [comment]
@flatsiedatsie That's a fair point. The UI doesn't necessarily have to display the full precision provided by the API, though I agree for this particular example you could argue at least one decimal place would make sense.

**Comment by flatsiedatsie** [comment]
This is from a test using the pre-0.9 version.

![temperature-sensor](https://user-images.githubusercontent.com/805405/61328218-0d6e9100-a80a-11e9-98a3-d6ff22542b60.png)

I tried the new support for MultipleOf, and got some unexpected results. It seems like the temperature value is still hardcoded to show no decimals?

At the same time I set humidity to show no decimals on the percentage, but it shows it anyway?



```
            elif new_main_type == 6:                       # Temperature
                if new_sub_type == 0: # V_TEMP
                    self._type.append('TemperatureSensor')
                    self.properties[targetPropertyID] = MySensorsProperty(
                        self,
                        targetPropertyID,
                        {
                            '@type': 'TemperatureProperty',
                            'label': new_description,
                            'type': 'number',
                            'unit': self.adapter.temperature_unit,
                            'readOnly': True,
                            'multipleOf':0.1,
                        },
                    new_value, new_node_id, new_child_id, new_sub_type)

            elif new_main_type == 7:                       # Humidity
                if new_sub_type == 1 or new_sub_type == 37: # V_HUM
                    self._type.append('MultiLevelSensor')
                    self.properties[targetPropertyID] = MySensorsProperty(
                        self,
                        targetPropertyID,
                        {
                            '@type': 'LevelProperty',
                            'label': new_description,
                            'minimum': 0,
                            'maximum': 100,
                            'type': 'integer',
                            'unit': 'percent',
                            'readOnly': True,
                            'multipleOf':1,
                        },
                        new_value, new_node_id, new_child_id, new_sub_type)
```

Could it be that using a capacity/@type overrides the `multipleOf` setting?

**Comment by mrstegeman** [comment]
What are you currently testing with? Latest master? Are you testing on a development machine or on the RPi?

**Comment by mrstegeman** [comment]
This was really fixed by #1971. It's up to add-ons now to use `multipleOf` as appropriate.

I think the necessary UI code was not present in the build you're using.

**Comment by flatsiedatsie** [comment]
Then the beta build I'm testing on the Pi 4 must be incomplete.

**Comment by mrstegeman** [comment]
Yes, it definitely is. It was not intended to be an 0.9 beta. It was solely built to see if the RPi 4 worked properly.

**Comment by flatsiedatsie** [comment]
I understand, thanks! I'll wait patiently for the next version.
