### ISSUE TITLE
Things API for Add-ons

### ISSUE THREAD

**Issue by tim-hellhake** [mozilla-iot/gateway#1874]
Currently, an addon can only access its own devices.
An addon with read and write access to all devices would allow it to connect a variety of other systems like databases, message queues and to expose the devices to other front ends.
There are already issues which mention mqtt (https://github.com/mozilla-iot/gateway/issues/637) and node-red (https://github.com/mozilla-iot/gateway/issues/690).

**Comment by mrstegeman** [comment]
As a temporary solution, you could have the user generate an OAuth token and then use the web thing API on the gateway.

**Comment by benfrancis** [comment]
The purpose of an adapter add-on is really to bridge another protocol to the Web Thing API.

It might be that what you're looking for is a different type of add-on, like an [Extension Add-on](https://github.com/mozilla-iot/gateway/issues/1505) which extends the functionality of the gateway and can access the Web Thing API.

Plus, you can always create your own application which communicates with the Web Thing API, as @mrstegeman mentioned.

**Comment by tim-hellhake** [comment]
I assumed the Extension Add-ons would extend the UI, not the backend.
But if that's not the case then this might be what I'm looking for.

> The purpose of an adapter add-on is really to bridge another protocol to the Web Thing API

Exactly, but what's currently missing is the other way around.
It would be nice if the user simply could install another extension rather than starting an external application somewhere.

**Comment by mrstegeman** [comment]
This would be part of #1840.
