### ISSUE TITLE
How to send data from sensor to cloud

### ISSUE THREAD

**Issue by thomas-tri-tran** [mozilla-iot/gateway#1888]
How can the gateway send the sensor data to cloud such as Azure IOT hub or AWS services?

**Comment by tim-hellhake** [comment]
With https://github.com/mozilla-iot/gateway/issues/1874 this could be easily solved with a new addon

**Comment by tim-hellhake** [comment]
@thomas-tri-tran Which services would you like to use?

**Comment by thomas-tri-tran** [comment]
The azure iot hub

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tim-hellhake** [comment]
Sorry i meant AWS

**Comment by thomas-tran** [comment]
Hi Tim,

Actually, I need a guideline on how to call send the data from the sensor device to the cloud (Azure or AWS) either in MQTT or HTTPS.  

The scenario is the gateway is getting data from the Z Wave sensor device such as the motion sensor or door sensor. Once the state of the sensor device changed, the gateway will send the push the info into the local message queue. Another process will pick the message in the queue and send out to cloud server using MQTT or HTTPS.

Thomas

**Comment by hobinjk** [comment]
My recommendation would be to register a local token (accessible from the Settings page's Developer -> Create Local Authorization) then use this token in a script you have running locally. You could then drop in an MQTT library or calls to HTTPS posts based on changes to the device.

For example, here's a script I have lying around which listens for property changes through the WebSocket API:

```javascript
const gatewayUrl = 'https://hobinjk.mozilla-iot.org';
let wsUrl = gatewayUrl.replace('http', 'ws');
let hrefTrellis = '/things/neotrellis-0';
let wsTrellis = new WebSocket(`${wsUrl}${hrefTrellis}?jwt=${jwt}`);

wsTrellis.addEventListener('message', function(event) {
  console.log(event.data);
  let msg = JSON.parse(event.data);
  if (msg.messageType === 'propertyChanged') {
    if (msg.data.hasOwnProperty('color')) {
      sendColor(msg.data.color);
    }
  }
});
```

**Comment by thomas-tran** [comment]
Thats really helpful. Do we have the api to auto generate the token instead
of create manually?

**Comment by hobinjk** [comment]
@thomas-tran Yes, you can use an OAuth flow as described in the [voice control setup guide](https://github.com/hobinjk/commander/blob/master/README.md#oauth-client-setup) or you can use [a direct request to the login API](https://github.com/mozilla-iot/curl-examples/blob/master/login.sh) (requires the script to contain your username + password)

**Comment by tim-hellhake** [comment]
I developed an addon which mirrors the things to an Azure IoT hub: https://github.com/mozilla-iot/addon-list/pull/342

**Comment by thomas-tri-tran** [comment]
Very well done Tim.
