### ISSUE TITLE
Request action over WebSocket

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#189]
As a developer I want to request an action on a Thing over a WebSocket

**Comment by benfrancis** [comment]
@hobinjk Is this implemented? Per-thing action request messages over WebSockets? All the other initial WebSocket API user stories appear to be closed.

**Comment by hobinjk** [comment]
@benfrancis No, there is currently no API for per-thing actions. I can mock one up based on the current gateway action implementation then put in a corresponding WS API

**Comment by benfrancis** [comment]
@hobinjk OK thanks. No hurry, just trying to update the backlog with what is complete.

**Comment by hobinjk** [comment]
Closed by #407
