### ISSUE TITLE
Logs - for on/off switch, graph incorrectly reports it as "on" for long time when I scroll back in time

### ISSUE THREAD

**Issue by dholbert** [mozilla-iot/gateway#1892]
STR:

 1. Have a log configured for an on/off device which is mostly off & that you only ever turn on for a few minutes at a time.

 2. View the log graph and scroll backwards through time.

ACTUAL RESULTS:
When I scroll an "on" time-range offscreen, the previous (chronologically) time-range suddenly gets extended all the way to the visible end of the graph, suggesting (incorrectly) that the device was on for an extremely long time.

Screencast:
https://www.dropbox.com/s/1aw2g31cu8ta0x4/mozilla-iot-onoff-log.ogv?dl=0

**Comment by dholbert** [comment]
I'm using gateway version 0.8.1, and the on/off device here is a "Sylvania Smart Home 72922 Sylvania LIGHTIFY Smart Plug": https://www.amazon.com/gp/product/B01M6UM8QD/

**Comment by hobinjk** [comment]
Sorry for not responding earlier, this should have been fixed in f1badac27427104b324a1490b2b7aafcf91d0b15 which will be in the next release
