### ISSUE TITLE
Icons often show as dimmed even though everything works fine

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#1895]
We saw this numerous times at maker faire. All of the icons the yo works show as dimmed. While in this state we could intact with them fine.

**Comment by mrstegeman** [comment]
This is the ongoing issue with WebSockets failing to (re-)connect for long periods of time.

**Comment by benfrancis** [comment]
Note: This was specifically in Safari on iOS (well, and all the other browsers on iOS which use the same browser engine), and may have been quite an old Safari as the iPads weren't signed into an Apple account.

Out of interest, do we do any feature detection and fallback if WebSockets aren't supported at all?

**Comment by mrstegeman** [comment]
No, I don’t believe we do.

**Comment by dhylands** [comment]
I'm still seeing the issue occaisonally at home using Firefox under Linux (ie in the past few days)

The times I saw it doing a refresh or hard refresh still showed dimmed icons.

**Comment by mrstegeman** [comment]
The WebSocket issue remains through refresh. Next time, can you try restarting Firefox? That usually fixes it for me, and that would confirm my suspicions.

**Comment by dhylands** [comment]
I ran into this again and restarted firefox and they still showed up as dim
