### ISSUE TITLE
read-only OnOff switch looks exactly the same as a normal one

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#1901]
Perhaps this is by design, but the read-only OnOff property looks the same as a normal one.

Functionally it does work. The top of these two toggles cannot be toggled. But visually they are indistinct.

![read-only-looks-the-same](https://user-images.githubusercontent.com/805405/58131493-580acd00-7c0e-11e9-84d0-88b645739ff5.png)

**Comment by benfrancis** [comment]
We could probably improve this by giving the switch part of the icon 50% opacity when it is read-only.
