### ISSUE TITLE
Rules - read-only property shows up as changeable

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#1902]
I noticed in the rules interface that this read only property showed up as being changeable?

![read-only-can-change](https://user-images.githubusercontent.com/805405/58185455-a36ebb00-7ca2-11e9-90fa-6b9072188bcd.png)

I checked, and in practice the rule can't actually change the value. 

So perhaps it's a good idea to filter out read-only values from the list?

**Comment by hobinjk** [comment]
This appears to already work as of 69c353608c47b2d16761f0c7560d7f764d9a2ac6
