### ISSUE TITLE
Don't generate links for web things which don't have them

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1904]
Currently if you add a web thing by its URL and that web thing doesn't provide links for its properties/actions/events then we will generate links anyway in the version of the thing description proxied by the gateway.

I suggest that if no links appear in the original thing description we shouldn't create any in the proxied thing description, because they are referring to resources which don't actually exist on the back end.

Note that it could be valid for a thing description to provide no links for a property in the REST API, but for that property to be supported via the WebSocket API.

This might live in the thing URL adapter?

**Comment by mrstegeman** [comment]
These are used by the UI and such to find the proper endpoints for the device (which are in the gateway), since the UI doesn't communicate directly with the web thing (due to CORS and routing issues).
