### ISSUE TITLE
LevelProperty assumes range between 0 and 100 when highlighted.

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#1905]
![weird-thermostat](https://user-images.githubusercontent.com/805405/58232855-2555f700-7d2a-11e9-8fbf-cfc36ca5596c.gif)

There are two oddities in the GIF above:
- While the property on the left is a 'degree celsius' item that can go between 0 and 150, the center bubble shows a percentage.
- If the property on the left is set to above 100, the central bubble does not respond.

It could be that I'm using MultiLevel wrong. Here's the initialising code from the MySensors adapter for the item on the left:

```
            elif child.type == 14:                      # Heater
                if new_sub_type == 0: # V_TEMP
                    self._type.append('TemperatureSensor')
                    self.properties[targetPropertyID] = MySensorsProperty(
                        self,
                        targetPropertyID,
                        {
                            '@type': 'TemperatureProperty',
                            'label': new_description,
                            'type': 'number',
                            'unit': 'degree celsius',
                            'readOnly': True,
                        },
                    new_value, new_node_id, new_child_id, new_sub_type)
                if new_sub_type == 45: # V_HVAC_SETPOINT_HEAT
                    self._type.append('MultiLevelSwitch')
                    self.properties[targetPropertyID] = MySensorsProperty(
                        self,
                        targetPropertyID,
                        {
                            '@type': 'LevelProperty',
                            'label': new_description,
                            'minimum':0,
                            'maximum':150,
                            'type': 'number',
                            'unit': 'degree celsius',
                        },
                    new_value, new_node_id, new_child_id, new_sub_type)

                    # TODO: V_HVAC_FLOW_STATE. Mozilla Gateway has no support for a multiple-buttons type yet?

```

[Looking at the schema](https://iot.mozilla.org/schemas/#LevelProperty) I found no indication that a LevelProperty is clamped between 0 and 100.

**Comment by mrstegeman** [comment]
This is a problem in the implementation. The UI assumes that a multi-level switch has a 0-100% LevelProperty, which is invalid. The following code will need to change:

https://github.com/mozilla-iot/gateway/blob/master/static/js/components/capability/multi-level-switch.js
