### ISSUE TITLE
Create multi-toggle

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#1908]
This is a proposal for a property that allows the user to select a certain value by clicking a button / selecting it from a dropdown.

An example would be a smart heater which lets users switch between "high", "normal" and "economy" mode. But there are all kinds of uses for this.

Here's an example from Domoticz:
![Screen Shot 2019-05-23 at 09 59 27](https://user-images.githubusercontent.com/805405/58236475-808be780-7d32-11e9-837b-85250224542f.png)

- The best UI for this is to show all options as a small button, so that a change is one click away. Considering the space constrained octopus interface in the WebThings Gateway, perhaps a drop-down UI element would fit better.

- Another question for the future would be: how to let people select multiple options at once. But this scenario might already be covered by just creating many binary toggle properties.

I'd call this multi-level-switch, but it's already taken :-)

Once way around this property is to create an on-off toggle property for each aspect. For example:
- HIGH on off
- NORMAL on off
- ECONOMY on off

But this would allow users to enable "normal" and "economy" at the same time. In theory the add-on could then disable the other options. But it all just feels bulky and unwieldy. A Multi-Level-Toggle could streamline this, and would bring the gateway in line with other systems that support this UI element.

**Comment by mrstegeman** [comment]
You can already do this. :smiley: 

```json
{
  "type": "string",
  "title": "Mode",
  "enum": [
    "High",
    "Economy",
    "Normal"
  ]
}
```

**Comment by mrstegeman** [comment]
This doesn't cover the multi-select option, but you could theoretically do that by creating more options for the user with valid combinations.

**Comment by flatsiedatsie** [comment]
That's great!
