### ISSUE TITLE
Zigbee2mqtt Support

### ISSUE THREAD

**Issue by s3rvant** [mozilla-iot/gateway#1910]
Would love to see an adapter for Zigbee2mqtt to support devices such as the Xiomi and Aqara series

**Comment by benfrancis** [comment]
Unless I've misunderstood, this sound out of scope for a gateway adapter. The purpose of gateway adapters is to bridge an existing protocol to the Web Thing API, not to bridge from one existing protocol to another.

Some Xiaomi devices should already work with the existing Zigbee adapter, though they are known to be unreliable.

Please re-open if I misunderstood the request.

**Comment by benfrancis** [comment]
I just spotted this thread https://discourse.mozilla.org/t/orvibo-zigbee-smartrelay-support/40765

So I think maybe you're talking about an adapter which can bridge a [zigbee2mqtt bridge](https://github.com/Koenkk/zigbee2mqtt) to the Web Thing API. That would be in scope (though I'd personally recommend pairing the Zigbee devices directly with the gateway).

**Comment by kabbi** [comment]
Until this is properly resolved, here is my small addon I made for myself to control xiaomi devices. Feel free to check it out and add support for your specific devices.
https://github.com/kabbi/zigbee2mqtt-adapter

**Comment by flatsiedatsie** [comment]
@kabbi do you intend to turn that into an official add-on?

**Comment by mrstegeman** [comment]
I'm going to close this. Anything supported by zigbee2mqtt should also be supported (or _can be_ supported) by our official Zigbee add-on.

**Comment by zx-ecco** [comment]
zigbee2mqtt supports the extremely cheap c2531, something the mozilla webthings gateway still doesn't

**Comment by flatsiedatsie** [comment]
I recently spoke to someone who repeated that this device supports many more devices than the commercial USB sticks.
