### ISSUE TITLE
Latest version won't boot into GUI

### ISSUE THREAD

**Issue by chiperic** [mozilla-iot/gateway#1927]
0.8.1 flashed to 16GB sdcard, Pi 3 B+ version. 
Everything looks good until the end and it displays the login prompt. I can login with pi/raspberry but I thought it was supposed to log into the GUI? Can't find any documentation on how to get past this. Any help is appreciated.

**Comment by flatsiedatsie** [comment]
There is no Linux GUI in the image. You open the interface by visiting the IP address (or 'gateway.local') via a browser on another device.

You can install a GUI if you want, and then boot into that.

**Comment by eduardocampano** [comment]
Not sure if this is related, but the web interface doesn't load for me

![image](https://user-images.githubusercontent.com/166483/59122438-247bb280-8931-11e9-91b7-63814a67196f.png)

**Comment by benfrancis** [comment]
Please see the [Getting Started Guide](https://iot.mozilla.org/docs/gateway-getting-started-guide.html) for first time setup (as @flatsiedatsie says, the Raspberry Pi image is headless and hosts a web interface).

@eduardocampano: That's an unrelated issue. Is this right after first time setup or has it loaded before? Does a hard reload fix this?

**Comment by eduardocampano** [comment]
@benfrancis will open a new issue, keep getting the same error
