### ISSUE TITLE
Add-ons Search

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1932]
As a user I'd like to search for an add-on (by its name and description) so that I can more quickly find the add-on I'm looking for.

The add-ons directory is starting to get quite long, we are soon going to need a way to search it!

**Comment by mrstegeman** [comment]
Back-end is available here: https://github.com/mozilla-iot/addon-proxy/pull/8

**Comment by hobinjk** [comment]
I think this would be a good way to preserve the accessibility of OS level software packages like the voice-addon by putting them under a hidden-by-default "Advanced"/"Stand-alone Software" category

**Comment by mrstegeman** [comment]
"Stand-alone" software should probably not be installable as an add-on. You'd want some UI for apt/opkg.

**Comment by hobinjk** [comment]
Hmm yeah that's fair.

I think what would be ideal here is an extension add-on which adds an apt/opkg UI with a list of recommended packages.

**Comment by createcandle** [comment]
![gateway_addons_search_filter](https://user-images.githubusercontent.com/39312291/84114985-9186c400-aa2d-11ea-88ef-559dd2c4d76e.png)

Going back to the original question of this issue, a basic clientside search filter option (type a letter and only add-ons titles that have that letter in it are left, etc) might be easy to make, and is really starting be get useful. The addon list really is getting very long. Especially scrolling on a touch screen is getting quite cumbersome.

**Comment by tim-hellhake** [comment]
@createcandle I created a draft for client-side filtering, but the UI looks awful right now.
Would you mind sharing your example?
If you send me a PR to my gateway repo, I'll merge it into my draft branch.

**Comment by tim-hellhake** [comment]
@createcandle @flatsiedatsie Ping

**Comment by flatsiedatsie** [comment]
The picture I posted was just a photoshop :-)
