### ISSUE TITLE
[OpenWrt] Consider disabling "Enable Wi-Fi" checkbox for Raspberry Pi

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1934]
Currently in OpenWrt builds there's a checkbox in Network Settings for "Enable Wi-Fi". This makes sense for a router where you may connect to the gateway via Ethernet, but on a Raspberry Pi where the only Ethernet port is configured as a WAN port, I can't think of any way this is useful. If you uncheck the box you'll no longer be able to access the web interface.

Should we consider detecting when running on a Raspberry Pi and disabling this checkbox to remove this obvious foot gun?

**Comment by mrstegeman** [comment]
@benfrancis is this something we want to do for 0.9 or not?

**Comment by benfrancis** [comment]
@mrstegeman If we're not going to promote the OpenWrt builds for Raspberry Pi then this is less of an issue. So far it looks like we're not, so no. But if the Turris Omnia build isn't ready in the 0.9 timeframe then it's possible we could have to re-visit that decision and end up needing it.
