### ISSUE TITLE
[OpenWrt] Zigbee add-on not working

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1939]
Testing the latest OpenWrt-based build on Raspberry Pi, I can get Z-Wave dongles to work, but not a Digi XStick Zigbee dongle.

I can install and stop/start the add-on, but a Zigbee adapter never appears in the adapters list.

**Comment by dhylands** [comment]
This should be fixed on 0.7.11 (I was able to use the Zigbee adapter under OpenWRT).

The problem was related to the recent security fixes, and for some reason, npm was failing to bundle one of the modules into the zigbee adapter package.

**Comment by mrstegeman** [comment]
Closing. Re-open if we have more issues.
