### ISSUE TITLE
On firefox mobile I get always "A network error occurred"

### ISSUE THREAD

**Issue by negrival** [mozilla-iot/gateway#1940]
Two days ago I had a problem on my router and i have lost connection, so I was not able to run the gateway via web but also on local nework.
I tried to open gateway on my phone with firefox using https://ip:4443 and I get network error:
A network error occurred

After solving the router problem everything started working again except firefox on my mobile phone, i still get network error.
How can I solve?

**Comment by benfrancis** [comment]
@negrival Are you still having this problem? Does a hard reload in the browser help?

**Comment by negrival** [comment]
After clear cache and cookies it work again.
