### ISSUE TITLE
Adding a device with  TemperatureProperty without unit not possible

### ISSUE THREAD

**Issue by klausahrenberg** [mozilla-iot/gateway#1941]
Tried to create a TemperatureSensor and add a Property for temperature:
```c++
WebThingProperty* actualTemperature = new WebThingProperty("temperature", "Actual measured temperature", NUMBER, "TemperatureProperty");
device->addProperty(actualTemperature);
```
Then I tried to add this to the gateway. Device was not automaticly detected and also adding by a link found the device but saving failed without any reason. If I removed the `TemperatureProperty` adding was possible and all was working fine. After looking at the examples at [https://github.com/mozilla-iot/webthing-arduino/blob/master/examples/PlatformIO/BME280/src/BME280.cpp](url) my code missed to define a unit for the property. After adding 
```c++
actualTemperature->setUnit("celsius");
```
I was able to add the device.
Expected behavior is that adding of a device with properties without units should be possible or, at least, the gateway should give an error message that one of the properties is not completely defined by the device. Actual the gateway is quitting the task without any feedback.
To reproduce this issue, run the example code at [https://github.com/mozilla-iot/webthing-arduino/tree/master/examples/PlatformIO/BME280](url) without the statement
```c++
weatherTemp.unit = "celsius";
```
at line 125 in file `BME280.cpp`

**Comment by mrstegeman** [comment]
This seems to be working fine now.
