### ISSUE TITLE
Add by URL ipv6 not working

### ISSUE THREAD

**Issue by yamennassif** [mozilla-iot/gateway#1944]
I have virtual things for some experiment and i can only access them via IPv6 address since my router doesnt support IPv4 port forwarding. So when I tried to add a new thing using Add by URL and then trying to use ipv6 address it keeps on loading forever. and even inspecting the browser i can see in the network tab that new_thing POST request is never finished.

Not a fail or a success or anything.

P.S IPv4 is working just fine.

**Comment by hobinjk** [comment]
Trying this locally with `http://[::1]:8888/0` I was able to add a thing without any issues. What's the format of the address that you've been trying?
