### ISSUE TITLE
Toggleable "group chat" view for assistant page

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/gateway#1953]
As a user I want to see my entire assistant history in one place but I don't want to be confused or overwhelmed when first visiting the assistant page.

Basic idea is to press a button (maybe in an overflow menu somewhere) and get this:
![group chat](https://user-images.githubusercontent.com/2776089/59888032-8baa5580-937a-11e9-841a-2cec5d95e892.png)

**Comment by benfrancis** [comment]
My general opinion (expressed elsewhere) is that chat history should be per-client, partly for privacy reasons.

**Comment by mrstegeman** [comment]
I’m in agreement with @benfrancis.
