### ISSUE TITLE
Rules - Invalid rule when trying to use percentage property

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#1957]
I'm trying to make this rule. For some reason it fails. 

![rule_unknown-error](https://user-images.githubusercontent.com/805405/59944408-3f334880-9454-11e9-8b56-c7f3ff912455.png)

The first property is just a numerical value, and the second is a generic percentage number set to a certain level.

Everything goes well at first, but when I close the rule editing screen it shows are invalid:

![rule-result](https://user-images.githubusercontent.com/805405/59944425-44909300-9454-11e9-817d-0493c8ca04b5.png)

My first thought is that you can't make a rule when the device is both the originator and the target. But then I remembered I already have another device with rules like that which work fine.

I tested it, and other rules that use the device as origin and target work ok, so it seems it's more about the combination of these properties.

Some more testing makes it look like it's most that second property that is throwing a spanner in the works. For example, I created a button -> binary output rule. Then I tried to modify it into a button -> percentage version, and this happened:

![rule-experimen-2](https://user-images.githubusercontent.com/805405/59945016-d2b94900-9455-11e9-9650-f186e6351b36.png)

Became:

![Screen Shot 2019-06-21 at 20 46 53](https://user-images.githubusercontent.com/805405/59945090-0a27f580-9456-11e9-87fd-1ff6c707ccb8.png)

So it reverted back to the previous version there the target was a binary output.

Trying that percentage-dimmer as the first variable immediately fails:

![rules-strange-3](https://user-images.githubusercontent.com/805405/59945190-625ef780-9456-11e9-843b-e024b07d0a33.png)

Here's the Python code in the MySensors adapter that generates the percentage property:

```
                if new_sub_type == 3: # V_PERCENTAGE
                    #self._type.append('Light')
                    self.properties[targetPropertyID] = MySensorsProperty(
                        self,
                        targetPropertyID,
                        {
                            #'@type': 'BrightnessProperty',
                            'label': new_description,
                            'minimum': 0,
                            'maximum': 100,
                            'step': 1,
                            'type': 'integer',
                            'unit': 'percent',
                        },
new_value, new_node_id, new_child_id, new_sub_type)
```

And finally here's the HTML:

```
<div class="property-select-option selected" data-rule-fragment="{&quot;effect&quot;:{&quot;type&quot;:&quot;PulseEffect&quot;,&quot;property&quot;:{&quot;title&quot;:&quot;Servo control 1&quot;,&quot;type&quot;:&quot;integer&quot;,&quot;unit&quot;:&quot;percent&quot;,&quot;minimum&quot;:0,&quot;maximum&quot;:100,&quot;name&quot;:&quot;38-7-3&quot;,&quot;id&quot;:&quot;38-7-3&quot;,&quot;thing&quot;:&quot;MySensors_38&quot;},&quot;value&quot;:50,&quot;label&quot;:&quot;Servo control 1&quot;}}"><span class="property-select-name" title="Servo control 1">Servo control 1</span><input class="value-input" type="number" step="1" min="0" max="100"></div>
```

**Comment by hobinjk** [comment]
Sorry about this! The behavior will be fixed by #1962 but in the meantime changing the type from 'integer' to 'number' will work around it.
