### ISSUE TITLE
add to homescreen on local IP 

### ISSUE THREAD

**Issue by vincentserpoul** [mozilla-iot/gateway#1967]
I have Android with firefox and chrome.
I also have iot gateway (0.8.1) with a fwding url https://xxx.mozilla-iot.org/things

I wanted to use the IP directly, in order to speedup things when I connect to the gateway at home.
It works well BUT on the certificate of the https is not valid (obviously and that's not an issue).

That certificate invalidity seems to prevent firefox android to add to homescreen on android (it works well with the fwding url).
It works on Chrome though, but I feel a bit sad about that.

**Comment by mrstegeman** [comment]
I'm assuming this is just a limitation of Firefox. The [docs](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Installable_PWAs) say that PWA must "be served from a secure (HTTPS) domain". Probably the invalid certificate breaks that criteria.

**Comment by vincentserpoul** [comment]
I guess we can't do antg then
