### ISSUE TITLE
List Notifier Add-ons

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1973]
As a user I would like to be able to differentiate between adapter add-ons and notifier add-ons so I know which are which

Part of #1758

UI mockup:
![add-ons](https://user-images.githubusercontent.com/552417/60293864-14476980-9918-11e9-82c8-3e04f14bae00.png)

Note: Adapter icon used for adapter add-ons, notifier icon used for notifier add-ons.

**Comment by mrstegeman** [comment]
I actually don’t think this is valid, since add-one can be both notifiers and adapters (and extensions and services).

**Comment by benfrancis** [comment]
I think we have to have an add-on pick a primary type in order for us to categorise them in the add-ons directory, and for users to differentiate between them.

Similarly, Firefox has extension, theme, plugin, dictionary, language and search add-ons which each have their owns section at addons.mozilla.org

**Comment by mrstegeman** [comment]
Is that still true? I don't see anything like that in the `manifest.json` spec: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json

**Comment by benfrancis** [comment]
It's definitely still true because they're clearly categorised both within Firefox and in the add-ons directory. I haven't checked but I suspect that Web Extensions are only used for extension add-ons.

**Comment by mrstegeman** [comment]
I know they're still categorized, but I'm trying to understand how that's done. Since we're planning on moving to the `manifest.json` format, it would make sense to follow that standard to some degree.
