### ISSUE TITLE
Configure notifier as rule output

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1974]
As a user I would like to use different types of notification provided by notifier add-ons as the output of a rule.

Notifier outputs may specify a title, message and level (Low, Medium or High).

Part of #1758

UI mockup:
![notifer_rule_output](https://user-images.githubusercontent.com/552417/60293763-d0ecfb00-9917-11e9-8c10-731fe6ce9a96.png)

**Comment by hobinjk** [comment]
What is the intended interaction for closing the popup? My first thought is to make any click on the popup that isn't hitting an input close it but that isn't really visible or particularly intuitive. I could also keep the triangle around and use that as a close button

**Comment by hobinjk** [comment]
<img width="312" alt="notifier outlet block closed" src="https://user-images.githubusercontent.com/2776089/60607923-3c0d5600-9d8c-11e9-938b-a843a40f93ad.png">
<img width="319" alt="notifier outlet block open" src="https://user-images.githubusercontent.com/2776089/60607924-3c0d5600-9d8c-11e9-8cc8-83152d1d0a81.png">

**Comment by mrstegeman** [comment]
Fixed by #2002
