### ISSUE TITLE
Disabling/Enabling adapter sometimes doesn't work

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#1979]
What I've observed is that if I disable and re-enable the adapter (perhaps quickly) that I'll sometimes get all of the thingAdded notifications BEFORE getting thingRemoved notifications. This then makes the gateway behave like there are no things for that particular adapter.

I have a suspicion that the thingRemoved notifications might not be getting delivered when disabling the adapter, and might be stuck in a queue someplace. It still doesn't make sense why the added notifications would come before the removed notificatons, but I've seen this behaviour several times.

**Comment by tim-hellhake** [comment]
That explains why reloading the Äffin by disabling/enabling fails most of the times...

**Comment by dhylands** [comment]
If you wait a few seconds between disabling/enabling then it doesn't seem to happen.

I notice it because I almost always run the gateway with the -d flag, which has some code enabled here: https://github.com/mozilla-iot/gateway/blob/f169b13a69e4ccab1a16eb17b8e5c58a792d5ca3/src/controllers/debug_controller.js#L24-L32 which prints the added/removed notification.

**Comment by mrstegeman** [comment]
Fixed by #2180.
