### ISSUE TITLE
Assistant behaves odd when device is already in desired state.

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#1983]
![assistant_responses](https://user-images.githubusercontent.com/805405/60501028-d9905900-9caa-11e9-9f91-b38d69cf7cdb.png)

The assistant DOES respond immediately when it doesn't understand something. But when I asked it to turn on a device that was already on, it doesn't say anything. Then when I asked it to turn the device off, it suddenly shows all the earlier responses all at once.

Expected behavior when a device is already on:
- Say "That device is already on" or
- Say "OK, turning on".

**Comment by mrstegeman** [comment]
This is actually adapter-specific, so if you are having troubles with a device from a specific adapter, we should tackle it there. For instance, I just recently fixed this bug in the Web Thing add-on here: https://github.com/mozilla-iot/thing-url-adapter/pull/83
