### ISSUE TITLE
Assistant - add support for toggling / reading any property

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#1984]
I have a [device that can 'clone' any 433 signal](https://forum.mysensors.org/topic/10094/candle-signal-hub-a-universal-433mhz-signal-detector-and-cloner). It learns the on and off code from a remote control once, and then you can replay those codes again using the Gateway.

![signal-hub](https://user-images.githubusercontent.com/805405/60502088-a222ac00-9cac-11e9-851b-dbf55f417bc2.png)

I believe manipulating properties isn't supported yet, and only capacities are supported. Still, I was trying to toggle these properties using the assistant. I saw some behavior that was inconsistent.

![signal-hub-assistant-odd](https://user-images.githubusercontent.com/805405/60502148-c1b9d480-9cac-11e9-94b1-fc95620af20c.png)

As far as I can tell it seems it reverts to the capacities, as expected. But it only does this when calling the first property, and not the second, which was unexpected.

Now that I think about it some more, I believe I understand what's going on. This must be because the Gateway has selected the second toggle as the 'dominant' one.

So this must be the same situation I came across earlier where having multiple on-off toggles leads to a random one being the 'main' toggle when each property is given the OnOffProperty. 

Perhaps as soon as a second on/off signal is copied I should remove the entire OnOff capability for this device to avoid any confusion on the user's part. But removing if would in itself be confusing to the user. Hmm. I still wish devices that don't / can't conform to capabilities would get some more love.

Anyway, this isn't so much an issue now.

// No, it's even simpler. It just ignores the property value. So it was simply ignoring the request to turn on a device that was already on, as [mentioned in the other issue](https://github.com/mozilla-iot/gateway/issues/1983).

In that sense, the name of this issue is still relevant: it would be great if properties could be toggled (or read), even if those properties do not conform to capabilities.

**Comment by dhylands** [comment]
What I've typically done for things like this, is to pick one and give it say the OnOffProperty, and make the rest be BooleanProperty.

Perhaps we need something that would allow OnOffProperty to be used, but have a way to indicate that it's a secondary or primary so that the UI would ignore the secondary OnOffProperties

**Comment by benfrancis** [comment]
> Perhaps we need something that would allow OnOffProperty to be used, but have a way to indicate that it's a secondary or primary so that the UI would ignore the secondary OnOffProperties

Yes, you should certainly be able to annotate multiple OnOffProperty properties in the Thing Descriptions. It's just tricky to represent in the GUI and the VUI without adding a lot of complexity.

**Comment by flatsiedatsie** [comment]
In my opinion the whole "things can only have one centered thing to display" is like painting yourself into a corner. If the user would be allowed to create a [dashboard of their favorite properties](https://github.com/mozilla-iot/gateway/issues/1597#issuecomment-486807585), then the whole concept of capabilities -and which property should be centered- might become less important.

From my perspective it would remove complexity, and empower the user at the same time. I would increase flexibility, since the inevitable long tail of devices that don't fit the capabilities molds could be displayed usefully. I'd go even further and estimate that 80% of my mainstream devices could not be boiled down to a single dominant property.
