### ISSUE TITLE
Unable to detect wifi

### ISSUE THREAD

**Issue by thomas-tri-tran** [mozilla-iot/gateway#1994]
The gateway is unable to detect the enterprise wifi e.g WPA2-EAP or Wifi that required user to accept the term and condition.

**Comment by benfrancis** [comment]
I don't know where exactly the limitation with WPA2-EAP is coming from, but for the case where terms and conditions need accepting, it could be challenging to connect to a Captive Portal from a Captive Portal... not sure how best to achieve that.

**Comment by thomas-tri-tran** [comment]
Hi Ben,

This issue was, for enterprise wifi , you are required to install the trusted certificate and the gateway seems unable to detect the network without the certificate installed.

Regards
Thomas

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by benfrancis** [comment]
I see, thank you for the additional information.

To be honest enterprise Wi-Fi is not a priority use case for a smart home hub, but being able to connect to these kinds of networks does also help make our demos run more smoothly so if there's anything we can do to make this easier we will. Perhaps there's a way to manually install the certificate on the command line...

**Comment by createcandle** [comment]
I had a similar situation yesterday.

![no_wifi](https://user-images.githubusercontent.com/39312291/69958233-a1fd3580-1504-11ea-8614-b13f6128f32d.png)

Clicking `next` leads to a very odd situation. While I was still connected to it in hotspot mode, I could access SSH and found this is the entry in the WPA file:

![undefined](https://user-images.githubusercontent.com/39312291/69958281-be996d80-1504-11ea-8177-5fcc3b28143f.png)

I created a new image to see if the image was the issue, but got the same situation. It must have been a hardware issue (or the strange wifi at the location I was at). In this case after clicking 'next' on an empty list I could no longer access the device in any way.

This is another example where it would be useful if the device went back into hotspot mode if (1) no connection is made to its setup page and (2) the device is then reset.
