### ISSUE TITLE
plus and voice buttons overlap scrollbar

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#1997]
Noticed this while creating an 800X600 touchscreen kiosk for an exhibit:

![buttons-on-scrollbar](https://user-images.githubusercontent.com/805405/60814790-d6530c80-a185-11e9-9f48-8cf037eff4ba.png)
The round buttons overlap the scroll bar

Firefox on Raspbian Jessie

**Comment by benfrancis** [comment]
I can also reproduce this on Firefox (ESR) on Raspbian Buster.

It shouldn't be possible for the browser to render outside its viewport so this looks like a bug in Firefox or Raspbian. I suggest filing an issue [here](https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox).

**Comment by mrstegeman** [comment]
My guess is that it’s an issue with the GTK theme.

**Comment by flatsiedatsie** [comment]
@benfrancis done

**Comment by benfrancis** [comment]
Thanks!

**Comment by Darkspirit** [comment]
= https://bugzilla.mozilla.org/show_bug.cgi?id=1564579
