### ISSUE TITLE
Cancel the registration of a subdomain to make it available to someone else?

### ISSUE THREAD

**Issue by grbesd1** [mozilla-iot/gateway#2004]
Hi Guys,

I'm working on mozilla iot. I need to Cancel the registration of a subdomain. So I can register subdomain with another e-mail id.  How can I cancel/revoke the certificate for a subdomain?

**Comment by benfrancis** [comment]
We don't have a UI for that yet, but if you email us at iot@mozilla.com with the domain you want to transfer we will confirm with the email the domain is registered with and may be able to do this manually for you.
