### ISSUE TITLE
addons - Boolean settings don't have a title on the settings page

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#2016]
![settings-title-missing](https://user-images.githubusercontent.com/805405/61329095-03e62880-a80c-11e9-9e3f-6772f6b67cfa.png)

String items have a title, but boolean items do not. This leads to confusing situations if a boolean follows a string. Then it looks like the boolean help text is the help text underneath the string box.

![settings-title-missing2](https://user-images.githubusercontent.com/805405/61329101-09437300-a80c-11e9-97f6-e262d8861f4b.png)

Perhaps it would be best to treat all settings items the same, and give them all a title?
Alternatively, show the help text underneath the checkbox?

This is on version pre-0.9

**Comment by mrstegeman** [comment]
Well, they _do_ have titles, but the placement is different. They're placed next to the checkbox, instead of above the input. I agree that this is inconsistent, though.

**Comment by flatsiedatsie** [comment]
I'd say that's a label and not a title? (HTML-wise). And even then why is the explanation text _above_ the 'title'?

I do agree it would give some duplication if it were added, as the title and label would be the same. Still, I think that's worth it.
Alternatively, more spacing, placing the text below the checkbox, or a HR could maybe help separate the inputs.
