### ISSUE TITLE
Unable to reclaim my tunnel id

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#2019]
Once the Wifi is setup, and you get reconnected, you get automcatically redirected to the tunnel setup.

I then tried to use an existing name, and clicked on the "Click here to reclaim it" link. On my iPhone as soon as I switch away from the captive portal login, it disconnects me from the Wifi and reconnects to my regular Wifi. Of course, once I get the code and go back thru the Wifi Setup, I have to click the "Click Here" link again which generates a new code and the cycle continues.

**Comment by dhylands** [comment]
I think that there should be an option to generate a new code (the existing click here) and another link to enter a code without generating a new one.

**Comment by mrstegeman** [comment]
That doesn't necessarily sound like a limitation of the gateway, more just a poor captive portal implementation on iOS. iOS is assuming that, since you left the captive portal screen, that you're connected now.

**Comment by dhylands** [comment]
You may need to change the Wifi anyways in order to get to your email client, so you can copy/paste the recovery ID. THe only way I've been able to get this to work is to use a second device to get my email, and manually type in all of the digits of the recovery code.

**Comment by mrstegeman** [comment]
This is one of the drawbacks of the secondary captive portal...

**Comment by benfrancis** [comment]
I had the same problem on Mac OS. Couldn't check my email to get the token because captive portal is active and blocking DNS lookups.

I'm struggling to think of a good solution to this which doesn't complicate the UI, short of having shorter (less secure) codes so the user can more easily use a secondary device and type them in. Not ideal.

@dhylands wrote:
> I think that there should be an option to generate a new code (the existing click here) and another link to enter a code without generating a new one.

Not sure I understand what you mean. Can you explain further?

**Comment by dhylands** [comment]
Then I can click on the "Click here" to generate a recovery code, switch WiFi back to my regular Wifi Copy the code from my email, and then switch back to the gateway. This will restart the process and now that I have a code in the clipboard, I need a place to be able to enter it. I can get to the screen which has "Click here" to generate a recovery code, but that winds up invalidating the code that I now have in the clipboard.

**Comment by benfrancis** [comment]
OK, I understand, thanks. That's quite a complicated process to explain to the user. In the short term I propose #2034
