### ISSUE TITLE
After entering the SSID and password during wifi setup, the captive portal should say Done rather than Cancel

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#2021]
This is pretty minor, but I noticed that after entering the Captive portal information, the screen says Cancel in the top right corner, rather than Done.

**Comment by benfrancis** [comment]
@dhylands Is this part of the gateway UI (web interface) or the client OS-provided native UI? If the latter, what operating system are you using?

In the gateway UI there's supposed to be a create button on the "Create a new Wi-Fi network" page, but no cancel or done button.

**Comment by dhylands** [comment]
I'm using an iPhone xR. The Cancel/Done shows as part of the native UI, and not part of the web ui. I noticed that other captive portal sites I use, that the Cancel changes to Done once you've gotten the captive portal setup.

**Comment by dhylands** [comment]
You can see the Cancel button in the screen shot in #2020 (to the Right of Login)

**Comment by mrstegeman** [comment]
I'm not sure how the iOS captive portal logic works. I'm assuming it periodically does a DNS lookup for their captive portal website and switches to "Done" when it works properly.

**Comment by dhylands** [comment]
Yeah - it looks like the change is done by the client. I thought maybe it was something that the captive portal controlled.
https://community.arubanetworks.com/t5/Controller-Based-WLANs/Apple-CNA-take-a-long-time-to-change-the-Cancel-Button-to-Done/ta-p/267612

It seems at most of the hotels it changes fairly quickly, but this might be because they typically redirect you to their reservation system or something similar once you get connected.

**Comment by mrstegeman** [comment]
So it seems like this is probably not something we can fix directly, right?

**Comment by dhylands** [comment]
That may very well be the case. Closing for now.
