### ISSUE TITLE
Feature request - locally connected touch screen support

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#2022]
Smart home controllers with a touch screen are becoming quite popular. Nowadays you don't need to hide your IoT controller in a broom cupboard like in the days of old. It's becoming a first class citizen in the home, acting more like a smart phone. 

An example is the Google Home Hub.

Smart home controllers with a built in touch screen have a lot of advantages.
- Make use of the processing hardware that is available in the controller anyway, and put it to additional use besides managing data flows with just a small monetary investment.
- It jives with how humans operate - they are used to having functionality located at specific nexuses in their home (e.g. light switches). Ambient smart systems, on the other hand, often have an affordability issue: users don't know that they can do and what is going on at any time. Having a fixed focal point for smart home functionality gives a feeling of overview, instant accessibility and control.
- Voice control is great, but voice feedback is not a good way to show more complex data like images or graphs. When voice and a screen are combined, users can use their voice to ask the system to show data on the screen. If there is a fixed place with a screen, it makes the smart home more 'glance-able'.
- It's more resilient. When a controller has a self-contained input device, there is no longer a requirement to connect to a local network or setup a wifi hotspot to interact with it. It still works fine when the router is down. This leads into:
- It opens the door to support more privacy and security sensitive use cases. In my opinion the use of TCP/IP to connect smart devices should be kept to an absolute minimum. Creating a situation where the user does not need to connect their smart phone or tablet to the same network as their smart devices ecosystem is a very effective way of decreasing the attack surface. The current crop of cheap IoT devices has made the smart home a juicy target. Smart homes need a digital counterpart to the blood-brain barrier.
- There is an opportunity for convergence and innovation. Google's home hub has a great built in picture frame functionality. Since a digital picture frame can cost quite a lot of money, users can be persuaded to pay for the additional touch screen by creating the narrative that when they get the touch screen controller they are also getting a picture frame for free. There's a lot of synergy to be had, since both are always on, have a fixed place, are glance-able, and act as a nexus in the mental map of the home.

Tablets and phones cannot operate in the same way.
- Phones cannot have their screen turned on on command, have tiny screens (try making an automation rule on it) that are not glance-able from across the room, and their do not easily allow for quick one-handed operation (during cooking for example), and can be unavailable. On top of this, having a second dedicated screen allows for more complex/parallel interactions. Imagine a user that is talking on the phone and that wants to open the smart lock by entering a pin code at the same time. With a mobile phone the user would have to leave the conversation. 
- Tablets have mostly the same issues as phones, except for the screen size. Like phones, controlling the home is not their primary function, and thus situations can arise where they are unavailable for that task. Tablets are often used as media consumption devices by family members. On top of being in use, the resting location of a tablet is not always known. This does not allow for optimal 'glance-ability'.

FEATURE REQUEST
It would be great if the Mozilla WebThings Gateway would have an easy way of enabling a locally attached touch screen. For example, through a kiosk-mode Firefox browser on a Linux desktop.

Implementation cost should be relatively low: I already have this running, although I was unable to get Firefox to run in Kiosk mode, and had to use Chrome. All that's missing is a user friendly "one click" way of setting it up.

USER STORY
- As a user, I'd like to have an always available, predictably located and glance-able way of interacting with my smart home.
- As a user I'd like my smart home controller to feel like a 'good deal' because it converges with other electronic devices in my living space (e.g. picture frame).
- As a user I want to be convinced that privacy and security are well protected, and as such I'd like to separate my personal network (laptop, phone, NAS, tablet) and the smart devices network as much as possible. Therefor I'd like a method for more complex interactions with the system that does not require me to (permanently) make my devices available to it.

GOING FORWARDS
I could create an add-on that hacks this functionality in. But since this feels like such a valuable bit of functionality, I wanted to appeal to make this core functionality that is built into the WebThings Gateway itself.

FUTURE OPPORTUNITIES
Over time it would be interesting to explore if add-ons, especially ones that can extend the UX, could turn on the screen and display information through some api call.

**Comment by benfrancis** [comment]
Hi @flatsiedatsie, thanks for sharing this idea.

A touch screen client is outside of the scope of the WebThings Gateway project, which is a server for headless devices like wireless routers (e.g. running OpenWrt, which does not have good touchscreen support). The client part is being addressed through a separate [things-controller](https://github.com/mozilla-iot/things-controller) project designed for touch screen controllers.

If you were to create a touch screen web client for Raspbian then you could install both the client and server on the same Raspberry Pi to create a combined DIY device, that's just not the product we're currently building at Mozilla. I wouldn't recommend building this as an add-on (it's not what adapter add-ons or notifier add-ons are intended for so may be rejected), but it could be built as a separate piece of software which could be installed on the same device but maintains a clear separation of concerns.

FWIW, in addition to [things-controller](https://github.com/mozilla-iot/things-controller) which is based on Android Things and GeckoView with Gecko's Android widget layer, I have also recently been experimenting with Gtk (desktop) builds of Gecko using the `MOZ_USE_XINPUT2=1` environment variable to enable touch-based scrolling, which works in Firefox ESR in Raspbian. This is nowhere near as well supported as the Android widget layer and you need to manually configure X11 to hide the cursor. It is apparently slightly better supported under Wayland (used by default by Fedora), but Wayland doesn't currently work on the Raspberry Pi.

Shipping a full desktop Firefox build on an IoT gateway is not a good idea, so you'd also need some way to create your own client application which embeds Gecko, which unfortunately is extremely difficult to do with anything other than GeckoView on Android (believe me, I've been trying for 13 years).

If you want to work on this then let me know, but I'm going to close this issue as out of scope for the WebThings gateway application.

**Comment by flatsiedatsie** [comment]
Thanks for the quick reply. If it's OK with you then I will try to create this functionality via an add-on. The add-on will install the desktop dependencies and add the auto-start-the-browser-at-boot code. Basically, it will recreate what I created manually, but do so automated.

**Comment by mrstegeman** [comment]
You may want to check out the [voice add-on source](https://github.com/andrenatal/voice-addon), as it handles installation of system dependencies and adding system services as well.

**Comment by benfrancis** [comment]
> Thanks for the quick reply. If it's OK with you then I will try to create this functionality via an add-on. The add-on will install the desktop dependencies and add the auto-start-the-browser-at-boot code. Basically, it will recreate what I created manually, but do so automated.

My recommendation is that you don't create this as an add-on. In version 0.9 there are two types of add-ons, adapter add-ons and notifer addons, and this doesn't fit into either of those categories. I would encourage you to create it as a separate application which can be run on the same hardware as the gateway.

I would like to discuss removing the voice client add-on from the add-ons directory too for the same reasons, as it would be better off as a separate application.
