### ISSUE TITLE
Allow for multiple add-on lists

### ISSUE THREAD

**Issue by mrstegeman** [mozilla-iot/gateway#2026]
As add-on policies become more stringent, we want to allow developers to host their packages elsewhere if they're not a good fit for our semi-curated add-on list.

We should change the config file to allow for multiple add-on lists, should a user desire to use some unapproved third party add-on.

**Comment by flatsiedatsie** [comment]
Interesting :-)

Will/could there be an easy way for users to add (copy+paste) a new source to the list via the UI?

**Comment by mrstegeman** [comment]
No, only via config file. This is intended only to be a developer/power user/distributor feature.
