### ISSUE TITLE
[OpenWrt] Error redirecting after first time setup

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#2028]
Environment:
* Turris Omnia as router
* Mac OS as client

STR:
* Flash 0.9.0-4 Turris Omnia image
* Connect to Wi-Fi access point
* Configure Wi-Fi network
* Re-connect to Wi-Fi network to start 2nd captive portal
* Configure subdomain (I reclaimed an existing one)

Expected:
* Re-directs to subdomain, ideally in a browser window rather than the captive portal window...

Actual:
* "A problem occurred"
<img width="900" alt="Screenshot 2019-07-22 at 17 46 57" src="https://user-images.githubusercontent.com/552417/61651141-2f09c580-acad-11e9-84cd-75a16ea6e540.png">

* Only option is to click cancel
* gateway.local and 192.168.1.2 do not resolve (Foris is accessible via 192.168.1.2:81)
* Was able to access web server after a reboot, had to do the domain registration step again

Anyone able to reproduce?

**Comment by mrstegeman** [comment]
The captive portal was probably still up when the redirect happened. Do you have the log, by chance?

**Comment by benfrancis** [comment]
> The captive portal was probably still up when the redirect happened. Do you have the log, by chance?

Unfortunately not, but I think #2034 should fix this.
