### ISSUE TITLE
Sigma Designs UZB3 - Duplicate device entries

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#203]
I just received my Sigma Designs UZB3 controller (model number [ACC-UZB3-E-STA](https://www.digikey.co.uk/product-detail/en/sigma-designs-inc/ACC-UZB3-E-STA/703-1127-ND/6111631)).

The good news is, it works with our gateway out of the box! Unfortunately the form factor is still not *quite* small enough to comfortably fit alongside the XStick when plugged into the Raspberry Pi (the unit I received doesn't look quite the one in the picture, it looks like [this one](https://www.digikey.co.uk/product-detail/en/sigma-designs-inc/ACC-UZB3-E-BRG/703-1130-ND/6111634)), but it is definitely better than the Aeotec adapter we have been using. It also works more consistently with the XStick when it comes to pairing (no built-in battery or button on the dongle).

The one bug I've found so far is that when I paired my smart plug I got three entries on the screen rather than one. The last entry couldn't be saved, but the first one could.

STR:
* Put dongle in pairing mode using "+" button in UI
* Plug in smart plug and press button on plug

Expected:
* One new entry appears on the screen

Actual:
* Three duplicate entries appear on the screen and not all of them can be saved

![screenshot-2017-7-10 things gateway](https://user-images.githubusercontent.com/552417/28012812-e639f75e-655e-11e7-93e4-e78ccedfad87.png)

@dhylands If you get hold of one of these dongles, it would be interesting to debug what's going on here.

**Comment by DavidKarlas** [comment]
I sometimes seen same behaviour also with Zigbee device

**Comment by dhylands** [comment]
@benfrancis It would be good to get the gateway log (if run on a raspberry pi, this will be in `/home/pi/mozilla-iot/gateway/run-app.log` along with the `OZW_Log.txt` file from the same directory.

**Comment by mrstegeman** [comment]
Fixed by #498
