### ISSUE TITLE
Things loosing their label once rebooted after update (0.9.0)

### ISSUE THREAD

**Issue by rzr** [mozilla-iot/gateway#2041]
Update from UI went fine, then I reported the gw from ssh and then all things are named "undefined".

I suppose this is caused by the API change (TD change adding URI as 1st param?)

Screenshots:

[![before](https://social.samsunginter.net/@rzr/102501191547219116)](https://cf.mastohost.com/v1/AUTH_91eb37814936490c95da7b85993cc2ff/socialsamsunginternet/media_attachments/files/000/016/575/small/a7700027d96a4a2b.png "before")

[![after](https://social.samsunginter.net/@rzr/102501191547219116)](https://cf.mastohost.com/v1/AUTH_91eb37814936490c95da7b85993cc2ff/socialsamsunginternet/media_attachments/files/000/016/578/small/feff2bb86c21d2ef.png "after")

Well if user is logging out and logging again they are displaying fine again:

[![relog](https://social.samsunginter.net/@rzr/102501191547219116)](https://cf.mastohost.com/v1/AUTH_91eb37814936490c95da7b85993cc2ff/socialsamsunginternet/media_attachments/files/000/016/576/small/4e0e1d46a15a64a4.png "relog")

Maybe the user should be logged out if gateway is no more reachable, or listen to version changes.

**Comment by benfrancis** [comment]
This is unfortunate, I suspect it's caused by "name" changing to "title" and something being cached. For me a hard reload of the page fixed it.

**Comment by rzr** [comment]
yes It's not a critical issue, but maybe it's a good justification for versioning API

**Comment by damianon** [comment]
The problem is browser caching. 
I had this exact same issue (even tried reflashing the microsd) and it was solved by ctrl+shift+r (full reload), because the browser caches the old js. Maybe add version numbers so the browser knows to reload them
