### ISSUE TITLE
ReferenceError: WebAssembly is not defined

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#2047]
I noticed this in the console on Firefox:

```
Source map error: ReferenceError: WebAssembly is not defined
Resource URL: http://gateway.local/bundle/39c290cf3389797e4bf6-app.js
Source Map URL: 39c290cf3389797e4bf6-app.js.map
```

Firefox 68.0.1 on Mac OS.

**Comment by mrstegeman** [comment]
That's weird. If you do a hard refresh, do you get the same error?

**Comment by flatsiedatsie** [comment]
Does the WebThings Gateway require WebAssembly? I think I turned it off manually once. My browser is locked down pretty hard for privacy and security reasons.

**Comment by hobinjk** [comment]
The voice assistant requires WebAssembly, otherwise you can safely ignore it

**Comment by JonasRothmann** [comment]
For anyone having this issue in the future, it is most likely because your firefox is in safe mode!
