### ISSUE TITLE
Connect webthings on local network 

### ISSUE THREAD

**Issue by negrival** [mozilla-iot/gateway#2049]
I'm able to get and set property of web things  via web(*.mozilla-iot.org.).
But not on local network...

**Comment by mrstegeman** [comment]
You'll need to use https://gateway.local:8443 and skip certificate verification, as it will fail.

**Comment by mrstegeman** [comment]
What do you mean, exactly? You have web things added to your gateway and you're only able to interact with them through the tunneled gateway?

**Comment by negrival** [comment]
If i use browser no problems,  but if i try control web things by code(javascript) and i refer things with ip it doesn't work

**Comment by mrstegeman** [comment]
Are you trying to control things which are attached the gateway, or standalone web things (e.g. they're using one of the webthing libraries)?

**Comment by negrival** [comment]
Things are attached the gateway.
I'm trying to control GPIO of Raspberry.
It work fine by browser.
It work by code if I use https://*.mozilla-iot.org/things/gpio-20/properties/on(i get correct status), but it doesn't work if I use local Ip address.
I try:
https://192.168.1.80:4443/things/gpio-20/properties/on
http://192.168.1.80/things/gpio-20/properties/on
http://192.168.1.80:8080/things/gpio-20/properties/on
and other combinations, but nothing work..

**Comment by flatsiedatsie** [comment]
That sounds suspiciously like the issue I'm having:
https://github.com/mozilla-iot/gateway/issues/2044

**Comment by mrstegeman** [comment]
Since you have the subdomain set up, your certificate is valid for `<domain>.mozilla-iot.org`, so here's what's happening.

1. `https://192.168.1.80:4443` - certificate is invalid for that hostname, you'll need to skip certificate validation
2. `http://192.168.1.80` - you get redirected to `https://192.168.1.80:4443` - you'll need to skip certificate validation
3. `http://192.168.1.80:8080` - you get redirected to `https://192.168.1.80:4443` - you'll need to skip certificate validation

**Comment by flatsiedatsie** [comment]
The plot thickens.

I installed the `virtual things` add-on, and tried to toggle it's basic power switch. It worked!
```
+++++++++++ PUT +++++++++++++
full path: http://gateway.local:8080/things/virtual-things-3/properties/on
trying api put now
200 OK {'on': True}
```

**Comment by mrstegeman** [comment]
May be an issue with your adapter, then.

**Comment by flatsiedatsie** [comment]
And now I have gotten a MySensors thing to switch!

While working on the MySensors add-on today I noticed that I hadn't updated its code to add `title` to properties. Only the things had it. Perhaps that change is what made the difference?

**Comment by flatsiedatsie** [comment]
Hmm, the existing MySensors device with 4 toggles still crashes it. A simpler device with only one toggle does toggle.

**Comment by flatsiedatsie** [comment]
I think I may have figured it out. I was toggling a property that was already on to on..

**Comment by mrstegeman** [comment]
Haha! Can we close your other issue now?

**Comment by mrstegeman** [comment]
Oh, never mind, it’s already closed.

**Comment by negrival** [comment]
So I cann't use xmlhttprequest to work con local network...

**Comment by mrstegeman** [comment]
Did you get around the certificate verification issue? And is there a reason not to use `fetch()`? Tends to be an easier API.

**Comment by negrival** [comment]
"Did you get around the certificate verification issue?" I don't know how...
Yes I can use fetch()...

**Comment by mrstegeman** [comment]
Can you see if `fetch` gives you better results? I believe it will honor the user’s acceptance of the certificate, so if you clicked through the warning when you browsed to the IP address, you should be fine.

**Comment by negrival** [comment]
Yes!
`fetch` give correct result!
Thanks.

**Comment by mrstegeman** [comment]
Fantastic!
