### ISSUE TITLE
Buster - 'Suite' value from 'testing' to 'stable'

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#2050]
Running `sudo apt-get update` via SSH I noticed:

`Repository 'http://raspbian.raspberrypi.org/raspbian buster InRelease' changed its 'Suite' value from 'testing' to 'stable'`

I had the same issue on another Pi 4 a few days ago, so in theory the image could have already been updated to this?

`sudo apt-get --allow-releaseinfo-change update` brings it to the release version.

**Comment by mrstegeman** [comment]
This was probably just due to when our Buster base image was built. Not really an issue and should not be a factor in future releases, since we build new base images (which will be based on the stable Buster build) each time.
