### ISSUE TITLE
Assets of 0.9.1 have 0.9.0 in their filenames

### ISSUE THREAD

**Issue by jaller94** [mozilla-iot/gateway#2051]
The assets of release 0.9.1 have the version number 0.9.0 in their filenames.
Maybe a script could perform a little sanity check before releases get uploaded?

https://github.com/mozilla-iot/gateway/releases/tag/0.9.1

**Comment by hobinjk** [comment]
I'll add a bit after "Note that there are no changes to the standalone image" to make it clearer that this is intentional

**Comment by mrstegeman** [comment]
This was intended. There was a small problem with the 0.9.0 OTA update, not with the image. There was no need to roll a brand new image.
