### ISSUE TITLE
Device connection problem

### ISSUE THREAD

**Issue by Raylands** [mozilla-iot/gateway#2053]
Disclaimer: I am new to the whole smart home world.
I ordered a smart light switch from Sainko and installed it. The connection via the recommended app "Smart Life" worked well (connection via wifi), but I want this whole thing offline, so I configured a Raspberry Pi with gateway. (setup was successful)

But for some reason, I can't manage to connect the switch to the gateway. (search and URL/IP)
I am not sure if I am doing something wrong or if this product is simply not supported by the current framework.

Appreciate any help :)

**Comment by mrstegeman** [comment]
We don't have an add-on capable of interacting with that Sainko device right now, so you won't be able to use it with the gateway.

**Comment by Raylands** [comment]
That's what I thought :/

I am pretty decent in coding c++ and know a bit javascript, but I have never dealt with these kinds of protocols. 
Do you think I have a change in developing an adapter for this switch?

**Comment by mrstegeman** [comment]
I looked into it a bit but couldn't find any existing libraries for communicating with the device. Since that's the case, you'd probably have to reverse engineer the whole protocol and writing bindings for it in some language.

**Comment by Raylands** [comment]
I guess that's too much. Sadly, I can't find a 2 gang switch that is supported via plugin and compatible with the 230V in Europe :/

I'll keep looking if I can find something compatible, but thanks for your help.

**Comment by mrstegeman** [comment]
This would _probably_ work with the HomeKit add-on (I'd be happy to fix the add-on, if not): https://www.koogeek.com/p-kh02cn.html

**Comment by Raylands** [comment]
Thanks. I ordered and installed it, but can't connect it to gateway. (add-on is activated)

**Comment by mrstegeman** [comment]
You have to use the Koogeek app to add it to your wi-fi, and then remove it from the Koogeek app. The whole process is a bit weird.

**Comment by Raylands** [comment]
So, after I have finally gotten my hands on an iPhone (doesn't work with the android app), I connected the switch to my wifi, and it's detected within Gateway, but it wants a PIN. I already read the manual and tried the code on the manual, but that didn't work.

**Comment by mrstegeman** [comment]
After connecting it to your wi-fi via the iPhone, you then have to "Remove Accessory" on your iPhone before you can add it to the gateway. Did you do that part?

**Comment by Raylands** [comment]
yes, I did. I also restarted my pi but that didn't help either.

**Comment by mrstegeman** [comment]
Can you post your log file? You can get it through the UI via _Settings -> Developer -> Internal Logs_. You’ll want the newest run-app.log file.

**Comment by Raylands** [comment]
[run-app.log.2019-08-17.txt](https://github.com/mozilla-iot/gateway/files/3512449/run-app.log.2019-08-17.txt)

**Comment by mrstegeman** [comment]
From the log, it looks like:
* When you started, you tried to pair several times. Each time, the device responded that it was already paired (probably to the iPhone still).
* The device then came up with a different ID. I'm guessing you did a reset on it or something?
* You didn't attempt to pair again after that point.
