### ISSUE TITLE
SSL error when trying to access the gateway remotly

### ISSUE THREAD

**Issue by cedizzy** [mozilla-iot/gateway#2054]
Hi,

I don't know why but when trying access the gateway with my browser using mozilla-iot.org subdomain, I get an SSL error :

SSL_ERROR_ACCESS_DENIED_ALERT

I've read some topics/issue about it saying the gateway is down, but in my case, it's up! I can connect to it locally.

Could you help me ?

Thks

**Comment by mrstegeman** [comment]
That typically happens when either your gateway is down or it can't connect to the tunneling service. In your case, it seems like the latter may be happening. Does your Pi have an internet connection still?

Also, if you look in the log, do you see any lines containing `[pagekite]`?

**Comment by cedizzy** [comment]
My pi is connectec to internet, I can open a tcp connection in CLI to the subdomain on port 443.
I can see a time_wait connection with netstat command, but nothing happens when  capturing the traffic with tcpdump.

this is what I've found in logs using web interface :
`2019-07-29 21:39:36.282 INFO   : Tunnel domain found. Tunnel name is: xxxx and tunnel domain is: mozilla-iot.org
2019-07-29 21:39:36.286 INFO   : Tunnel name is set to: https://xxxx.mozilla-iot.org
2019-07-29 21:39:36.288 INFO   : Local mDNS Service Domain Name is: gateway`

Any idea ?
Where are located log files on the disk ?

thanks for help

**Comment by mrstegeman** [comment]
The TLS connection is really 2 parts:
1. Browser connects to the registration server.
2. PageKite tunnels that connection to your gateway.

So, what you're seeing as an open TCP connection is really just to the registration server. When you see the SSL error you posted, that means the other end (the tunnel) is not up.

The log files are located in `~/.mozilla-iot/log`.

**Comment by cedizzy** [comment]
I've checked in log files, nothing about kite. I've finally found that my ISP DNS was not resolving the domain pagekite.net, maybe for security reason, so the Pi was not able to create the tunnel.
After changing it for google DNS, everything is working perfectly now. I share that information, it could help people facing that issue.
Thanks @mrstegeman
