### ISSUE TITLE
ERROR  : Failed to import platform utilities for linux-unknown on Fedora

### ISSUE THREAD

**Issue by nylki** [mozilla-iot/gateway#2066]
I tried to install and start gateway on a fedora 30 thinkpad yoga I installed the dependencies and switched to the node version defined in `.nvmrc` as described in the readme. I get `ERROR  : Failed to import platform utilities for linux-unknown` when doing `npm start`. I am able to load the website on https 4443. Will this cause any issues later on?

```.sh
➜  gateway git:(master) ✗ node build/gateway.js
Opening database: /home/tom/.mozilla-iot/config/db.sqlite3
2019-08-03 12:28:37.140 ERROR  : Failed to import platform utilities for linux-unknown
2019-08-03 12:28:37.288 INFO   : Opening database: /home/tom/.mozilla-iot/log/logs.sqlite3
2019-08-03 12:28:37.487 INFO   : HTTPS server listening on port 4443
2019-08-03 12:28:37.488 INFO   : Redirector listening on port 8080
2019-08-03 12:28:37.495 INFO   : DNS config is: nypad
2019-08-03 12:28:37.495 INFO   : Service Discovery: changing profile - local domain is now: nypad
2019-08-03 12:28:37.497 INFO   : Service Discovery: state changed to: true
2019-08-03 12:28:47.511 INFO   : Checking for add-on updates...
2019-08-03 12:28:47.898 INFO   : Finished updating add-ons
```

**Comment by mrstegeman** [comment]
That error is not really a problem. All that will do is prevent you from using network settings and such.

**Comment by flatsiedatsie** [comment]
I had a similar issue on MacOS:

`failed to import platform utilities for darwin`. 

It works anyway.

**Comment by rudietuesdays** [comment]
Is there a way to fix the error so we can use network settings? I'm having the same issue as @flatsiedatsie on MacOS.

**Comment by mrstegeman** [comment]
You'd have to create a `darwin.js` file [here](https://github.com/mozilla-iot/gateway/tree/master/src/platforms) with the required functionality.

**Comment by ssbarnea** [comment]
I read the same message on Ubuntu Bionic running on intel arch:
```
Failed to import platform utilities for linux-unknown. Network and system configuration features will be disabled.
```
If that is not an issue the message itself is the bug, you do not start a message with "Failed to ..." if that is something expected.

Maybe something like below would be more appropiate:
```
Network and system configuration features are disabled on current platform:  linux-unknown
```
As you can see there is no "error" or "failure" in that message.

**Comment by mrstegeman** [comment]
I lowered the log level down from `error` to `info`, specifically to indicate that this is not an error.
