### ISSUE TITLE
Reload Things when switching views

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#207]
Re-load the list of Things when switching back to the Things view.

Currently the user has to manually reload the page for new Things to appear.

**Comment by mrstegeman** [comment]
Fairly certain this happens now.

**Comment by benfrancis** [comment]
Yeah, and it's kind of annoying because it's so slow over the SSL tunnel! :P

**Comment by mrstegeman** [comment]
Haha yes. Anyway, we can close this, right?
