### ISSUE TITLE
Improve Device Removal

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#2073]
Ben made some comments on slack about having issues removing a zigbee light bulb. So I thought I'd create an issue to discuss this. I decided to put this in the main repository since this affects other adapters as well, not just zigbee.

Some background.

Battery powered zigbee or zwave devices sleep for long periods and time and may only communicate with the dongle once every few hours. In order to properly support these, information about the devices needs to be persisted. The openzwave library does this automatically. Our zigbee adapter persists the information in the zb-XXXX.json file. Enough information to classify the devices needs to be persisted so that when the gateway starts up it can properly reflect the devices.

Currently, zigbee devices aren't removed from the json file when they are removed from the gateway. The reason for this was that when adding devices, sometimes the device would stop communicating and sometimes factory reseting and re-adding the device would allow it to finished beeing added. Some of the issues with adding devices may have been due to misunderstandings in how the protocol works. I'm not aware of any issues adding devices (related to communication stopping) using the current adapter, so it may make sense to have the adapter remove the information from the json file when removing the device from the gateway.

A similarish issue happens with zwave devices. Zwave devices don't have a unique identifer like the zgibee devices do, so if you add a zwave device, factory reset it and add it a second time, the zwave adapter has no way of knowing that the second add is the same device as the first one. You then wind up with a "ghost" device. For zwave, I think that the ghost devices will show up in the UI but just be non-responsive. Since the ghost device isn't actually present any more, the normal zwave removal process doesn't work, so we may need to be able to detect this and use a different removal process.

Part of the problem arises from the fact that there are actually 2 sets of devices, one which the adapter is aware of and one which the UI is aware of. The UI doesn't currently have any mechanism to manage devices which the adapter knows about but which the UI doesn't. The only thing that a user can currently do is add a device like this to the gateway (and that may or may not be possible depending on the exact state that the device is in).

For zigbee devices, devices can be in a paired but unconfigured state. Currently devices in this state do not show up in the UI anywhere, but they will be persisted in the json file. We don't show these in the UI because until the device is configured, we don't know what type of device it is. The word "configured" in this context includes querying the device to find out what capabilities it has.

**Comment by mrstegeman** [comment]
Related:
* #1930
* #1334
* #1275
* #1252 
* #1013

**Comment by benfrancis** [comment]
And #1334

**Comment by mrstegeman** [comment]
That was in my list :smiley:

**Comment by benfrancis** [comment]
@mrstegeman So it was. I've clearly read too many bug numbers while triaging the inbox! :P

**Comment by tdaede** [comment]
Another effect of this is that once-paired devices always appear in the "Add new devices" list, regardless of whether they are actually on or nearby.

**Comment by mrstegeman** [comment]
@tdaede This is actually adapter-specific, not a global gateway issue. Do you have specific add-ons which are doing this?

**Comment by tdaede** [comment]
@mrstegeman The Zigbee addon does it for me. Any devices in the JSON file always appear as available to add, and nothing ever deletes devices from the JSON file.

**Comment by mrstegeman** [comment]
@dhylands can probably give you a better explanation, but as I understand it, the devices are cached to the JSON file specifically because battery powered devices are finicky about when they’ll report all their properties and such. For example, low power sensors may only report back once a day, if that. So, it can be hard to tell what’s actually “present” and what’s not.

**Comment by dhylands** [comment]
The issue is that you can't unpair battery powered devices "on demand". What should probably happen is that when you remove a zigbee device it should be "scheduled for unpairing". Then when the device next reports in, the gateway could detect that it's been scheduled for unpairing and send the unpairing request at that time.

The zigbee adapter does remove devices from the json file when it gets back a confirmation that the device has "left the network". For AC powered devices this happens immediately at removal time.

We could also remove the devices from the JSON file at removal time, but the devices will in fact still be paired with the dongle and will continue to send in events.

**Comment by mrstegeman** [comment]
We've decided to leave this clean up to individual adapters, now that they receive a list of saved devices (#2143).
