### ISSUE TITLE
Install Mosquitto by default

### ISSUE THREAD

**Issue by createcandle** [mozilla-iot/gateway#2077]
MQTT has become a popular standard for communication in the smart home.

Already multiple add-ons have been created that use it in some capacity.

To avoid add-ons al starting their own MQTT server, it would be great if Mosquitto came pre-installed on the WebThings Gateway.

See:
https://github.com/mozilla-iot/addon-list/issues/388

**Comment by mrstegeman** [comment]
@hobinjk any opinions on this? I'm not personally opposed.

**Comment by hobinjk** [comment]
I remember a weird interaction between apt's mqtt and snips' mqtt where snips wanted it configured one way and I wanted it configured another but that can be a thing for each individual add-on/third-party app to fight over. Having it installed by default is definitely good
