### ISSUE TITLE
Display artifact in network settings

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#2079]
I saw this with 0.9.2 on my iPhone XR using the firefox browser.

It looks like a small Wifi icon is overlaid on top of a larger wifi icon.
![IMG_0960](https://user-images.githubusercontent.com/127500/63061245-52d5bb00-bea9-11e9-8030-8cb9c7acfd2a.PNG)

**Comment by flatsiedatsie** [comment]
Noticed something similar the other day:

![strange_wireless-icon](https://user-images.githubusercontent.com/805405/70087740-cb08ed80-160c-11ea-9a06-edd9167a4791.png)

Changing the length of the wifi SSID (by manipulating the html) had no effect.
