### ISSUE TITLE
Idea: enable router functionality on the Raspberry Pi build too

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#2094]
On July 25th: someone called frenchfaso [commented on the blog](https://hacks.mozilla.org/2019/07/webthings-gateway-for-wireless-routers/) post announting the router version with:

    _It would be awesome to be able to configure the gateway as a router/accesspoint also in the raspbian version!
    Please consider this feature for the next Raspbian based release.
    Great project, thanks for the hard work!_

I think this is an interesting idea. A Raspberry Pi is an order of magnitude cheaper than the Turis Omnia (although I understand the goal is to target more affordable platforms).

I could imagine a few configurations:
1. Plug it into my main router to run an isolated sub-network for wifi IoT devices. It could run extra software that keeps an eye on these devices, and reports suspicious activity.

2. Run the pi in between the ISP provided internet access point and a secondary router, as a firewall. It could also force itself to be a DNS provider on the network and offer some security that way.

3. Use the Pi as a travel router.

4. Actually use it as the main router. Since the Pi 4 has USB3, I could imagine plugging in an ethernet adapter and, if more range and throughput is required (likely) a wifi dongle.

The first two use cases sounds like a match for the goals of the project?
The third and fourth would be.. interesting. It would certainly make for a powerful, configurable router platform. (although calling it a Frankenstein router would be another label...)

I did a bit of searching, and it turns out running OpenWRT on the Pi [is a thing](https://duckduckgo.com/?q=openwrt+raspberry+pi&t=ffab&ia=web).

I'd be curious to hear your thoughts. I suspect there may also be a lot of reasons not to do this :-)

**Comment by mrstegeman** [comment]
We actually already have a build of OpenWrt for the Pi, but chose not to publicize it for the following reasons:
1. The wi-fi on the Pi is far from sufficient for an actual router.
2. There is only a single ethernet port, which is also not a good fit for a router.
3. Making non-technical users figure out which build to download for the Pi seemed like a bad idea.

If you're interested in trying out a build, just to see what it's like, I'm sure @dhylands could point you to one.

**Comment by flatsiedatsie** [comment]
I'd love to try it actually!

I had a look around and there are some pretty powerful yet cheap USB Wifi dongles with dual 5dbm antenna's for $20. An extra USB ethernet adapter would probably be $10. The old router could take the role of the switch.

Or I could let the router just be an access point and let the Pi be the boss of the network. Let it do DHCP.

I did also read that the gigabit ethernet of the Pi 4 is still 3 times slower than the ethernet on the Jetson Nano. But it's 3 times cheaper too.

I suspect that for a lot of use non-power users a basic router might actually suffice. E.g. grandma's, parents. If the Gateway's UX was a step up in usability from most router software (which it already is), then it could be totally worth it in my opinion.

Wouldn't it be easier to develop/maintain the gateway if both images would be based on OpenWRT instead of Raspbian?

**Comment by mrstegeman** [comment]
> Wouldn't it be easier to develop/maintain the gateway if both images would be based on OpenWRT instead of Raspbian?

Slightly easier, but we'd be forcing all of our existing users to re-flash their Pi. Also, there is certain functionality that is not currently working for us on OpenWrt, such as Bluetooth. That would prevent a fair amount of add-ons from working.

**Comment by flatsiedatsie** [comment]
@hobinjk Would you be willing to share an image of the OpenWRT version for the Raspberry Pi?

**Comment by flatsiedatsie** [comment]
Thanks! Wow, it's so tiny.

**Comment by flatsiedatsie** [comment]
ah, I guess that doesn't run on a Pi 4.

**Comment by benfrancis** [comment]
No, unfortunately OpenWrt doesn't support the Raspberry Pi 4 yet (which would have further added to confusion if we'd included it on the downloads page!)

**Comment by benfrancis** [comment]
We made a conscious decision to have separate versions of the UI for Raspbian and OpenWrt images, with only OpenWrt providing full router functionality. OpenWrt builds are available for Raspberry Pi for people who want to experiment with that. Closing.

**Comment by flatsiedatsie** [comment]
I tested it on a Pi 3. Very very cool!
