### ISSUE TITLE
Port number in Settings not always correct

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#210]
Settings shows the gateway's secure web address but always shows port 4443 even when port 443 is being used and so doesn't need to be shown.

@andrenatal Any idea how to fix this given the port forwarding going on on the Raspberry Pi?

**Comment by andrenatal** [comment]
That port was hard coded @benfrancis. I removed it here: https://github.com/mozilla-iot/gateway/commit/20f034efdacab5f28652298f1fc2021af207978b.

**Comment by benfrancis** [comment]
Oh, great! Thanks. I'll close this then.

I'm not sure if this will be correct in all cases (e.g. if someone manually configures the port or runs on localhost with self-signed certs), but this UI is probably going to change when we implement the full settings UI anyway.
