### ISSUE TITLE
Trigger rules in the gateway UI

### ISSUE THREAD

**Issue by MadeByMike** [mozilla-iot/gateway#2105]
Virtual adapters and especially buttons are really useful for configuring rules. But only allowing one of each type is limiting. 

For example I can create a virtual on\off button then configure a rule to change a set of lights. I can set a rule that changes the dining and living room lights to sunset colors when I push the virtual button:

![image](https://user-images.githubusercontent.com/1320567/63647801-e0e35880-c769-11e9-80ea-8ba044e25d74.png)

However once I add a single virtual button I can't add any more. It is possible to clone the virtual adapters and add many, but that's very clunky and what I'd really like is some supported means of triggering rules in the UI. 

Virtual buttons seem like a good way to go. Maybe this can be extracted from the virtual adapters package and added as a feature?

**Comment by mrstegeman** [comment]
You can actually create an unlimited number of virtual things, but you have to create them through the add-on config. Navigate to _Settings -> Add-ons_, then on the "Virtual Things" entry, click _Configure_. You can create custom things by just filling in all of the entries. Some helpful terms:
* `@type` for the top-level thing, you'll want "PushButton" or "OnOffSwitch"
* `@type` for the property, you'll want "PushedProperty" or "OnOffProperty"
