### ISSUE TITLE
Add instructions to the README to turn on SSH

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#211]
SSH is disabled by default (because there's a default username and password), but you can switch it on by adding a file to the boot partition or using a serial connection.

@dhylands Would you mind documenting how to do this?

**Comment by dhylands** [comment]
@benfrancis I have some simple documentation for adding the file to the boot partition here: https://github.com/mozilla-iot/wiki/wiki/Creating-an-image-file-for-the-Raspberry-Pi#enable-ssh

Where would you like the documentation to live?

**Comment by benfrancis** [comment]
@dhylands Oh OK, actually that's probably fine. The [README](https://github.com/mozilla-iot/gateway/blob/master/README.md) is mostly about manually building the gateway for development, which includes instructions on [setting up the OS](https://github.com/mozilla-iot/wiki/wiki/Setting-up-Raspberry-Pi) including enabling SSH if you want to do it that way.

We don't have obvious instructions on how to enable SSH after you've downloaded a pre-built image, but maybe people can figure that out from general Raspberry Pi documentation.

**Comment by dhylands** [comment]
@benfrancis We probably need a section in the UI of the gateway for doing a few simple system related things, like power off, reboot, and we could also add an enable/disable SSH.

**Comment by benfrancis** [comment]
@dhylands Yes I'd like to start to build out the settings section of the UI for things like that and I like the idea of having a reboot button. Implementing that as an action in the API and treating the gateway itself as a "thing" will make me so happy ;)

**Comment by benfrancis** [comment]
Enable/disable SSH https://github.com/mozilla-iot/gateway/issues/216
Reboot https://github.com/mozilla-iot/gateway/issues/217
