### ISSUE TITLE
I still can’t understand protocols Mozilla IoT

### ISSUE THREAD

**Issue by EduardShaid** [mozilla-iot/gateway#2121]
I still can’t understand which protocols are used:

1) between web-client and Gateway
2) between the Gateway and Thing 

Is this the same protocol Web Thing ?
Can anyone explain these issues ?

**Comment by mrstegeman** [comment]
1. Browser -> Gateway: [Web Thing API](https://iot.mozilla.org/wot/) plus some custom REST APIs where required.
2. Gateway -> Thing: Technically, the gateway communicates with adapters via [IPC](https://github.com/mozilla-iot/wiki/wiki/Adapter-IPC). The adapters then communicate with devices in whatever way is required.

**Comment by EduardShaid** [comment]
Then according to what scheme (where what protocols are used between the Qateway, Thing and Arduino) does this project work?
https://github.com/96boards-projects/mozilla-iot-neopixel-demo

Thank you very much.

**Comment by mrstegeman** [comment]
That project uses the [webthing-python](https://github.com/mozilla-iot/webthing-python) library, which represents the NeoPixel as a Web Thing through that same REST API. So the flow looks like this:

* Browser -> Gateway: Web Thing API
* Gateway -> thing-url-adapter: Adapter IPC
* thing-url-adapter -> NeoPixel: Web Thing API
