### ISSUE TITLE
Z-wave Add-on missing in Gateway Portal

### ISSUE THREAD

**Issue by eanmikale** [mozilla-iot/gateway#2122]
We have built the newest version of the gateway on the Pi. We see the Zigbee add-on, but do not see the Z-wave add-on. We have installed the z-wave add-on from source. I know the installation may or may not have changed? Any assistance on connecting z-wave devices after changes to the installation would be great! Thanks in advance.

**Comment by mrstegeman** [comment]
Can I ask why you built the add-on yourself?

It would be helpful if you could restart the gateway and attach your most recent log file from `~/.mozilla-iot/log`.

**Comment by adocampo** [comment]
I'm facing the same issue. I tried first the docker instance of the gateway, but  it seems my Z-Wave stick (Aeotec Z-Stick Gen5 (ZW090) - UZB) cannot be loaded, so I tried on Pine64. 

I've installed armbian and then, followed the instructions to set up Mozilla WebThings Gateway manually for debian.

I cannot see all the addons I can see on the docker instance, to illustrate this, a capture to my addon list on the docker container
![image](https://user-images.githubusercontent.com/2266612/66277534-2b471180-e8a0-11e9-9a27-71306ff77b78.png)
and another from the manual installation on armbian under pine64
![image](https://user-images.githubusercontent.com/2266612/66277543-44e85900-e8a0-11e9-8b71-090f68849687.png)
How can I get the missing addons, specially the z-wave one?

**Comment by mrstegeman** [comment]
@adocampo This is a different issue.

For you, you have two problems:
1. To use your Z-Wave dongle in Docker, you need to share the device into the container. See the Notes in the [README](https://github.com/mozilla-iot/gateway-docker/blob/master/README.md#notes).
2. For the Pine64 issue... That armbian build is for 64-bit ARM. However, all of our add-ons are built for 32-bit ARM, so they will not be available to you.

**Comment by adocampo** [comment]
Hey @mrstegeman thank you for your answer.

Well, I didn't explain what I did on docker because I thought it wasn't related to this thread. On the docker I did pass the device with the `--device /dev/ttyACM0:/dev/ttyACM0` It is detected inside the container and the error is  
```
2019-10-07 22:08:19.707 INFO   : zwave: Found ZWave port @ /dev/ttyACM0
2019-10-07 22:08:19.711 INFO   : zwave: Initialising OpenZWave 1.6.0 binary addon for Node.JS.
2019-10-07 22:08:19.711 INFO   : zwave:         OpenZWave Security API is ENABLED
2019-10-07 22:08:19.711 INFO   : zwave:         ZWave device db    : /home/node/.mozilla-iot/addons/zwave-adapter/openzwave/config
2019-10-07 22:08:19.712 INFO   : zwave:         User settings path : /home/node/.mozilla-iot/data/zwave-adapter
2019-10-07 22:08:19.712 INFO   : zwave:         Option Overrides : --SaveConfiguration true --ConsoleOutput false
2019-10-07 22:08:39.937 INFO   : zwave: failed to start driver
```
I can open the configuraion screen, but I let all blank as I don't use that networkKey thing.
![image](https://user-images.githubusercontent.com/2266612/66352533-fac6ac80-e95f-11e9-851a-5a0face9bc08.png)

Anyway, as the log says, it fails to start driver, so I can't add any device. I faced the same issue on the Openhab docker, but it works just fine in HomeAssistant docker, so my USB is working.

That's on the docker side, on the Pine64 side, is there any option to install WebThings Gateway on it (and see all the plugins, I mean)?

**Comment by mrstegeman** [comment]
My guess is that it's a permissions issue with the device inside the container. The gateway runs as UID 1000, so that user would need to have access to the device.

For the Pine64, you could either run a 32-bit distro or manually build the add-ons you need.

**Comment by adocampo** [comment]
Thank you @mrstegeman, chown 1000 to /dev/ttyACM0 worked on the docker! It shown directly the sensor I had paired with home assistant ! :)

On the Pine64 side, I'd download the https://github.com/mozilla-iot/zwave-adapter and ran `./package.sh` but after a while compiling, it failed... anyway, I prefer to use docker anyway, so I'm going to pair some devices and play a bit with Webthings :)

Thank you very much!
