### ISSUE TITLE
Websocket opening not pipelined, slow on high latency links

### ISSUE THREAD

**Issue by tdaede** [mozilla-iot/gateway#2129]
On a mobile device or in another country with a high latency to the gateway, it's extremely apparent that the WebSocket to each device is opened serially - I watch each device slowly report its status. It would be much better if they were all opened at the same time. Or maybe the initial status could be retrieved via pipelined HTTP requests, without websockets at all?

**Comment by mrstegeman** [comment]
This should actually be fixed now. We've reduced everything down to a single websocket. Please open a new issue if you still have problems when 0.10 is released!

Fixed by #2085
