### ISSUE TITLE
Send logs to usb stick (and extend sd card life)

### ISSUE THREAD

**Issue by carver7** [mozilla-iot/gateway#2132]
It’d be nice to make it easy for users to select a “write logs to usb stick or other usb drive” that can also be accessed remotely to preserve sd card life and space. When the space runs out the newest logs simply overwrite the oldest.

(and even another option to send logs to Azure, etc if that’s not already available in the Azure IOT hub add on)

That way the benefits of logging and graphs etc could be had without worrying about the sd card running out of space or getting corrupted.

In the meantime, is there a recommended way of setting this up manually in fstab?

**Comment by mrstegeman** [comment]
As an interim step, you could mount a USB stick to `/home/pi/.mozilla-iot/log`. You'll need to make sure that file permissions are set up properly, and that the mount occurs before the `mozilla-iot-gateway` service starts up.

**Comment by carver7** [comment]
Thanks! That gives a good idea of what to start googling. Would this approach be something along the lines of making that happen in the needed order? Appreciate it!
https://superuser.com/questions/1240367/how-to-wait-for-a-usb-flash-drive-to-be-mounted-present-before-running-services

**Comment by mrstegeman** [comment]
Yes, I think you'll want to do the following:

1. Add something like the following to `/etc/fstab`:
    `/dev/sda1 /home/pi/.mozilla-iot/log vfat defaults,uid=1000,gid=1000,umask=022 0 0`
2. Modify the `After=` line in `/etc/systemd/system/mozilla-iot-gateway.service` to be:
    `After=multi-user.target home-pi-.mozilla\x2diot-log.mount`
3. Restart the Pi and see if it worked.

**Comment by carver7** [comment]
Nice thanks. Will have the chance to try it out tomorrow (Friday) and verify with a reboot via ssh. Will report back!

**Comment by mrstegeman** [comment]
This could actually be completely done by modifying the `profileDir` property in the config file.
