### ISSUE TITLE
Cannot remove Google Home Text to Speech device

### ISSUE THREAD

**Issue by igilham** [mozilla-iot/gateway#2133]
The Google Home Text to Speech addon seems to be broken. That is not a problem for this project to deal with, but it device removal is so I thought I'd raise it here.

I've connected my gateway (v0.9.2 on a Raspberry Pi 3B) to a Google Home device via this addon. None of the features of the addon work, so I tried to remove the devices and clean up. Unfortunately, device removal doesn't work so I'm left with the clutter of useless devices on my gateway UI.

I'd appreciate any help getting these devices properly removed.

**Comment by mrstegeman** [comment]
Can you try to remove the device again, then upload your latest log file? That can be accessed in the UI via _Settings -> Developer -> View Internal Logs_, or on the Pi in `~/.mozilla-iot/log`.

To manually remove the device, you'll have to SSH into your Pi and do the following:
```
sqlite3 ~/.mozilla-iot/config/db.sqlite3 "DELETE FROM things WHERE id LIKE 'google-home-%'"
sudo systemctl restart mozilla-iot-gateway
```

**Comment by tim-hellhake** [comment]
Related to tim-hellhake/google-home-adapter#6

**Comment by igilham** [comment]
There are no useful logs, only Open ZWave stuff. A reboot of the gateway seems to have corrected the problem, suggesting there may be a reliability issue around installing addons.

While that may warrant further investigation, my issue is resolved for now.
