### ISSUE TITLE
Proper code cleanup of gateway repo before we pull new gateway code in device?

### ISSUE THREAD

**Issue by grbesd1** [mozilla-iot/gateway#2139]
Hi,

A few days back my gateway was working fine[before 6th september]. But after 6th Sep, I tried installing TP-Link addon but it was throwing up error.

Well after checking gateway and TP-Link addon source code I found out issue lies with new commit.

"Send user profile information to plugins."

https://github.com/mozilla-iot/gateway/commit/d0ec79dbebc568dc5e0ad321ec8b62901401dcf8

I was using the old gateway source but installing new addons. So obviously addon will not work.

So, I tried removing node_modules, build in gateway source. Performed git reset on the entire gateway source followed by git pull. install npm dependent packages. I'm getting stack error and unwanted errors while installing npm packages.

My question is:

**What steps I should take to properly clean my gateway to pull new code changes. start gateway server without having any error?**

**Comment by abhijitnathwani** [comment]
Hi @grbesd1 ,

The proper approach would be performing the following steps on the gateway itself:

1. `git pull`
2. `npm install`
3. `node_modules/.bin/webpack`
4. `sudo service mozilla-iot-gateway restart`
