### ISSUE TITLE
Intermittent 'NetworkError when fetching data' occurs when setting up the tunnel

### ISSUE THREAD

**Issue by andrenatal** [mozilla-iot/gateway#214]
@benfrancis I just reproduced this error too.

**Comment by andrenatal** [comment]
Probably this error happens [here](https://github.com/mozilla-iot/gateway/blob/f3f3673a2445c66b218a992671ca51510257fec6/static/js/setup_subdomain.js#L39) because the backend stops the http server and starts https while the client is still connected to it and waiting the response. We should find a better way to handle this and do the redirection.

**Comment by dhylands** [comment]
With #206 then we wouldn't shut down the http server.

**Comment by andrenatal** [comment]
Fixed by #206
