### ISSUE TITLE
Hotpluggable adapters

### ISSUE THREAD

**Issue by andrenatal** [mozilla-iot/gateway#215]
As a user I want to be able to plug in a new USB adapter and for it to appear in the adapters screen, without having to reboot the gateway.

**Comment by benfrancis** [comment]
@dhylands How feasible is it to "hotplug" adapters?

**Comment by dhylands** [comment]
@benfrancis Seems totally viable to me. They'll be separate processes, so they should be able to connect and disconnect from the gateway.

**Comment by mrstegeman** [comment]
There should be nothing preventing this at this point.
