### ISSUE TITLE
No Event Log for devices 

### ISSUE THREAD

**Issue by Silvan85** [mozilla-iot/gateway#2158]
I'm running WebThings Gateway (0.9.2) as docker image on 
Ubuntu 18.04.2 LTS (GNU/Linux 4.14.102-156 armv7l)

Problem:
When enter sensors Event Log I see blank page. 

I have Temperature sensor and on/off switch (for door opening monitoring).
Both operational and logging data in Logs Tab.

**Comment by mrstegeman** [comment]
Are there any errors in your [browser console](https://webmasters.stackexchange.com/a/77337)?

**Comment by Silvan85** [comment]
Failed to load resource: the server responded with a status of 404 (Not Found) settings/experiments/assistant:1

**Comment by mrstegeman** [comment]
What add-on(s) are you using for your devices?

**Comment by Silvan85** [comment]
ZigBee 0.9.0. 
Bat also have one device added from DateTime Adapter 1.0.0 and Pushbullet 0.1.0.
Event Log page is empty for them too.
Also on my android device this page are empty.

**Comment by dhylands** [comment]
From other reports I've seen, the biggest problem with using docker images is that you need to explicitly allow the docker image to have access to the particular serial port with the zigbee dongle.

**Comment by Silvan85** [comment]
I did this. I see dongle and even gat values. Everything is working except EventLog page per thing.
I even can add and see Logs for Things in Log tab

**Comment by mrstegeman** [comment]
That probably just means that no events have occurred. Are you expecting to see something in particular? What device are you using, and what events are you expecting?

**Comment by Silvan85** [comment]
There is no explanation what should be there. But I expected from my previous experience with Xiomi hub that for devices like on/off switch or motion detector I can find list of events that occured. Like data/time motion detected etc.

**Comment by mrstegeman** [comment]
Ahh, now I see what you're getting at.

An [Event](https://iot.mozilla.org/wot/#event-object) is a special object of a web thing. Property changes are not necessarily events. An example would be a "restarted" event. "Restarted" would not really map to a property, but it's still something that happened. Either way, they must be defined at the adapter level, they're not automatically generated.

If you want to see date/time of property changes, you can do that on the Logs page.
