### ISSUE TITLE
Settings - Enable/disable SSH

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#216]
As a power user I would like to enable SSH on my gateway so that I can log in via the command line.

**Comment by dhylands** [comment]
This should use the same technique that raspi-config uses.
https://github.com/asb/raspi-config/blob/3a5d75340a1f9fe5d7eebfb28fee0e24033f4fd3/raspi-config#L327-L345

**Comment by codeadict** [comment]
Is someone actively working on this one?

**Comment by benfrancis** [comment]
@codeadict I don't think so. People are just using the method of dropping a file called ssh onto the boot partition.

If you're interested in implementing this I can create a UI mockup if you like? I think it may require a new section in settings.

**Comment by codeadict** [comment]
Yeah i'm interested, i can do it :). For now, what does the ssh file needs to have on it?

**Comment by benfrancis** [comment]
Just an empty file, see https://github.com/mozilla-iot/wiki/wiki/Logging-into-the-Raspberry-Pi

**Comment by codeadict** [comment]
Thanks!

**Comment by dhylands** [comment]
Note that creating the ssh file will only enable ssh, it won't disable ssh. To disable ssh will require something like mentioned in comment 2 above.

**Comment by rzr** [comment]
If you're building images you can use:

    ./make-prep.sh --ssh # (...)

**Comment by dhylands** [comment]
Yes - but the images we ship should have ssh disabled (for security). This is to have a mechanism in the UI to enable/disable SSH.

**Comment by benfrancis** [comment]
UX spec: https://docs.google.com/presentation/d/1rMeg6hep8JQflqwbiNIbhSoK9StCeVZ2npphmQHKda4/edit#slide=id.g3c095fbf0e_6_1

UI mockup:
![developer-settings](https://user-images.githubusercontent.com/552417/40841501-95eaad08-65a2-11e8-9625-cfcc75397b59.png)

**Comment by mrstegeman** [comment]
@benfrancis Do we want this to be present outside of the RPi (or other platforms where we've implemented the required bits of code)? Should it be gone, or just disabled?

**Comment by benfrancis** [comment]
SSH icon: https://drive.google.com/file/d/1fgtzqfcgJ40TxixkbnBXLP29wOOgJYcz/view?usp=sharing

**Comment by benfrancis** [comment]
It would be good to be able to do feature detection and disable the options which aren't available on the current platform (e.g. disabling the text box, making "view logs" un-clickable). Can you think of a straightfoward way to do that?

**Comment by mrstegeman** [comment]
Yes, that was my plan. I just didn't know if you wanted things disabled or hidden.

**Comment by rzr** [comment]
As a suggestion, a way to add user's key from web would be nice if we want to prevent to share password.
