### ISSUE TITLE
Creating adapter for the last version of gateway

### ISSUE THREAD

**Issue by alexe100** [mozilla-iot/gateway#2167]
Hi all!
Great project!

I am doing the first steps in Mozilla gateway. I have setup it on my linux box and now I would like to create an adapter. I tried to follow the article from James Hobin but this last version of gateway seem to have a different set of folders and.... Is there any detailed documentation on how to create a new adapter for the last version of the gateway? 

Another info that would help: when we install a new add-on (I tried to install flic-button) where is the add-on installed on the gateway? I would like to look to the source code.

Thanks a lot
Alex

**Comment by tim-hellhake** [comment]
Hi @alexe100.
> I have setup it on my linux box

How did you set it up? By cloning the repository?

> where is the add-on installed on the gateway?

Addons are located under `$HOME/.mozilla-iot/addons`

**Comment by tim-hellhake** [comment]
Hi @alexe100, I hope I can help.

> I have setup it on my linux box

How did you set it up? By cloning the repository?

> where is the add-on installed on the gateway?

Addons are located under $HOME/.mozilla-iot/addons

**Comment by tim-hellhake** [comment]
> I would like to look to the source code

The profile directory is configured [here](https://github.com/mozilla-iot/gateway/blob/dcdd48e348a21a5ee0d39ecc18088628f19edd74/config/default.js#L19).

This is used to determine the addons directory [here](https://github.com/mozilla-iot/gateway/blob/dcdd48e348a21a5ee0d39ecc18088628f19edd74/src/user-profile.js#L39).

The installation directory of the addon is set [here](https://github.com/mozilla-iot/gateway/blob/dcdd48e348a21a5ee0d39ecc18088628f19edd74/src/addon-manager.js#L1056).

**Comment by tim-hellhake** [comment]
If you want to develop a nodejs based adapter you can simply clone the [example-adapter](https://github.com/mozilla-iot/example-adapter), modify it and copy it to the addons folder.
After a restart, the gateway should pick up the new addon.
All you need to do now is to activate it in the settings.

**Comment by alexe100** [comment]
I did that but i put my add on in the addons tester folder because it was the one with the mostclosed name to the one referred in the tutorial. Now i got it and i will try it.
Thank you very much Tim

**Comment by tim-hellhake** [comment]
> By the way when you say "and copy it to adapter folder" do you mean adapter or add on folder?

Sorry for the confusion.
I meant this: `cp -r example-adapter $HOME/.mozilla-iot/addons`
There is one folder for all addons.
Currently, there are two types of add-ons:  `adapter` and `notifier`.
