### ISSUE TITLE
Kernel Panic on RPI B+ v1.2

### ISSUE THREAD

**Issue by Falci** [mozilla-iot/gateway#2171]
Hi all,

First of all, can I run the gateway in a Raspberry PI B+ v 1.2?

When I boot, I can login (usb keyboard + HDMI monitor). 
I tried to use the `wpa_supplicant` file to auto connect to the wifi. No success.

After boot/login, `iwconfig wlan0` it shows the *WebThings Gateway XXXX*. In my computer, I checked the wifi list, and indeed it's there. Once I try to connect, the RPI shows a bunch of log info (way more than I can understand) in the end it says "kernel panic"

I tried in 2 different Raspberries, same version.

I'm using the Gateway version 0.9.2

**Comment by mrstegeman** [comment]
This may be related to #2080 somehow.

**Comment by mrstegeman** [comment]
Out of curiosity, what Wi-Fi dongle are you using?

**Comment by mrstegeman** [comment]
(I'm assuming this is the same issue as [this](https://discourse.mozilla.org/t/iot-gateway-on-raspi-crashes-when-clients-try-wireless-connect/48231/7), which means it's due to the Wi-Fi dongle driver).
