### ISSUE TITLE
SHA256SUMS file missing

### ISSUE THREAD

**Issue by alexe100** [mozilla-iot/gateway#2175]
Hi again...
Sorry for another question but I have been searching for information about gateway adapters SHA256SUMS and no results until now...

Main aim is to create an addon based on bluetooth. For now I just want to scan for nearby devices. Hence, I started to copy example_adapter (no changes) to the addons folder to see what happens. I restarted the gateway and it now detects it but says that SHA256SUMS file missing .

Is there any information referring the context of the SHA256SUMS file? Is it a checksum of all directory or just one specific file?

(Even the "Making a Clap-Sensing Web Thing" does not mention the SHA256SUMS file)

Thank you very much
Alex

ERROR  : Failed to load add-on example-adapter: Error: SHA256SUMS file missing for add-on example-adapter

**Comment by mrstegeman** [comment]
[This page](https://github.com/mozilla-iot/addon-list) should have everything you need.

Essentially, every add-on is expected to have a SHA256SUMS file containing a checksum of every file contained in the package (excluding itself).

However, during development, if your add-on directory contains a `.git` directory, the check will be skipped.

**Comment by tim-hellhake** [comment]
The simplest way to fix this is to create a `.git` directory in your addons directory.
This way the gateway will ignore the missing checksum file.

**Comment by tim-hellhake** [comment]
You can see here how the checksum file is usually created: https://github.com/mozilla-iot/example-adapter/blob/master/package.sh

**Comment by alexe100** [comment]
Great!
The example-adapter skeleton works fine now...
Time to fill it with useful source code.

Thank you very much for your help

Alex
