### ISSUE TITLE
Addon: call seqence and events?

### ISSUE THREAD

**Issue by alexe100** [mozilla-iot/gateway#2186]
Hi
I am still learnig and trying to understanding the call sequence and the involved events in a (new) addon. It seems that each (new) addon must have a Device, which adds one or more property and an Adapter. Where can I find information about how these objects are called when one enables and desables the addon using the web interface and how is adapter related with the device? Any help document that describes the mechanism, events, calling flow etc related with device and adapter of a specific addon?

Thank you
Alex

**Comment by mrstegeman** [comment]
There are multiple types of add-ons now, which are explained in [this document](https://github.com/mozilla-iot/addon-list/blob/master/guidelines.md)

If you're specifically talking about adapters, you got the gist of it. Each add-on runs in its own process. The process creates one (or more) Adapters. Each Adapter owns a set of Devices, each of which can have a number of Properties, Actions, and Events.

All communication with the gateway is done via IPC (using nanomsg). I'm actually in the process of fully documenting the IPC system, but for now, here are a couple wiki pages you can check out:
* https://github.com/mozilla-iot/wiki/wiki/Adapter-IPC
* https://github.com/mozilla-iot/wiki/wiki/Adapter-API
