### ISSUE TITLE
Log view: properties and Log data api?

### ISSUE THREAD

**Issue by alexe100** [mozilla-iot/gateway#2188]
Hi all
I finally managed to create my first custom addon (after getting important help from you on).
Now, my addon adapter is able to instantiate devices when they are detected and is also able to update properties of each instantiated device. 

Now I would like to enter in the next level: show properties values and show charts from (special?) logs...  By the way, using console.log() I can see on gateway console all the information related with instantiated devices and related properties and everything is ok.

According to the info in https://hacks.mozilla.org/2019/04/introducing-mozilla-webthings/  it is possible to see logged values on charts which is what I am looking for (for temperatures). Where can I find the LOG API in order to generate info to be seen on charts or how to generate log information able to be seen on charts?

Another question, please: At this time I can have my addon adapter with 2 devices, each device with a property called temperature. Is there any way to see temperate property (value!) in the web interface? If, so, how?

Thank you
Alex

**Comment by tim-hellhake** [comment]
> how to generate log information able to be seen on charts

First, you need to activate the logs in the settings if you haven't already done that.
This should add a new menu item called `Logs`.
There you can create new charts.
You just need to select a device and one of its properties which should be used as a data source for the chart.

**Comment by tim-hellhake** [comment]
> I finally managed to create my first custom addon

Congratulations :)

> Where can I find the LOG API

What do you mean by `LOG API`?
The rest api which is used by the charts in the ui or an api to generate the datapoints which should be shown in the chart?

> how to generate log information able to be seen on charts

First, you need to activate the logs in the settings if you haven't already done that.
This should add a new menu item called Logs.
There you can create new charts.
You just need to select a device and one of its properties which should be used as a data source for the chart.
All your addon needs to do is updating the values of the device properties.

**Comment by tim-hellhake** [comment]
Updating the property: https://github.com/mozilla-iot/example-adapter/blob/0d012d72fd3704aa6431302b02eb20325e734e05/example-adapter.js#L20
Propagating the update to the gateway: https://github.com/mozilla-iot/example-adapter/blob/0d012d72fd3704aa6431302b02eb20325e734e05/example-adapter.js#L21
There is also a method in the node addon which first checks if the value actually changed before propagating it:
https://github.com/mozilla-iot/gateway-addon-node/blob/f032f3116cb3775c58a6afd33065efde6ac9a0d8/lib/property.js#L106

**Comment by tim-hellhake** [comment]
> Is there any way to see temperate property (value!) in the web interface?

Do you see your device in the `things` view?
If not you need to first add it by clicking on the plus sign.
This shows you all discovered devices.
As soon you added the device you can click on the symbol in the upper right of the device to see all its properties.

**Comment by alexe100** [comment]
The logs were already enabled but I could not add a new Log chart because the thing was not created. After your guidance, I created the things and gave it a name and then a new log could be created and shown...
Great!!
Thank you very much once again

Alex
