### ISSUE TITLE
Why does Timer addon does not appear in the Rules editor?

### ISSUE THREAD

**Issue by alexe100** [mozilla-iot/gateway#2191]
Hi
I would like to, from 30secs to 30secs to send and email or sms or push notification if mycustom_addon.temperature is above a specified value
Clock appears in the Rules editor but theirs events could not be periodic, I think. Hence, I tried to locate an addon to do that. I found the timer and added it and configure it giving it a name and a period: 30
When I try to add a new rule, the timer addon does not appear to be dragged. Any help would be very appreciated.

Thanks
Alex

**Comment by tim-hellhake** [comment]
Did you add the newly discovered thing in the things view?

**Comment by tim-hellhake** [comment]
It sounds like this is an issue of the addon rather than the gateway.
It would be better to file the issue directly against the repository of the addon.
The maintainers of the addons know there code best.
You can see all available addons [here](https://github.com/mozilla-iot/addon-list/tree/master/addons).
Every addon has a `homepage_url` which is usually the github repo.
As I'm the creator of the timer addon I'll answer you here 😄.

**Comment by tim-hellhake** [comment]
Did you add the newly discovered timer thing in the things view?

**Comment by tim-hellhake** [comment]
> I would like to, from 30secs to 30secs to send and email or sms or push notification if mycustom_addon.temperature is above a specified value

Do you want to send an email every 30 seconds as long as the temperature is above the threshold?

**Comment by alexe100** [comment]
My god... I am sorry. You have helped me with my custom addon (I also forgot to create a thing with it) and now I made the same mistake, I forgot to create a thing based on timer.
Ok, I have created it already but now it seems that timer must be reset and started by hand, using the buttons!? IS it possible to configure it to fire elapsed event forever?

Yes, my main aim (now just for testing) is to keep sending emails or push notifications as long as the temperature is above x degrees. Is the timer the best input thing to do that?

(PS: I am able already to send emails and push notifs using the clock input thing)

Thank you
Alex

**Comment by tim-hellhake** [comment]
> My god... I am sorry

No need to apologize 😄
I'm happy to help.

> it seems that timer must be reset and started by hand

That is correct.
The addon is designed as a countdown timer.
What you need is an interval timer.

> IS it possible to configure it to fire elapsed event forever

Currently not.
But I can add it if you need it.

**Comment by alexe100** [comment]
Well, as interval timer does not exist yet, at least in the available addons list, I think that a thing like that would be very useful.
Thinking better, may be it could be a nice challenge for me! 
Untill now I only know how to implement custom things with adapters, devices and properties. 
May be it is time to implement a thing (e.g.timer) to fire events forever, hence learning how to have things with events?! (I have to read about that)
If you decided to implement it or extend your timer for that, you are welcome, for sure! :-)

Alex


I need it for sure and maybe someone else...

**Comment by mrstegeman** [comment]
@alexe100 The pulse adapter may suit your need.

**Comment by alexe100** [comment]
Let me check...
Thanks

**Comment by alexe100** [comment]
The problem is that I need it firering forever like this: fire forever every 30 seconds and the adapter must fire an event or property change or ... every 30 seconds, like a periodic timer in a programming language...

**Comment by mrstegeman** [comment]
It's too bad the date-time adapter doesn't have a `second` property, as that would cover your need.

**Comment by alexe100** [comment]
Sure...

**Comment by mrstegeman** [comment]
Couldn't you just call the `reset` action on the timer every time it expires?

**Comment by mrstegeman** [comment]
Or maybe there could be a new `restart` property which would reset the timer AND start it?

**Comment by alexe100** [comment]
Well, I dont know because I am a (still) beginner in the gateway architecture and alike. I found it at two days ago! :-) But I am very impressed!! until now I have just created a basic BLE custom adapter with just one property (temp) in order to deal with a cheap beacon with temp. It works! :-)
Now I would like to send a push notif if temp is too high, for instance. 
Hence I need a timer to test temperature periodically or find a way to detect temperature property change  and use that event in the rule editor. I think I can not simple use if temp > x then send push because it would be always sending, right?
So, the timer seems to be very usefull in order to test temp periodically in order to avoid anoying the user with push notifications or emails

**Comment by tim-hellhake** [comment]
> I have just created a basic BLE custom adapter with just one property (temp) in order to deal with a cheap beacon with temp

I have a similar addon for the ruuvi tags 😁

**Comment by tim-hellhake** [comment]
> I think I can not simple use:" if temp > x then send push" because it would be always sending, right?

If you want to send a notification each time the threshold is crossed then your example rule would be sufficient.
If you want to send continuously notifications as long as the threshold is crossed you need a periodic trigger like the interval timer.

**Comment by tim-hellhake** [comment]
@alexe100 Interval is on the way: mozilla-iot/addon-list#475

**Comment by alexe100** [comment]
"Does your ble beacon also send the temperature in the advertisement packets?"
Yes, my cheap beacon is similar to ruuvitag device. It broadcasts info (no connection needed). 
Now I realize that there is a ruuvitag adapter and that ruuvitag adapter would do the job, just by modifying the source code related to the bytes where the temp is encoded. :-) No problem, it was a way to practice creating adapters...

Ok, my starting requirement would be to send push notifications while temperature is above the threshold from 20 to 20 seconds and Stop sending only when temperature returns to values bellow threshold...
Glad that the new interval timer is being developed... Please, inform us when it is done. ;-)

In the meanwhile I started also to create my (extremely) simple and basic timer adapter. Your would be better for sure but my aim is just learn a little bit more. At the end I will use yours, for sure...
One advice, please:
I am thinking to launch a node timer on the adapter constructr and then when it times out I set the device fired property to 1 and in the next moment (next instruction) set it again to zero, in order to just create one and only one property change event per timer timeout. Then, on the rule editor, I can make a rule using and AND between temp > x and cust_timer.fired==1. Is this acceptable? 

Thanks
Alex

**Comment by tim-hellhake** [comment]
@alexe100

> Glad that the new interval timer is being developed... Please, inform us when it is done. ;-)

@mrstegeman merged it shortly after I wrote here 😬.

> when it times out I set the device fired property to 1 and in the next moment (next instruction) set it again to zero

The gateway has the concept of `events` for this case.
My interval timer fires an `elapsed` event when the timer times out.
This way you don't need the `cust_timer.fired==1` part of your rule.
You can simply select the event as a source.

**Comment by alexe100** [comment]
Hello Tim
My experimental gateway is already working at my home.for now it just monitor the temperature of some home rooms and alerts me by push notifs when temp is greater than 30 degrees. Yes the firts version of  my timer is working. :-)  with property set to 1 and property set to zero. But it is working in a rpi zero w just to test it in this resource poor hardware And evaluate the reliability of disk card when updating temp in ten seconds to see if diskcard breaks or not.
Now in my laptop i willchange timer in order to rely onevents instead of properties as you said.
Thanks a lot for all you attention

Alex

**Comment by tim-hellhake** [comment]
> My experimental gateway is already working

Nice to hear that.

> Thanks a lot for all you attention

You're welcome.
