### ISSUE TITLE
Error when issuing cert

### ISSUE THREAD

**Issue by andrenatal** [mozilla-iot/gateway#220]
@dhylands said:

>  I was trying to create a release and test it, but I got the following error while testing:

```
le.challenges[tls-sni-01].loopback should be defined as function (opts, domain, token, cb) { ... } and should prove (by external means) that the ACME server challenge 'tls-sni-01' will succeed
[le/lib/middleware.js] created middleware
[le-store-certbot] certificates.check
Error: ENOENT: no such file or directory, open '/home/pi/letsencrypt/etc/live/release2.box.mozilla-iot.org/privkey.pem'
[le/lib/core.js] checkAsync failed to find certificates
[le-store-certbot] accountId: null
[le/lib/core.js] calling le.acme.getCertificateAsync [ 'release2.box.mozilla-iot.org' ]
[le/lib/core.js] setChallenge called for 'release2.box.mozilla-iot.org'
[le/lib/core.js] removeChallenge called for 'release2.box.mozilla-iot.org'
Challenge for 'release2.box.mozilla-iot.org' complete. You may remove it.
The CA was unable to validate the file you provisioned. 
 - https://acme-v01.api.letsencrypt.org/acme/challenge/mKKnrHjO7ec_M__r2THE1JXXqkomaCVculGsVNAB5Fs/1558358155 [invalid]
   DNS problem: SERVFAIL looking up CAA for box.mozilla-iot.org
 - https://acme-v01.api.letsencrypt.org/acme/challenge/mKKnrHjO7ec_M__r2THE1JXXqkomaCVculGsVNAB5Fs/1558358156 [pending]
 - https://acme-v01.api.letsencrypt.org/acme/challenge/mKKnrHjO7ec_M__r2THE1JXXqkomaCVculGsVNAB5Fs/1558358157 [pending] null { identifier: { type: 'dns', value: 'release2.box.mozilla-iot.org' },
  status: 'invalid',
  expires: '2017-07-23T21:38:47Z',
  challenges: 
   [ { type: 'dns-01',
       status: 'invalid',
       error: [Object],
       uri: 'https://acme-v01.api.letsencrypt.org/acme/challenge/mKKnrHjO7ec_M__r2THE1JXXqkomaCVculGsVNAB5Fs/1558358155',
       token: '1IPlycB0R7xQzds_QDmG7hp5lhnNazX8DwHarK0TzXg',
       keyAuthorization: '1IPlycB0R7xQzds_QDmG7hp5lhnNazX8DwHarK0TzXg.AwriQXEMHbfGIdgPIyFrWLjzQ-ugwSJaJjJ5mFGfTyg',
       validationRecord: [Object] },
     { type: 'tls-sni-01',
       status: 'pending',
       uri: 'https://acme-v01.api.letsencrypt.org/acme/challenge/mKKnrHjO7ec_M__r2THE1JXXqkomaCVculGsVNAB5Fs/1558358156',
       token: 'McVsKYmm-BGVXT77zYuQ_hJk8g0ZWBeUM9A1LAwsHd0' },
     { type: 'http-01',
       status: 'pending',
       uri: 'https://acme-v01.api.letsencrypt.org/acme/challenge/mKKnrHjO7ec_M__r2THE1JXXqkomaCVculGsVNAB5Fs/1558358157',
       token: '0h63JYSGvJgiqNEZ5MpGdSJLQKLfwfJQigJx1UY0CjI' } ],
  combinations: [ [ 0 ], [ 2 ], [ 1 ] ] }

```

**Comment by dhylands** [comment]
I tried again today, and this seems to be an ongoing error and not just a temporary thing. When I tried using the same name (release2) I just got this:
```
le.challenges[tls-sni-01].loopback should be defined as function (opts, domain, token, cb) { ... } and should prove (by external means) that the ACME server challenge 'tls-sni-01' will succeed
[le/lib/middleware.js] created middleware
```
and when trying with a new name, I get a similar error to the one reported. The fundamental problem seems to be:
```
 DNS problem: SERVFAIL looking up CAA for box.mozilla-iot.org
```

So for the time being it looks like we can't issue new certificates.

**Comment by andrenatal** [comment]
@dhylands I tried to reproduce but got blocked by: https://github.com/mozilla-iot/gateway/issues/222

Are you using the latest master or the version before the refactor?

**Comment by andrenatal** [comment]
Reference: https://community.letsencrypt.org/t/solved-dns-problem-servfail-looking-up-caa-for-mit42-de/20965/2

**Comment by andrenatal** [comment]
Fixed by https://github.com/mozilla-iot/registration_server/pull/16

**Comment by andrenatal** [comment]
`[le/lib/core.js] checkAsync failed to find certificates
[le-store-certbot] success reading arg.accountsDir
[le-store-certbot] regrs.length 2
[le-store-certbot] accountId: bd4bd0b5569e13dd34f080c4b6ba1eef
[le/lib/core.js] calling le.acme.getCertificateAsync [ '35464364364.box.mozilla-iot.org' ]
[le/lib/core.js] setChallenge called for '35464364364.box.mozilla-iot.org'
Validating domain ... done
[le/lib/core.js] removeChallenge called for '35464364364.box.mozilla-iot.org'
Challenge for '35464364364.box.mozilla-iot.org' complete. You may remove it.
Requesting certificate...
Requesting certificate: done
Successfully verified cert at https://acme-v01.api.letsencrypt.org/acme/cert/03f538ce486f91efe898fb88b6f1cc89f857
Requesting issuer certificate...
Requesting issuer certificate: done
[le-store-certbot] writeRenewalConfig privkeyPath /Users/anatal/letsencrypt/etc/live/35464364364.box.mozilla-iot.org/privkey.pem
[le-store-certbot] writeRenewalConfig privkeyPath /Users/anatal/letsencrypt/etc/live/35464364364.box.mozilla-iot.org/privkey.pem
`
