### ISSUE TITLE
Building the image from the latest code fails to load `gateway-addon`

### ISSUE THREAD

**Issue by abhijitnathwani** [mozilla-iot/gateway#2200]
Hi,

I noticed that when we build a fresh image using all the steps and scripts, the `mozilla-iot-gateway service` does not start. On checking the service logs, 
![image](https://user-images.githubusercontent.com/5513984/66045954-59e08780-e542-11e9-821d-1bc185ec1c86.png)

When I manually install `npm install https://github.com/mozilla-iot/gateway-addon-node` the error is resolved and the service starts as expected.

Ideally, we should not be doing this step as the `npm install` is already happening from the `package.json` entries and it does have the `gateway-addon` dependency.

Let me know if some more information is required to reproduce the issue.

**Comment by mrstegeman** [comment]
What's your full process here?

**Comment by abhijitnathwani** [comment]
The image is being built for Raspberry Pi.

1. Clone the repo https://github.com/mozilla-iot/rpi-image-builder
2. Run the `./create-rpxc.sh` script that pulls and sets up the docker image for cross-compiling.
3. Run the `./build-image.sh` script which clones the `gateway` source and builds the `gateway` source and packages it in a tarball.
4. Add that `tar` to the base image prepared by `prepare-base.sh` using the `add-gateway.sh`. 
5. Flash the final image on the SD card.
6. Boot and check the service logs.

**Comment by mrstegeman** [comment]
@dhylands any idea?

**Comment by dhylands** [comment]
Hmm. So I kicked off a build using rpi-image-builder:
https://travis-ci.org/mozilla-iot/rpi-image-builder/builds/592652173

and when I examine the tarball which gets built:
https://s3-us-west-1.amazonaws.com/mozillagatewayimages/tarfiles/master-gateway.tar.gz

The node_modules/gateway-addon subdirectory only has a package.json file. None of the other files seem to be present.

**Comment by mrstegeman** [comment]
I assume `git` is available to the builder, right? The gateway-addon module pulls a git submodule now.

**Comment by abhijitnathwani** [comment]
@dhylands Thank you for triggering the build. This will help point another issue I noticed( or may be the root cause for this?). If you check the build logs, the `npm install nanomsg` fails. https://travis-ci.org/mozilla-iot/rpi-image-builder/builds/592652173#L296
and here https://travis-ci.org/mozilla-iot/rpi-image-builder/builds/592652173#L3415.
If I am not wrong, this wasn't happening until recently. I am seeing this behavior in the build since a day. The `nanomsg` eventually compiles here: https://travis-ci.org/mozilla-iot/rpi-image-builder/builds/592652173#L4610 

The error comes twice and it rebuilds `nanomsg` twice.


> I assume `git` is available to the builder, right? The gateway-addon module pulls a git submodule now.

@mrstegeman  the builder clones the `gateway` code [here](https://travis-ci.org/mozilla-iot/rpi-image-builder/builds/592652173#L222). So `git` is present.

**Comment by mrstegeman** [comment]
@dhylands figured out that it's because of the way we cross-compile things. He's working on a solution.

**Comment by dhylands** [comment]
Building twice is normal. We build a development build the first time so that we get webpack.

We then build a production build and pack it using webpack.

The nanomsg build problem should be fixed by https://github.com/mozilla-iot/gateway/pull/2204

**Comment by abhijitnathwani** [comment]
@dhylands 
https://travis-ci.org/mozilla-iot/rpi-image-builder/jobs/592652174#L125
The `DEV_BUILD=0`. It shouldn't build again for the production as per the [condition](https://github.com/mozilla-iot/gateway/blob/master/image/build-gateway.sh#L64)

**Comment by dhylands** [comment]
@abhijitnathwani 
The condition is `if [ "${DEV_BUILD}" != "1" ]` (i.e. the condition is satisifed when DEVBUILD is set to 0).

We always do the dev build, because webpack (needed to do the production build) is considered a devDependency.
Once we have webpack we then remove node_modules and rebuild the production build unless DEV_BUILD is 1.
Seems a bit backwards, but webpack takes up quite a bit of space and is only needed to create the production build, but not needed to actually run the production build.
So by doing it this way we make the final image quite a bit smaller.

**Comment by abhijitnathwani** [comment]
Yes. Got it. My bad understanding of the condition. I got confused. Thanks for the update @dhylands

**Comment by dhylands** [comment]
I just triggered another build https://travis-ci.org/mozilla-iot/rpi-image-builder/builds/592716551 (using the latest master) and it looks good. I'm just writing an sdcard to test on a real pi.

**Comment by dhylands** [comment]
And it looks good now, so you should be able to use the updated build-gateway.sh script to build your Pi image.

I think that you can trigger builds as well using the trigger-build.sh script found in the rpi-image-builder, but I'm not 100% sure.
