### ISSUE TITLE
Move mozilla-iot.org registrar from fasthosts to Amazon route 53

### ISSUE THREAD

**Issue by andrenatal** [mozilla-iot/gateway#221]

**Comment by andrenatal** [comment]
@benfrancis can you take care of this one, please?

**Comment by benfrancis** [comment]
@andrenatal I don't have access to the AWS account, but you have access to both. I can unlock the domain and give you a transfer code if it helps? The only step you should need me for is the email confirmation on the Fasthosts end as I'm listed as the admin contact.

https://help.fasthosts.co.uk/app/answers/detail/a_id/252

**Comment by andrenatal** [comment]
Hi @benfrancis, yes that will help. When you have a chance, just forward it to me. I think moving to Amazon will help us to fix and not incur on errors like this: https://github.com/mozilla-iot/gateway/issues/220 anymore since Route 53 allows more customization to the DNS server than fasthosts.

**Comment by andrenatal** [comment]
We do not need amazon 53 anymore since now the whole TLD will be managed by the registration server.
