### ISSUE TITLE
Set the time it takes for a thing to 'timeout'.

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#2210]
Some [MySensors users asked](https://forum.mysensors.org/topic/10674/mysensor-things-show-up-as-active-when-they-are-unplugged) out 'timeouts' that would set a thing to `inactive`.

Does the gateway set devices to 'offline' if it hasn't seen them in a while? Or should the add-ons manage this?
If the gateway does it, how long does it take before it is set as 'unavailable'?

**Comment by mrstegeman** [comment]
No, the add-on should do that. You can use [device.connected_notify()](https://github.com/mozilla-iot/gateway-addon-python/blob/master/gateway_addon/device.py#L199-L205) for that.
