### ISSUE TITLE
can't connect RPi to Wi-Fi network that is open SSID but no password

### ISSUE THREAD

**Issue by kgiori** [mozilla-iot/gateway#2213]
Tried twice to connect the RPi to a Wi-Fi network that has no password. Would require /etc/wpa_supplicant/wpa_supplicant.conf to look like this:
```
network={
        ssid="Museum"
        key_mgmt=NONE
}
```

After manually inserting the config data into the file, similar to above, the connection via Wi-Fi worked fine.

**Comment by benfrancis** [comment]
Hi @kgiori, when you get chance could you test this with a freshly flashed gateway? @mrstegeman wasn't able to reproduce. It is possible there's something unusual about the network you're connecting to though.

**Comment by mrstegeman** [comment]
I confirmed on a freshly flashed RPi that connecting to an open network works fine. The `wpa_supplicant.conf` looks exactly as it should.
