### ISSUE TITLE
First time setup broken

### ISSUE THREAD

**Issue by andrenatal** [mozilla-iot/gateway#222]
After update my repo and run `npm start` I am getting the following error:

`Error: ENOENT: no such file or directory, stat '/Users/anatal/projects/mozilla/wot/gateway/build/views/tunnel_setup.html'`

Maybe the refactor broke the tunnel setup? I can't see this page in the repo anymore.

**Comment by benfrancis** [comment]
@andrenatal The file is here https://github.com/mozilla-iot/gateway/blob/master/src/views/tunnel_setup.html It moved from views/ to src/views which I guess broke your sendFile call https://github.com/mozilla-iot/gateway/blob/c0d902829a410a5ec4feb5379ac04de0161552f1/src/tunnel_setup.js#L39

CC @lightsofapollo
