### ISSUE TITLE
Unable SSH to IoT Gateway via mozilla-iot.org subdomain

### ISSUE THREAD

**Issue by elfgoh** [mozilla-iot/gateway#2222]
Say I have a gateway connected to foobar.mozilla-iot.org, and I turn enable ssh on the gateway, should I be able to ssh in directly via command `ssh pi@foobar.mozilla-iot.org` over the internet?

By default, my pi has been setup to use password authentication, though I have also added my ssh public key to the list of authorized keys. But either way, I can't ssh and get the error `Permission denied (publickey).`. 

However, if I connect to the same network that the gateway is on, I can ssh using the ip address eg `ssh pi@192.168.0/53`, either using password or ssh key

Question: Is the gateway behaving as intended, and blocking ssh attempts from the internet, or is there something else I missed? Thanks!

**Comment by mrstegeman** [comment]
No, the only thing that's tunneled is the HTTPS port. SSH must be done locally, unless you manually set up some other method of doing it through the internet.
