### ISSUE TITLE
Values should be rounded as-per multipleOf

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#2224]
The easiest way to see this is to modify the virtual things adapter. Change the heatingTargetTemperature from 19 to 19.66667 and then add a multipleOf: of 0.1

Then when you view the thermostat it shows the value as 19.66667 with a red border (since 19.66667 isn't valid) instead of showing it as 19.7

I first saw this with a zwave thermostat that reports in F. However since the spec want C we convert F to C, which causes values which don't fit nicely into the multiupleOf:

**Comment by mrstegeman** [comment]
I’ve been undecided about where this should be handled: in the adapter/thing or in the gateway? The same issue exists for things like minimum/maximum.

**Comment by dhylands** [comment]
If we put it in the adapter then every adapter will need to have code to deal with it.

For minimums/maximums it probably makes sense to display the out-of-spec value (if read) but clamp it if the user tries to change it. If the value is outside the min/max then probably means that there is an issue with the adapter/device.

multipleOf is really just a user-convenience feature for displaying values, so I think that all values should be adjusted consistently and I think it makes the most sense to do this on the gateway side.

**Comment by mrstegeman** [comment]
multipleOf is not just a user convenience; it is also used the other direction when setting values.

It seems to me that if an adapter is dictating a minimum, maximum, multipleOf, or any other limiting factors, it should be the one handling that. We do apply such things to inputs and such via min/max/step values, and we do have a [default handler](https://github.com/mozilla-iot/gateway-addon-node/blob/master/lib/property.js#L167-L198) when setting values, but it again, it seems like the adapter should be able to handle adjusting its own readings, rather than relying on the gateway. Just my 2 cents.

**Comment by dhylands** [comment]
ok - it just seems to me then that we'll have a bunch of duplicated and not necessarily identical implementations.

**Comment by dhylands** [comment]
I guess zigbee and zwave don't care on the values coming from the user.

I agree that if the adapter cares, it should apply the min/max/multipleOf on values which are coming from the UI to the adapter.

In the other direction, though, we're currently using multipleOf mostly to make up for shortcomings in the UI, which has no ability to "adjust" for reasonable values, and in fact that's the only reason (currently) for the zigbee or zwave adapters to even use multipleOf

**Comment by mrstegeman** [comment]
I can make a small change to the UI that will round off values.

**Comment by tim-hellhake** [comment]
> Change the heatingTargetTemperature from 19 to 19.66667 and then add a multipleOf: of 0.1

Wouldn't that be a bug in the addon?
What's the point of reporting `multipleOf` as 0.1 when the actual precision of the values is 0.00001?

> it just seems to me then that we'll have a bunch of duplicated and not necessarily identical implementations

Reporting the correct value for `multipleOf` wouldn't require any new code.

**Comment by dhylands** [comment]
The extra decimal places come into play when say a temperature sensor only reports in F, but our spec days that it needs to be in C.

Reporting degress celsius beyond one digit after the decimal point doesn't seem particularly useful.

I'm not even sure that the adapter can do the correct thing anyways. In order to take a floating point number and report it to X digits after the decimal requires converting it to a string, but then its not a number any more.

**Comment by dhylands** [comment]
Since the numbers need to be converted to strings to perform the rounding properly, the rounding has to happen in the UI.
