### ISSUE TITLE
How to stop RPI gateway 'service' and launch it on console?

### ISSUE THREAD

**Issue by alexe100** [mozilla-iot/gateway#2229]
Hello
Until now I have used ubuntu in order to get started with gateway. From the command line I used to execute 
npm start
in order to start GW ans see all logging.
Now I am trying GW in RPI using the gateway system image on the micro SD card.
Now I am facing a problem in a addon and it would be very useful to see the log. Hence I tried to stop service like : sudo service mozilla-iot stop but without success. I searched in the systemd for the service name without success.

My question is: how to shop gateway running on RPI and launch it again in console (on demand)?

Thank you
Alex

**Comment by mrstegeman** [comment]
```bash
sudo systemctl stop mozilla-iot-gateway
cd ~/mozilla-iot/gateway
npm run run-only
```
