### ISSUE TITLE
Adjust automatically for daylight savings time changes

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#2240]
As a user I want my rules to automatically update when daylight savings time changes so that I don't have to manually shift all my rules by one hour twice a year

**Comment by benfrancis** [comment]
See also https://discourse.mozilla.org/t/weird-summer-time-behaviour/47563/2

**Comment by mrstegeman** [comment]
This is actually a duplicate of #808, and should be fixed by #2227.
