### ISSUE TITLE
Missing One Wi-Fi Network From List

### ISSUE THREAD

**Issue by eode** [mozilla-iot/gateway#2245]
During initial setup, the first question it asks (when you connect to the setup wifi network) is what network to use.  This list was blank.  I'm in a rural area, and there was only one wi-fi access point -- mine.

I couldn't figure out what it was for a bit, but then tried creating another access point (from my phone).  That didn't show up, but my home wi-fi did.

It seems like the list is one access point short -- and if there's only one to show, it doesn't show at all.

**Comment by mrstegeman** [comment]
This is actually just due to the wi-fi scanning software in Raspbian (`iwlist scanning`). Refreshing the page actually re-scans, so that would be a good way to get the network to come up. Admittedly, refreshing is not always an option in captive portal displays, but it is in the browser.

**Comment by mrstegeman** [comment]
@eode My fault, there actually _is_ an issue. Fix incoming.

**Comment by eode** [comment]
Thanks!
