### ISSUE TITLE
Rearranging the order of things in a rule doesn't change either the logic or action order

### ISSUE THREAD

**Issue by montyrwalls** [mozilla-iot/gateway#2247]
Rearranging the order of things in a rule doesn't change either the logic or action order.  The only way to do this is to delete all the things in front of the selected thing and re-add them.

**Comment by mrstegeman** [comment]
Are you just wanting to rearrange them for aesthetic purposes? The logic would not change at all.

**Comment by montyrwalls** [comment]
I had assumed that for logic it was subject to short-circuit boolean evaluation, and that for the actions, they were performed in order (timer reset/start being an example).

**Comment by mrstegeman** [comment]
I see what you’re getting at. Short circuit evaluation for these basic rules isn’t really going to gain you much. As for the outputs, none of them are actually synchronous, so even if you get them in the order you want, they won’t necessarily finish in that order.
