### ISSUE TITLE
Can't tell if fix has shipped

### ISSUE THREAD

**Issue by hwine** [mozilla-iot/gateway#2250]
As a Gateway user, I'm interested in when a bug fix has been shipped, rather than fixed-but-not-released.

For example, I was about to file a bug for the DST issues, which appear to be fixed by a1f670be71b20565e761dc85f5bc1a6e0c022ed9, so local issue #808 is closed. Only by checking the release version and commit dates could I determine that I don't yet have this fix.

If would be wonderful if there was a label that was applied when fixes/enhancements actually shipped to non-bleeding-edge users. It might even cut down on the number of duplicates filed. ;)

**Comment by mrstegeman** [comment]
You can look at the milestone on the GitHub issue, which says 0.10. I try to keep those updated as much as possible.
