### ISSUE TITLE
wifi SSID names duplication

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#2254]
While giving a workshop yesterday I came across a very strange situation:

![mozgateway-weird-wifi](https://user-images.githubusercontent.com/805405/68204398-c9bdb400-ffbf-11e9-9713-f93c29778308.png)

The list was actually about three times as long as the screenshot shows.

Perhaps related to https://github.com/mozilla-iot/gateway/issues/2015

**Comment by mrstegeman** [comment]
Was this using an 0.9.X release?

**Comment by flatsiedatsie** [comment]
I'm not sure anymore. I did indeed use an upgraded 0.8-to-0.9.2 Gateway that evening (which caused a lot of trouble), so it could indeed have been with the old version.

**Comment by mrstegeman** [comment]
@flatsiedatsie Have you seen this recently? Wondering if this has been fixed.

**Comment by flatsiedatsie** [comment]
We can close this, and I'll reopen it if it occurs again.
