### ISSUE TITLE
Hostname not always working

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#2255]
This is not really a concrete issue or bug, but I've noticed that often typing in the _gateway.local_ hostname in the browser to continue setup doesn't work.

I've given a lot of workshops and created a lot of Gateway images in various locations. I've noticed how very differently routers can handle things.

- Sometimes the router may hand out gateway.**lan** as the name. E.g. my Gl.Inet router (which is openWRT based) does this.
- Sometimes a reboot of the Raspberry Pi fixes the issue.
- Sometimes it just doesn't work, and I have to use a network scanner to find the IP address. But this doesn't always work (as happened yesterday).
- I've also noticed that sometimes my (mac) laptop does find it, but a participants (windows) laptop does not.

It would be great if this could be made more robust somehow. I don't know if this is possible, but perhaps have the hotspot stay active while it tries connecting to the new network, and then show the actual IP address on the other network in the captive portal window (I know @dhylands was working on something like this a while ago). If that's not possible, perhaps the gateway could do a connection test, and then go back into captive portal mode with the results. There the user could be presented with the IP address/hostname that the system will have on the new network?

Alternatively, perhaps during initial setup phase the system could 'notice' that despite being on the new network, it hasn't actually been connected to for ten minutes, and revert back to hotspot state?

As a side-note, this is where having a (touch-)screen attached to the Raspberry Pi shines. It makes it so easy to see the IP address of the system.

**Comment by mrstegeman** [comment]
Sadly, this is just a pitfall of using mDNS.
* Sometimes, routers do whatever they want and ignore mDNS.
* Linux machines have to be set up to do mDNS hostname resolution, which is not always done by default.
* Windows won't do mDNS hostname resolution by default unless Apple's Bonjour software is installed. Even then, it won't do it in all cases.

The long-running hotspot or double captive portal solution seems like a good idea, but it caused many more headaches than it was worth. Also, we can't keep the original AP running while connecting to the second wi-fi network, as Raspbian won't let us do that.

If we had a native mobile app or something, we could use some other discovery mechanism, e.g. SSDP (which, sadly, also fails sometimes). We're definitely open to other suggestions, but right now, mDNS is the best we have.

**Comment by flatsiedatsie** [comment]
I understand.

How about the idea of using the 'hotspot -> user inputs password -> turn off hotspot, test connection to new network, check which hostname/DNS is has there -> disconnect, re-enable hotspot -> user is informed/agrees` option? 

Or how about an option to revert to the hotspot state if the gateway is rebooted while the setup phase is not complete? Then at least there is an opportunity to try again with perhaps a different wifi network?

**Comment by mrstegeman** [comment]
There's not really a good way for the gateway to tell if mDNS is going to work for the user.

As for reverting upon reboot... that's not a bad idea. @benfrancis thoughts?

**Comment by benfrancis** [comment]
> As for reverting upon reboot... that's not a bad idea. @benfrancis thoughts?

If the gateway fails to connect to a Wi-Fi network then as I understand it it should already revert to a hotspot.

If the gateway successfully connects to a Wi-Fi network but mDNS is not working, then clearing Wi-Fi credentials is not really going to fix anything. Especially if the mDNS problem is client-specific. It's just going to create more work for the user to re-connect to the network and create confusion if they try to manually look its IP address on the network but it isn't connected.

Am I missing anything?

**Comment by mrstegeman** [comment]
> If the gateway fails to connect to a Wi-Fi network then as I understand it it should already revert to a hotspot.

Well, yes and no. During first time setup, if the password is typed wrong, the gateway has to be rebooted (see #1900). After that point, though, yes, it will return to AP mode.

> If the gateway successfully connects to a Wi-Fi network but mDNS is not working, then clearing Wi-Fi credentials is not really going to fix anything. Especially if the mDNS problem is client-specific. It's just going to create more work for the user to re-connect to the network and create confusion if they try to manually look its IP address on the network but it isn't connected.
> 
> Am I missing anything?

That's very true. I suppose it doesn't really solve anything at all. I was thinking less about this case and more "wait, what was I supposed to do?", but even in that case, reverting back to Wi-Fi setup doesn't seem beneficial.

I'm going to close this issue since there's nothing we can really do about mDNS failures on the client side.

**Comment by flatsiedatsie** [comment]
The issue is not "If the gateway successfully connects to a Wi-Fi network but mDNS is not working". The issue is a broader "the gateway succesfully connects to a Wi-Fi network but the user seems unable to then access the gateway".

> It's just going to create more work for the user to re-connect to the network and create confusion if they try to manually look its IP address on the network but it isn't connected.

The distinction is that the user has to power-cycle the gateway for it to revert to the hotspot state, which is proposed to mean "I was unable to reach the gateway somehow, and would like to try again".

I have been in this situation myself when giving workshops (IP scan failed too, no access to the router), and the only way out of it was to reflash the image onto the SD card.

**Comment by createcandle** [comment]
See also: https://github.com/mozilla-iot/gateway/issues/1994#issuecomment-560370459
