### ISSUE TITLE
Certificate renewal failure

### ISSUE THREAD

**Issue by gucci-on-fleek** [mozilla-iot/gateway#2260]
The certificate on my Gateway expired sometime yesterday and the renewal keeps failing. The relevant portion of the log is [here](https://gist.github.com/gucci-on-fleek/eefb2d417fc84949af69eb01df241ac1) and I've put the a small excerpt below:
```
2019-11-06 03:10:29.093 ERROR  : Failed to renew certificate: Error: certificate has expired
…
    code: 'CERT_HAS_EXPIRED'
```
The error seems a little odd since I'm trying to renew the certificate _because_ it's expired. I've restarted the Gateway a few times and I keep getting the same error. I'm able to connect locally, but I can't connect externally because HSTS won't allow me to bypass the expired certificate. I'm running version [8310dc20430abcc8bdf784934a80fcee6ddcba0d](https://github.com/mozilla-iot/gateway/tree/8310dc20430abcc8bdf784934a80fcee6ddcba0d) on Node 12 in Alpine Linux if that's relevant.

Thanks!

**Comment by mrstegeman** [comment]
Could you set the DEBUG flag in `src/certificate-manager.js` to true and then restart the gateway?
https://github.com/mozilla-iot/gateway/blob/8310dc20430abcc8bdf784934a80fcee6ddcba0d/src/certificate-manager.js#L23

Also, can you verify that the time is set correctly on your gateway, via `date`?

**Comment by gucci-on-fleek** [comment]
Here you go: https://gist.github.com/gucci-on-fleek/772bf6b4ef514bf2b6f25c1969c1f59c
I enabled the `DEBUG` flag but it didn't do to much. The time is definitely correct though. I put my system info in the Gist above in case that helps with anything.

**Comment by mrstegeman** [comment]
Thank you for all of the details! Would you be willing to test #2261?

**Comment by gucci-on-fleek** [comment]
Yep, that solved it. The certificate renewed and everything is working as it should. Thanks!

**Comment by mrstegeman** [comment]
Great!
