### ISSUE TITLE
Small issues in beta of 0.10.0

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#2273]
Just some small things I noticed:

- When creating a new user, the number "400" briefly showed up in the page, in a yellow color. The new user was created though. Could be case of 'double click'.
- When removing an add-on (Candle Manager), I noticed this in the console:
```
 Failed to uninstall add-on: Candle-manager-addon
TypeError: el is null
```
This could also be a case of 'double click' (the real issue: there is no UI feedback after clicking on 'remove').
- In Firefox, when using the mobile testing tool (Galaxy S9), and visiting the rules page with a single rule, it seems the rule doesn't actually fit on the screen. The CSS says a rule's minimal width is 32rem. It seems odd that a very common, modern phone wouldn't be able to fit a single rule normally?

![gateway_rule_doesnt_fit](https://user-images.githubusercontent.com/805405/68546696-23175000-03d1-11ea-90d2-bb160d8cba59.png)

**Comment by flatsiedatsie** [comment]
I created a "HeatingCoolingProperty" on a test thermostat device, which is updated with a string value of "off" or "heating".

```
                if new_sub_type == 47: # V_TEXT
                    self.properties[targetPropertyID] = MySensorsProperty(
                        self,
                        targetPropertyID,
                        {
                            '@type': 'HeatingCoolingProperty',
                            'label': new_description,
                            'type': 'string',
                            'enum': [
                                'off',
                                'heating',
                                'cooling',
                              ],
                            'readOnly': True,
                        },
                        values, new_value, new_node_id, new_child_id, new_main_type, new_sub_type)
```

Yet when I look at the property in the Gateway, it has very different options:
![theromstat_strange_values](https://user-images.githubusercontent.com/805405/68606396-495aef80-04a6-11ea-93ee-2f31b41fb901.png)

My code doesn't provide those `min, normal, max, auto` options anywhere. But I also don't see them anywhere in the thermostat specifications?

They are a part of the [HVAC_SPEED specification](https://www.mysensors.org/download/serial_api_20) of MySensors, but my device doesn't have that property, and there is no code that would transpose those values to the gateway somehow.

Also, this test device doesn't have a real temperature sensor connected, so the temperature value isn't transmitted at any point, meaning it hasn't created a `temperature` property either. The thermostat value in the central bubble is set to 0, which is probably the result of this. This is not a bug, but just interesting to see what happened if part of the compulsory properties isn't provided.

(all of this is on the second release candidate of version 0.10.0)

**Comment by flatsiedatsie** [comment]
I think I found the issue. It's a routing error on my side.

**Comment by mrstegeman** [comment]
> * When creating a new user, the number "400" briefly showed up in the page, in a yellow color. The new user was created though. Could be case of 'double click'.

https://github.com/mozilla-iot/gateway/pull/2277

> * When removing an add-on (Candle Manager), I noticed this in the console:
> 
> 
> ```
>  Failed to uninstall add-on: Candle-manager-addon
> TypeError: el is null
> ```
> 
> This could also be a case of 'double click' (the real issue: there is no UI feedback after clicking on 'remove').

#2276 

> * In Firefox, when using the mobile testing tool (Galaxy S9), and visiting the rules page with a single rule, it seems the rule doesn't actually fit on the screen. The CSS says a rule's minimal width is 32rem. It seems odd that a very common, modern phone wouldn't be able to fit a single rule normally?

This is part of a much larger issue with the rule layout on small screens that is going to require a lot of design effort.

**Comment by flatsiedatsie** [comment]
Wow, those are some lightning fixes!
