### ISSUE TITLE
browser notifications are not showing

### ISSUE THREAD

**Issue by nylki** [mozilla-iot/gateway#2291]
I do not get browser notifications when they should be send via a rule. I tested it with a basic time-based rule. Other actions like toggling a light did work via rules.

I use Firefox 70 on Fedora 31, Gnome, Wayland. Tried Firefox-wayland and the regular X11 Firefox. 

Below is a screenshot of my setup.
![2019-11-16_20-35](https://user-images.githubusercontent.com/1710598/68998321-0edfc100-08b1-11ea-8930-c1e5df068c50.png)

**Comment by mrstegeman** [comment]
Browser notifications require that you are using HTTPS, so they will only work if you use the tunnel service (XYZ.mozilla-iot.org) or you set up your own do,main and certificates.

**Comment by nylki** [comment]
@mrstegeman 
Thank you for the explanation. I created a self-signed certificate via https://github.com/mozilla-iot/gateway#download-and-build-gateway and https://stackoverflow.com/questions/50788043/how-to-trust-self-signed-localhost-certificates-on-linux-chrome-and-firefox so that I don't have to add a security exception and get a green/full lock.

Still, I don't seem to be able to receive any browser notifications. Is there anything else I forgot?

![2019-11-16_23-38](https://user-images.githubusercontent.com/1710598/69000081-6b9ba580-08ca-11ea-87a4-b59ea46e8309.png)

**Comment by nylki** [comment]
btw. `window.isSecureContext` returns `true`

**Comment by mrstegeman** [comment]
The problem is still the same. In order for your browser to receive a push notification, it has to be able to communicate back and forth with the [Mozilla Push Service](https://mozilla-push-service.readthedocs.io/en/latest/). Since you're running locally only, and using a self-signed certificate, that's not going to work.

**Comment by mrstegeman** [comment]
What you may want to do is look into some of the notifier add-ons, as they can use other means of notifying you.

**Comment by nylki** [comment]
> The problem is still the same. In order for your browser to receive a push notification, it has to be able to communicate back and forth with the Mozilla Push Service. Since you're running locally only, and using a self-signed certificate, that's not going to work.

I see. I was under the impression the [Notification API](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API)  was used, which if I understand the architecture correctly, would not require an external service, since the notifications would be created and dispatched on the client itself, which could be triggered via WS call from the gateway. I was not aware of the Push API and its capabilities yet.

> What you may want to do is look into some of the notifier add-ons, as they can use other means of notifying you.

Thank you for the hint, will certainly do! If I don't find something fitting I may look into writing an addon to do just that, if I find time and motivation :)

It would still be nice to be able to receive non-push notifications as a fallback by the pre-installed notification module. Or atleast have a warning that the current setup doesn't support Push Notifications.

**Comment by mrstegeman** [comment]
The problem with the Notification API is that you can only receive notifications when the page is open. With the Push API, you can get them anytime. We've found that it's often unreliable, and not even supported at all on iOS, which is part of the reason we added notifier add-on support.
