### ISSUE TITLE
Thing GUI not showing real numbers

### ISSUE THREAD

**Issue by atirage** [mozilla-iot/gateway#2295]
Lately I have noticed that the thing GUI is not showing real numbers, i.e. it's always rounding to the nearest integer.
For ex. for the following JSON :
{
  "pressure": 0.97,
  "motion": 1,
  "light": 0.9,
  "temperature": 22.4
}
the GUI looks like this:
![image](https://user-images.githubusercontent.com/2630602/69082262-0669c080-0a40-11ea-9073-226e492225e5.png)
I'm pretty sure this was working fine in the past, so was there any change around the API/WoT spec or is there a bug somewhere?
My webThing is based on the 0.12.0 Milestone of the Python implementation.

Thanks in advance!

**Comment by mrstegeman** [comment]
You'll need to add `multipleOf: 0.1`, for example, to your numeric properties if you want additional decimal places to be shown. That's how we figure out precision in the UI.

**Comment by atirage** [comment]
Thanks for the hint! Working as expected.

**Comment by jaychub** [comment]
> You'll need to add `multipleOf: 0.1`, for example, to your numeric properties if you want additional decimal places to be shown. That's how we figure out precision in the UI.

Hello i'm facing similar issue, and i do not understand your answer, add `multipleOf: 0.1` where exactly?
i'm using Arduino: and declaring my temp property as the following:
ThingProperty InternalTemp("CPUTemperature", "CPU Temperature", NUMBER, "TemperatureProperty");

can you please show me where i should add teh above?
thanks
