### ISSUE TITLE
duplicated ID's in html?

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#2296]
Looking through the gateway html, I noticed multiple 'things' can have child elements with recurring `id`. E.g. "contaciner" and "icon".

According to the html specification, an ID should be unique? Perhaps these things should be classes instead? Or am I overlooking something?

Example:

```
<div id="container" class="webthing-multi-level-switch-capability-container on">
    <div id="info" class="webthing-multi-level-switch-capability-info">
      <div id="bar" class="webthing-multi-level-switch-capability-bar" style="background: rgba(0, 0, 0, 0) linear-gradient(white, white 100%, rgb(93, 155, 199) 100%, rgb(93, 155, 199)) repeat scroll 0% 0%;"></div>
      <div id="label" class="webthing-multi-level-switch-capability-label">0</div>
    </div>
  </div>
```

It's almost as if the ID's and Classes are switched.

**Comment by mrstegeman** [comment]
Each of the top-level capability containers, as well as each property container, is implemented as a [Web Component](https://developer.mozilla.org/en-US/docs/Web/Web_Components). Each of these components has its own [Shadow DOM](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM). The elements inside the Shadow DOM are encapsulated and do not affect those outside, so each Shadow DOM can use the same IDs and such.

**Comment by flatsiedatsie** [comment]
I'm reading up on it now. Interesting stuff.
