### ISSUE TITLE
How does smart assistant works ? [Sorry, I didn't understand that.]

### ISSUE THREAD

**Issue by andreabenini** [mozilla-iot/gateway#2301]
I've inserted few Appliances in my WebThings installation (RPi3) and I've also enabled the smart assistant. I'm not expecting that much because I have found it in the experimental features but I cannot even get any documentation on it. I'm not worried about the generic [Sorry, I didn't understand that.] message but hopefully would be nice to understand what kind of configuration or features I need to setup in order to get it working.
I don't know what can I ask it or available commands. I'm now typing on the textbox but I cannot get a different message.
I don't have Alexa or Google Home so I'd like to know how it works and minimum requirements for it. Is there a wiki or a doc page related to it ?

Thanks

**Comment by mrstegeman** [comment]
This is a pretty decent summary of the current command list: https://github.com/mozilla-iot/gateway/blob/master/src/controllers/commands_controller.js#L6-L16

**Comment by flatsiedatsie** [comment]
If you have a USB microphone, try the Voco add-on :-)

**Comment by andreabenini** [comment]
I was thinking about some sort of offline virtual assistant with builtin logic inside.  
I have carefully taken a read at the source code but it's not what I thought.  
As a noob I need to focus on module creation before evaluating it, I'd like to add some sort of command interaction without depending on online assistants. I'll probably deal with NLTK+NLP+Python+... later on and integrate them with this assistant.

**Comment by mrstegeman** [comment]
To be clear, the only part of this process that requires you to be connected to the internet is STT.

Voco has its own intent parser, while the voice add-on and the gateway share a very basic intent parser.
