### ISSUE TITLE
Addon list not updating after Version swtich

### ISSUE THREAD

**Issue by tklitschi** [mozilla-iot/gateway#2310]
Hey,
After changing from master to v.0.10.0 branch and install it again/run it again, add-on list is not updating. 

## Steps to reproduce
- git clone 
- npm install && npm start
- stop process and delete git repi and ~/.mozila-iot 
- install again

Using nix-shell to run it on nix-os.

**Comment by mrstegeman** [comment]
Can you post one of your logs from `~/.mozilla-iot/log` please?

**Comment by tklitschi** [comment]
Sure

## run-app.log.2019-11-22                                                                                                                                                                     
2019-11-22 21:36:43.881 INFO   : Failed to import platform utilities for linux-unknown. Network and system configuration features will be disabled.
2019-11-22 21:36:44.068 INFO   : Creating database: /home/tk/.mozilla-iot/log/logs.sqlite3
2019-11-22 21:36:44.155 INFO   : HTTP server listening on port 8080
2019-11-22 21:36:44.396 INFO   : DNS config is: eddi
2019-11-22 21:36:44.397 INFO   : Service Discovery: changing profile - local domain is now: eddi
2019-11-22 21:36:44.398 INFO   : Service Discovery: state changed to: true
2019-11-22 21:36:54.458 INFO   : Checking for add-on updates...
2019-11-22 21:36:54.746 INFO   : Finished updating add-ons
2019-11-22 21:37:12.460 INFO   : Tunnel name is set to: Not set.
2019-11-22 21:37:12.460 INFO   : Local mDNS Service Domain Name is: eddi


Thats all in there so far.

**Comment by mrstegeman** [comment]
```
2019-11-22 21:36:54.458 INFO : Checking for add-on updates...
2019-11-22 21:36:54.746 INFO : Finished updating add-ons
```

Looks like it updated just fine. What's the specific issue you're seeing, or what are you expecting to happen that isn't?

**Comment by tklitschi** [comment]
looking for tp-link Addon. This need at least v0.10.0.

**Comment by mrstegeman** [comment]
Add-ons are installed in the UI via _Settings -> Add-ons_, then clicking the + button in the bottom right.

**Comment by tklitschi** [comment]
^^ Yea I know but theres no tp-link addons even so I'm runnung v0.10.0

**Comment by mrstegeman** [comment]
I’m still unclear about what’s happening. Could you take a screenshot of the settings pages? The Add-ons page, and then the page after you click the + button.

**Comment by tklitschi** [comment]
Really? 

I cloned the master branch. 
run npm install and then npm start. 
Went to localhost:8080 and clicked threw the setup. 
checked that tp-link addon needs at least v0.10.0, so I stopped the process, checked out to branch v0.10.0 and ran npm install and start again. 
Even though I deleted the hole ~/.mozilla-iot folder the tp-link addon was not visible. 
I tried it multiple times. 

When the first time I install gateway on another machine and it's on branch v0.10.0, I can see the addon, but when I had swtiched the branch, the addons were not updated properly. 

This also happens when you switch from v0.10.0 to master. The TP-link addon is still visible even though it's not supported in the master Version. 

Hope you understand me now ^^ :)

**Comment by mrstegeman** [comment]
The TP-Link add-on will basically work with any gateway version since 0.5, I believe, including master. The only requirement is that you have Python 3.5+ installed, as well as the gateway_addon library from [here](https://github.com/mozilla-iot/gateway-addon-python).

When you install add-ons, they are installed to `~/.mozilla-iot`. So, when you’re deleting that directory, you’re also deleting the add-on and will have to reinstall it.

**Comment by tklitschi** [comment]
Ok, it was some problem with loacal Issue and symlinks that Python was not loading properly. Thanks for youre help :)
