### ISSUE TITLE
deb package

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#2321]
As a user I want to install the gateway application from a deb package on my existing Raspbian/Debian/Ubuntu system so I don't have to flash a whole OS image and can run the gateway alongside other software

**Comment by benfrancis** [comment]
Note to self:
- https://wiki.debian.org/HowToPackageForDebian
- https://wiki.debian.org/DebianRepository/Setup

**Comment by gucci-on-fleek** [comment]
I've got a working setup for making .deb packages.
https://github.com/gucci-on-fleek/gateway-deb-package
At this point it's just the absolute minimum to make a package, but it works fairly well. I've got [successful builds](https://github.com/gucci-on-fleek/gateway-deb-package/releases) for [Ubuntu](https://github.com/gucci-on-fleek/gateway-deb-package/releases/download/fa6236d8ff6d0ed63bb01d6a3a4da44de66a388c41aa803079c8ea1a2f46bed4/webthings-gateway-ubuntu.latest.deb) and Raspbian. Right now it's nothing but the gateway, so lots of addons don't work, and there's no service so it needs to be started manually. Nevertheless, it's a binary package that can be installed with `apt`, and it runs pretty well.

**Comment by benfrancis** [comment]
@gucci-on-fleek Nice, thanks for sharing!

**Comment by mrstegeman** [comment]
@gucci-on-fleek @benfrancis I've started a repo for this.

Status:
* Gateway builds, things are installed to proper directories
* gateway-addon python module is not yet installed
* intent-parser is not yet present

See: https://github.com/mozilla-iot/gateway-deb

**Comment by benfrancis** [comment]
Nice, thanks @mrstegeman !

**Comment by MagicFab** [comment]
Can you provide more details / a roadmap regarding Debian support and packaging ?
I'd like to contribute in testing, documentation and QA.

**Comment by mrstegeman** [comment]
I'm waiting on a couple translation updates before I make the final 0.11 build. At that point, I will also build .deb and .rpm packages.
