### ISSUE TITLE
Forum / Chat

### ISSUE THREAD

**Issue by diginfo** [mozilla-iot/gateway#2325]
Many of my questions at this stage are more of how-to when creating custom adapters etc.

Other than raising an issue, or using stackoverflow is there a forum that can provide help with this as rather than using issues as forum threads :-)

**Comment by mrstegeman** [comment]
Yes!

https://discourse.mozilla.org/c/iot

**Comment by mrstegeman** [comment]
You can also find us on [IRC](https://wiki.mozilla.org/IRC) in #iot.

**Comment by diginfo** [comment]
Thanks, FYI - now have the temp sensors adapters running very reliably and interracting with rules, thanks for your help the other day.

The only thing I have yet to figure out is how to rename a sensor (or description) so that I can give a name to each one based on it's location.

I have just signed up with the forum and will try there.
