### ISSUE TITLE
ESPHome adapter

### ISSUE THREAD

**Issue by BrianGilbert** [mozilla-iot/gateway#2340]
This would allow for Sonoff device support which is the 2nd most popular thread by views on the WebThings forum.

**Comment by benfrancis** [comment]
See also: https://github.com/haydnnewport/esphome_adapter

**Comment by tim-hellhake** [comment]
Now the cycle is complete 😬

**Comment by BrianGilbert** [comment]
@tim-hellhake unfortunately the linked project isn't functional at this stage according to repo owner

**Comment by tim-hellhake** [comment]
@BrianGilbert 
Yeah, I can confirm that.
Currently, the property and device files are empty, and the adapter file contains mostly boilerplate code.

**Comment by mrstegeman** [comment]
@BrianGilbert We now have a Tasmota adapter, thanks to @tim-hellhake.

**Comment by BrianGilbert** [comment]
@mrstegeman great news, thanks!

**Comment by BrianGilbert** [comment]
@mrstegeman I think there will still be people that would like to see an esphome adapter? It's non trivial to reflash as Tasmota on the research I've done in the past 30 minutes

**Comment by mrstegeman** [comment]
Ah, fair enough. I just figured the two were sort of redundant if they're primarily being used with the gateway.

**Comment by BrianGilbert** [comment]
@mrstegeman Tasmota and ESPHome are alternative firmwares that can run on Sonoff and other ESP based devices, people will always make a choice based on some reason that fits their case.. so ideally Gateway can support both.

**Comment by BrianGilbert** [comment]
@mrstegeman https://github.com/tim-hellhake/tasmota-adapter/issues/1

**Comment by madb1lly** [comment]
It may be sensible to separate this into separate issues:
1. For the ESPHome adapter, which supports a wider range of hardware but needs the owner to flash their device with this firmware
2. For Sonoff Ewelink Wifi switches which don't need to be flashed with any firmware by the owner:
https://sonoff.tech/product-category/wifi-diy-smart-switches
No-longer maintained wiki, but still useful: https://www.itead.cc/wiki/Product#Smart_Home

**Comment by mrstegeman** [comment]
See also: #2360

**Comment by tim-hellhake** [comment]
See also https://github.com/mozilla-iot/addon-list/pull/604 😬
