### ISSUE TITLE
Add internal ID to API output for /things

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#2351]
Currently the API call to `/things` gives a lot of data, but it doesn't offer a field that holds the thing's internal ID. 
For example, I can get the thing's human readable title straigt away with 

```
for thing in self.things:
                    if 'title' in thing:
                        thing_titles.add(str(thing['title']))
```
Which might give `fireplace` 

But I wish I could also do:
```
for thing in self.things:
                    if 'id' in thing:
                        thing_titles.add(str(thing['id']))
```
Which would then give something like `mysensors-34`

Why?

I'm trying to match the thing ID with the user friendly title, so that I can show the human readable title of a thing in the interface (UI extension). 

Current workaround is to scrape the thing ID from the end of the `href` field.

**Comment by benfrancis** [comment]
I think I'm right in saying that the `id` for all web thing exposed by the gateway are the same as their URI, so they could probably be used interchangeably.

However, the specification for the [Things](https://iot.mozilla.org/wot/#things-resource) resource does show it including `id`s for each `Thing`, so we should probably update the gateway's API to match.

**Comment by flatsiedatsie** [comment]
Sounds great.

> I think I'm right in saying that the id for all web thing exposed by the gateway are the same as their URI, so they could probably be used interchangeably.

Well, not really. `/things/mysensors-33` is not the same as `mysensors-33`? It's not difficult to extract is from it, but I was just worried that if the API/URL changed at some point in the future, my extraction code might not work anymore.

**Comment by mrstegeman** [comment]
@benfrancis we already include the ID, as shown in that spec.

This is a part of a much longer discussion about what the IDs should actually be.

**Comment by benfrancis** [comment]
Oh, so we do. Then I think this is a non-issue.

@flatsiedatsie Please re-open if you think otherwise.

(Agreed that there are still issues around what to use as IDs for some adapters.)

**Comment by flatsiedatsie** [comment]
It's a feature request/suggestion, so I'm not sure why the 'invalid' label is applied? 

For now I'm just extracting the variable from the `href`, and that works fine. What I don't know is whether you guys considered this a good practise (might be fragile). If not, then a 'clean' ID would be a solution.

> we already include the ID, as shown in that spec.

By that do you mean the `href`?

**Comment by mrstegeman** [comment]
> For now I'm just extracting the variable from the `href`, and that works fine. What I don't know is whether you guys considered this a good practise (might be fragile). If not, then a 'clean' ID would be a solution.

That's what we do in our UI as well, so I'd say it's safe.

> > we already include the ID, as shown in that spec.
> 
> By that do you mean the `href`?

No, I mean the `id`. I promise it's in there!
* https://iot.mozilla.org/wot/#id-member
* https://iot.mozilla.org/wot/#thing-resource

**Comment by flatsiedatsie** [comment]
> That's what we do in our UI as well, so I'd say it's safe.

Great!

I'll have another look to see if I can find it :-)

**Comment by flatsiedatsie** [comment]
I had another look, and there is indeed an `id` field in there. But it's a full URL, which makes it difficult to use as a variable in code. It's also not a consistent URL, as a shift from http to https would change the ID. E.g. `'id': 'https://127.0.0.1:4443/things/internet-radio'` or `'id': 'http://127.0.0.1:8080/things/internet-radio'`

Still, scraping the unique part from the end works fine.

**Comment by benfrancis** [comment]
> It's also not a consistent URL, as a shift from http to https would change the ID. E.g. 'id': 'https://127.0.0.1:4443/things/internet-radio' or 'id': 'http://127.0.0.1:8080/things/internet-radio'

I'd actually argue that's correct. From a client's point of view two Thing Descriptions coming from two different origins are actually two separate web things.

Also the specification says that ID should be a URI. "/things/internet-radio" wouldn't be a valid URI.

**Comment by tim-hellhake** [comment]
@benfrancis 

> Also the specification says that ID should be a URI.

`urn:thing:internet-radio` would be a valid URI.
