### ISSUE TITLE
Issues using custom sub-domain with reverse proxy

### ISSUE THREAD

**Issue by kdickerson** [mozilla-iot/gateway#2362]
I have multiple sub-domains resolving inside my firewall.  To handle them properly I'm using Apache VirtualHosts to terminate the external https connections and then an SSL reverse-proxy to the correct endpoint.

For my other services this is working fine, but I'm experience strange behavior with my gateway.

I can access and log in to the device fine and working with Rules/Settings/etc. works, but `Things` always show "disconnected" even though I can still control them.  `Discovering` new `Things` always fails (nothing is ever found).  When accessing the gateway either internally or via the tunnel everything works fine.  I spent my entire evening and reflashed my Pi before figuring out the issue was only when I connected via the reverse proxy.

My VirtualHost configuration is really simple, here are the parts pertinent to the reverse proxy:

```
SSLProxyEngine on
SSLProxyVerify none
SSLProxyCheckPeerCN off
SSLProxyCheckPeerName off
SSLProxyCheckPeerExpire off
ProxyPass "/" "https://192.168.7.7/"
ProxyPassReverse "/" "https://192.168.7.7/"
```

My firewall is configured to forward port 443 to this server.

Should a reverse proxy configuration be enough to use a custom domain?  Clearly I'm missing something since this doesn't work.  Are additional ports needed?

My goal is to be able to access the gateway from https://home.serindu.com instead of https://serindu.mozilla-iot.org with the added catch that I can't route port 443 directly through my firewall to the gateway because I have other domains to serve as well.  So I have to bounce through another machine to reroute based on domain name.

Would someone be willing to point me at some resources to help me figure out how to get this to work?

**Comment by mrstegeman** [comment]
You have to proxy WebSocket connections as well, based on the `Upgrade` header.

See: #1806
