### ISSUE TITLE
Can't re-add thing after removing

### ISSUE THREAD

**Issue by madb1lly** [mozilla-iot/gateway#2363]
Hi WebThings team,

Recently I've had a few cases where I have removed a Thing and then tried to re-add it from the New Thing page but it doesn't appear there.

https://github.com/tim-hellhake/systeminfo-adapter - Removed System uptime thing because it didn't update with release 1.1.3 and now it does not appear in the New Thing page

https://github.com/flatsiedatsie/webthings-network-presence-detection - Removed two presence Things to test behaviour but they didn't reappear in the New Thing page until I updated the adapter at the next release. In the case of this adapter, I tried disabling and re-enabling it but this caused all available presence Things to disappear from the New Thing page. Removing and reinstalling the adapter did not help the situation, it was only when a new release was available that the Things could be added again.

https://github.com/tim-hellhake/timer-adapter - I created two new things in the config, added both new Things, removed one and now that one I removed is not visible in the New Thing page but is still defined in the adapter config.

Please let me know what I've done wrong, what the workaround is or what further information you need.

Cheers :)

**Comment by tim-hellhake** [comment]
Did you try to turn it off and on again? 😬

**Comment by mrstegeman** [comment]
Those adapters need to make sure they re-add any missing devices in their `startPairing` method. For example, see [here](https://github.com/mozilla-iot/virtual-things-adapter/blob/d9757b660d94cc6d76c491d0281b52e5c0b7b390/virtual-things-adapter.js#L1323-L1325).

@tim-hellhake @flatsiedatsie

**Comment by madb1lly** [comment]
Thanks @mrstegeman :)

**Comment by createcandle** [comment]
> https://github.com/flatsiedatsie/webthings-network-presence-detection - Removed two presence Things to test behaviour but they didn't reappear in the New Thing page until I updated the adapter at the next release. In the case of this adapter, I tried disabling and re-enabling it but this caused all available presence Things to disappear from the New Thing page. Removing and reinstalling the adapter did not help the situation, it was only when a new release was available that the Things could be added again.

That was a known issue and was fixed.

**Comment by tim-hellhake** [comment]
@madb1lly

>Unfortunately @tim-hellhake the classic tech-support fix didn't work :( :D

Disabling and reenabling the adapter starts a new discovery.
It really should work.
If this didn't work, adding the devices in the `startPairing` won't work either.

>Removed System uptime thing because it didn't update with release 1.1.3

The old thing page is still in the browser cache.
You have to hard reload the page: `command` + `shift` + `r`.
[Firefox: Reload (override cache)](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_current-page)
[Chrome: Reload the current page, ignoring cached content](https://support.google.com/chrome/answer/157179?hl=en)

**Comment by madb1lly** [comment]
Hi @tim-hellhake,
:doh: I had been trying to hard-refresh but was using the wrong key combination. In any case, the System Uptime thing did reappear yesterday after I power-cycled the RPi (as opposed to a reboot) when trying to fix another issue.
Thanks 🙂
