### ISSUE TITLE
Trying to cross-compile using dockercross and cross-compile.sh -- arch not getting passed..

### ISSUE THREAD

**Issue by MarcKarasek** [mozilla-iot/gateway#2378]
I am trying to cross-compile the node_modules using the cross-compile.sh and dockercross to create the docker images with the cross-compiler. 

It runs fine until it tries to cross-compile ctx.o and is not node-gyp is not passed the arch=armv7l flag. So it fails with the cross-compiler saying it does not understand -m64 (x86 flag)

It is using the proper cross-compiler 9see below) but the cross-compiler script is calling npm : 
npm --arch=${ARCH} install 
where ARCH=armv7l

I have tried removing the ${ARCH} and directrly putting armv7l there but still same problem. 
I have looked at docs for npm and cannot find any reference to a --arch= flag?

Help!

```
npm ERR! prepareGitDep > node-gyp rebuild
npm ERR! prepareGitDep 
npm ERR! prepareGitDep make: Entering directory '/home/marck/.npm/_cacache/tmp/git-clone-48fd7cdf/node_modules/nanomsg/build'
npm ERR! prepareGitDep   CC(target) Release/obj.target/nanomsg/deps/nanomsg/src/aio/ctx.o
npm ERR! prepareGitDep deps/nanomsg.target.mk:252: recipe for target 'Release/obj.target/nanomsg/deps/nanomsg/src/aio/ctx.o' failed
npm ERR! prepareGitDep make: Leaving directory '/home/marck/.npm/_cacache/tmp/git-clone-48fd7cdf/node_modules/nanomsg/build'
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep arm-linux-gnueabihf-gcc: error: unrecognized command line option '-m64'
```

**Comment by mrstegeman** [comment]
Try `npm --arch=armv7l --target_arch=arm install`.

**Comment by MarcKarasek** [comment]
Tried that as well i can do it again to make sure..   Just tried it by using the above in the cross-compile.sh script.. 

same behavior compile of ctx.o in nanomsg fails because node-gyp is trying to build as x86 using the arm cross compiler..

**Comment by mrstegeman** [comment]
I'm not really sure beyond that. You can look at how we cross-compile add-ons, if you want, but we build the gateway natively on-target.
* https://github.com/mozilla-iot/addon-builder/blob/master/build-adapter.sh (look for the `linux-arm` bits)
* https://github.com/mozilla-iot/zigbee-adapter/blob/master/package.sh (called by the first script)

Is there a reason you're trying to cross-compile?

**Comment by MarcKarasek** [comment]
Yes for our target we cannot build natively on it (like Rasp Pi for example).  So we need to be able to cross-compile it and then install the node-modules from the cross compile to the device.

**Comment by mrstegeman** [comment]
Does our existing ARM Docker image work for you?

https://hub.docker.com/r/mozillaiot/gateway

**Comment by MarcKarasek** [comment]
Well I got one problem fixed.. 
I managed to get the nanomsg cross compiled by adding this to the cross-comple.sh
npm install nanomsg@4.1.0 --arch=armv6l --target_arch=arm
npm install --arch=armv6l --target_arch=arm

Now when it goes to do the npm install of all the other packages, it does not see that nanomsg is already there and tries to rebuild it again.  And again fails with the -m64 option error..

**Comment by MarcKarasek** [comment]
> 
> 
> Does our existing ARM Docker image work for you?
> 
> https://hub.docker.com/r/mozillaiot/gateway

Thanks for the link.   This would require the device to have docker installed...  I am not sure that will be an option.   Think embedded device, not a Rasp Pi which for all purposes is a full linux system.

**Comment by mrstegeman** [comment]
Oh, I was confused by your first post. I thought you were trying to create a Docker image of the gateway. You're creating a Docker image for the cross-compiler itself, right?

**Comment by MarcKarasek** [comment]
I have that via dockcross project.   It has docker images for all kinds of cross-compiling
https://github.com/dockcross/dockcross

The issue I am facing is the module gateway-addon-node has a dependency on nanomsg.  When it tries to cross-compile the node_modules it gets to this one an tries to "native" compile nanomsg with the arm cross-compiler but using the x86 cmdline args (-m64) which fails.  

If I add the line: 
npm install nanomsg@4.1.0 --arch=armv6l --target_arch=arm
to the cross-compile.sh script it will cross-compile the nanomsg (arm elf) just fine.  But when it gets to the gateway-addon-node it again fails with the -m64 errror.

I have removed the gateway-addon-node from package.json/package-lock.json and it builds it all ok.  Creates a node_modules.tar.gz file.  I have yet to test this on a Pi to see if all is ok.   This was just a temp fix and I have an idea on how to get this to cross-compile properly.  

I should be able to take the above tarball along with the gateway src put them on a pi and do a ./run-app.sh correct?  

Marc

**Comment by mrstegeman** [comment]
> I should be able to take the above tarball along with the gateway src put them on a pi and do a ./run-app.sh correct?

Yes, in theory.

**Comment by MarcKarasek** [comment]
ok  will try that

**Comment by MarcKarasek** [comment]
Got it all to cross-compile using dockcross and was able to copy over and run on Pi.
The process is a bit convoluted:
1. download and install into local_packages in gatewway the gateway-addon-node repo.  (Do git submodule update to get schema files)
2. Modify package.json to point to this dir ../local_packages/gateway-addon-node
3. Modify gateway-addon-node/package.json to point to the nanomsg under node_modules. 
../node_modules/nanomsg
4. Remove gateway/package-lock.json file
5. Modify cross-compile.sh 
npm install nanomsg --arch=armv6l --target_arch=arm
npm install --arch=armv6l --target_arch=arm
# This will create a build dir for deployment 
npm run webpack

This will then create the all files needed to run the gateway on the device.
