### ISSUE TITLE
Avoid using the octopus as an icon

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#2386]
Currently the WebThings Gateway icon refers to the "octopus" interface design. However, with some themes (such as the square theme) this depiction might not be a given. There has even been mention of moving the default away from the octopus design in the future.

Perhaps another icon, one that is more agnostic to the interface's current default design language, would be more future proof?

**Comment by benfrancis** [comment]
LOL, thanks for the suggestion.

1. The icon is not an octopus. Octopi have eight arms ;)
2. It's not really tied to the UI design. Try Googling [IoT icon](https://www.google.com/search?q=iot+icon&client=firefox-b-d&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiC4-nI2snmAhVZPcAKHTKvAAIQ_AUoAXoECA4QAw&biw=1280&bih=703) and you'll see this is a very common type of icon for representing IoT.

So yeah, it's a pretty lazy icon design but it's not really a representation of the UI, if anything it's the other way around! :)

**Comment by benfrancis** [comment]
P.S. Funnily enough I asked our Branding team for a better icon a while back and they sent the same icon back to me :P

Maybe we can come up with a better one.

Behold, the Pentapus:
![pentapus](https://user-images.githubusercontent.com/552417/71327032-2129cc00-24fb-11ea-8c02-bb4bbb8dd1ba.jpg)

**Comment by flatsiedatsie** [comment]
Spectre! :-D

**Comment by flatsiedatsie** [comment]
![progress_home](https://user-images.githubusercontent.com/805405/73887556-15585600-486c-11ea-87e3-92ccc7c221c9.png)
- A home (although a western style one)
- OSI layers of the web, with a home (triangle) on top
- Arrow, signifying improvement of living


![playfull_staircase](https://user-images.githubusercontent.com/805405/73887632-39b43280-486c-11ea-8b71-5f1e4c3ea27d.png)
- Porch. A staircase leading up to a door
- A joystick, signifying playing with technology
- Elements building op top of each other, signifying the open source movement.
