### ISSUE TITLE
Turn switches on and off with speech

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#239]
As a user I want to turn switches on and off using voice commands (e.g. "turn desk lamp on", "turn desk lamp off").

**Comment by benfrancis** [comment]
This is intended as the simplest possible use case for voice control to start experimenting with this feature. I suggest adding a microphone button to the "things" screen in the top right corner (see mockup below) to access voice commands as a starting point and having the feature turned off by default.

![speech](https://user-images.githubusercontent.com/552417/29081031-586eee40-7c59-11e7-9642-d78685ac132e.png)

**Comment by andrenatal** [comment]
Closed by #290
