### ISSUE TITLE
Closed issues with no information

### ISSUE THREAD

**Issue by rei-vilo** [mozilla-iot/gateway#2390]
Two tickets (nominally, #674 and #690) have been changed to **closed** then **done**.

Unfortunately, those changes come with no information whatsoever.

+ Could you please explain how to use the solutions to the issues?
+ In which release are the solutions going to be available?
+ Where can I find the related documentation to use the solutions?

Thank you!

**Comment by mrstegeman** [comment]
I commented on each of those issues now.
