### ISSUE TITLE
Arduino device (esp32) Add events to PushButton

### ISSUE THREAD

**Issue by Diallomm** [mozilla-iot/gateway#2392]
hello team, i'm new to the mozilla webthings project which i think is great, my problem is that i recently created a program for the esp32s microcontroller which represents a push button, here is the link to the repository "https://github.com/Diallomm/webthings_pushbutton_esp32/blob/master/src/main.cpp", and i can't create the 3 events "PressedEvent", "DoublePressedEvent", "LongPressedEvent", i can't find any example or code arduino that shows how to do it, thanks for your future help.

**Comment by Diallomm** [comment]
`#include <Arduino.h>
#include "Thing.h"
#include "WebThingAdapter.h"

const char *ssid = "WIFI Name";
const char *password = "WIFI PASSWORD";

const int button = 23;
const int led = 2;

WebThingAdapter *adapter;

const char *PushButtonTypes[] = {"PushButton",nullptr}; // define a type of device referenc to context https://iot.mozilla.org/schemas
ThingDevice Pushbt("PushButton","Pushbutton0",PushButtonTypes); //configure device id, name and type
ThingProperty PushBtOn("push","button is pressed",BOOLEAN,"PushedProperty"); // device property of device, name, text, boolen type


bool state = false;

void detectpush()
{
  if(digitalRead(button) == HIGH)
  {
    state = true;
  }
  else
  {
    state = false;
  }
  //Serial.println(digitalRead(button));
}

void setup() {
  pinMode(button, INPUT);
  pinMode(led, OUTPUT);
  Serial.begin(9600);
  Serial.println("");
  Serial.print("Connection to \"");
  Serial.print(ssid);
  Serial.println("\"");

  #if defined(ESP8266) || defined(ESP32)
    WiFi.mode(WIFI_STA);
  #endif
    WiFi.begin(ssid, password);
    Serial.println("");
  
  // Wait for connection
  bool blink = true;
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
    digitalWrite(led, blink ? LOW : HIGH); // active low led
    blink = !blink;
  }
  digitalWrite(led, HIGH); // active low led

  Serial.println("");
  Serial.print("Connected to ");
  Serial.println(ssid);
  Serial.print("IP address: ");
  Serial.println(WiFi.localIP());
  adapter = new WebThingAdapter("pushbutton", WiFi.localIP());

  Pushbt.addProperty(&PushBtOn);
  adapter->addDevice(&Pushbt);
  adapter->begin();
  Serial.println("HTTP server started");
  Serial.print("http://");
  Serial.print(WiFi.localIP());
  Serial.print("/things/");
  Serial.println(Pushbt.id);
}

void loop()  {
  detectpush();
  ThingPropertyValue value;
  
  value.boolean = state;
  PushBtOn.setValue(value);
  adapter->update();
  delay(300);

}`

**Comment by mrstegeman** [comment]
I’ve been working on proper action and event support in that library and should have a release out later this week with some examples. Watch [https://github.com/mozilla-iot/webthing-arduibi] for more. 😀

**Comment by mrstegeman** [comment]
Duplicates mozilla-iot/webthing-arduino#7

**Comment by Diallomm** [comment]
All right, well, thank you very much. I look forward to testing it.

**Comment by rarno** [comment]
Please excuse my bad English. I also need help with "PressedEvent". Unfortunately, in the examples "Update LEDLamp example to use actions & events. (# 101)" I cannot find any instructions on "Events". I cannot correctly adapt the "Event" "Overheated" in the example "LEDLamp" to a "pressedEvent". I'm trying a "flip-flop implementation" like in "# 694". Do you have an example for me to learn more?
