### ISSUE TITLE
removing addon causes related things to be unremovable

### ISSUE THREAD

**Issue by kennethklee** [mozilla-iot/gateway#2398]
If you remove an add-on that still has a thing, that thing can no longer be deleted.

STR (using speed test as an example):
1. add speed test add-on
2. add speed test thing
3. remove the add-on
4. try to remove the thing

Not sure if removing the add-on should automatically delete the thing as well or just disable them, but still make them removable?

**Comment by mrstegeman** [comment]
We have several open issues around this, e.g. #1013, #1252, and #1930. It's also not always reproducible (like right now, for me). Typically, if you restart the gateway, you can then remove the thing.
