### ISSUE TITLE
Distinguish thing with no adapter

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#240]
If a thing is associated with an adapter which is not available (i.e. it got turned off in the config, or the USB dongle isn't plugged in), then we should do something in the UI to indicate that the device is "unusable".

This could be a small symbol in one corner of the icon, or perhaps a big X overlaid or perhaps even just a different coloring.

Once dynamic adapters are supported, then the UI should update anytime an adapter is added or removed (perhaps this last item should be a separate issue?)

**Comment by benfrancis** [comment]
Good idea. We do have three states for the current on/off icons and binary sensor icons. There's "on" and "off" but also a neutral state which displays "...", we could use that latter unknown state to begin with, until we come up with a new design for more complex types.

**Comment by mrstegeman** [comment]
Now that we have the dimmed "disconnected" state, I think we can say this is done.
