### ISSUE TITLE
Expand the number of supported Zigbee USB sticks

### ISSUE THREAD

**Issue by mentarus** [mozilla-iot/gateway#2405]
Currently, the only choice for Zigbee network seems to be the Digi XStick for $99!, as the other two on [the wiki page](https://github.com/mozilla-iot/wiki/wiki/Supported-Hardware) are no longer available for purchase.
What would it take to support the [Z Stack USB sticks](https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator), the cc2531 based dongles can be acquired much more readily and at a much lower cost (under $10, pre-flashed)

**Comment by mrstegeman** [comment]
The Conbee II is available for purchase: https://www.phoscon.de/en/conbee2?buy=1#buy

We do have an [open PR](https://github.com/mozilla-iot/zigbee-adapter/pull/101) for CC253x support, but it's incomplete. Perhaps you could help resolve any remaining issues (and/or test)?
