### ISSUE TITLE
redis  and gateway

### ISSUE THREAD

**Issue by 2738671** [mozilla-iot/gateway#2408]
There is a problem integrating redis and gateway. The screenshot is as follows. Because redis version 2.2.0 already supports reactivestringredistemplate, this problem occurs. What about the exclusion?

-------------------------------------------------------------------------------------------------------------
2020-01-17 17:21:38.083 ERROR 13032 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method redisRateLimiter in org.springframework.cloud.gateway.config.GatewayRedisAutoConfiguration required a single bean, but 2 were found:
	- reactiveStringRedisTemplate: defined by method 'reactiveStringRedisTemplate' in class path resource [org/springframework/boot/autoconfigure/data/redis/RedisReactiveAutoConfiguration.class]
	- stringReactiveRedisTemplate: defined by method 'stringReactiveRedisTemplate' in class path resource [org/springframework/cloud/gateway/config/GatewayRedisAutoConfiguration.class]

Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed

**Comment by mrstegeman** [comment]
I think you may be looking at the wrong software here...
