### ISSUE TITLE
Use desktop Raspbian image as a base instead of the headless?

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#2415]
If the Raspberry Pi image was based on a Raspbian image with desktop output support instead of the current headless image it would allow for a number of useful things:
- Extra option for debugging by connecting a monitor, mouse and keyboard.
- Makes it easier to use the same Raspberry Pi for other things besides being a WebThings gateway. E.g. act as an open source network video player, an education platform, etc.

You could say this is a "light" version of an [earlier issue](https://github.com/mozilla-iot/gateway/issues/2022) that asked for touch screen support. The difference is that this issue is simpler, and only asks to include the fundamentals that allow others to more easily create such functionality.

**Comment by kgiori** [comment]
@dhylands created a desktop image for me once, so I could share with a middle school teacher who wanted the students to learn RPi basics, and take advantage of the WebThings Gateway as a hub for sensor data. I'm not sure how involved it would be to create, but I agree that sometimes there are opportunities to take advantage of the gateway in parallel with a desktop image. You could also bring up Raspbian and then install the gateway in a Docker container.

**Comment by davehylands** [comment]
The desktop image requires a much larger SD card (minimum 8gb). To build an image based on the desktop, image you need to build a base image by following the steps here:
https://github.com/mozilla-iot/wiki/wiki/Creating-the-base-image-file-for-the-Raspberry-Pi
and use the desktop image rather than the lite image.
You can then use the rpi-image-builder (which runs on Travis) to build a version of the gateway software:
https://github.com/mozilla-iot/rpi-image-builder
Note that the "uploading to AWS" portion of both of those are optional and are not needed if you're building locally. You'll need a linux machine to perform both steps.

**Comment by flatsiedatsie** [comment]
@davehylands Thanks for the explanation. But the goal of this issue was to explore if the default image that Mozilla provides could come with a desktop as standard.

The smallest Sd card I can buy in the shops around here until recently was 16Gb (6 euro), but the minimum has now shifted to 32Gb (10 euro and dropping). So an 8Gb image wouldn't be much of an issue.

Perhaps alternatively, the current image could just come with just the etra files needed to output to a minimal desktop and the chromium browser? Then the image might stay relatively small, yet still offer the options mentioned above.

**Comment by mrstegeman** [comment]
This was never the intended use case for the Raspbian image. To address cases like this, we provide packages for several Linux distros now, as well as the Docker image.

**Comment by flatsiedatsie** [comment]
Sure, but that means beginners won't have an out-of-the-box ready to go option. They'll have to 
A. Burn a Linux image, and then install the gateway (probably via the commandline? Or is it in the app stores too?).
B. Burn the pi image, and then venture into the world of SSH.

The beauty of the current gateway image is how easy it is for beginners to get started - just burn an image and they're done.

Anyway, if option A is easy enough I guess that's the way to go.

**Comment by mrstegeman** [comment]
Let me address the two use cases you provided in the issue at the beginning.

> * Extra option for debugging by connecting a monitor, mouse and keyboard.

I would argue that, with the current image, you can already connect a monitor and keyboard. Debugging in both cases requires the user to log in with the same username and password, and the logs and such would still have to be accessed via the command line.

> * Makes it easier to use the same Raspberry Pi for other things besides being a WebThings gateway. E.g. act as an open source network video player, an education platform, etc.

Sure, but in these cases, the user is going to have to install those additional things separately anyway, so what's one more package?

**Comment by mrstegeman** [comment]
And installing the package is as easy as:
1. Download package from the [releases page](https://github.com/mozilla-iot/gateway/releases) of this repo
2. `sudo apt install ./webthings-gateway-XYZ.deb`

**Comment by flatsiedatsie** [comment]
I get where you're coming from, but does installing the package require a user to open a terminal?

I'd love it to be as simple as this:
- Burn image to SD card
- Attach a touch screen display via HDMI
- Open browser
- Surf to gateway.local
- Go fullscreen

Presto! You can now manage your smart home via a touch screen directly.

This would also be great:
- Burn Ubuntu or similar to SD card
- Attach a touch screen display via HDMI
- Install WebThings Gateway from app store
- Surf to gateway.local
- Go fullscreen

For me the goal would be to have 'normal people' never have to leave the GUI, where they feel safe. If installing webthings can be done through an app store, then my issue is indeed moot.

**Comment by kgiori** [comment]
I really like this idea. The ability to enable it could be in the "Developers" section of Settings, where ssh is enabled. It's an area where you're changing things "beyond the app". Networking affects beyond the app too, so there are other analogies. There are plenty of gateway users I know, who would like this enhancement, including myself. For example, I set up and installed gateways for some of my relatives They would not have an easy time following "command line" instructions. And I am not physically there to do it for them.

**Comment by mrstegeman** [comment]
You can install a `.deb` package on Debian by double clicking it, so no terminal should be necessary.

**Comment by kgiori** [comment]
> You can install a `.deb` package on Debian by double clicking it, so no terminal should be necessary.

Double-clicking what, from where? Wouldn't a "Desktop Raspbian" (headed) gateway image be necessary before there's an ability to install and/or run desktop apps like a browser, directly on the gateway? As I think I understand from @flatsiedatsie request above, a desktop gateway install could be customized so that the browser app icon was on the desktop, ideally with a home page of gateway.local, so that the user could just click on it to launch the gateway UI.

**Comment by mrstegeman** [comment]
From the original post:
> Makes it easier to use the same Raspberry Pi for other things besides being a WebThings gateway. E.g. act as an open source network video player, an education platform, etc.

My point here is that you can install a normal Raspbian desktop image, then download the .deb package and double click it to install.

**Comment by flatsiedatsie** [comment]
That is pretty sweet.

#kgiori have a look here:
https://www.candlesmarthome.com/adding-a-touch-screen-to-the-candle-controller

Basically, all you have to do now is install the `seashell` addon, and paste in this command, then hit 'run':
curl -sSL www.candlesmarthome.com/tools/kiosk.txt | sudo bash

After about a minute of two, depending on your internet speed, it will reboot.

The script creates a kiosk version of the Gateway.

- No need to connect a mouse and keyboard, it can be done from an initial gateway install.
- No problems with users being confused by a Linux desktop, and needing to know how to use it.
- It uses a privacy friendly "ungoogled" version of Chromium. It has a lot of kiosk-friendly feaures. E.g. drag down to refresh the page.
- It's been made consumer-proof by removing as many possibilities for confusion as possible. E.g. keyboard shortcuts have been disabled, file upload is disabled (so users don't see a weird Linux file system), outside links cannot be opened, etc.
- It has some nice bootup animations so the user never sees weird bootup text scrolling by. You can replace the current Candle image and video with your own by plugging the SD card into your computer.

It even works great as a video player for exhibits :-)

**Comment by dizzwold** [comment]
@flatsiedatsie ,
 Did you get anywhere with regards to a touchscreen display to use webthings gateway.
 I'm new to RPi's, but have some knowledge with Arduino's.
 I've just installed webthings on a RPi 4b 4g and now looking to use a 7" touchscreen instead of my phone or desktop computer.
 Gratefull for your advise.
Dizzwold.
