### ISSUE TITLE
System clock warning on registration page

### ISSUE THREAD

**Issue by viren-moradiya** [mozilla-iot/gateway#2432]
Hello Folks,

I am facing an warning/error message while doing the gateway registration.
Please find below snap for detail.

![image](https://user-images.githubusercontent.com/11868727/74420726-eea0ad80-4e71-11ea-9a6d-2674a3840c94.png)

Before this I have never seen this issue.
This is suddenly came in picture.

Can you please help me here to come out of this issue?

Thanks,
Viren

**Comment by viren-moradiya** [comment]
I am getting this error because of below part of code area :
File : src/platforms/linux-raspbian.js

Code : 
###################
function getNtpStatus() {
  const proc = child_process.spawnSync(
    'timedatectl',
    ['status'],
    {encoding: 'utf8'}
  );

  if (proc.status !== 0) {
    return false;
  }

  const lines = proc.stdout.split('\n').map((l) => l.trim());
  const status = lines.find((l) => l.startsWith('System clock synchronized:'));

  if (!status) {
    return false;
  }

  return status.split(':')[1].trim() === 'yes';
}
#####################

In this code "status" value getting set based on "timedatectl status" command output.
This command output does not have line like "System clock synchronized:" which code is finding.
And due to this failure, status value always set false.

Reference output : 
pi@gateway:~ $ timedatectl status
      Local time: Thu 2020-02-13 12:55:45 UTC
  Universal time: Thu 2020-02-13 12:55:45 UTC
        RTC time: n/a
       Time zone: Etc/UTC (UTC, +0000)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no
pi@gateway:~ $

Can you please explain why code is finding this specific string for NTP status?
Request you to help me to resolve this issue.

Thanks,
Viren

**Comment by mrstegeman** [comment]
You must be using an older version of Raspbian. The string is different in newer versions of systemd. I'll add a workaround for the older version.

**Comment by viren-moradiya** [comment]
@mrstegeman Thank you for quick resolution.
