### ISSUE TITLE
Need some help in removing user sessions

### ISSUE THREAD

**Issue by ravish0007** [mozilla-iot/gateway#2436]
I'm a noob, I need a tip to deauth from a wifi which it is connecting to after every boot.

Thanks

**Comment by mrstegeman** [comment]
You can SSH into the Pi and remove the offending networks from `/etc/wpa_supplicant/wpa_supplicant.conf`.

**Comment by mrstegeman** [comment]
(Closing, but feel free to continue the conversation if you need more help).

**Comment by ravish0007** [comment]
That's very quick, figured it out anyway, Thanks a lot and this project is just incredible
