### ISSUE TITLE
"Update Now" button should not be available for Docker image

### ISSUE THREAD

**Issue by Arzachena** [mozilla-iot/gateway#2439]
I am running the gateway (current version 0.10.0) on a Synology Nas using Docker. Under Settings, Updates, I saw that an update was available and clicked on Update Now which changed to In Progress. Nothing seems to be happening.

If I understand correctly, this way of updating the gateway cannot work for a Docker image. I think I need to download the latest image via Docker. Is this correct?

If yes, can the Gateway detect that it is running within Docker and change the content of the Updates screen?

**Comment by mrstegeman** [comment]
This was already taken care of in the 0.11 release. 🙂
