### ISSUE TITLE
Issues with v0.11.0 - cannot TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by abhijitnathwani** [mozilla-iot/gateway#2451]
Hello,

I flashed a new gateway image on Raspberry Pi 3 using the v0.11.0 branch and strangely seeing the attached error logs. I can't figure out why do they occur. The adapters which are loaded works fine. 

[run-app.txt](https://github.com/mozilla-iot/gateway/files/4266105/run-app.txt)

**Comment by mrstegeman** [comment]
It looks like something is talking to your gateway but not setting the `Host` header on the HTTP request, so I'm assuming it's not a browser. I can fix the issue, but I'm curious what else may be using the gateway's API. Do you have some custom scripts? What add-ons are you using?

**Comment by abhijitnathwani** [comment]
Hi @mrstegeman 
I guess that problem arose due to a vulnerability scanning tool(nessus) working on my network. Probably not a `gateway` bug. But thanks for the quick fix!
