### ISSUE TITLE
Limiting log size

### ISSUE THREAD

**Issue by dan1elhughes** [mozilla-iot/gateway#2459]
Hey 👋 My server was failing to start properly today. With a bit of manual fiddling, I found that the root `/` partition was 100% full. With some more digging I found this file was over 90GB: 

```
/var/lib/docker/containers/1684b2163581131c0c1c910717a08c548636d0250bb11a030fbc7d1aea0fb6c5/1684b2163581131c0c1c910717a08c548636d0250bb11a030fbc7d1aea0fb6c5-json.log
```

This container is the mozilla IOT container:

```
> docker inspect --format='{{.Config.Image}}' 1684b2163581131c0c1c910717a08c548636d0250bb11a030fbc7d1aea0fb6c5
mozillaiot/gateway:latest
```

I'd like to be able to set a limit on the size of this log, or maybe rotate it every few days. Is this a feature you'd consider? 😸 Thanks!

**Comment by dan1elhughes** [comment]
As an aside, it looks like this container produced 88GB of logs in just a few hours! Is there a way to reduce the verbosity of these logs?

![image](https://user-images.githubusercontent.com/9041370/76344664-db122680-62f9-11ea-95ad-0c6e2534f525.png)

**Comment by mrstegeman** [comment]
The reason it gets so large is that

You can do this with your `docker run` command, by adding `--log-opt max-buffer-size=50m` or something similar.

* `docker run`: https://docs.docker.com/config/containers/logging/configure/#configure-the-delivery-mode-of-log-messages-from-container-to-log-driver
* `docker-compose`: https://docs.docker.com/compose/compose-file/#logging

**Comment by mrstegeman** [comment]
I just updated the README and docker-compose sample with the appropriate flags.

**Comment by dan1elhughes** [comment]
That's wonderful - thank you!
