### ISSUE TITLE
Help building 0.12

### ISSUE THREAD

**Issue by trentmillar** [mozilla-iot/gateway#2460]
I tried following, https://github.com/mozilla-iot/wiki/wiki#the-new-way, It looks like the build script is linux specific so I followed these steps to build the gateway,

- `git clone https://github.com/mozilla-iot/gateway.git`
- `cd gateway`
- `docker run --rm -it -v $PWD:/gateway ubuntu:latest`
- from docker, `cd gateway/image`
- `. build.sh`

and  the output

```
cp: error reading '/bin/../proc/1/task/1/personality': Operation not permitted
cp: error reading '/bin/../proc/1/task/1/syscall': Operation not permitted
cp: cannot open '/bin/../proc/1/task/1/mem' for reading: Permission denied
cp: error reading '/bin/../proc/1/task/1/clear_refs': Invalid argument
```

Clearly I'm missing something...maybe only runs on raspbian?

Any insight would be appreciated.

**Comment by mrstegeman** [comment]
The instructions you linked to are specifically for building a full Raspbian image, which is probably not what you want. You have a few options here.

1. To build the gateway manually on Linux or macOS, you can walk through the [README](https://github.com/mozilla-iot/gateway#readme), which has instructions for the whole process.
2. If you want a minimal Docker setup, with the bare minimum dependencies, you can build against [this Dockerfile](https://github.com/mozilla-iot/gateway/blob/master/Dockerfile).
3. If you want a full Docker setup, you can use our [prebuilt image](https://hub.docker.com/r/mozillaiot/gateway) or build it yourself, using [this Dockerfile](https://github.com/mozilla-iot/gateway-docker).
