### ISSUE TITLE
Reload Add-On button

### ISSUE THREAD

**Issue by Galveston01** [mozilla-iot/gateway#2462]
It would be really useful, especially during development, to have a single button for reloading an Add-On.
![reload](https://user-images.githubusercontent.com/44091658/77321573-aa2aec00-6d12-11ea-95b1-aadcf0847c50.png)

**Comment by jaller94** [comment]
While as a dev setting I would consider this a great addition, I wouldn't want that to be the default.
It's adding another choice (adding complexity) and 1. "Disabled" 2. "Enable" performs the same action.

**Comment by mrstegeman** [comment]
Agree. The current approach is sufficient here. It’s just one extra click plus 3 seconds.

**Comment by jaller94** [comment]
@Galveston01 Cheeky way to reload the addon from your terminal / your IDE:

```
GATEWAY="https://your-gateway.mozilla-iot.org"
ADAPTER="zigbee-adapter"
# Copy paste this from an active session in your browser using the Network tab of the Developer Tools.
AUTHORIZATION="Bearer eyJh…"
curl -H "Authorization: $AUTHORIZATION"\
  -d '{"enabled":true}'\
  -H "Content-Type: application/json"\
  -H "Accept: application/json"\
  -X PUT\
  "$GATEWAY/addons/$ADAPTER"
```

Even if the addon is already enabled, sending PUT enable: true will restart it.

**Comment by Galveston01** [comment]
Pretty neat, gonna use this a lot, thanks :)
