### ISSUE TITLE
Thing disconnected

### ISSUE THREAD

**Issue by LionMike** [mozilla-iot/gateway#2468]
Things show disconnected after adding to Tuya Smart Life adapter by Gavelston1. Am I missing something? Also a Roku TV disconnected but another is working fine.

**Comment by mrstegeman** [comment]
This type of issue is specific to the add-on. Can you file individual issues with those two?

* https://github.com/Galveston01/tuya-adapter
* https://github.com/mozilla-iot/roku-adapter

**Comment by LionMike** [comment]
Done. Thank You
