### ISSUE TITLE
Can't connect to wireless and can't connect to raspberry pi gateway.local/ 

### ISSUE THREAD

**Issue by inteldon** [mozilla-iot/gateway#2469]
I used a new SD card and flashed the raspberry pi image. Started the pi and here are the issues I'm facing: 

1. The instruction available on the [official site](https://iot.mozilla.org/docs/gateway-getting-started-guide.html) seems outdated. It assumes that connecting to the raspberry pi access point will automatically let you in. That's not true, because it's asking me for a password. There are no indications of a default password, I tried every default raspberry pi password and nothing worked. The SSID was wrong too, it was not "WebThings Gateway XXXX" as shown on the official documents, but something like "RPi3-XXXX'. 

FYI - I tried reflashing and using the SD card and also tried using wpa_supplicant.conf on the boot folder of the SD card and the same problem was experienced. 

2. After giving up on the wireless settings I used an Ethernet connection to my router and finally got the IP address of the device. I tried to access "http://gateway.local" and I got nothing. Then, I tried "http://192.168.2.1" and still got nothing. 

I spent good 5 hours on this project and arrived at the same spot that I started from over and over again. Other websites assume the same things and there seems to be no mention of any new updates or changes made to the user experience. If we want people to catch on this and gain some level of popularity then we'll need to do a better job with the documentation, people can't really assume the unknown. If anyone knows what changed or what the missing step here is then please share. I think this is a great project and we shouldn't discourage people from trying it out and contributing to it for some very minor issues that can easily be fixed. 

Thanks
-D

**Comment by abhijitnathwani** [comment]
Hi @inteldon ,

Can you let us know which image did you use to flash on the Raspberry Pi? Or did you build it from scratch? If so, can you share the steps?

**Comment by kgiori** [comment]
Indeed @inteldon -- all the details you describe don't match the WebThings Gateway image at all. Make sure you downloaded it from [here](https://iot.mozilla.org/gateway/) -- current version is 0.11.

**Comment by inteldon** [comment]
Thanks @kgiori. I downloaded the precompiled image and it worked. 

@abhijitnathwani  I was initially trying to build it from source, I think the precompiled image is the better alternative. 

Thanks for your quick response, gives me confidence to see this level of support.

**Comment by abhijitnathwani** [comment]
@inteldon Yep. the community is active here. Let us know if you need any more help.
