### ISSUE TITLE
Things cannot be edited if they don't have a capability?

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#2472]
This is likely an issue on my end, but I thought I'd check. I've noticed that since version 0.11 a device might not be editable (e.g. to change it's name) if it doesn't have a capability? 

![candle_receiver_edit_weirdness](https://user-images.githubusercontent.com/805405/78420982-7629c200-7654-11ea-8285-86caa633ab7e.gif)

I hope and suspect I'm wrong, because the MySensors add-on doesn't give every device a capability, simply because there are endless possibilities for people to create, and because some devices can be made with MySensors that don't have corresponding capabilities in the Gateway yet.

**Comment by mrstegeman** [comment]
This is fixed in 0.12, which I’ll be releasing in a few days.
