### ISSUE TITLE
0.12.0 update - can't connect to gateway via https or SSH

### ISSUE THREAD

**Issue by gtbrons** [mozilla-iot/gateway#2476]
Since 0.12.0 update my home automation system is dead in the water:
Raspberry Pi is connecting to my wireless network however gateway is no longer accessible via https (LAN or WAN address) - connection refused

**Comment by mrstegeman** [comment]
This is probably relevant: https://discourse.mozilla.org/t/screeching-to-a-halt/57440

**Comment by gtbrons** [comment]
All fixed now.  See https://discourse.mozilla.org/t/screeching-to-a-halt/57440
