### ISSUE TITLE
Recover a gateway domain

### ISSUE THREAD

**Issue by DSiwi** [mozilla-iot/gateway#2477]
Hello,
I have had a corruption of some sort occurred on the SD of the RasPi I was using for a gateway and it is no longer bootable. However when I create a new SD, I cannot get back my original domain. At the page where it asks for the personal subdomain name and email address for the gateway it just says that is in use, and choose a new one. 
Is that possible to recover my original one?
Not that it is relevant, but that is gateway img 0.12.0. SD card is a 8GB Transcend, formatted with "SD Card" formatter and the img written with Etcher.
Thanks.

**Comment by benfrancis** [comment]
Did you use the same email address you originally registered the domain with? If you enter the same domain with the same email address the UI should give the option to re-claim the domain, which sends you an email with a code to enter.

**Comment by DSiwi** [comment]
Yes, the same address.

**Comment by mrstegeman** [comment]
Email me at mstegeman@mozilla.com with the domain name and email address you are trying to use and I’ll see what’s going on.

**Comment by mrstegeman** [comment]
(Resolved via email)
