### ISSUE TITLE
Automatically detect native things

### ISSUE THREAD

**Issue by lazylazyllama** [mozilla-iot/gateway#2478]
When i use proprietary things like the yeelight lamp with the "yeelight adapter" you will automatically see all your lamps in the "add thing" page.

But you don't see any native things there, but have to add them by url.

I think that's a bit annoying and complicated as you have to remember the ip addresses of your devices etc.

Will there be a way so that the gateway could automatically detect all your native webthings devices that are active in your local network?

**Comment by mrstegeman** [comment]
Native web things are discovered via [mDNS](https://github.com/mozilla-iot/wot/issues/75#issuecomment-429934133), which should be implemented in all of the webthing libraries we provide.
