### ISSUE TITLE
Is there 'Add Thing by URL' functionality for Version 0.12.0?

### ISSUE THREAD

**Issue by GFPar** [mozilla-iot/gateway#2481]
Hello, i am playing around creating a custom Webthing (using data transmitted via a esp8266) but cannot see the option of adding a Thing by URL in the latest version of IOT (v0.12). I recalled seeing this as an option in earlier versions of the platform,  when an Add Thing resulted in 'No new things found'.  Is there something i am missing or is an add-on required for such functionality?
Thanks;  Gerry

**Comment by mrstegeman** [comment]
You need to have the Web Thing add-on installed.

**Comment by GFPar** [comment]
Excellent, thank you
