### ISSUE TITLE
Add theme_color property to webappmanifest

### ISSUE THREAD

**Issue by lazylazyllama** [mozilla-iot/gateway#2483]
Adding "theme_color" to the webappmanifest would improve the design on android by coloring the statusbar etc.

I guess the current background color of the gateway might be a good fit:

`"theme_color": #5d9bc7`

**Comment by benfrancis** [comment]
`theme_color` is actually [already set](https://github.com/mozilla-iot/gateway/blob/master/static/app.webmanifest#L22).

Out of interest, what combination of browser and Android version are you using where this doesn't' work? Would you be able to provide a screenshot?

**Comment by lazylazyllama** [comment]
Oh my bad you are right there.

I'm using chrome in dark mode.. apparently if you start the app in full screen mode from the homescreen it still gets a dark status bar.. So thats rather a chromium issue then.
