### ISSUE TITLE
Unable to configure

### ISSUE THREAD

**Issue by LionMike** [mozilla-iot/gateway#2485]
Email notifications. When setting a rule I am unable to configure title and message in e-mail sender add-on.

**Comment by mrstegeman** [comment]
See the README here for a walkthrough: https://github.com/mozilla-iot/email-sender-adapter#readme

**Comment by LionMike** [comment]
I have set all that up and I can send email through the adapter. When I create a rule:

 Motion detected = email sender notification

 I am unable to save configuration. Any text I enter for title or message does not save. However I still receive an email notification. 

![Annotation 2020-04-25 220230](https://user-images.githubusercontent.com/47491873/80296413-9ffc7300-8740-11ea-8273-5a616bb3d7b7.gif)
