### ISSUE TITLE
All domain names resolved to 192.168.2.1

### ISSUE THREAD

**Issue by Gachapen** [mozilla-iot/gateway#2487]
In my gateway all domain names are mapped to 192.168.2.1. This seems to break both updating, time sync, and remote access. From what I could gather, the dnsmasq config seems to be the culprit. I changed `address=/#/192.168.2.1` to `address=/local/192.168.2.1`, and now it properly resolves domain names, but I can't access it on `gateway.local` anymore.

How should I configure it so that it correctly resolves domain names, while still being accessible on gateway.local?

**Comment by LionMike** [comment]
I wonder if this has anything do with not being able to login via remote access with subdomain address?

**Comment by mrstegeman** [comment]
This happens only when your RPi is in AP mode, e.g. waiting for first time setup.

**Comment by mrstegeman** [comment]
If something broke, and things are already set up, you can exit AP mode by doing this:

```
sudo systemctl stop hostapd
sudo systemctl disable hostapd
sudo systemctl stop dnsmasq
sudo systemctl disable dnsmasq
```

**Comment by LionMike** [comment]
Thanks for the info mrstegman. I will add this to my troubleshooting guide. However, the issue resolved itself as I am now able to access the gateway via remote login.
