### ISSUE TITLE
No welcome screen after initial WiFi connection

### ISSUE THREAD

**Issue by Draghmar** [mozilla-iot/gateway#2493]
Hi.
I wanted to play with Mozilla's Gateway a little bit. I took Pi version, installed it and got the IoT's WiFi network. Connected it to my local and, as guide suggested, head to gateway.local on my PC. But instead of the 'Welcome' page I was already redirected to gateway.local/things and the screen was all greyed out. And now I can't do anything...Tried this few times already.
Once it stopped being greyed out and I could use menu and all. But there was nothing I could actually change with empty Users or Network.
I see there's quite a lot of errors in the FF's console, like can't connect to the `ws://gateway.local/internal-logs`

**Comment by Draghmar** [comment]
And quick update. Suddenly I've got 'Welcome' screen but when I click to skip I redirects be back to it.
I have no idea what's going on...

**Comment by mrstegeman** [comment]
Try opening the page in a private browsing window or something. It seems like something may be cached that shouldn't be.

**Comment by Draghmar** [comment]
Yup, I've manage to get through the process eventually. It looked like cache problem. Not sure where it came from. Sometimes hard refreshing helped sometimes restarting process.
Thanks for suggestion.
