### ISSUE TITLE
Updating Action Metadata

### ISSUE THREAD

**Issue by Dahfizz9897** [mozilla-iot/gateway#2498]
Hi! I am developing an addon for the WebThings gateway. I want to be able to populate the dropdown options for an action based on the value of a property, but this does not seem possible on the frontend. In psuedocode:

If myProperty == "valueA":
    myAction.input.enum = [optionX, optionY]
If myProperty == "valueB":
    myAction.input.enum = [optionZ]

I have written the code in my Device that listens for property updates and calls `this.addAction` with the new metadata. I can confirm that `this.actions.get('myAction').input.enum` updates as expected, but the frontend does not update the values in the dropdown of the action. The api also does not reflect that the action's enum has changed.  

I believe this is because information about a device is only gathered when the device_added notification is sent.

My actual code, if it matters: https://gitlab.com/Dahfizz/pimote-adapter/-/blob/master/lib/pimote-device.js

**Comment by mrstegeman** [comment]
You can call `this.adapter.handleDeviceAdded(this)` again to notify the gateway of the change.

**Comment by Dahfizz9897** [comment]
Duh... That should have been obvious to me. Thank you for your help!
