### ISSUE TITLE
npm ERR! notarget No matching version found for type@module.

### ISSUE THREAD

**Issue by opandey007** [mozilla-iot/gateway#2502]
pm ERR! code ETARGET
npm ERR! notarget No matching version found for type@module.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'React-UI'

**Comment by mrstegeman** [comment]
What exactly is this coming from?
