### ISSUE TITLE
Touch - input can be hidden under the virtual keyboard

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#2509]
As mentioned in other issues related to trying the UI with a 1024x600 touch screen, the content can become hidden under the touch screen, with no way to scroll it into view. I don't think this is an issue with the Gateway, but perhaps good to discuss and document anyway.

![touch_strange2](https://user-images.githubusercontent.com/805405/83883828-4ece9e80-a744-11ea-8ca6-c31740a7244f.jpg)

**Comment by flatsiedatsie** [comment]
I've created [a script](https://www.candlesmarthome.com/adding-a-touch-screen-to-the-candle-controller) that installs a basic window manager and a privacy friendly browser, and boots the device into the Gateway. It could be useful in case you'd like to recreate the experience.

**Comment by mrstegeman** [comment]
Definitely seems like this is a browser/keyboard issue. The keyboard extension seems to be drawing on top of the page content, which is not going to work well in a lot of cases.
