### ISSUE TITLE
Gateway stopped working

### ISSUE THREAD

**Issue by Draghmar** [mozilla-iot/gateway#2513]
Hi
I have Gateway on RPI W Zero. I was uing it only to check out how it works so there's almost no devices connected there. Only one temp/humidity sensor from Xiaomi, connected through add-on.
There was also log for temperature ongoing with data saved set for 7 days.
Everything worked fine and I left it for some time without checking. Few days ago I wanted to check out if it still works and...it didn't. Address is unreachable (I'm accessing through IP). I can log in with SSH although it's quite slow. I tried to restart a few times but it didn't help. There's still no web GUI. What can I check through SSH to try to get idea of what's going on?
I mean I know W Zero is very low-end and I planned to buy RPI 4 if I'm happy with this project but at the moment I don't know if it's really hardware related.

**Comment by mrstegeman** [comment]
Here are a few things for you to check:
1. Memory usage: `free -m`
2. Disk usage: `df -h`
3. Logs: `~/.mozilla-iot/log/run-app.log`

**Comment by Draghmar** [comment]
Thanks for suggestions.

1. I've seen min ~45MB of free RAM.
2. Disk looks ok to me.
3. Logs...there are few things that looks weird. But I did found one very interesting. It seems HTTP server moved from :80 to :8080. I do have another device listening on :80 but it didn't cause issue before when accessing directly through IP address.

So yeah, I got web access again. But that didn't resolve reason why it's so sluggish. Sometimes writing on SSH have few second lag - launching `top` took about 10s...
Is it because of W Zero? I don't see CPU being utilized too much most of the time.

**Comment by mrstegeman** [comment]
The memory seems a bit low... You may want to try adding a swap file and see if that helps.

The gateway listens on ports 8080 and 4443, but we have iptables rules in place to route port 80 and 443 to those ports.

Generally speaking, the Zero is pretty underpowered for the gateway. I've used it in the past, but yes, it is pretty sluggish. Node.js is unfortunately pretty heavyweight.

**Comment by Draghmar** [comment]
Ok, thanks for your help.
Swap seems to be on by default:
```
Filename                                Type            Size    Used    Priority
/var/swap                               file            102396  256     -2
```
So you're suggesting that having RPi 4 will make it work much better?

**Comment by mrstegeman** [comment]
Yes, an RPi 4 will do a much better job.

**Comment by madb1lly** [comment]
The symptoms sound just like on my Pi Model B! 😆 Almost any other RPi model will be an improvement.
