### ISSUE TITLE
Short flash of html elements on page refresh

### ISSUE THREAD

**Issue by createcandle** [mozilla-iot/gateway#2514]
![candle_html_elements](https://user-images.githubusercontent.com/39312291/84113223-7f575680-aa2a-11ea-9c6c-216284e1034f.png)

On a page refresh this is visible for about half a second. It's not an issue, but perhaps it's easy to polish out.

**Comment by mrstegeman** [comment]
Duplicate of #1193

**Comment by createcandle** [comment]
I was wondering ifi this could be fixed with CSS, where the elements don't appear/fade in until after a second of two. Especially for messages like "there are no thing connected", which is on the main things page, this could be a simple fix.
