### ISSUE TITLE
WiFi air conditioner connection question

### ISSUE THREAD

**Issue by Draghmar** [mozilla-iot/gateway#2518]
Hi.
I have mobile air conditioner (Columbia Vac) that normally connects through WiFi with mobile app (Smart Life). 
Is there a way to connect this device to the Gateway? I tried to put device into pairing mode and start detection on Gateway but it didn't work. Device is present at my local network because I can manage it through the app. How can I check/test connection?

**Comment by mrstegeman** [comment]
We have a Tuya add-on, which should be what you need. However, I don't believe it currently supports air conditioners. You can try it out, and if your device is not supported, I'd suggest filing an issue here: https://github.com/Galveston01/tuya-adapter/issues
