### ISSUE TITLE
Icon issue when editing floorplan

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#2521]
When I click the edit button on the floorplan page, I see this icon in the bottom right:

![gateway_floorplan_icon_issue](https://user-images.githubusercontent.com/805405/85006557-8f71e300-b15a-11ea-822b-65f1c0972bf6.png)

It shows up after dragging one or two items.

**Comment by benfrancis** [comment]
I'm not able to reproduce this. Is it possible to provide more detailed steps to reproduce or a video?

**Comment by flatsiedatsie** [comment]
I haven't figured out how to reproduce it myself :-D

Something that's possibly related:
- Click on a disconnected item
- You now see the item's detail page, and a "disconnected" bar pops up at the bottom.
- Click "back", and you are back at the floorplan page. However, the "disconnected" overlay is still there.

![gateway_floorplan_disconnected](https://user-images.githubusercontent.com/805405/85011866-72411280-b162-11ea-88fd-4caa6c4384c7.png)

So perhaps the mixing of the icons has something to do with opening a device and then going back, and having that device's edit button still being visible?

**Comment by flatsiedatsie** [comment]
Make sure you're in edit mode, adn then click on an icon. That's when it happens.

![gateway_floorplan_bugs](https://user-images.githubusercontent.com/805405/85012127-d8c63080-b162-11ea-99b0-b032f2ea57e3.png)

Perhaps the bug is that when you're in edit mode, clicking on a device can lead you to that device's detail page in the first place.

**Comment by flatsiedatsie** [comment]
Im now on a thing details page, coming from the floorplan. This is the url: `gateway.local/things/zb-00000000000?referrer=%2Ffloorplan`

I cannot press the edit button of this device.

Try this:

- Go to floorplan page
- long-press on a device to go to it's details page (just discovered this)
- Go back.
- Click edit
- long press on the device again.

That makes it happen consitently here.

For extra fun, click on the bottom-right hybrid icon. Nothing happens. Now press the back icon.
