### ISSUE TITLE
[Feature request] Add comparison operators to Rules Engine

### ISSUE THREAD

**Issue by madb1lly** [mozilla-iot/gateway#2526]
Hi @mrstegeman,

I'd like to be able to do comparison operations between different Thing Properties. These could be properties of the same thing or different things. I presume that to work properly the properties would have to be of the same time.

This would allow various Things to be automated depending on conditions. In my case I'll be comparing temperature values and possibly a wind speed via a weather API.

The comparison operations I'd like are just the standard arithmetic ones: <, >, <=, >=, = 

I presume this would be best done by an extension and I've got it on my list of things to try and do but at my current glacial pace that won't happen this year (at least!) so I'm putting this here in case anyone else thinks it's something they'd like and are able to make.

Cheers 🙂

**Comment by mrstegeman** [comment]
@madb1lly we’ve had a lot of requests for this feature, but it’s pretty tricky to implement. See more discussion at #805.

**Comment by madb1lly** [comment]
Hi @mrstegeman,
You're right, and I knew about that request so I don't know how I didn't put two and two together!
Cheers 🙂
