### ISSUE TITLE
Can not install .deb file on Ubuntu 20.04

### ISSUE THREAD

**Issue by rajibeee** [mozilla-iot/gateway#2527]
I am having these dependency issues on Ubuntu 20.04 LTS

1. Depends on python3(<<3.7.0~~)
2. Depends on libffi6 

For the first one, I tried uninstalling python3 and install python 3.6.5 but it keeps detecting python3.8.2 on my system.

sudo apt-get install libffi-dev says it's not installable.

How do I solve this?

**Comment by mrstegeman** [comment]
The gateway is currently not packaged for 20.04, but will be with the next release. Until then, you could use the [Docker image](https://hub.docker.com/r/mozillaiot/gateway).
