### ISSUE TITLE
README doesn't mention how to install yarn

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#253]
The README suggests using yarn, bur makes no mention of how you're supposed to go about installing it.

Apparently, under OSX you can use `brew install yarn`. Searching for linux I found this page:
https://yarnpkg.com/en/docs/install

and @hobinjk suggested that npm install -g yarn might work.

We should document how we think yarn should be installed.

**Comment by hobinjk** [comment]
Closed by #255
