### ISSUE TITLE
Add CSS class name to discern log detail view?

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#2535]
I'm trying to theme the logs overview page. Currently there is no difference in CSS tags if the overview page is shown, or a detail page (showing only one log).

Would it be possible to add a classname somewhere that allows CSS to respond to these two separate types of display?

For example, perhaps

`<section data-view="logs" id="logs-view" class="selected">`

could become

`<section data-view="logs" id="logs-view" class="selected detail">`

When the user is in the detail view?

**Comment by mrstegeman** [comment]
Right now, you could get that in JS with:

```js
document.querySelector('.logs-log-container-solo-view').parentElement.parentElement
```

**Comment by flatsiedatsie** [comment]
Thank you! Very nice!
