### ISSUE TITLE
Suggestion: add Jquery

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#2543]
In addon development I try to avoid using Jquery, because it don't want every addon to bring its own version of Jquery with it and bloat the application. Already the UI can sometimes get a bit sluggish.

Unfortunately, avoiding Jquery not only slows down development, it apparently brings [its own problems](https://github.com/flatsiedatsie/followers-addon/issues/3) with it.

So it would be really great to have jQuery available.

Would it be possible to have the gateway come with its own jQuery that all addons can then make use of? With would keep the code light weight, as well as make it easier to develop new addons.

Perhaps it could be loaded if at least one UI extension addon is loaded?

Or does having multiple version of jquery loaded really not matter all that much?

**Comment by mrstegeman** [comment]
I have no desire to pull in a (large) dependency that the gateway itself won’t be using.
