### ISSUE TITLE
Logs: limit output quantity?

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#2546]
I tried to log the wireless network speed of the `system` addon, but this creates a log item that is so full of data that trying to load its week view brings my laptop to a crawl.

I suspect the log loads in more data than necessary. If so, perhaps the width of the log in pixels could be sent to the backend, and then the function that loads in the data could average the values according this first. For example, if there are 10000 datapoint in a week view, and there are only 1000 pixels, then the function would average every 10 points into a new single point per pixel? After all, the logs don't support zooming in, so there is no need to have all the data present on the client side?

**Comment by mrstegeman** [comment]
> After all, the logs don't support zooming in, so there is no need to have all the data present on the client side?

That's wrong, and it is _exactly_ why all the data is loaded.

![output](https://user-images.githubusercontent.com/457381/88311911-f6d10480-ccbd-11ea-8df1-fdb49a3750f0.gif)

**Comment by flatsiedatsie** [comment]
Whoa, you're right. I totally forgot about that feature.
