### ISSUE TITLE
Open license links in an overlay

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#2550]
I'm trying to develop this, but am having some trouble getting the Gateway to restart with a new webpacking.

Firstly, this is what I see after `npm install` on a Raspberry Pi 4 1Gb
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/eslint-plugin-html/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
```

Running `npm start` shows this:

```
npm start

> webthings-gateway@0.12.0 start /home/pi/mozilla-iot/gateway
> webpack --display errors-only && node build/gateway.js

ℹ ｢atl｣: Using typescript@3.8.3 from typescript
ℹ ｢atl｣: Using tsconfig.json from /home/pi/mozilla-iot/gateway/tsconfig.json
ℹ ｢atl｣: Checking started in a separate process...
ℹ ｢atl｣: Time: 13213ms
```

Should it continue after this?

I am unable to open the gateway in the browser, even after waiting a few minutes.

**Comment by flatsiedatsie** [comment]
Wait, a few minutes later, and it has now launched. I can also see the changes I made.

**Comment by flatsiedatsie** [comment]
I have most of it working, except for one thing: loading in the external file via AJAX. It seems Github doesn't allow CORS. It also doesn't allow loading in iframes.

Is there already code in the gateway to load external files into javascript via a Node detour?

**Comment by mrstegeman** [comment]
I've added a new API to the add-on proxy, so you can use: `https://api.mozilla-iot.org:8443/addons/license/<addon-id>`

The base URL can be found from `API.getAddonsInfo()`

**Comment by flatsiedatsie** [comment]
Brilliant!

**Comment by flatsiedatsie** [comment]
I've created a pull request
