### ISSUE TITLE
SerialPort.list() doesn't find devices if webthing service is not run as root

### ISSUE THREAD

**Issue by labou77** [mozilla-iot/gateway#2562]
Hello,
I am facing an issue on Raspberry PI 4 with official Raspbian installed. I have installed Webthings using .deb package and I have a Conbee 2 usb dongle to connect to Zigbee devices. When I enable the Zigbee-adapter, I have an error message "No Zigbee dongle found".

After some debugging, here are my findings:
- Webthings is launched with **webthings** user as defined [ here](https://github.com/mozilla-iot/gateway-deb/blob/master/debian/patches/add-launcher.patch) by using setpriv python library
- When zigbee-adapter is added, it calls _serialport_ node library to discover serial devices like Conbee 2: 
`const ports = await SerialPort.list();` [(here)](https://github.com/mozilla-iot/serial-prober-node/blob/5dc4cd88371ebc8601f8fe0d1b3beed84f9d8984/serial-prober.js#L134)

Issue is this method returns nothing. I have tried to run webthings as root, and it is working, Conbee 2 dongle is discovered.
I don't understand why webthings user has no access to SerialPort.list():
- I have added webthings user in dialout group
- I have these access rights on serial device: **crw-rw---- 1 root dialout 166, 0 Jul 31 14:44 /dev/ttyACM0.**

To reproduce the issue,
```
cd /etc/webthings-gateway/addons/zigbee-adapter 
sudo PYTHONPATH=/opt/webthings-gateway/python setpriv   --reuid=webthings   --regid=webthings   --init-groups   --inh-caps=-all node
> const SerialProber = require('./serial-prober');
> SerialProber.listAll()  ==> You will see no serial device found
```
then try the same in root mode:
```
node
> const SerialProber = require('./serial-prober');
> SerialProber.listAll()  ==> You will see serial device found
```

Any recommendation?

**Comment by flatsiedatsie** [comment]
I would recommend running the official Raspberry Pi image. It doesn't have those problems. And you get additional benefits, such as the availability of more addonds that are developed specifically for that image.

**Comment by mrstegeman** [comment]
I actually can't reproduce, but I just [fixed](https://github.com/mozilla-iot/gateway-deb/commit/379c03dd62dde091fbf35bbc1af8da9bdabd9d9e) an issue with this in the package.

Here's the output I get:

```sh
$ cd /etc/webthings-gateway/addons/zigbee-adapter 
$ sudo setpriv --reuid=webthings --regid=webthings --init-groups --inh-caps=-all $(which node)
>
Error: Could not open history file.
REPL session history will not be persisted.
> const SerialProber = require('serial-prober')
undefined
> SerialProber.listAll().then(console.log)
Serial ports that were found:
Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events:
      [Object: null prototype] {
        removeListener: [Function: updateExceptionCapture],
        newListener: [Function: updateExceptionCapture],
        error: [Function: debugDomainError] },
     _eventsCount: 3,
     _maxListeners: undefined,
     members: [],
     [Symbol(kWeak)]: WeakReference {} } }
> USB Serial Device 0658:0200 Vendor: 0658 found @ /dev/ttyACM0
Serial Device found @ /dev/ttyAMA0
Serial Device found @ /dev/ttyS0
undefined
$ sudo $(which node)
> const SerialProber = require('serial-prober')
undefined
> SerialProber.listAll().then(console.log)
Serial ports that were found:
Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events:
      [Object: null prototype] {
        removeListener: [Function: updateExceptionCapture],
        newListener: [Function: updateExceptionCapture],
        error: [Function: debugDomainError] },
     _eventsCount: 3,
     _maxListeners: undefined,
     members: [],
     [Symbol(kWeak)]: WeakReference {} } }
> USB Serial Device 0658:0200 Vendor: 0658 found @ /dev/ttyACM0
Serial Device found @ /dev/ttyAMA0
Serial Device found @ /dev/ttyS0
undefined
```

And here's what my `webthings` user looks like:

```sh
$ id webthings
uid=111(webthings) gid=115(webthings) groups=115(webthings),20(dialout),997(gpio)
```

**Comment by labou77** [comment]
@mrstegeman you are awesome! Your fix worked for me. My `webthings ` was like this:
```
$ id webthings
uid=111(webthings) gid=115(webthings) groups=115(webthings),20(dialout)
```

The only difference was the gpio group. So I tried the command you added in your fix :
`usermod -a -G gpio webthings`
I don't understand why this fixes the serialport issue. Would you have some explanations, maybe related to the inital bug you fixed?

And thanks a lot for your quick answer!

**Comment by mrstegeman** [comment]
Honestly, no idea why that fixed it, but I’m glad it works now!
