### ISSUE TITLE
Add HTTP proxy settings

### ISSUE THREAD

**Issue by hbkoenig** [mozilla-iot/gateway#2566]
I'm trying to run webthings-gateway on a RPI4 behind a http proxy and cannot access add-ons directly from the internet:

2020-08-03 11:23:50.266 ERROR : Failed to parse add-on list: { FetchError: request to https://api.mozilla-iot.org:8443/addons?arch=linux-arm&version=0.12.0&node=64&python=2.7%2C3.7 failed, reason: getaddrinfo ENOTFOUND api.mozilla-iot.org api.mozilla-iot.org:8443
...
   'request to https://api.mozilla-iot.org:8443/addons?arch=linux-arm&version=0.12.0&node=64&python=2.7%2C3.7 failed, reason: getaddrinfo ENOTFOUND api.mozilla-iot.org api.mozilla-iot.org:8443',
  type: 'system',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND' }

and I cannot find any hint how/where to configure http proxy ?!

**Comment by mrstegeman** [comment]
As far as I can tell, Node.js currently has no way to globally configure a proxy, and the gateway doesn’t either.

**Comment by hbkoenig** [comment]
other idea for workaround: is there a method to load/add add-ons from local files (like firefox/thunderbird offer) ?
picking up the file with wget works (read: proxy setup works, too;)

I've tried to setup environment vars -- doesn't help:

# ps up `pgrep node`
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
webthin+ 21869  3.3  1.9 187196 75912 ?        Sl   18:50   0:17 node build/gateway.js

# strings /proc/`pgrep node`/environ  | grep -i proxy 
https_proxy=https://127.0.0.1:3128
HTTPS_PROXY=https://127.0.0.1:3128
HTTP_PROXY=http://127.0.0.1:3128
http_proxy=http://127.0.0.1:3128

# systemctl  show  webthings-gateway | grep -i prox
Environment=PYTHONPATH=/opt/webthings-gateway/python http_proxy=http://127.0.0.1:3128 https_proxy=https://127.0.0.1:3128 HTTP_PROXY=http://127.0.0.1:3128 HTTPS_PROXY=https://127.0.0.1:3128

then I found some hints in /opt/webthings-gateway/... about 'options.get("http_proxy_host", None)' etc and tried to setup /etc/webthings-gateway/config/local.json like this without luck:

{
    "security": "nosec_sc",
    "proxy_info": {
        "proxy_type": "http",
        "http_proxy_host": "127.0.0.1",
        "http_proxy_port": "3128"
    },
    "proxy_type": "http",
    "http_proxy_host": "127.0.0.1",
    "http_proxy_port": "3128",
    "ports": {
        "https": 443,
        "http": 8081
    }
}

thanks for any hint!!

**Comment by mrstegeman** [comment]
Yeah, Node ignores all of those variables. It has to be set up per Node library, and we don't have any code in place to do that.

You _can_ install add-ons manually, though.
1. Download the appropriate package
2. Unpack it into `~/.mozilla-iot/addons`
3. Rename the unpacked `package` directory to the add-on ID, e.g. `zigbee-adapter`
4. Restart the gateway
5. Enable the add-on in the UI, via _Settings -> Add-ons_

**Comment by hbkoenig** [comment]
thanks!!! 
manual setup worked...

now next quest is to get ConBee II usb stick detected: https://github.com/mozilla-iot/zigbee-adapter/issues/224
