### ISSUE TITLE
Unknown property ‘touch-callout’

### ISSUE THREAD

**Issue by madb1lly** [mozilla-iot/gateway#2583]
Hello everyone,

Another error from the Devtools console when loading the Gateway UI:
```
Unknown property ‘touch-callout’.  Declaration dropped. ecb8214310f4b58c1a56-style.css:1566:17
Elements matching selector: .floorplan-thing
NodeList []
```
​This seems less likely to be causing the slowdown, but could it?

Cheers 🙂

**Comment by mrstegeman** [comment]
CSS is here: https://github.com/mozilla-iot/gateway/blob/e8a9cc43e8146aab41cb1a65e8a6f412197e6b27/static/css/floorplan.css#L33

This should just be ignored, though, not cause any issues.

**Comment by madb1lly** [comment]
Hi @mrstegeman,
Thanks for demystifying some of this stuff for me!
Cheers 🙂
