### ISSUE TITLE
Integrate an intent parser inside the gateway and communicate with the gateway actions REST api

### ISSUE THREAD

**Issue by andrenatal** [mozilla-iot/gateway#261]

**Comment by benfrancis** [comment]
@andrenatal or @tamarahills I would be grateful if you could provide some more information here so we are clearer on exactly what the requirements are and what work is involved.

A good way to express the requirements would be a high level user story for the new gateway feature(s) and a brief breakdown of the work involved.

My understanding from our meeting yesterday was that this component is needed to turn an "intent" (in the form of a JSON object from api.ai) into a Web Thing API call as part of the process of turning a speech command into an action on a web thing.

One concern I have is how specific this would be to the api.ai service. I would prefer us not to hard code support for third party services into the gateway. As a minimum it should be possible for the user to turn the speech UI on and off from the "experiments" section of settings. This feature could be implemented as a separate pluggable module like the [rules engine](https://github.com/mozilla-iot/rules-engine), but we don't currently have a great mechanism for these types of "add-ons".

Anyway, it would be great to get a bit more detail here so we can measure progress and test against some clear requirements :)

**Comment by tamarahills** [comment]
![gateway speech 1](https://user-images.githubusercontent.com/7558944/29981068-571bbeb4-8f1a-11e7-9e04-04750435b874.png)

**Comment by tamarahills** [comment]
Attached the flow from our discussions this afternoon

**Comment by andrenatal** [comment]
Fixed by #273
