### ISSUE TITLE
Have you considered the use of this project on Arduino Yun-like boards (openwrt based)?

### ISSUE THREAD

**Issue by q2dg** [mozilla-iot/gateway#289]
Thanks!

**Comment by dhylands** [comment]
As long as you can run a recent version of node, then it should work. I'm not sure that is anything that is raspberry pi specific. The startup scripts might need to be tweaked, (since the pi uses systemd - not sure what Yun uses).

**Comment by q2dg** [comment]
Ok. I'm not sure...assuming Yún uses a customized OpenWrt and this system uses a custom init system called "procd" (https://wiki.openwrt.org/doc/techref/procd) maybe necessary changes can be a little cumbersome. If you don't mind, I'll close the issue. Thanks a lot anyway!!
