### ISSUE TITLE
Running the gateway modifies the floorplan

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#295]
Everytime I run the gateway, the floorplan .svg file gets modified.

This makes it show up as changed in git. If we need to modify it, perhaps we can make a copy and have the changes made to the copy rather than the original?

**Comment by benfrancis** [comment]
floorplan.svg should be ignored by git https://github.com/mozilla-iot/gateway/blob/master/.gitignore#L13

It should only get modified when you upload a floorplan (which over-writes the default), and possibly when you run integration tests...

Anyway, @hobinjk has suggested fixing this by storing the default floorplan separately from an uploaded one https://github.com/mozilla-iot/gateway/issues/279

**Comment by dhylands** [comment]
Yeah - I was seeing it modified after running `npm test`.
```
2027 >git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   static/uploads/floorplan.svg

no changes added to commit (use "git add" and/or "git commit -a")
```
even though its in .gitignore

So I had to keep checking it out so that I could use `git add -u .`

**Comment by dhylands** [comment]
Ahh - .gitignore only ignores untracked files, and not tracked files.
