### ISSUE TITLE
Adapter IPC needs to support multiple adapters per plugin

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#307]
The current model only supports one adapter per plugin, but some adapters, like zigbee and zwave can support multiple adapters (if you use multiple dongles).

To support that case, some small changes need to be made in order to allow multiple adapters to be supported per plugin.

I think that most of the changes will be renaming some adapterIds to be pluginId's

**Comment by sogaani** [comment]
Is this resolved by #708?
I seem to have already been implemented.

**Comment by mrstegeman** [comment]
Fixed by #708
