### ISSUE TITLE
Figure out how to get rid of adapter-constants.js

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#308]
Currently, src/adapters/adapter-constants.js is a symlink to src/constants.js

I found that this was needed because constants.js winds up being included into the webpack gateway.js in the build directory. The adapters are dynamicallyrequired rather than statically required and this breaks the dependency checking that webpack does.

If the dynamically loaded adapter uses require('../constants') then it fails because build/constants.js doesn't exist. We need to figure out how to reach into they gateway.js file and get the constants from there, then we can remove the adapter-constants.js

**Comment by sogaani** [comment]
Maybe we cant reach into gateway.js directly.

Can webpack's [multi-part-library](https://github.com/webpack/webpack/tree/master/examples/multi-part-library) help you?

If APIs (e.g. addon-constant.js adapter.js device.js) require file out of addons folder, multi-part-library flatten required files in to a library file.

Example webpack options is follows.
```js
{
    entry: {
        adapter-constant: './src/constant.js'
    },
    target: 'node',
    node: {
        __dirname: false,
        __filename: false,
    },
    optimization: {
        minimize: false,
    },
    output: {
        path: path.join(__dirname, 'build', 'addons'),
        filename: "[name].js",
        library: '',
        libraryTarget: "commonjs"
    },
    devtool: 'sourcemap',
    plugins: addonPlugins,
    externals,
}
```

**Comment by mrstegeman** [comment]
This is done. Constants are now in the gateway-addon package.
