### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#317]
After flashing version 0.2 I got through the first time setup, was enable to add devices, enable the rule engine and create a rule.

Then on reloading the page Firefox freaked out about an SSL error:

> An error occurred during a connection to tola8.mozilla-iot.org. Peer received a valid certificate, but access was denied. Error code: SSL_ERROR_ACCESS_DENIED_ALERT

**Comment by hobinjk** [comment]
This error occurs when the Gateway is down. A configuration change on the server might make this error less confusing

**Comment by mrstegeman** [comment]
Duplicates #560
