### ISSUE TITLE
As a user, I'd like my gateway to support more things and sensors

### ISSUE THREAD

**Issue by andrenatal** [mozilla-iot/gateway#330]
Like this one, for example: https://www.amazon.com/Aeotec-Multisensor-temperature-humidity-vibration/dp/B0151Z8ZQY/ref=sr_1_1?ie=UTF8&qid=1507757418&sr=8-1&keywords=zwave+aeotec

**Comment by rzr** [comment]
Hi I have work in progress regarding sensors:

https://discourse.mozilla.org/t/creating-i2c-add-on/26696/4

Feel free to suggest sensor references in this thread.

**Comment by mrstegeman** [comment]
We support a whole lot more things now.

**Comment by rzr** [comment]
More hints about building your sensors things:

https://github.com/rzr/webthing-iotjs/wiki/Sensor
