### ISSUE TITLE
Property status messages can be lost during websocket opening

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/gateway#333]
There's a brief window when the page is loading where the initial GET property status arrives and is out of date by the time the websocket opens and can track further changes to property status.

**Comment by benfrancis** [comment]
@hobinjk Would this be fixed by https://github.com/mozilla-iot/wot/issues/95 ?

**Comment by hobinjk** [comment]
Yes, this is essentially the same issue described from the gateway side

**Comment by mrstegeman** [comment]
Fixed by #2403
