### ISSUE TITLE
Speech UI doesn't work in Safari

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#334]
Trying to issue a speech command in the Chrome web browser fails with the following error:

```
stm_web.min.js:1 DOMException: Failed to construct 'MediaRecorder': Failed to initialize native MediaRecorder the type provided (audio/ogg) is not supported.
    at r (https://192.168.1.69:4443/js/lib/stm_web.min.js:1:528)
    at <anonymous>
```

Tested in Chrome on Mac OS & Android.

@andrenatal This is going to a problem for our MozFest demo, is there an easy fix for this or does the stm library not support Chrome?

**Comment by benfrancis** [comment]
Also doesn't work in Safari:

```
ReferenceError: Can't find variable: AudioContext
r — stm_web.min.js:1:86
promiseReactionJob
```

**Comment by andrenatal** [comment]
We started to investigate this issue. Implementation of gum on safari is pretty new and I still need to understand how it works, but for Chrome we already now and are fixing.

**Comment by andrenatal** [comment]
This is working on Chrome already, but no plans for Safari yet since they don't support MediaRecorder iirc.

**Comment by mrstegeman** [comment]
On latest Safari, when enabling the MediaRecorder experimental feature:

```
[Warning] Error requiring STM (8c0c869d48789a2a46c2-app.js, line 39161)
TypeError: MediaRecorder.isTypeSupported is not a function. (In 'MediaRecorder.isTypeSupported(RECORDING_MIME_TYPE)', 'MediaRecorder.isTypeSupported' is undefined)
```
