### ISSUE TITLE
Need a mechanism to detect and remove failed ZWave nodes

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#35]
The ZWave controller will eventually mark a node as failed if it stops responding after a while. We need a way to tag these nodes as failed, and a way to call the Manager::RemoveFailedNode C++ API.

I think that this can be reproduced by adding a node and then factory resetting it. You can then add the node a second time, and the first nodeId will stick around and should eventually get marked as failed.

**Comment by benfrancis** [comment]
@dhylands In my testing, un-pairing a Z-Wave device does not remove it from the list of devices the adapter reports. Shouldn't a device be removed immediately when manually un-paired? This is a bit annoying because at the moment you can get lots of duplicate devices in the add device dialog.

**Comment by dhylands** [comment]
It's possible it's not getting removed from everywhere. I'll take a look.

**Comment by mrstegeman** [comment]
Moved: mozilla-iot/zwave-adapter#31
