### ISSUE TITLE
Zigbee devices show up multiple times during pairing

### ISSUE THREAD

**Issue by mrstegeman** [mozilla-iot/gateway#365]
When adding a device through the UI, if the device is in pairing mode (i.e. the status LED on the switch is actively blinking), the device will show up multiple times in the UI. It seems like one entry is created for every time the LED blinks. It might just be a case of not filtering out duplicate values.

<img width="1788" alt="screen shot 2017-10-30 at 08 50 58" src="https://user-images.githubusercontent.com/457381/32181080-27fd797a-bd59-11e7-8631-25bc97f01b0b.png">

**Comment by benfrancis** [comment]
Strange nobody else has come across this bug yet, which ZigBee controller/dongle and end device are you using here? It shouldn't be necessary to filter anything out, we should just get one message over the WebSocket.

CC @dhylands

**Comment by mrstegeman** [comment]
It's the 45852GE Plug-In Smart Dimmer.

**Comment by dhylands** [comment]
Does yours say ZB3101 on the back? If so its the same as mine.

I've also seen this behaviour before, but it seemed intermittent. I'll see if I can figure out what's going on.

**Comment by mrstegeman** [comment]
Yes, ZB3101. It was happening every single time I would reset the device and re-pair it, but the number of entries on the UI would change each time.

**Comment by dhylands** [comment]
This appears to be a problem with the UI not closing web sockets. Each time you press plus and done, it sets up a new websocket but doesnt shut it down. So if you sit there and click Plus/Done/Plus/Done/Plus/Done a bunch of times and then do a factory reset, then you'll get one device added per Plus/Done cycle.
There also appears to be an issue where the device can exist, and when if you factory reset the device and plug it in it creates a "new thing" notification which the UI doesn't detect as a duplicate (i.e. it got a new thing notification for a thing that was already on the screen).

**Comment by benfrancis** [comment]
LOL, and I think I implemented that code, should have known better :)

Thanks @dhylands for debugging, @mrstegeman for fixing and @hobinjk for reviewing!
