### ISSUE TITLE
Page loading is slow

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/gateway#366]
As a user I want the gateway's UI to be interactive within at most 5 seconds the first time I load it, and within 2 seconds on subsequent loads. Ideally this performance would be achievable on mobile.

This is an issue covering various investigations into the loading speed of the gateway. The main goal is to reduce the time until the gateway is interactive (TTI).

[Baseline](https://www.webpagetest.org/result/171030_SF_48c1dfc0a4a9b9cbe49055a357d48f3b/): 16s first, 13s repeat
[Enabling max-age caching](https://www.webpagetest.org/result/171030_DS_a065d7b9c740090d4d09318b422e0c32/): 16s first, 6s repeat
[Enabling compression and caching](https://www.webpagetest.org/result/171030_K0_45c9e74e9c027535be48ed15c7a65e2a/): 16s first, 5.5s repeat

**Comment by hobinjk** [comment]
Time to first byte is consistently at 2.5s when it could be closer to 0.4-0.8s

**Comment by hobinjk** [comment]
The majority of the TTFB is from the 3G slow latency

**Comment by hobinjk** [comment]
[Compress+cache desktop](https://www.webpagetest.org/result/171030_3B_6dd39200bcb5f5ba3bb8d1b0a011ba42/): 6.4s first, 2.7s repeat
[Baseline desktop](https://www.webpagetest.org/result/171030_V4_8c781afcd48ff1f896d80fc2f77481ae/): 6.4s first, 5s repeat

**Comment by hobinjk** [comment]
[Concat desktop](https://www.webpagetest.org/result/171030_G8_2be1c9401af1a7299cb43d2ad00032ce/): 4.7 first, 4.6 repeat
[Concat+compress+cache desktop](https://www.webpagetest.org/result/171030_T6_f8bd0220eea1cff69548f52f886a3885/): 5.1 first, 2.4 repeat

**Comment by hobinjk** [comment]
[Caching /things HTML output, not concating](https://www.web pagetest.org/result/171031_HT_5da53402d2127f0ba8ce56537003f2a6/): 6.7s first, 1.7s repeat

At this point I think the main focus should be SW caching and reducing the latency of the server. The dominating factor is the 0.8s TTFB.

**Comment by hobinjk** [comment]
Something that would also help but require a ton of design thought is to perform early termination of the SSL connections at the api.mozilla-iot.org server and count on pagekite to secure the api to gateway connection

**Comment by benfrancis** [comment]
Nice data-driven analysis of the performance issues!

Agree about Service Workers, which is something I think we should do anyway and may also be a component of a local security model.

I wish the tunnel could just go away :( Not sure about terminating the SSL connection in the cloud, I like the fact that HTTP payloads are encrypted all the way from browser to gateway so that the messages are opaque to the tunnelling service.

**Comment by hobinjk** [comment]
[SW enabled + normal caching](https://www.webpagetest.org/result/171031_XJ_bfbd4420990f175e9b3f76c1062056e7/): 10s first, 2.3s repeat
The SW delays the initial load because it caches files that aren't included then the CPU overhead of the SW delays repeated loads (and doesn't appear to cache more than normal HTTP caching in this case).

This is using https://serviceworke.rs/strategy-cache-and-update_service-worker_doc.html and could very well be different with a different strategy

**Comment by hobinjk** [comment]
Following up in #447
