### ISSUE TITLE
Add New Device Timeout

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#37]
Currently the Add New Device dialog will appear to keep scanning for new devices forever.

We should add a timeout (at the adapter layer, the UI layer, or both) and close open websockets when we're done.

**Comment by mrstegeman** [comment]
Should be easy enough to add, but what timeout? 30s?

**Comment by benfrancis** [comment]
@dhylands Do you know how long it takes for Zigbee and Z-Wave adapters to time out? If we could surface the timeout to the UI through the WebSocket API rather than use a fixed timeout that would be a better solution because otherwise things could get paired added after the timeout.

**Comment by mrstegeman** [comment]
The problem is that each adapter can have a completely different timeout. For instance, the TP-Link adapter is pinned at 3 seconds, because that's all it really takes.

**Comment by dhylands** [comment]
Zwave has no timeout. With Zigbee the timeout can be anything between 1 and 254 seconds. It's currently set to 180 seconds in the config.

**Comment by benfrancis** [comment]
How about if we set the Zigbee timeout to say 60 seconds (or 120 seconds?) and turn of Z-Wave pairing after that same period of time?

**Comment by mrstegeman** [comment]
Seems reasonable to me.
