### ISSUE TITLE
Gateway sdcard image will only run on RPi 3

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#374]
If you try to boot up the sdcard image on a Raspberry Pi earlier than the Pi 3 then the gateway won't load.

It turns out that the base image needs to be built on an earlier version of the RPi, and the build-image.sh script needs to specify armv6l rather than armv7l.

Building the base image on an RPi Model B+ I was able to run the gateway on the B+ and on a PiZero.

**Comment by mrstegeman** [comment]
@dhylands I believe this is fixed now, correct?

**Comment by dhylands** [comment]
Yes - this was fixed by https://github.com/mozilla-iot/rpi-image-builder/commit/867ab35845f8ef50f5121e0a3c4e078c1e21f174
Also see #380 for further details.
