### ISSUE TITLE
OAuth - Authorize third party application

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#376]
As a user I want to authorize a third party application to access my Things gateway to monitor and control Things

- #335 - Implement OAuth authorization flow
- #340 - OAuth Third-party registration
- #339 - OAuth Authorization Grants and JWT Expiry
- #305 - Support OAuthv2 as a Server

**Comment by benfrancis** [comment]
@hobinjk Is there anything left to do here or can all of these issues be closed?

**Comment by hobinjk** [comment]
@benfrancis All of the open issues are still part of the backlog since at this point only the core implementation of the OAuth protocol is done

**Comment by hobinjk** [comment]
This issue is more of a tracking issue for the complete OAuth implementation whereas the part that we wanted to get in 0.3.0 (just the flow, #335) is done

**Comment by benfrancis** [comment]
OK, thanks.

**Comment by hobinjk** [comment]
This is definitely done by now
