### ISSUE TITLE
Re-claim subdomain

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#379]
As a user I want to re-claim a subdomain I previously registered so I don't lose my subdomain if I re-install or reset my gateway

**Comment by mrstegeman** [comment]
I was thinking about an architecture something like the following:

- When gateway is first set up, they are presented with a login/register form.
  - If it's a new user, they will then set up a new domain as usual.
  - If it's an existing user, they are given the option of creating a new domain (again, as usual), or they can choose one they've previously registered. Their list of previously registered domains would ideally only include "inactive" ones, i.e. gateways that haven't pinged/registered with the registration server in some time, or at least we could show the user the last time each domain was used. Either way, we'll have to handle the case where the user chooses a subdomain they're already using on another gateway.
- Secondarily, we should give the user the ability to manage their domains from the gateway's settings (or some other) UI.

**Comment by benfrancis** [comment]
Your "architecture" sounds like a UI design :) Let's get a UI design from UX, or if not I'll mock one up.

My suggestion is to offer to reclaim a domain if a user enters a subdomain which is already taken. Something along the lines of... "This name is already taken. If you previously registered this subdomain and want to transfer it to this gateway then click here to reclaim it".

**Comment by mrstegeman** [comment]
How does this look (an extension of `flow.md` from the registration server):

1. [gateway <-> browser] Start the server on HTTP and load the setup UI at http://localhost:8080
2. [gateway <-> cloud] User chooses a DNS name already in use (determined via `/subscribe`) and is given the option to reclaim.
3. [gateway <-> cloud] Gateway calls `/reclaim`. A random reclamation token is generated and emailed to the registered email address.
4. [gateway <-> browser] User enters the reclamation token.
5. [gateway <-> cloud] Gateway again calls `/subscribe` with the reclamation token, receives and API token.
6. [gateway <-> cloud] Run the LE DNS challenge, use `/dnsconfig`, retrieve the certificates, restart the server on HTTPS.
7. [gateway <-> browser] Create the admin account with an email address, verify email using `/setemail`.
8. [gateway <-> cloud] Periodically ping the cloud service using `/ping`.

**Comment by mrstegeman** [comment]
Server side is working and merged: https://github.com/mozilla-iot/registration_server/pull/45
