### ISSUE TITLE
Automated Raspberry Pi 3 builds

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#380]
As a Mozilla IoT developer I want a Raspberry Pi 3 OS image to be created automatically on each commit/day/sprint/release so that I don't have to manually create one.

Frequency to be determined.

**Comment by dhylands** [comment]
Completed by https://github.com/mozilla-iot/rpi-image-builder/commit/867ab35845f8ef50f5121e0a3c4e078c1e21f174

For instructions on use, see the README.md file in the rpi-image-builder repository:
https://github.com/mozilla-iot/rpi-image-builder

This page: https://github.com/mozilla-iot/wiki/wiki/Uploading-a-base-image-to-AWS has instructions on uploading new base images, and this page: https://github.com/mozilla-iot/wiki/wiki/Creating-the-base-image-file-for-the-Raspberry-Pi has instructions on how to create a base image.

The 0.2.2 release of the gateway was targeted to the armv6l which is essentially the same as 0.2.1 except that it will run on the Raspberry Pi 2, Pi-Zero and Pi-Zero-W.
https://github.com/mozilla-iot/gateway/releases/tag/0.2.2

Note: You'll need to use a Raspberry Pi 2/Pi-Zero/Piz-Zero-W to build the armv6l base image. If you use an RPi 3, then you'll get an armv7l base image that won't run on the armv6l boards.

**Comment by benfrancis** [comment]
@dhylands  This is great, although arguably this user story is not actually complete yet, depending on what we want the frequency to be.

Do you think we should have nightly builds that are automatically generated every day like Firefox Nightly, or just stick to manually triggering a build at the end of each sprint or release?

**Comment by dhylands** [comment]
I guess I'm not sure. Is anybody going to actually going to download nightly builds? It seems like it would be much faster to install git and update the repository that way.

Its not very difficult to trigger nightly builds. We could add it using Travis's cron job feature.

We'd be accumulating 1/2 a gig of image files every night. Do we pay for that?

**Comment by benfrancis** [comment]
I suppose nightly builds does seem excessive. A build every two weeks at the end of the sprint might be useful, but maybe not that important yet. Let's leave it for now.
