### ISSUE TITLE
show voice commands for things

### ISSUE THREAD

**Issue by kgiori** [mozilla-iot/gateway#403]
I learned what the acceptable voice commands were from listening to others. But how does a new user know what to say? Provide help to show the user what command(s) are expected.

An idea:
* mouse over an actionable or readable widget (like a binary switch) to see the command: "Turn [on|off] the [widget name (e.g., kitchen)]" or "Read the [widget name (e.g., temperature)]"

Optional administrative actions:
* allow user to change the command text and/or select an alternate supported language

**Comment by mrstegeman** [comment]
I think we can call this closed now that we have hints on the assistant page.
