### ISSUE TITLE
hands-free trigger for browser-based voice commands and microphone-enabled gateways

### ISSUE THREAD

**Issue by kgiori** [mozilla-iot/gateway#404]
Currently clicking the microphone icon invokes having the browser listen for a voice command to be interpreted. When the browser is capable of listening for a call sign or specific keyword, trigger that same action.

For gateways enabled with microphones (or for a device like [respeaker](https://www.seeedstudio.com/series/Respeaker-10.html)), there is no gui/browser, so take actions based on voice commands directly, that are triggered by a keyword.

Help and edit of keyword:
* mouse over of the microphone button could show the trigger word, akin to "alexa", "hey siri", or "ok google".
* in admin config, allow user to change the voice command keyword (e.g., "hey mr. fox")

**Comment by benfrancis** [comment]
I think wake word detection would need to be implemented on the client side (i.e. in the web browser or a dedicated client device) not the server side (i.e. the gateway).

**Comment by kgiori** [comment]
For independent voice controllers (e.g., can even be another RPi with a mic hat), where the voice software is running on a remote platform, not the gateway, what action is necessary to tie the controller commands, or the entire controller device, to the gateway? And what information from the gateway should users be allowed to share with the remote controller? (For example, can the person using the voice controller ask for a list of the names of things that can be controlled?)

**Comment by benfrancis** [comment]
A Web of Things controller could get a list of things hosted by a gateway via the Web Thing API on the gateway https://iot.mozilla.org/wot/#things-resource

I have filed https://github.com/mozilla-iot/things-controller/issues/1 to discuss a hands-free trigger, in a new [things-controller](https://github.com/mozilla-iot/things-controller) repository to discuss features of a potential new Things Controller component for project things.
