### ISSUE TITLE
Weave/Thread adapter

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#410]
Investigate what it would take to create a Nest Weave adapter to be compatible with "Works with Nest" devices.

https://developers.nest.com/weave/

**Comment by benfrancis** [comment]
Note: Nest recently open sourced a Weave implementation on GitHub which may help https://github.com/openweave/openweave-core

**Comment by benfrancis** [comment]
Specifications: https://github.com/openweave/openweave-core/tree/master/doc/specs

**Comment by benfrancis** [comment]
New documentation at https://openweave.io/

**Comment by benfrancis** [comment]
@dhylands As I understand it this growing range of Nest devices use Weave over Thread, which uses the same 802.15.4 wireless layer as Zigbee, but requires different firmware. Have you looked into this at all?

My assumption is that an 802.15.4 radio can not do Zigbee and Thread at the same time, so you'd need two separate radios. Do you think that's correct?

Theoretically the XStick should be able to use Thread with the right firmware, but I'm not sure if that firmware exists.

I think you have the [Nordic nRF52840](https://www.nordicsemi.com/eng/Products/nRF52840-Dongle) dongle which says it supports both Zigbee and Thread (and Bluetooth), but I don't know if it can do both Zigbee and Thread at the same time? This is also something to consider for any production hardware we may target in the future.

The [OpenThread](https://openthread.io/) and [OpenWeave ](https://openweave.io/) open source implementations may be helpful.

**Comment by stefanreimers** [comment]
Would definitely appreciate more Zigbee Adapters, as Digi XStick appears to be hard to get. Raspbee sounds great.

**Comment by dhylands** [comment]
I'm actively working on ConBee/RaspBee and have plans to add Nordic nrf52840-Dongle and TI cc2531 down the road.

**Comment by dhylands** [comment]
The zigbee-conbee-adapter talks to the deConz REST API which needs the deConz REST server running. In my development code I can talk directly to the ConBee and since the RaspBee uses the same chip, I just need to test it with that, which I'll be doing next week.
