### ISSUE TITLE
Smart Plug Web Thing Type

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#431]
As a user I want to see my smart plug represented as a smart plug thing type so that I can use more features than just turning it on and off.

**Comment by benfrancis** [comment]
I've been  looking at defining a smart plug web thing type and what prior art exists.

oneiota.org (used by OCF) has a basic "binary switch" type (https://www.oneiota.org/revisions/2468), an "energy" type (https://www.oneiota.org/revisions/2734) which defines voltage, current, and and frequency and a energy.consumption type (https://www.oneiota.org/revisions/2437) which defines power and energy. 

Beyond the basic On/Off Switch and On/Off output device types which support the "On/Off" cluster, ZigBee has a "Smart Plug" device type which supports the "Metering and "On/Off clusters". I can't find the "Metering" cluster defined in the ZigBee Home Automation profile (I think it's part of the separate Smart Energy Profile), but the Home Automation profile does also have an "Electrical Measurement Cluster" which includes all kinds of measures of frequency, current and power as well as "alarms" like "ACCurrentOverload" which we could use to trigger events if supported.

In addition to the SWITCH_BINARY command class, Z-Wave also has a METER command class. The METER command class can be set to an electric meter with scales including kWh and W.

I'm really just guessing here about what commercial ZigBee and Z-Wave smart plugs actually support so it requires some investigation into the devices we've already bought to get an idea.

**Comment by mrstegeman** [comment]
I assume we're good to close this now that we have device support?

**Comment by dhylands** [comment]
Now implemented via #495 and #497
