### ISSUE TITLE
Rules should support basic time-of-day triggers

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/gateway#444]
If it is 7 AM turn on my lights
If it is 11 PM dim the lights

**Comment by hobinjk** [comment]
Also `when it is between 12 PM and 1 PM`

**Comment by dhylands** [comment]
Perhaps this should be a separate issue, but I'd also very much like to see a couple of special constants for sunset and sunrise. Having time arithmetic would also be good. i.e. someway to specify 30 minutes before sunset

This would require that the user enter a location (lattitude/longitude). There appears to be a node library for doing the math: https://github.com/mourner/suncalc
