### ISSUE TITLE
settings doesn't seem to be logging useful information

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#445]
I see lots of messages like the following in the console log:
```
getSetting undefined
getSetting { value: '1' }
getSetting undefined
getSetting { value: '1' }
getSetting { value: '1' }
getSetting undefined
```
which seem slightly less than useful as the key information seems to be omitted.

I would suggest that the settings module should also probably have something like a `const DEBUG = false;` at the top of the file and the logging should be conditional based on that.

**Comment by benfrancis** [comment]
Which reminds me, PageKit can be very noisy in the logs too, especially if you access a server from localhost which has been configured with a domain!
