### ISSUE TITLE
Too much is cached?

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#454]
Here's the scenario. My gateway is plugged in via ethernet. I had previously connected to my gateway using gateway.local and gotten back a list of things (I hadn't added any so it was empty).

Then I rebooted in a way that caused the wifi setup to become active. When I browse to http://gateway.local from my desktop using the ethernet interface, I still get back an empty things screen, even though the gateway software isn't even running. If I browsed instead directly to the IP address using http://192.168.1.79/ then I get back the wifi setup screen, which I was expecting. I was also able to browse to http://gateway.local:8080 and get the wifi setup screen. Pressing reload on the empty things screen just gives an error, since it's already been redirected to https://gateway.local/things and the setup code isn't listening to https requests.

Looking at the the network inspector (using developer tools), it shows that all of the results were retrieved using cached data. the final few fetches (like from /things/) showed that zero bytes were transferred, but the UI didn't give any indication that something was amiss. Presumably we should at least have / setup so that it doesn't cache it.

**Comment by benfrancis** [comment]
I'd say we do want index.html to be cached, ideally using a Service Worker so that the whole client part works offline. But we should also be detecting when the server can't be reached and responding accordingly.

**Comment by dhylands** [comment]
I had occasion for a variation of this where the javascript for the UI was updated, but the browser was using the older version of the javascript rather than the newer version that the gateway had.

This is going to cause all kinds of weird issues when updates happen.

**Comment by benfrancis** [comment]
Note: Fabrice suggested using [HTTP ETag](https://en.wikipedia.org/wiki/HTTP_ETag) headers to know when to invalidate the cache.

**Comment by hobinjk** [comment]
Quoting from #503: The contributing factor to the 15 second loading time isn't throughput, it's latency. The ETag header prevents the file from being sent but still costs a full round trip. Using maxAge prevents the need for the round trip but means that you have to use a hard refresh to signal that you don't want to use the cache.

**Comment by hobinjk** [comment]
In general, I have yet to have a single problem with caching. This is due to my habitual use of hard refresh instead of normal refresh. In terms of key commands, this is Apple-Shift-R instead of Apple-R (s/Apple/Ctrl/g if you're on windows/linux).

**Comment by mrstegeman** [comment]
We'll let this get fixed by #447.

**Comment by dhylands** [comment]
I do what the typical user would do, which is click the little circle icon beside the back/next arrows.
