### ISSUE TITLE
Addon loader causes intermittent test failures

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#460]
I've uncovered a race condition which can cause intermittent test failures.

When the addon-test.js test runs, it installs the example-adapter and then later uninstalls it. Other tests, running in parallel, call loadAddons, which scans the addons-test directory and attempts to load all of the adapters it finds.

Its possible that during this scan, another parallel test is in the process of removing the example-adapter. Depending on exactly what files have been removed, this can cause a variety of failures. One that I've been able to capture is:
```
    console.error src/addon-manager.js:564
      { Error: ENOENT: no such file or directory, lstat '/home/dhylands/Dropbox/moziot/gateway/src/addons-test/example-adapter'
          at Object.fs.lstatSync (fs.js:961:11)
          at /home/dhylands/Dropbox/moziot/gateway/src/addon-manager.js:560:19
          at FSReqWrap.oncomplete (fs.js:114:15)
        errno: -2,
        code: 'ENOENT',
        syscall: 'lstat',
        path: '/home/dhylands/Dropbox/moziot/gateway/src/addons-test/example-adapter' }
```
In this particular case, the example-adapter directory existed when the call to fs.readdir was made, but the directory did not exist when the call to fs.lstatSync was made. It's conceivable, that under the right conditions, some of the files from the example-adapter are deleted, but not all, and then the process of loading the plugin would fail in other more mysterious ways.

Comment 1: I don't think that we should be installing addons into the source tree.

Comment 2: Installed addons (which are stored on the filesystem) for tests should go into a directory which won't collide with other tests running in parallel. The src/app-instance.js file can be used to generate a string which is guaranteed to be unique for each test.

Comment 3: We should probably have some way of validating the files in the installed plugin directory. For example, if power were removed partway through expanding the plugin tarball, then we would be leaving an incomplete set of files, and the next time we run, we'd try to load this incompletely installed plugin which may very well cause a crash.

**Comment by mrstegeman** [comment]
Comment 2 addressed by #464 and #465

**Comment by mrstegeman** [comment]
Comment 3 addresses by #461

**Comment by dhylands** [comment]
Since all of the issues are addressed, this would be valid to close.
