### ISSUE TITLE
Need to report a decent error if the user doesn't have permissions for a serial port

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#47]
Both ZigBee and ZWave use serial dongles. By default (under ubuntu) you need to be root or a member of the dialout group in order to open the serial port.

If the user doesn't have sufficient permissions then we should detect this and report a reasonable error. Currently we just report: `ZWave: failed to start driver`

**Comment by rzr** [comment]
Can you suggest any widget that can be used to report error/exceptions ?

**Comment by dhylands** [comment]
Right now the UI doesn't have a place to do that.

**Comment by benfrancis** [comment]
Have filed https://github.com/mozilla-iot/gateway/issues/877

**Comment by mrstegeman** [comment]
Moved:
mozilla-iot/zwave-adapter#33
mozilla-iot/zigbee-adapter#39
mozilla-iot/serial-adapter#7
