### ISSUE TITLE
On/off Color Light UI

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/gateway#485]
As a user, I want to see the detail view of my color-supporting bulb and control its color and on-off state from one page. Note that I'm using the term "HSBBulb" instead of "Colo(u)redDimmableBulb" because I'm avoiding reliving the events of 1776.

Current WIP:
<img width="579" alt="screen shot 2018-01-10 at 4 42 42 pm" src="https://user-images.githubusercontent.com/2776089/34797162-84fc9e58-f625-11e7-8cbd-de88ac70c082.png">

**Comment by hobinjk** [comment]
@benfrancis Can you upload a light icon whenever you get the chance? Also, if desired I can throw the positioning of the detail circles into a d3 force simulation and automatically position them based on that.

I think it might be interesting to have the concept of a ThingDetail which attaches to a thing's view so that we can maximize reuse of components across DimmableBulb, HSBBulb, smart plugs, and whatever device we come up with next.

**Comment by benfrancis** [comment]
Nice!

I've uploaded some icons:
- [bulb.png (uknown state)](https://drive.google.com/file/d/1ZEsslhS8Hfm7NPL6QIydHq5MFKmPcy6c/view?usp=sharing)
- [bulb-on.png (on)](https://drive.google.com/file/d/1gskS1DCbl0NWIaTZNC29EakwhfxEHcvZ/view?usp=sharing)
- [bulb-off.png (off)](https://drive.google.com/file/d/1er9JTcF2lLyCUy4YSMxKeajvTsJu99QT/view?usp=sharing)

However, I think we've reached the point where we need to generate these icons in code, in the case of a dimmable coloured bulb to set the colour and percentage value on the icon. I've uploaded an SVG of the bulb on its own:

- [bulb.svg (just the bulb itself in SVG format)](https://drive.google.com/file/d/18pbxzFb23uLctGnJ3J3qLQbwRXhYKAsU/view?usp=sharing)

I'd been working on a `Property` class to represent `Thing` properties in the detail view and a `BinaryProperty` class to represent the on/off property. I suppose once we have actions represented on the detail view as well we might want to further abstract that to a `ThingDetail` as you suggest.

A d3 force simulation sounds cool, I'd like to see it in action.

Getting this view to work well may require some experimentation, so maybe we should both keep stabbing at it and see what we come up with. I'm not yet sure how much to do as static images vs. HTML vs. SVG.

**Comment by benfrancis** [comment]
> Note that I'm using the term "HSBBulb" instead of "Colo(u)redDimmableBulb" because I'm avoiding reliving the events of 1776.

LOL, I missed this bit. I'm fine with ColoredDimmableBulb BTW. (I just put "Colo**u**red Dimmable Bulb" as a human readable string in the mockups because in my head that's internationali**s**ed and could be in any language vs. the underlying code which to be consistent with HTML and CSS should be the Amercian English spelling!)

HSBBulb makes sense if the Thing has separate hue, saturation and brightness properties, but if there is in fact a single color property (e.g. as a hexidecimal number or string) then ColoredDimmableBulb is probably a better name because otherwise you could argue for an RGBBulb or a CMYK bulb as well!

My current thinking is to have a single color property and allow hexidecimal color codes (and maybe even CSS color names like "red").

What do you think?

**Comment by benfrancis** [comment]
Here's an example Thing Description (the "name" member of a property object is a human readable string which is currently [part of the JSON-TD proposal](https://benfrancis.github.io/wot/proposals/json-td/index.html#property-object) and is useful for generating the UI).

```
{
  "name": "Colored Dimmable Light",
  "type": "coloredDimmableLight",
  "description": "My colored dimmable light",
  "properties": {
    "on": {
      "type": "binary",
      "name": "On/Off",
    },
    "level": {
      "type": "number",
      "name": "Level",
      "unit": "percent",
      "minimum": 0,
      "maximum": 100
    },
    "color": {
      "type": "string",
      "name": "Color",
    }
  }
}
```

The question is how the UI knows that this string represents a color. For now we can add a special case for properties called "color", but you could argue this should be a semantically defined "capability" of a Thing with a formal definition.

**Comment by hobinjk** [comment]
I don't really have a problem with color as a string as long as it's in a consistent format and doesn't require the adapter to support the entirety of CSS color formats.

My main concern is with the "level" property because both the TP Link lights and Philips Hue expose only HSB for color control. This makes them effectively just ColoredLights because there's no independent dimming. We could clamp the color to have value 1 (i.e. the top slice of [this cylinder](https://en.wikipedia.org/wiki/HSL_and_HSV#/media/File:HSV_color_solid_cylinder_alpha_lowgamma.png)) or multiply the color's value by the "level" property. Both of these are slightly hairy but I think the second one is the more logical

**Comment by benfrancis** [comment]
Oh OK, yes we could just fix level to 100, or we could have a ColoredLight type. I'd actually suggest the latter as it will make a difference to the UI (which should just say ON or OFF).

This is another example of the inflexibility of the current type system, arguably further justification for a capabilities based system where "on", "level" and "color" are standard capabilities you can mix and match.

color could have to be a string representing a hexidecimal RGB code like #FF0000.

**Comment by hobinjk** [comment]
I agree with preferring ColoredLight. This definitely highlights how capabilities would be much more flexible.

This is a minor point, but I prefer ColorLight to ColoredLight because to me ColoredLight sounds like a light that has been colored (like a christmas light)

**Comment by benfrancis** [comment]
An argument for colored vs color is that both colored and dimmable and adjectives and bulb is the noun. Arguably then onOffSwitch should have been binarySwitch.

The ZigBee spec uses "On/off Switch", "Color Dimmable Light", "Color Dimmer Switch" and Z-Wave has SWITCH_BINARY and SWITCH_COLOR. "Colored Dimmable Bulb" or "Coloured Dimmable Light" (slightly more generic) sounds right to me, but I don't have strong feelings about it.

Another alternative for the color representation is an array of three integers (RGB), like this https://www.oneiota.org/revisions/2378

Z-Wave colors can have all kinds of components including Warm White, Cold White, Red, Green, Blue, Amber, Cyan, Purple and "Indexed Color" - and can be scaled by brightness specified by a multi level switch. Similarly the ZigBee color control cluster can specify colors by CurrentHue and CurrentSaturation or by CurrentX and CurrentY coordinates or by up to six primary colours, or by colorTemperature.

I suggest just sticking to a hexidecimal color code like CSS for now for the Web Thing Description, I'm sure schemas like this will eventually be debated ad nauseam by some standards body or other!

**Comment by twobraids** [comment]
May I join you in this bikeshed? It's all about a generic name for a light that is both dimmable and color changeable.

If I look up "colored" in the dictionary, I find six adjective definitions, none of which imply "color changeable" and two of the definitions are annotated as "offensive".  In my book, that latter fact is justification to avoid use of the word entirely.  There is no single word adjective in English that I can find that means "color changeable". 

However, there is precedent for use of "color" as a adjective describing a technological device that emits colors: "color TV", it's not "colored TV". It's not a stretch to coin the term "color light". "Color Dimmable Light" sounds awkward. Reversing the adjectives to "Dimmable Color Light" is far less awkward.

The use of the word "bulb" is at the crux of archaic and think it should be avoided.

**Comment by benfrancis** [comment]
I'm not entirely convinced by the argument that the word "colored" would be considered offensive, at least not in this context, but I do like dimmableColorLight. I'm going to change the spec to that, thanks!

**Comment by hobinjk** [comment]
@twobraids I agree wholeheartedly, thank you for articulating it so well.

**Comment by hobinjk** [comment]
Current progress:
<img width="483" alt="screen shot 2018-01-12 at 2 45 23 pm" src="https://user-images.githubusercontent.com/2776089/34892551-aef9f614-f7a7-11e7-8d2e-4d266eec95f5.png">
<img width="537" alt="screen shot 2018-01-12 at 2 48 49 pm" src="https://user-images.githubusercontent.com/2776089/34892563-b7cea7da-f7a7-11e7-8582-aa21c5982310.png">

This is using a d3 forceLayout for aligning the thing detail bubbles but I'm probably going to switch to a simple circular layout even though d3's animations are very spiffy.
