### ISSUE TITLE
Virtual Things Adapter

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#490]
As a user I want to add a virtual Thing to the gateway so that I can experiment with how it works without having to buy a physical device

**Comment by benfrancis** [comment]
Maybe there could be a virtual adapter add-on you can install which lets you play with virtual devices.

**Comment by kgiori** [comment]
Since I would like to use MicroBlocks eventually, to quickly turn a virtual thing into a real thing, a virtual device adapter for [Snap_!_](http://snap.berkeley.edu/) and/or [Snap4Arduino](http://snap4arduino.rocks/) that could be used now would be really cool. We could create an example block for each standard thing type.

**Comment by benfrancis** [comment]
> Since I would like to use MicroBlocks eventually, to quickly turn a virtual thing into a real thing, a virtual device adapter for Snap_!_ and/or Snap4Arduino that could be used now would be really cool. We could create an example block for each standard thing type.

For virtual Snap things, where does the thing simulation happen? Would the thing be simulated by the Snap application on a desktop PC and the gateway communicate with the PC using the same Snap adapter for both virtual and physical devices connected to Snap? Or would Snap expose the Web Thing API to a network directly? Either way I think that's different to a Virtual Thing adapter for the gateway which simulates virtual devices on the gateway itself.

**Comment by hobinjk** [comment]
I needed a virtual multiLevelSwitch for writing it's UI so I hacked together https://github.com/hobinjk/virtual-things-adapter

The main thing it needs is a display/control UI which could be based on the WoT API with a special flag (like `{"virtual": true}`) for overwriting read-only properties

**Comment by benfrancis** [comment]
Let's try to add support for all the Web Thing Types defined so far:

- onOffSwitch
- multiLevelSwitch
- binarySensor
- mulitLevelSensor
- smartPlug
- onOffLight
- dimmableLight
- onOffColorLight
- dimmableColorLight

**Comment by hobinjk** [comment]
Implemented by virtual-things-adapter
