### ISSUE TITLE
Unknown Thing UI

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#511]
As a user I would like to be able to add a thing to the gateway, view and set its properties, and request actions, even if it doesn't conform to one of the standard thing types.

Currently the UI only lets you interact with things which conform to a standard Thing type. As people create custom things users should be able to add those things to the gateway and interact with them via a generic UI.

Mockups in progress...

**Comment by benfrancis** [comment]
OK, this is my first stab at this. This is a very clunky and very literal representation of a thing as HTML.


![uknown_thing](https://user-images.githubusercontent.com/552417/35233248-774a748c-ff95-11e7-9b58-37da34d64b97.png)

- A "string" property is represented as an form input with type="text"
- "number" as a form input with type="number"
- "number" with a unit has the unit displayed in full text underneath
- "number" with a "minimum" and "maximum" attribute set is represented as a form input with type="number" and "min" and "max" set (which usually renders with arrows to step the value up and down)
- "boolean" as a form input with type="checkbox"
- Actions are represented as a button, with the button's label set to the action's name field

One obvious shortcoming is that we don't currently know whether a property is writeable or not. If we did then we could set the "disabled" attribute on a read-only property's form input.

Given time there are lots of thing we could do to improve this aesthetically (!), but as a fall back for unknown thing types, is this quick to implement and better than nothing?

**Comment by mrstegeman** [comment]
At what point are the properties actually set for things like text or numeric inputs? With inputs such as a checkbox or slider, it's easy to know when the user has finished their input. What do you suggest for these other inputs, a timeout of some variety after the last keypress event?

**Comment by benfrancis** [comment]
I was thinking that they'd get set on the "blur" event. The only one that might not work well for is "number" with min and max which has up and down arrows to step up and down.

**Comment by mrstegeman** [comment]
Do you think a checkbox is best for boolean properties or a switch? We use a switch for things like `on` elsewhere, but that makes sense given the context.
