### ISSUE TITLE
Add new device hint

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#514]
Kathy suggests changing the empty message to "No devices yet. Click + to scan for available devices." to give a hint as to what to do next.

**Comment by hobinjk** [comment]
It would also be nice to have a no scanned devices found hint that prompted people to go to the adapter settings to install an adapter (or better yet, provided a link to them)

**Comment by hobinjk** [comment]
s/adapter/add-on/g

**Comment by mrstegeman** [comment]
The seems like a good follow-on to #37
