### ISSUE TITLE
zwave timeouts after gateway idle time

### ISSUE THREAD

**Issue by twobraids** [mozilla-iot/gateway#521]
I've noticed that my zwave devices timeout and become unusable after several hours of the gateway sitting idle.   This happens both with the RPi image 0.3.0-pre2, and when I use the latest pull from github and run on my linux workstation.  I've reproduced it several time on both platforms.  The timeouts can begin as soon as one hour after starting the gateway.

I'm running three Z-Wave switches and one ZigBee switch.  The ZigBee switch does not suffer the timeout.  My Z-Wave controller is the Aoetec Z-Stick.  My ZigBee controller is the Digi XStick.   

[zwave-timeout-2018-01-22.log](https://github.com/mozilla-iot/gateway/files/1652768/zwave-timeout-2018-01-22.log)

**Comment by dhylands** [comment]
It would be good to also get the OZW_Log.txt file (found in the root of the gateway source tree).

**Comment by twobraids** [comment]
Oddly, the OZW_Log.txt timestamps do not match the timestamps in log that I attached.   I'm going to zero out both logs, reproduce the problem and then examine and post the logs

**Comment by twobraids** [comment]
new logs:
[OZW_Log.txt](https://github.com/mozilla-iot/gateway/files/1657148/OZW_Log.txt)
[zwave-timeout-2018-01-23.log](https://github.com/mozilla-iot/gateway/files/1657149/zwave-timeout-2018-01-23.log)

**Comment by dhylands** [comment]
Just to clarify, I presume that you're referring to the `node3: timeout`?
```
2018-01-23 09:58:11.290 PropertyProxy: setProperty property: on for: zwave-fd86a997-3 to value: false
2018-01-23 09:58:11.291 zwave: setProperty property: on for: zwave-fd86a997-3-Switch valueId: 3-37-1-0 value: false
2018-01-23 09:58:12.291 zwave: node3: timeout
2018-01-23 09:58:13.292 zwave: node3: timeout
2018-01-23 09:58:48.443 zigbee: zb-f0d1b800000297d6-onOffSwitch property: on profileId: 0104 endpoint: 1 clusterId: 0006 report value: off (0)
2018-01-23 10:00:11.365 PropertyProxy: setProperty property: on for: zwave-fd86a997-3 to value: false
2018-01-23 10:00:11.367 zwave: AddonManagerProxy: Failed to setProperty on to false for device: zwave-fd86a997-3
2018-01-23 10:00:11.367 zwave: setProperty property on already has a set in progress.
```

If so, then the root cause of the timeout is at the ZWave radio layer (i.e. beyond our control). Our handling of the situation is definitely flawed. I've seen these on my network as well, and it seems to happen more frequently when I have 2 modules right next to each other. I suspect that playing with transmit power (some of the modules have this ability) may help, but we don't currently have a way to do that.

On the gateway side of things, we definitely need to deal with the timeout and take some type of action (like retry the command a few times and perhaps queue it up to try again later). We also need to deal with the `setProperty property on already has a set in progress.` error (so I think that there are a couple of improvements that could be made).

**Comment by twobraids** [comment]
Yes, the node 3 timeout is the #fail one.  Not in this log, but all the devices suffer the same timeout when the timeouts begin.  

Interesting that the OZW_log.txt file shows that I have five known Z-Wave devices, but if you look at the initialization in the other log, I have only three.  This is because two of my devices are dual switches, two devices in one package.  The UI also shows only three devices.  

All of my devices are at about 10 feet of each other in what is effectively an equilateral triangle with the ZWave controller at the center.

**Comment by dhylands** [comment]
Just FYI. The node numbering starts at 1 and the dongle itself is device 1. It looks like you have nodes 3,4 and 5 showing up and node 2 missing. I don't see any messages about node 2, so it looks like the controller (dongle) thinks it doesn't exist either.

If you add a device and later factory reset it, then it will be assigned a new node number, or if you add a device, and then unpair it, it will also get assigned a new node number. So that's a couple ways that I'm aware of to have holes in the node number assignments.

**Comment by twobraids** [comment]
the problem ends up being the particular USB slot into which the Aotec Z-Stick was plugged.  Moving it to a different outlet and everything seems stable.

**Comment by dhylands** [comment]
Very interesting. Can you do an `lsusb --tree` for the good and bad usb ports? I'd like to see if there is a hub or anything internally.

**Comment by twobraids** [comment]
below, you'll find the output of lsusb, lsusb -D /dev/bus/usb/001/043, and lsusb --tree

The Z-stick will only work in a USB2 - it is unrecognized and ignored if plugged into USB3.  To accommodate this restriction, I plugged in the USB2 Hub built into my DELL monitor.  Both the Z-Stick and the DIGI XStick are in that USB2 hub.  The output below is for the configuration that works.  The configuration that results in ZWave timeouts is simply the Z-Stick and XStick in swapped positions.

ᚥ lsusb
Bus 002 Device 004: ID 4971:1014 SimpleTech 
Bus 002 Device 002: ID 045b:0210 Hitachi, Ltd 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 014: ID 05ac:9221 Apple, Inc. 30" Cinema Display
Bus 001 Device 010: ID 05ac:912f Apple, Inc. Hub in 30" Cinema Display
Bus 001 Device 006: ID 05ac:1008 Apple, Inc. Mini DisplayPort to Dual-Link DVI Adapter
Bus 001 Device 011: ID 05f3:02a8 PI Engineering, Inc. 
Bus 001 Device 004: ID 045b:0209 Hitachi, Ltd 
Bus 001 Device 042: ID 0403:6001 Future Technology Devices International, Ltd FT232 USB-Serial (UART) IC
Bus 001 Device 043: ID 0658:0200 Sigma Designs, Inc. 
Bus 001 Device 035: ID 0424:2640 Standard Microsystems Corp. USB 2.0 Hub
Bus 001 Device 034: ID 0424:2514 Standard Microsystems Corp. USB 2.0 Hub
Bus 001 Device 009: ID 29ea:0102  
Bus 001 Device 002: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

ᚥ lsusb -D /dev/bus/usb/001/043
Device: ID 0658:0200 Sigma Designs, Inc. 
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            2 Communications
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0         8
  idVendor           0x0658 Sigma Designs, Inc.
  idProduct          0x0200 
  bcdDevice            0.00
  iManufacturer           0 
  iProduct                0 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           67
    bNumInterfaces          2
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         2 Communications
      bInterfaceSubClass      2 Abstract (modem)
      bInterfaceProtocol      1 AT-commands (v.25ter)
      iInterface              0 
      CDC Header:
        bcdCDC               1.10
      CDC Call Management:
        bmCapabilities       0x00
        bDataInterface          1
      CDC ACM:
        bmCapabilities       0x00
      CDC Union:
        bMasterInterface        0
        bSlaveInterface         1 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval              32
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass        10 CDC Data
      bInterfaceSubClass      0 Unused
      bInterfaceProtocol      0 
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0020  1x 32 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x02  EP 2 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0020  1x 32 bytes
        bInterval               0

ᚥ lsusb --tree
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/6p, 5000M
    |__ Port 3: Dev 2, If 0, Class=Hub, Driver=hub/4p, 5000M
        |__ Port 3: Dev 4, If 0, Class=Mass Storage, Driver=usb-storage, 5000M
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/14p, 480M
    |__ Port 1: Dev 2, If 0, Class=Human Interface Device, Driver=usbhid, 12M
    |__ Port 1: Dev 2, If 1, Class=Human Interface Device, Driver=usbhid, 12M
    |__ Port 1: Dev 2, If 2, Class=Human Interface Device, Driver=usbhid, 12M
    |__ Port 2: Dev 34, If 0, Class=Hub, Driver=hub/3p, 480M
        |__ Port 1: Dev 35, If 0, Class=Hub, Driver=hub/3p, 480M
            |__ Port 2: Dev 43, If 0, Class=Communications, Driver=cdc_acm, 12M
            |__ Port 2: Dev 43, If 1, Class=CDC Data, Driver=cdc_acm, 12M
            |__ Port 3: Dev 42, If 0, Class=Vendor Specific Class, Driver=ftdi_sio, 12M
    |__ Port 3: Dev 4, If 0, Class=Hub, Driver=hub/4p, 480M
        |__ Port 2: Dev 11, If 0, Class=Human Interface Device, Driver=usbhid, 1.5M
        |__ Port 2: Dev 11, If 1, Class=Human Interface Device, Driver=usbhid, 1.5M
    |__ Port 9: Dev 6, If 0, Class=Hub, Driver=hub/1p, 480M
        |__ Port 1: Dev 10, If 0, Class=Hub, Driver=hub/3p, 480M
            |__ Port 2: Dev 14, If 0, Class=Human Interface Device, Driver=usbhid, 12M
    |__ Port 10: Dev 9, If 0, Class=Human Interface Device, Driver=usbhid, 12M
    |__ Port 10: Dev 9, If 1, Class=Human Interface Device, Driver=usbhid, 12M
