### ISSUE TITLE
Aeotec Smart Switch 6 not registering power consumption

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#543]
I have the UK version of the Aeotec Smart Switch 6 and it always shows in the UI as 0W of power consumption (model ZW096-C07).

![screen shot 2018-01-26 at 18 44 28](https://user-images.githubusercontent.com/552417/35455263-27da5458-02c9-11e8-954f-d8662c8b8922.png)

**Comment by mrstegeman** [comment]
Silly question, but I assume you have a lamp or something plugged in that should actually be consuming a non-insignificant amount of power?

**Comment by benfrancis** [comment]
Yep, same lamp plugged into Zigbee smart plug registering 4.3 watts :)

**Comment by mrstegeman** [comment]
@dhylands any idea here? My US version shows the power properly.

**Comment by dhylands** [comment]
Nothing springs to mind. I tested mine and it works fine as well. It would be worth trying another UK switch just in case ben's is broken somehow.

**Comment by benfrancis** [comment]
I just plugged in and paired a brand new smart plug out of the box and I have the same issue, reporting 0W and 0V.

**Comment by mrstegeman** [comment]
That's so strange. Maybe @dhylands or I should pick up one of the UK plugs and figure out what's going on.

**Comment by benfrancis** [comment]
Is there any console output or debugging information I can provide that would help?

**Comment by mrstegeman** [comment]
The gateway log and the `OZW_Log.txt` file would probably be helpful.

**Comment by mrstegeman** [comment]
Moved to the zwave-adapter repo: https://github.com/mozilla-iot/zwave-adapter/issues/5
