### ISSUE TITLE
Thing labels on floorplan view cut off

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#545]
The labels on things in the floorplan view get cut off. I think I tried to fix this before and it's tricky because SVG.

![floorplan_edit](https://user-images.githubusercontent.com/552417/35455406-a61c2aee-02c9-11e8-9ba2-4a586539c9c4.png)

**Comment by hobinjk** [comment]
I can take this on. I plan to do something like https://stackoverflow.com/questions/475804/svg-word-wrap-show-stopper with wrapping the name using a helper function.

@benfrancis Let me know if you'd prefer another approach
