### ISSUE TITLE
Confusing message in Rules Engine

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#548]
@hobinjk The rules engine says "If Zigbee Smart Plug is on then pulse Z-Wave Smart Plug on to true" What does that mean?

**Comment by hobinjk** [comment]
It only switches to the proper turn on/off messaging for onOffSwitches right now. I'll update it to not require the exact thing type.

This won't come up until the Rules engine gains support for setting properties other than `on` but I can also change the default effect from pulse (when the trigger is inactive restore original state) to set (never restore original state)
