### ISSUE TITLE
Replace Mozilla IoT wordmark

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#549]
"IoT" should be using the Zilla Slab font rather than Courier to be consistent with branding guidelines.

![mozilla_iot_wordmark](https://user-images.githubusercontent.com/552417/35455813-38e1fd58-02cb-11e8-871a-92bdf943f88a.png)

**Comment by mrstegeman** [comment]
Can you generate a new PNG?

**Comment by benfrancis** [comment]
(the one attached to this issue is the new one, sorry if that wasn't clear)
