### ISSUE TITLE
Things overlap buttons with a large number of things

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#553]
It would be nice if we handled a large number of things on the things screen a bit better.

Currently if you have a very large number of things they overlap with the menu button, add button and wordmark. It's not too bad because the buttons are on top and the wordmark is underneath so all the functionality still works. it just looks bad.

480x800:
![screen shot 2018-01-26 at 19 20 59](https://user-images.githubusercontent.com/552417/35456783-9a44082c-02ce-11e8-866e-dc59c1a18446.png)

320x480:
![screen shot 2018-01-26 at 19 24 53](https://user-images.githubusercontent.com/552417/35456792-a2884ad4-02ce-11e8-90b5-71246def506f.png)

I'm not sure of the best design to solve this. One option would be having a single row of things scrolling horizontally, but that's a bit wasteful on a large screen. Will play around with some designs.

**Comment by hobinjk** [comment]
I personally think that the best way of solving this problem is to add a proper title bar which would include the hamburger button and the Mozilla IoT branding
