### ISSUE TITLE
Allow deleting Rule in Rule page

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/gateway#564]
As a user, I want to be able to delete the rule I'm working on from the edit page instead of having to return to the rules list.

**Comment by marti1125** [comment]
@hobinjk could I help with this! could you give some advices?

**Comment by hobinjk** [comment]
@marti1125  Sorry for the delay in responding! The general idea is to make sure that the logic in https://github.com/mozilla-iot/gateway/blob/master/static/js/rule-screen.js#L76 works. To do this, you'll just need to delete this line https://github.com/mozilla-iot/gateway/blob/master/static/css/rule.css#L32 to make the trash can icon show up (at least in theory).

When this icon is clicked it should pop up a working rule deletion overlay when clicked. I think there will be some CSS/JS fixes necessary to get everything looking and behaving properly.
