### ISSUE TITLE
Allow disabling OTA updates

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/gateway#565]
As a privacy-conscious user I want to make sure that my gateway never updates by disabling OTA updates.

**Comment by benfrancis** [comment]
I'm not sure we should allow this...

**Comment by hobinjk** [comment]
The OTA update system downloads and executes code from the internet and requires trusting GitHub in addition to trusting us. I think it's reasonable for a user to decide that they want their gateway to never talk to the outside world except when they explicitly allow it.

Admittedly, this can already be accomplished by running `sudo systemctl disable mozilla-iot-gateway.check-for-update.service` so the actual question is whether we want to enable running that command from the UI. At least for now my answer to that is that we don't given that our software is rapidly changing and improving

**Comment by benfrancis** [comment]
Yes that's a fair point. We could also probably improve the security of our update system.

**Comment by flatsiedatsie** [comment]
> As a privacy-conscious user I want to make sure that my gateway never updates by disabling OTA updates.

I'm totally in favour of this :-) Perhaps it could be a dropdown with options such as:

```
- every hour
- every day
- every week
- every month
- never
```

**Comment by madb1lly** [comment]
> 
> 
> As a privacy-conscious user I want to make sure that my gateway never updates by disabling OTA updates.

I also want this but not for privacy reasons - I would say it is for security reasons (since availability is one of the three cornerstones of security). I want to be able to postpone updates during critical times when I need the gateway to not crash or stop working for any other reason.
