### ISSUE TITLE
floor plan uploaded image lost if activate a thing before leaving page

### ISSUE THREAD

**Issue by kgiori** [mozilla-iot/gateway#567]
I upload a floor plan, sprinkle my things on it, then click the check mark to exit edit mode.
Next I click on one of the Things, which opens a new page to turn it on/off, and then I click the back arrow. My floor plan image has disappeared. (But the things I have positioned on it are still in the same place.)

If instead, after I finish edit mode I go to a different page, such as the Things page, to turn something on/off, and then go back to the floor plan page, the image is still there.

**Comment by hobinjk** [comment]
I reproduced this locally. It looks like this is an issue with the baseline caching. In theory the serviceworker will allow this to resolve itself after a couple of refreshes. I think the floorplan's cache-busting might need to be improved as well

**Comment by kgiori** [comment]
It is actually worse than I thought, and may be something to strive to fix for 0.3. Upon more consistent testing I find that when I return to the floor plan page, my image is consistently "missing". Fortunately the icons stay in the same position, so a simple upload of the same image file is all it takes to fix.

**Comment by benfrancis** [comment]
James working on a solution in #568 but I'd prefer to better understand why the cache is misbehaving rather than hack around it.
