### ISSUE TITLE
WebSockets don't work over plain HTTP

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#574]
If I skip the subdomain setup and use the gateway via gateway.local over plain HTTP, I see errors in the console and properties don't get updated over WebSockets.

```
Firefox can't establish a connection to the server at ws://gateway.local/things/virtual-things-6?jwt=eyJhbG{truncated}
thing.js:45:14
```

**Comment by benfrancis** [comment]
@mrstegeman Could this be anything to do with the skip tunnel setup patch?

**Comment by mrstegeman** [comment]
Potentially, but I tested this specifically and had no issues.

**Comment by benfrancis** [comment]
Can no longer reproduce. Suspect a weird caching issue.
