### ISSUE TITLE
Keep thing state while reloading things view

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#576]
Currently when switching back to the things view we re-load all the thing icons from scratch. Over a slow connection (like our tunnelling service!) it's quite painful to watch them all gradually be re-drawn as their property status is received from the server.

If they've already been rendered, could we instead maintain their current state and only update them once we get an API response from the server to say whether something has actually changed? This would have to include a thing being added or removed.

**Comment by hobinjk** [comment]
This is the other direction of #566. I think the best way to accomplish both is to keep a persistent list of Thing objects on the ThingsScreen and update Thing with lifecycle management methods (show, hide, etc.).

**Comment by benfrancis** [comment]
Ah, yes. I think this pretty much a duplicate of #566.
