### ISSUE TITLE
Binary Sensor & Multilevel Sensor missing SVG icons for floorplan

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#578]
In Firefox they're just blank, but you get a default image in Chrome & Safari
<img width="740" alt="screen shot 2018-01-31 at 19 03 36" src="https://user-images.githubusercontent.com/552417/35641961-8ead204a-06b9-11e8-8733-3949ba338ec9.png">

**Comment by mrstegeman** [comment]
@benfrancis you were supposed to get me some SVG icons for these and drop them in place :-)

**Comment by benfrancis** [comment]
LOL, OK.

**Comment by hobinjk** [comment]
Closed by #591
