### ISSUE TITLE
Service Worker error

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#588]
I can't figure out how to reliable re-produce this but I've got this error a few times:

```
Service worker event waitUntil() was passed a promise that rejected with 'TypeError: NetworkError when attempting to fetch resource.'.
service-worker.js:14:2
Failed to load 'https://tola.mozilla-iot.org/floorplan'. A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with 'TypeError: NetworkError when attempting to fetch resource.'.
service-worker.js:13:2
```

**Comment by hobinjk** [comment]
The error in `waitUntil` means that the SW was unable to contact the gateway to refresh its cache. Looking at this in conjunction with #560 I think that your gateway sometimes goes offline. It might be worthwhile to run something like `ping google.com | tee pings.log` to see if it's a network issue.
