### ISSUE TITLE
virtual multilevel sensor defaults to 0% and "active" on gui icon

### ISSUE THREAD

**Issue by kgiori** [mozilla-iot/gateway#592]
When the virtual multilevelSensor is selected, the default value is 0, so it shows 0%. But it also shows the icon as white background, normally signifying an "active" status. I think it should be inactive state at 0%. However, what % value is logical to trigger a change from inactive to active? 1%, 50%, 90%...?

And when some other sensor that offers a value in units is connected, would the icon be shown as active or inactive?

**Comment by benfrancis** [comment]
I actually just changed the background to blue (off) as it felt like a better default than white (on).

There is no on/off state of a multiLevelSensor. A multiLevelSwitch actually has an on/off state which is separate from its level (it can be at 50% but off). So we just have to pick one or the other.

If a sensor defines a unit other than percent, it won't be rendered as a multiLevelSensor, it will be rendered as an "Unknown Thing" and its value reported as a number and a unit.

**Comment by mrstegeman** [comment]
This has really been resolved with the capabilities system, as `MultiLevelSensor` only includes a `LevelProperty` now.
