### ISSUE TITLE
rules of on/off virtual switch only triggers on/off of real smart plug switch if plug state is off

### ISSUE THREAD

**Issue by kgiori** [mozilla-iot/gateway#599]
setup steps (Things page):
1. added real devices (zwave smart plugs) for kitchen and balcony. each smart plug has a dumb light plugged into it.
2. added a virtual on/off light (V kitchen) and a virtual on/off switch (V balcony).
<img width="746" alt="screen shot 2018-02-02 at 1 23 00 pm" src="https://user-images.githubusercontent.com/9487286/35755540-87fb439e-081c-11e8-8338-202b319d0043.png">

3. created three rules:
a. V kitchen on => kitchen on
b. V balcony on => balcony on
(delayed addition of rule c, see results)
c. V kitchen off => kitchen off

UI results:
1. if kitchen and balcony plugs are off, then V kitchen and V balcony control both on and off with only "on" rules (a and b).
<img width="744" alt="screen shot 2018-02-02 at 1 23 32 pm" src="https://user-images.githubusercontent.com/9487286/35755571-a6d6ef66-081c-11e8-89a0-f59b831f539e.png">

2. if kitchen and balcony plugs are on, then V kitchen and V balcony toggles between on and off does nothing to the plug states. (just rules a and b).
3. when real plugs are on, even if add rule c, same problem. toggle of V kitchen on/off does not trigger actual plug to toggle.
4. when "V kitchen" icon changes state when plug is on, the plug icon changes from showing actual power (in W) to showing "0 W" even though the icon is still highlighted as on and the plug is in fact still on. clicking that icon to see break out and coming back to Things overview page causes the actual 2.50 W or whatever the value is to be displayed again. But a "V kitchen" toggle will again zero out the power displayed.
<img width="741" alt="screen shot 2018-02-02 at 1 24 15 pm" src="https://user-images.githubusercontent.com/9487286/35755610-d15f67fe-081c-11e8-8ddc-9fed79df5c55.png">

Other issues seen during these tests:
1. I deleted an unrelated rule for a virtual device that I had removed, and after that only one of my a, b, c rules remained visible on the Rules page. However, rule b (balcony) still worked, even though I did not see that the rule existed on the Rules page.
2. I had added GPIO pin 18, which by default was labeled "led", but I renamed it when I added it. When I tried the right-click approach to remove it, and clicked the big red REMOVE button, the Things page reloaded and the GPIO device was still there, and still worked.

**Comment by benfrancis** [comment]
I can't quite get my head around this. It might help to split each individual issue into separate bugs and write down for each:
- Steps to reproduce
- Expected behaviour
- Actual behaviour

Unless, can you make sense of what's going on here @hobinjk ?

**Comment by hobinjk** [comment]
I think most of the issues raised have been resolved. I was unable to reproduce the issue with the renamed GPIO device.
