### ISSUE TITLE
thing icon locations on floorplan not saved

### ISSUE THREAD

**Issue by kgiori** [mozilla-iot/gateway#605]
After uploading a floorplan image and positioning Thing icons on that plan, if you go to another page and come back or simply to a shift-reload, the Thing positions are lost.

**Comment by kgiori** [comment]
Also, if you open a Thing icon from the floorplan view and then use the back arrow on the GUI to return to the floorplan view, you are met with a blank page.

**Comment by kgiori** [comment]
One more thought, is that the floorplan page should use the new icon format where a single click toggles on/off devices and the little web bubble can be clicked for an expanded view. This will help us migrate eventually to using the floorplan page as the default way to control and monitor things within a home or building.

**Comment by hobinjk** [comment]
https://github.com/mozilla-iot/gateway/commit/6750ea702339a33fd419ca0e554971d4e637f77b should have fixed position saving. The idea to use the things list UI with on-off/expand is interesting. My main concern would be whether the expand button gets too small to be useful at the floorplan's scale

**Comment by mrstegeman** [comment]
@kgiori @hobinjk This is all fixed now, correct?

**Comment by hobinjk** [comment]
Yes, thanks for checking!

**Comment by mrstegeman** [comment]
@ShawnHymel Just saw your YouTube video about our project. Great work, and thank you for doing that!

I've fixed this issue in #2380.

By the way, the issue with being unable to resolve gateway.local in your browser is due to Windows being unfriendly towards mDNS. You typically have to install the Bonjour service from Apple to make that work.

**Comment by ShawnHymel** [comment]
@mrstegeman Glad you liked it! It's really cool to have an IoT gateway that doesn't need Internet access.

Good to know about Bonjour--I've had printers complain about similar things, too.

**Comment by jekkel** [comment]
I just have the same issue with things added by the sonos adapter. It turns out the thingID contains colons (`:`) which are not properly handled.
