### ISSUE TITLE
Internal server error fetching smart plug properties

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#614]
When testing a Zigbee smart plug, the GET requests on each of its properties started returning HTTP 500 responses (internal server error).

`Error fetching smart plug status: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

The payload of the HTTP response to the GET request on the "on" property for example reads: 
`Property "on" not found`

**Comment by benfrancis** [comment]
The problem persisted after a hard reload of the web interface.

After a reboot the problem went away with the Zigbee smart plug, but the same problem presented on a Z-Wave smart plug instead. Problem went away after another reload.

**Comment by mrstegeman** [comment]
See #764 and #666
