### ISSUE TITLE
Pairing seems to be initiated with no timeout

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#615]
When I add a console.log into the AddonManaget's addNewThing method, the pairingTimeout is set to 'undefined' which causes pairing to be immediately cancelled due to timeout.

**Comment by hobinjk** [comment]
This sounds like you may need to clear your browser cache to deal with the recently added timeout parameter of the pair action. @mrstegeman might know more

**Comment by dhylands** [comment]
Doing a hard reload seems to have fixed the problem.
