### ISSUE TITLE
Wifi setup looking weird

### ISSUE THREAD

**Issue by arcturus** [mozilla-iot/gateway#618]
Just installed Things 0.3 on a rpi2 with a standard wifi module (sorry for not being more specific), I got no problem on getting the access point, but when performing the wifi setup I get a screen like the one attached:

<img width="1392" alt="screen shot 2018-02-06 at 21 32 55" src="https://user-images.githubusercontent.com/60801/35885763-d49d388e-0b86-11e8-808f-9cff263ccec7.png">

**Comment by benfrancis** [comment]
Egad! Thanks for reporting.

Does it still let you connect to a WiFi network, or do you have to skip it?

**Comment by arcturus** [comment]
I would say 'yes'.

Unfortunately the list is so big that doesn't show my network (or is hidden between that noise), so I had to click in one of the options and modify the form hidden input in the next screen, adding the name of my wifi network.

With that trick and with the correct password I managed to get the wifi configuration process done.

**Comment by Frank0427** [comment]
Better sort the list by signal strength, so user can at least move closer to the wifi source. lol.

**Comment by washeck** [comment]
@benfrancis I encountered the same and it makes the wizard unusable. I saw a similar screen and selected and option like one of those on the bottom of the screenshot with label ESSID:"mynetwork"

I checked the gateway did not connect to my AP, mounted the SD card to my computer and I see it created supplicant.conf with this content:

```
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=GB

network={
	ssid="ESSID:"mynetwork""
	psk="mypassword"
}
```

Obviously, the ssid should be just "mynetwork" without the ESSID and the double quotes.

I can see another problem in the file, my country is not GB but CZ (I guess this might cause some issues with different wifi channels being accessible in different countries).

**Comment by dhylands** [comment]
It looks like raspi-config offers the option to change the Wifi country, and it uses this code to determine the list of countries:
cat /usr/share/zoneinfo/iso3166.tab | tail -n +26 | tr '\t' '/'
to get a list of lines containing the 2 character country code followed by a human readable version of the country.

**Comment by mrstegeman** [comment]
Closing in favor of https://github.com/mozilla-iot/gateway-wifi-setup/issues/55 and https://github.com/mozilla-iot/gateway-wifi-setup/issues/57
