### ISSUE TITLE
webofthings related?

### ISSUE THREAD

**Issue by laoshaw** [mozilla-iot/gateway#622]
a  general question, does this project have anything to do with: https://webofthings.org/  which started calling web-of-things since 2007?

**Comment by benfrancis** [comment]
Yes, actually we are working very closely with the founders of that website via the W3C Web of Things Interest Group on defining standards for the Web of Things. This is an ongoing evolution of the Web of Things, including their Web Thing Model member submission from 2015 http://model.webofthings.io/
