### ISSUE TITLE
IoT email address confirmation link isn't available over HTTPS (and yields error page if you try)

### ISSUE THREAD

**Issue by dholbert** [mozilla-iot/gateway#625]
I just set up a Mozilla IoT Things Gateway on a Raspberry Pi, and I got an email asking me to confirm the email address that I used to set up the gateway.

That email had a link that looked like this:
http://api.mozilla-iot.org/verifyemail?s=some-long-uuid-goes-here
Notice ^^^ that this is insecure HTTP (not a huge deal, but it triggers a broken lock icon in URLbar and is generally worth avoiding now that we can have free https).

After I visited the confirmation link, I tried visiting the same link again, but with "https" substituted into the URL -- but that gave me a browser HTTPS misconfiguration error page (which you can see if you just go directly to https://api.mozilla-iot.org/ ).  The page looks like this:
> Secure Connection Failed
> An error occurred during a connection to api.mozilla-iot.org.
> Peer received a valid certificate, but access was denied.
> Error code: SSL_ERROR_ACCESS_DENIED_ALERT

I suspect this means the server has misconfigured HTTPS configuration.  Specifically, this URL returns an actual page with some "error 400" JSON:
 http://api.mozilla-iot.org/verifyemail
...but this triggers the above-quoted *browser-level* HTTPS error page:
 https://api.mozilla-iot.org/verifyemail

EXPECTED RESULTS:
 1) api.mozilla-iot.org should be usable over https, at least for the purpose of these links (maybe this is already true, the first time you visit a URL with a valid not-yet-confirmed UUID token? I'm not sure since I visited the URL using the provided http spelling initially, and that made my UUID invalid for further visits)
 2) The "confirm email address" email should provide a secure https URL, rather than an insecure http URL, because we're encouraging others to adopt https where possible, so we should do so too.

**Comment by dholbert** [comment]
In Chrome, https://api.mozilla-iot.org/verifyemail yields an emptier/more-site-blaming error page:
> This site can’t provide a secure connection
> api.mozilla-iot.org sent an invalid response.
> ERR_SSL_PROTOCOL_ERROR

**Comment by mrstegeman** [comment]
The verify links are now redirected to the proper HTTPS site.

**Comment by dholbert** [comment]
Hi @mrstegeman - thanks! I'm a bit confused, though.  I'm still seeing the same browser SSL protocol error pages when I directly visit https://api.mozilla-iot.org/verifyemail (granted, with no actual UUID in the URL because I'm not currently activating a device).

Maybe it's fixed if you have a UUID, though? But even if that's the case, it seems like we should at least successfully complete the SSL connection for the lacking-UUID-scenario... (and then show a "bad request" error of some sort, rather than triggering a browser SSL protocol error)

**Comment by mrstegeman** [comment]
@dholbert The API server runs on port 8443 for various reasons.

**Comment by dholbert** [comment]
Ah, thank you -- that clears up my confusion.
