### ISSUE TITLE
Smart plug displays 0W when updated over WS

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/gateway#633]
Reproduced from #599 

My steps to reproduce which are a bit more involved than they absolutely have to be:

1. Edit virtual-things-adapter so that the virtual smart plug has a nonzero watt property
2. Set up a rule connecting the "on" property of the virtual on/off switch to the "on" property of the virtual smart plug
3. Make sure both the virtual on/off switch and the virtual smart plug are turned off
4. Turn on the virtual on/off switch
5. The virtual smart plug should now be in the on state but displaying "0W" instead of its actual reading

**Comment by dhylands** [comment]
For the real plugs, this code: https://github.com/mozilla-iot/zwave-adapter/blob/e1e310a94cc49f27e34320d40bde7eed454c4e6d/zwave-classifier.js#L202-L224 sets a configuration entry on the plug which enables meter reporting. The device then sends meter reports if the wattage changes by more than 1 watt. On my plug this causes wattage changes (like plugging/unplugging the device from the plug) to be reported even if the switch doesn't change state.

**Comment by dhylands** [comment]
I realize my comment might not be relevant to the bug.
