### ISSUE TITLE
Xiaomi Mi Flora adapter

### ISSUE THREAD

**Issue by sharukins** [mozilla-iot/gateway#636]
[These](https://www.aliexpress.com/wholesale?initiative_id=SC_20180208001013&SearchText=mi+flora&g=y&misspellText=MiFlora) are small sensors that you put into the soil of your plants which then measure temperature, soil moisture, soil conductivity and light intensity. They can be bought directly from china and cost ~13US $ each.
There is a python [library](https://github.com/open-homeautomation/miflora) that handles interaction with them (which is used by home-assistant), but I think openhab supports them as well. The progress on reverse engineering how to read the sensors has been [documented](https://www.open-homeautomation.com/2016/08/23/reverse-engineering-the-mi-plant-sensor/) as well using gatttool.
I don't know if BLE support is already present as the wiki shows no supported devices but I'll leave this here for possible implementation in the future (:

edit: I just found an JS [implementation](https://github.com/demirhanaydin/node-mi-flora)

**Comment by benfrancis** [comment]
@sharukins Perhaps you could work on an adapter? We'd love to support some Bluetooth devices as the Raspberry Pi 3 has Bluetooth built in, but there not yet adopted smart home profiles in Bluetooth in the same way there are for Zigbee and Z-Wave.

**Comment by sharukins** [comment]
Sorry, but I'm not a dev. I can only do a little bit of python ^^

**Comment by rzr** [comment]
Do you own some of those devices ?

Which BLE profile is used ?

Also check WIP on BT:
https://github.com/mozilla-iot/gateway/pull/165

My side, I can try to handle moisture sensors running on gateway (i2c)

**Comment by flatsiedatsie** [comment]
Awesome! This would have been the third adapter I would have wanted to work on, and now it's already here!
