### ISSUE TITLE
Philips Hue doesn't report status change

### ISSUE THREAD

**Issue by mbos** [mozilla-iot/gateway#638]
I connected my hue bridge and can control the lights perfectly. When the hue lights are manipulated through the philips hue remote control the changes are not shown in the gateway. 
ie Press the lights on in the gateway, off with the dimmer. The lights in the gateway are still shown on, even after a refresh. 
The same happens with dimmer adjustments.

**Comment by mrstegeman** [comment]
The Hue adapter does not currently poll devices for their status, as far as I can tell. @hobinjk would this be easy to add?

**Comment by mrstegeman** [comment]
Closing this issue in favor of the Hue adapter issue.

**Comment by dhylands** [comment]
Providing a link to the issue in the adapter repo: https://github.com/mozilla-iot/philips-hue-adapter/issues/6
