### ISSUE TITLE
Web Thing REST API documentation

### ISSUE THREAD

**Issue by DurandA** [mozilla-iot/gateway#640]
As a web app developer I want to be able to access my Web Things from the [REST API](https://iot.mozilla.org/wot/#web-thing-rest-api).

I tried ```curl --insecure -H "Accept: application/json" https://127.0.0.1:4443/things/virtual-things-0``` which return *401 Unauthorized*. Since the Web UI for authorization is empty (*/settings/authorizations*), I suppose that both authorizations and Web Thing API are not ready for prime time yet.

Is this feature already available in the the gateway?

**Comment by hobinjk** [comment]
When using curl you also need to specify the Authorization header. The current easiest way of doing this is to open the network tools on the Gateway, right click on an API request, and click "Copy as cURL". The command on your clipboard will include the required `-H 'Authorization: Bearer large-base64-jwt'` that you can use in requests to the API to prove to the gateway that you're a known user.

**Comment by benfrancis** [comment]
Note that there is also a simple OAuth implementation for third party applications to request access to the gateway (which is what that Authorizations section in the UI is for). @hobinjk Perhaps you could document how that is intended to be used on the wiki, with caveats for things that aren't yet supported?
