### ISSUE TITLE
Investigate recompiling openzwave after migration from 0.3.0 image to Node LTS

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/gateway#641]
Also have a post-update script that can perform things like this
```
nvm install --lts
nvm use --list
nvm alias default node
```

**Comment by hobinjk** [comment]
It will also require rebuilding OpenZWave which will be interesting

**Comment by dhylands** [comment]
Yeah - I'm not sure we have all of the resources installed in the distributed image to rebuild (like some of the -dev modules). We shouldn't need to rebuild OpenZWave itself (i.e. the C++ library), just the node-openzwave-shared module

**Comment by mrstegeman** [comment]
Related to #632

**Comment by hobinjk** [comment]
Fixed by #814

**Comment by hobinjk** [comment]
Although the open-zwave thing is still a concern

**Comment by dhylands** [comment]
The addon-builder can now build node-openzwave-shared as one of the dependencies of the zwave-adapter.

**Comment by hobinjk** [comment]
Fixed since it's a dependency now
