### ISSUE TITLE
View Logs

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#645]
We should provide an easy way for the end-user to download log files from the gateway. The run-app.log and OZW_Log.txt files are 2 that immediately come to mind.

**Comment by benfrancis** [comment]
As a user I would like to be able to share log files from my gateway so that someone can help debug my problems.

**Comment by mrstegeman** [comment]
Do we want this accessible from the UI or just a URL that we can tell people to browse to?

**Comment by benfrancis** [comment]
I don't really think this should be exposed through the UI. It's more of a developer feature than an end user feature. I suppose it could be part of a developer mode you enable like on Android. Having a special URL like "/logs" might be OK but we should be careful about security.

**Comment by Swaagie** [comment]
This would be a nice to have feature indeed. In addition, having a route on the Web Thing API could be nice to allow external analyzers to fetch and parse logs?

**Comment by mrstegeman** [comment]
This is possible now, we just need to decide if we want to put this in the UI or not, and where. `/logs/*` is authenticated, so the JWT must be included.

**Comment by benfrancis** [comment]
This should go in a new developer settings section, coming soon...

**Comment by benfrancis** [comment]
UX specification: https://docs.google.com/presentation/d/1rMeg6hep8JQflqwbiNIbhSoK9StCeVZ2npphmQHKda4/edit#slide=id.g3c095fbf0e_6_1

UI mockup (just a button in developer settings):
![developer-settings](https://user-images.githubusercontent.com/552417/40841583-e492de12-65a2-11e8-8ab3-7bb2fd6a3b24.png)
