### ISSUE TITLE
error run gateway in pc

### ISSUE THREAD

**Issue by hydfxy2018** [mozilla-iot/gateway#653]
WARNING in ./src/addon-manager.js
33:9-16 Critical dependency: require function is used in a way in which dependen
cies cannot be statically extracted

ERROR in ./src/addons/addon-constants.js
Module parse failed: D:\selfgateway\gateway\src\addons\addon-constants.js Unexpe
cted token (1:0)
You may need an appropriate loader to handle this file type.
| ../constants.js
 @ ./src/addons/plugin/plugin-server.js 16:18-47
 @ ./src/addon-manager.js
 @ ./src/app.js
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! things-gateway@0.3.0 start: `webpack && node build/gateway.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the things-gateway@0.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
![1](https://user-images.githubusercontent.com/36319852/36058272-9b56c41e-0e56-11e8-9710-c9def0f9fb67.png)
[2018-02-10T01_36_51_018Z-debug.log](https://github.com/mozilla-iot/gateway/files/1712976/2018-02-10T01_36_51_018Z-debug.log)

**Comment by dhylands** [comment]
Hmm. We've never tried running under windows.

Under linux/OSX the gateway/src/addons/addon-constants.js file is a symbolic link to gateway/src/constants.js

You might need to remove the addon-constants.js file and manually make a copy of constants.js instead.

**Comment by hobinjk** [comment]
There's an option you can enable when installing Git on windows that enables support for symbolic links. When I ran the Gateway on windows to test it out (which was a couple of months ago) this option worked well.

This stackoverflow page goes into detail about alternative solutions: https://stackoverflow.com/questions/5917249/git-symlinks-in-windows

**Comment by sogaani** [comment]
I made some fixes locally to make gateway work with windows.

- Since symlink requires administrator authority, it changed to copyfile.
- Add pagekite.py for windows.
- Since cmd.exe does not allow ```./``` as prefix of file position, I changed prefix of pagekite to. ```\.```.

**Comment by mrstegeman** [comment]
Windows should be fully supported now, I believe.
