### ISSUE TITLE
[Device] Broadlink RM Pro

### ISSUE THREAD

**Issue by claell** [mozilla-iot/gateway#656]
Link: http://www.ibroadlink.com/rm/

**Comment by mrstegeman** [comment]
Broadlink support is provided by this add-on: https://github.com/sogaani/broadlink-adapter

**Comment by claell** [comment]
Nice, thanks for the hint!

**Comment by mrstegeman** [comment]
@joelafonso sorry to hear you’re having troubles! The Broaldink add-on is maintained by an outside contributor. Could you file a new issue to the add-on’s repository?

https://github.com/sogaani/broadlink-adapter

**Comment by mrstegeman** [comment]
Discussion should take place here: https://github.com/sogaani/broadlink-adapter/issues/8
