### ISSUE TITLE
WebSockets keepalive

### ISSUE THREAD

**Issue by daenney** [mozilla-iot/gateway#660]
When gateway is proxied (lets say behind an nginx for example) eventually the websocket connection will timeout and nginx will close it. Though I can up the timeout to be days or weeks (this feels really hacky though), eventually one of the websocket connections for a device can timeout. Once that happens it will no longer update in the UI. I currently have the timeout set to a day, but it's entirely possible that my window sensors don't update over a period of 24hrs, since I'm not really in the habit of opening/closing them much.

It would be great if the gateway could send some kind of heart beat, at a configurable interval, to ensure these connections don't die. This keepalive message could also be used to detect if a remote has received all updates, and if not push the current state.

**Comment by daenney** [comment]
This would also laregly be mitigated if a single websocket connection was opened for the UI, instead of a websocket connection per device in the UI. Since lights are on there, paired with a timeout of about a day, the timeouts would always reset if everything was multiplexed over a single connection.

Which begs the question, why is there one websocket connection per device in the UI?

**Comment by apiel** [comment]
Actually to respond at your first comment, there is an existing method in the WS protocol to solve this issue, [it's a simple ping/pong by using some special opcode message](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers#Pings_and_Pongs_The_Heartbeat_of_WebSockets) between client and server. You are also right the client should take of this. I would guess that's the library they use to make websocket connexion should take care of this automatically, so if it now the case there is something weird :p

**Comment by hobinjk** [comment]
Based on the documentation it looks like the websocket server library we're using doesn't default to sending pings intermittently. This is something I can add pretty easily. Thanks for reporting the issue!

**Comment by daenney** [comment]
Thanks for fixing this so quickly!
