### ISSUE TITLE
Feature Request: Firmware Architecture

### ISSUE THREAD

**Issue by steamraven** [mozilla-iot/gateway#664]
Since the two main goals for the Mozilla Web of Things and the gateway is interoperability and security, let me suggest creating a framework for update firmware.  The IOT space is going rapidly and many devices need regular firmware upgrades to fix large security holes and also to  enable new features that may increase interoperability.  As of now, you may need a vendor specific hub to initiate firmware updates.

The idea would be to develop  a framework for vendors to add plugins to allow firmware updates for connected devices.   Even if vendors did not officially provide plugins, the community may be able to provide un-official plugins based on reverse engineering.

This would go a long way to ensuring devices are kept secure.

**Comment by kgiori** [comment]
I agree that keeping the firmware of the "things" connected to the gateway up to date and secure is going to be necessary for commercial deployments. For our current experimentation phase, I think that incorporating the [PlatformIO](platformio.org) core into the Things Gateway might be an option. It supports so many different boards and sw frameworks. Perhaps we can also take advantage of the "platformio remote agent" capability that let's a user edit firmware source wherever they are, then deploy the newly compiled image from a remote gateway (i.e., the Things Gateway) to the little connected IoT "thing" that needs the update.

**Comment by mrstegeman** [comment]
Duplicates #791
