### ISSUE TITLE
Unable to remove non-responsive device

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#665]
While writing a new adapter, I got into a situation where a device was added into the database but I can't remove it. On the UI it shows with ... as the value. I can right click and select remove, but it doesn't actually remove the device.

**Comment by benfrancis** [comment]
Any errors in the browser console?

**Comment by dhylands** [comment]
I see:
```
Error removing thing Not Found                         context-menu.js:73:9
handleRemove/<               https://localhost:4443/js/context-menu.js:73:9
```

**Comment by gerritanne** [comment]
I have the same problem, where a device is added to the UI as an unknown device type (Philips Hue Straina bathroom light). The device is not responsive, and I cannot delete it either...
