### ISSUE TITLE
Philips Hue Struana bathroom light detected as unknown device type

### ISSUE THREAD

**Issue by gerritanne** [mozilla-iot/gateway#673]
I’ve setup the gateway with the RPi 3 and have factory reset my Philips Hue Bathroom light with the Hue Dimmer switch. The gateway then found the Hue but adds it as an unknown device type. So I know see it in the gateway but I cannot do anything (tapping the device in the UI doesn’t do anything).

Any thought why this would not work?

**Comment by mrstegeman** [comment]
Moved: https://github.com/mozilla-iot/zigbee-adapter/issues/8
