### ISSUE TITLE
SensorTag adapter

### ISSUE THREAD

**Issue by rei-vilo** [mozilla-iot/gateway#678]
The [SensorTag from Texas Instruments](http://www.ti.com/ww/en/wireless_connectivity/sensortag/) is very popular as it features many sensors and runs on BLE. 

- Infrared and Ambient Temperature Sensor
- Ambient Light Sensor
- Humidity Sensor
- Barometric Pressure Sensor
- 9-axis Motion Tracking Device – Accelerometer, Gyroscope and Compass
- Magnet Sensor

There are many Python and Node.JS scripts to get the values and even an interface for Node-RED. They rely on the standard Bluez 5.2.x for communication.

Here some pointers:
- [Raspberry pi 3 and sensortag more fun in command line](https://e2e.ti.com/support/wireless_connectivity/bluetooth_low_energy/f/538/t/499589)
- [Working with SensorTags](https://github.com/greeniot/SensorTag-Sample)
- [ble-sensor-pi](https://github.com/msaunby/ble-sensor-pi)
- [Python interface to Bluetooth LE on Linux](https://github.com/IanHarvey/bluepy)
- [TI Sensor Tag and Raspberry Pi](https://developer.ibm.com/recipes/tutorials/ti-sensor-tag-and-raspberry-pi/)
- [Node.js lib for the TI SensorTag](https://github.com/sandeepmistry/node-sensortag)
- [node-red-node-sensortag](https://www.npmjs.com/package/node-red-node-sensortag)

**Comment by kgiori** [comment]
Other platforms with BLE and lots of sensors/actuators onboard
Nordic Thingy:52 
https://www.mouser.com/new/nordicsemiconductor/nordic-thingy-52/
BBC micro:bit
http://microbit.org/

**Comment by tim-hellhake** [comment]
@kgiori RuuviTag is on the way: https://github.com/mozilla-iot/addon-list/pull/276
