### ISSUE TITLE
IKEA Tradfri bulb not found by gateway

### ISSUE THREAD

**Issue by gerritanne** [mozilla-iot/gateway#679]
I executed the following steps (please note I do not have a hub):

1. Switch on the Tradfri
2. Execute a factory reset through the use of a Hue dimmer switch
3. Then hit the ‘+’ in the gateway UI to try and pair the Ikea bulb with the gateway. The gateway keeps scanning, but does not find the bulb). 

This is the way it should work right? Am I doing something wrong?

**Comment by dhylands** [comment]
Do you have a Digi XStick ZB plugged into the gateway? The gateway requires this in order to talk to ZigBee devices.

**Comment by gerritanne** [comment]
Hi dhylands,

Thx for your response! Yes, I have the Digi XStick ZB plugged in(the correct one, ordered from mouser). I am really excited about your project, but it suprises me why the gateway doesnt recognise the tradfri.

When i put the tradfri into factory reset (by using the Hue dimmer switch, pressing both on /off for 10 seconds), the tradfri is ‘dimming’ up and down a bit for about 10 seconds and then juist remains on. I assume the tradfri is in pairing mode during those 10 seconds correct? When i hit the ‘+’ on the gateway during that time, the gateway doesn’t find the tradfri. 

Do hou have any advice on where to start looking for whats causing this, since I would really like to test more devices...

Thx!

**Comment by gerritanne** [comment]
After reinstalling the gateway and again resetting the tradfri to factory settings, the gateway now finds 'a zigbee' thing, but it's an unknown device type, with a '?' as icon. When I try to connect my Philips Hue Struana bathroom light, I have the exact same thing, the gateway also detects it, but as an unknown device type. When I then save the device in the gateway, I cannot do anything with it. Tapping the thing doesn't do anything, no option to switch on / off neither the option to set the level...

**Comment by mrstegeman** [comment]
Moved: https://github.com/mozilla-iot/zigbee-adapter/issues/9

**Comment by dhylands** [comment]
Make sure that you remove and reinstall the zogbee adapter. The zigbee adapter that was released with the gateway didn't have support for the Zigbee bulbs. It was updated a few days after the release.

**Comment by TonyCanning** [comment]
I literally just set all up fresh again and am now not able to see IKEA Tradfri bulb when I go to add.

I've been able to add other devices  but no good for Tradfri - I've done the factory reset for the bulb but no go.....

**Comment by gerritanne** [comment]
Did you try and reinstall the Zigbee adapter?
