### ISSUE TITLE
Web Thing API - Get Thing

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#68]
As a Web Thing API consumer I want to get a Thing Description for a Thing via its Thing URL.

Original report:

If you do a get on /things, each thing has an href which looks like /things/:thingId, but if you do a GET on that there is no handler installed.

**Comment by benfrancis** [comment]
Yep, we haven't had any need for this feature yet which is why it isn't implemented.

**Comment by benfrancis** [comment]
Transforming into a user story for this feature.

**Comment by benfrancis** [comment]
Implemented by https://github.com/mozilla-iot/gateway/pull/229
