### ISSUE TITLE
Gateway not detecting SSL files

### ISSUE THREAD

**Issue by BlackHoleFox** [mozilla-iot/gateway#680]
I have tried both a `ssl` directory inside the `gateway` folder, and my home directory. Both attempts led to the server still starting in plain HTTP, even though inside the `ssl` folder there is a valid `certificate.pem` and `privatekey.pem`. Is there a setting somewhere or did I just manage to do it wrong? The certificate was generated using Certbot and the files have had new permissions and renaming.

**Comment by mrstegeman** [comment]
Are you running with the 0.3.0 release, or with the current master branch? If running with 0.3.0, the certificates need to be directly inside the `gateway` directory.

**Comment by hobinjk** [comment]
You might have to run
```shell
sqlite3 db.sqlite3
>delete from settings where key="notunnel";
```
but that's just what I did the last time I saw this issue so there should have been a more user-friendly way to do it.

**Comment by mrstegeman** [comment]
Wouldn't he want the notunnel setting to stay? It seems like he's trying to skip the tunnel and just do SSL himself.

**Comment by hobinjk** [comment]
The behavior I noticed on my end which I worked around by deleting the notunnel setting was that if I selected "Skip" on the registration screen then later tried to run ./tools/make-self-signed-certificates.sh the gateway would start up in HTTP mode despite the certificate's existing. The Gateway started up in HTTPS mode after I deleted the notunnel setting.

**Comment by BlackHoleFox** [comment]
Currently away so I am unable to check the exact version I have installed but I installed the master branch at the time of making the post. For clarification, I did skip the Mozilla tunnel option as I do want to use or own subdomain.

**Comment by BlackHoleFox** [comment]
@hobinjk Your solution to delete the key out of the database worked, and it is now using the SSL certificate as it should be. Thank you for the help!
