### ISSUE TITLE
Pin Naming for GPIO Adapter

### ISSUE THREAD

**Issue by rei-vilo** [mozilla-iot/gateway#681]
The example at [Configuring GPIO for use with the gpio adapter](https://github.com/mozilla-iot/wiki/wiki/Configuring-GPIO-for-use-with-the-gpio-adapter) uses `pin 18`.

```
{
  "pins": {
    "18": {
      "direction": "out",
      "name": "led",
      "value": 0
    }
  }
}
``` 

However, there are two ways of numbering the pins:

+ GPIO numbering
![gpio-numbers-pi2](https://user-images.githubusercontent.com/951776/36298977-1eafd6cc-12fb-11e8-8f9e-30f235eead18.png)

+ Physical numbering
![physical-pin-numbers](https://user-images.githubusercontent.com/951776/36298980-2190dbb6-12fb-11e8-9905-6907ed99de3c.png)

See [Appendix 1. A note on pin numbering](https://www.raspberrypi.org/documentation/usage/gpio-plus-and-raspi2/README.md).

Wouldn't `GPIOs` instead on `Pins` be more adequate?

```
{
  "gpios": {
    "18": {
      "direction": "out",
      "name": "led",
      "value": 0
    }
  }
}
```

**Comment by mrstegeman** [comment]
Moved: https://github.com/mozilla-iot/gpio-adapter/issues/12
