### ISSUE TITLE
Can't connect remotely despite account created during installation

### ISSUE THREAD

**Issue by rei-vilo** [mozilla-iot/gateway#689]
When I try to connect to `<myname>.mozilla-iot.org`, connection fails.

The menu **Settings > Domain** shows `Not set`. However, the credentials were provided during installation. How to fix this?

> Failure of the secure connection
> 
> An error occurred during a connection to <myname>.mozilla-iot.org. The pair received a valid certificate but access has been denied. Error code: SSL_ERROR_ACCESS_DENIED_ALERT the page you are trying to view cannot be displayed because the authenticity of the received data cannot be verified.
>     Please contact the web site owners to inform them of this problem.

**Comment by rei-vilo** [comment]
Obviously, there is the classic port forwarding procedure. 

However, there are other solutions that do not require port forwarding 

See for example [ACCESS YOUR RASPBERRY PI OVER THE INTERNET](https://www.raspberrypi.org/documentation/remote-access/access-over-Internet/README.md)

> Rather than using port forwarding, there are a number of alternative online services available. These provide varying levels of functionality - see their websites for more details.
> 
> - [remot3.it](https://www.remot3.it/), by Weaved Inc
> - [Dataplicity](https://dataplicity.com/)
> - [Yaler.net](https://yaler.net/)
> - [Losant](https://losant.com/)
> - [Remote IoT](https://remote-iot.com/)

**Comment by benfrancis** [comment]
This error message sometimes occurs when the gateway has crashed and isn't responding.

If that's the case then it also won't be accessible via gateway.local or its local IP address and may need a reboot.

If it still doesn't work after a reboot you may need to go through the setup process again and look out for any other errors.

**Comment by rei-vilo** [comment]
Yes, that is what I did. The trick was to connect first to the gateway locally using its IP address and not `gateway.local`, as discussed in #688 and #691.

**Comment by mrstegeman** [comment]
Closing. Please re-open if you see this again.
