### ISSUE TITLE
 Feature Request: Add Node-RED Connection?

### ISSUE THREAD

**Issue by rei-vilo** [mozilla-iot/gateway#690]
This is a feature request very similar to #637 **Feature Request: Add MQTT server**.

> Node-RED is a programming tool for wiring together hardware devices, APIs and online services in new and interesting ways.
> 
> It provides a browser-based editor that makes it easy to wire together flows using the wide range of nodes in the palette that can be deployed to its runtime in a single-click.
> 

Node-RED is emerging as a widely used standard. It supports MQTT natively, provides a nice GUI for development and dashboard, is expandable thanks to a rich library of nodes, excels in managing heterogenous hardware and software configurations.

References:
+ https://nodered.org/

**Comment by benfrancis** [comment]
As I understand it Node-RED isn't a "standard", it's a software application like the Things Gateway which has its own web interface. How do you imagine this integration would work?

What are you hoping to be able to achieve with this integration?

**Comment by rei-vilo** [comment]
Sorry for the word "standard": I just want to mean Node-RED is emerging as a widely used solution that could make it a _de facto_ standard.

My guess is, the Mozilla Foundation hasn't unlimited resources. So why re-invent a GUI and tools that are already available? Node-RED and MQTT are just examples. AFAIK, Node-RED doesn't feature [Web Thing Description](https://iot.mozilla.org/wot/). 

As this topic is not purely technical, I've open a thread at [Discussion: Scope of the Project and Re-Use of Existing Tools](https://discourse.mozilla.org/t/discussion-scope-of-the-project-and-re-use-of-existing-tools/25783).

I'm just trying to understand the philosophy of this project. Thank you for your answers!

**Comment by hobbyquaker** [comment]
I think the other way round would be a more simplistic approach: Create some Node-RED Nodes to communicate with a Things Gateway and provide some convenient nodes to fetch device descriptions, receive updates and send commands...

**Comment by rei-vilo** [comment]
@mrstegeman The ticket has been changed to **closed** then **done**.

+ Could you please explain how to use this feature? 
+ In which release is it going to be available? 
+ Where can I find the related documentation?

Thank you!

_Actually, very same questions as for #694_

**Comment by mrstegeman** [comment]
This seems like it should be one of two things:
1. An add-on
2. A plugin for Node-RED

This is not functionality that is core to the gateway, so it should live elsewhere.

**Comment by rei-vilo** [comment]
Fair. 

By `eslewhere`, which repository do you recommend?

**Comment by mrstegeman** [comment]
Somewhere that's not the gateway. It would either be a new add-on or something for Node-RED.

**Comment by Slyke** [comment]
Just stumbled across this thread. Is there an adapter in development? Seems like it'll need to be done on the NodeRed side. I was hoping to switch from HASSIO to WebThings and use NodeRed, but seems it's not ready yet.

**Comment by mrstegeman** [comment]
As far as I can tell (from a quick web search), no one has done anything toward this. It would definitely be a great addition, though.

**Comment by OpenSourceDevelop** [comment]
found this, but it is not ready https://github.com/iot-schema-collab/iotschema-node-red

**Comment by tim-hellhake** [comment]
Fyi WebThingsIO/addon-list#1376
