### ISSUE TITLE
Discover Web Things via Bluetooth Eddystone

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#695]
As a user I want to search for nearby web things which are broadcasting their URL so I can add them to my gateway

Let's experiment with discovering things using Thing URLs broadcast via the Bluetooth [Eddystone](https://developers.google.com/beacons/eddystone) protocol.

This would provide the ability to add web things which are in physical proximity to the gateway, either on the same local network or elsewhere on the web.

**Comment by mrstegeman** [comment]
This is supported by https://github.com/mozilla-iot/thing-url-adapter
