### ISSUE TITLE
Discover Web Things via mDNS

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#696]
As a user I want to search for things which are broadcasting their URL on the local network so I can add them to my gateway

Let's experiment with discovering things using mDNS to broadcast their URL.

**Comment by mrstegeman** [comment]
[webthing-python](https://github.com/mozilla-iot/webthing-python) and [webthing-node](https://github.com/mozilla-iot/webthing-node) have been implemented to broadcast an mDNS service with type `_wot._tcp` and a `url` field in the TXT record.

**Comment by hobinjk** [comment]
I was using `var browser = mdns.createBrowser(mdns.tcp('http', 'webthing'));` locally which I think is a bit more semantic (_http._tcp,_webthing, "a tcp service providing http that uses the webthing api"). I took this approach from http://agnat.github.io/node_mdns/user_guide.html#service_types

**Comment by hobinjk** [comment]
I was also using `href` instead of `url` but your use of `url` is much better and more semantic so I'll modify accordingly.

**Comment by mrstegeman** [comment]
@hobinjk I'm fine with that. Is webthing supposed to be a sub-type? If so, I believe it should be mapping to `_webthing._sub._http._tcp`, not `_http._tcp,_webthing`. Maybe that's just what `mdns` uses internally?

**Comment by mrstegeman** [comment]
Yep, that works.

**Comment by hobinjk** [comment]
Oh, that's interesting, it should be _webthing._http._tcp, it looks like the comma syntax is just what mdns and the dns-sd utility use internally

**Comment by mrstegeman** [comment]
According to [this book](https://books.google.com/books?id=--R3jxPwQhUC&pg=PT87&lpg=PT87&dq=bonjour+subtypes&source=bl&ots=iSIjpKc26l&sig=RKSp18RqRYRT0o2dLZJ4fLdqheM&hl=en&sa=X&ved=0ahUKEwiw49qR9vzJAhUG52MKHUSNBC8Q6AEITjAJ#v=onepage&q=bonjour%20subtypes&f=false), you use the comma format when browsing, but on the network, a subtype actually maps to an additional PTR record with the format `_webthing._sub._http._tcp`.

**Comment by hobinjk** [comment]
Oh wow this is much more confusing and convoluted than I thought it would be. Thanks for the reference! Do you think it makes more sense as _webthing._sub._http._tcp or as _webthing._tcp?

**Comment by mrstegeman** [comment]
It makes more sense to me to do the sub-type. It's a bit easier to do it the other way, but this seems more proper.

**Comment by benfrancis** [comment]
See also https://tools.ietf.org/html/rfc6763

An example in the RFC is `_printer._sub._http._tcp.<Domain>` so ` _webthing._sub._http._tcp` seems reasonable.

Do you think a `_webthing` subtype is something we could propose as a standard in a "Thing Discovery" section of our Web Thing API spec? Presumably that would include defining the field in the TXT record where you can find the URL of the thing description.

There appears to be an [IANA registry for service types](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml) but it doesn't seem to include any sub-types. It doesn't even include http.

**Comment by mrstegeman** [comment]
I definitely think the subtype would be good to include, along with the Eddystone beacon format, if that's something we want to push forward.

**Comment by mrstegeman** [comment]
And yes, HTTP is included: https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?&page=2

**Comment by mrstegeman** [comment]
This is supported by https://github.com/mozilla-iot/thing-url-adapter
