### ISSUE TITLE
OTA update pings

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#697]
As Mozilla I want to log when gateways contact the update server so that I can get a better idea of the number of active gateways which may need updating

Currently we can only count the number of active gateways using our TLS tunnelling service and a *.mozilla-iot.org domain. It appears that many users are opting out of this service and choosing to use their own DNS configuration.

If we anonymously logged when a gateway contacts the OTA update server for updates, this would give us a more complete picture of how many active gateway they are requiring the use of the OTA update server so we can plan resources accordingly.

As updates are currently statically hosted on GitHub this may require changing our update infrastructure to Mozilla infrastructure in order to log this information.

**Comment by hobinjk** [comment]
The https://api.github.com/repos/mozilla-iot/gateway/releases endpoint lists the number of downloads for each component of the OTA update which right now shows that 5 attempts were made to OTA update to 0.3.0 from 0.2.1 and one confused person downloaded the gateway component thinking it was the gateway image.
