### ISSUE TITLE
New repository for UI and more documentation for the REST API

### ISSUE THREAD

**Issue by antonellopasella** [mozilla-iot/gateway#698]
It would be useful to separate the UI and declare an API to change the UI, maybe multiple folders and a way to revert to the default one?

**Comment by benfrancis** [comment]
Hi @antonellopasella, what is it that you're trying to do?

The [front end](https://github.com/mozilla-iot/gateway/tree/master/static) is fairly well separated from the [back end](https://github.com/mozilla-iot/gateway/tree/master/src) in separate folders, although not separate repositories. In most cases non-JSON requests are handled by a client side router, which gives the front end a lot of flexibility.

If you want to create your own front end, you could do that in a fork or create a separate application which requests access to the back end API using OAuth.

I'd personally prefer to keep them in the same repository for the time being, but it's not a bad suggestion.

**Comment by svrooij** [comment]
Any change you could show me how to request a token using oauth? Want to give it a go, because I really like the whole WOT idea. Solves the communication problem perfectly.

**Comment by benfrancis** [comment]
@svrooij This blog post by @hobinjk  might help https://hacks.mozilla.org/2018/05/visualizing-your-smart-home-data-with-the-web-of-things/

Otherwise feel free to ask for further help in #iot on irc.mozilla.org or on [Discourse](https://discourse.mozilla.org/c/iot).

**Comment by hobinjk** [comment]
@svrooij This page: https://github.com/mozilla-iot/wiki/wiki/Running-OAuth-Locally should also help, let me know if you have any questions!
