### ISSUE TITLE
Feature Request: Add support for Linear HUSBZB-1 ZWave + Zigby adapter

### ISSUE THREAD

**Issue by mmmurf** [mozilla-iot/gateway#703]
This appears to be one of the more readily available Zwave + Zigbee adapters.

https://www.google.com/shopping/product/100099638837075248?q=Linear+HUSBZB-1

**Comment by mrstegeman** [comment]
On the Z-Wave side, this was done earlier in the week. See: https://github.com/mozilla-iot/zwave-adapter/issues/10

To get the updated Z-Wave adapter, go into _Settings->Add-ons_, remove the old Z-Wave adapter and then get the updated version by clicking the + at the bottom right.

For Zigbee, see this discussion: https://discourse.mozilla.org/t/supported-hardware-digi-xstick-zigbee-usb-end-of-life-april-2018/25884/3
