### ISSUE TITLE
On/Off rule does not trigger consistently

### ISSUE THREAD

**Issue by ollu** [mozilla-iot/gateway#704]
I have a simple rule that triggers a wall plug (http://www.fibarouk.co.uk/the-system/wall-plug/) to turn on/off a lamp at a certain time. It seems to me that the rule will only trigger if I have visited the rules page before the rule is set to trigger.

Here is how the rule is set up:
![image](https://user-images.githubusercontent.com/280377/36582394-968988e8-1871-11e8-90a8-5958883fd202.png)

Is there a sleep mode for the server or some other configuration that I've missed? I'm running the application on a rasperry pi 3 model b and the communication with the wall plug is done via a z-stick gen 5 (https://aeotec.com/z-wave-usb-stick).

**Comment by mrstegeman** [comment]
@hobinjk actually fixed this yesterday with #702. Thanks for the report!

**Comment by ollu** [comment]
I'm sorry to bother you here but I could not find any better place ...

 I've tried finding information about a release cycle but with no luck I hope that maybe you can provide me with more information.
Also I've tried finding a forum to ask my question but I did not find any forum for the gateway/mozilla iot.

So to my question, when will the fix #704 be released?

Yes, I understand that I can build my own version but at the moment I would like to just update the installed version.

Thanks, Ola

**Comment by benfrancis** [comment]
Hi Ola,

The [0.4 release](https://github.com/mozilla-iot/gateway/milestone/12) will be feature complete at the end of March and will be released shortly after that.

However, we work in two week sprints and there may be a 0.3.1 release before that date if we feel there's enough that we want to push out early.

Either way your gateway should be automatically updated over the air when a new release comes out. See Settings -> Updates for your current version.

There is a Mozilla IoT forum on Discourse https://discourse.mozilla.org/c/iot
