### ISSUE TITLE
Feature Request: support Xiaomi Mi Home sensors/adapters

### ISSUE THREAD

**Issue by thgreasi** [mozilla-iot/gateway#707]
Support for Xiaomi's [Mi Home devices](https://xiaomi-mi.com/sockets-and-sensors/) would be nice.

**Comment by MrKou47** [comment]
@thgreasi Have you tested xiaomi yet?

**Comment by haralambos85** [comment]
This would be very useful!

**Comment by thgreasi** [comment]
@MrKou47 I tested just my aqara temperature-humidity-pressure sensor and it pair but shows up as unknown adapter without any extra info. I'm using just the zigbee plugin (and zwave).

PS: had to long-press the sensor's button to make it discoverable by the RPi.

**Comment by DurandA** [comment]
This could be done using [zigbee-shepherd](https://github.com/zigbeer/zigbee-shepherd). It does not use Digi XStick but CC2531 USB stick (which is cheap). The [xiaomi-zb2mqtt](https://github.com/AndrewLinden/xiaomi-zb2mqtt) project use zigbee-shepherd to communicates with Xiaomi Zigbee sensors and switches.

**Comment by neugartf** [comment]
I would be interested in this too.

**Comment by mrstegeman** [comment]
@dhylands Are these officially supported now?

**Comment by dhylands** [comment]
That particular sensor didn't come with my kit. The place to add it would be in the zb-xiami.js file:
https://github.com/mozilla-iot/zigbee-adapter/blob/master/zb-xiaomi.js Whether more needs to be added depends on the exact clusters used by the sensor.

**Comment by mrstegeman** [comment]
Please file [issues](https://github.com/mozilla-iot/zigbee-adapter) for individual sensors, as there are a lot to choose from.
