### ISSUE TITLE
Broadcast a Eddystone Beacon message in the First-time setup with the gateway's local IP address

### ISSUE THREAD

**Issue by andrenatal** [mozilla-iot/gateway#714]

**Comment by andrenatal** [comment]
Reference:

https://webgazer.org/update/tutorial/2016/03/16/raspberrypi-eddystone-url.html
https://google.github.io/physical-web/
https://developers.google.com/beacons/

**Comment by mrstegeman** [comment]
This should only need to be done on the gateway-wifi-setup side: https://github.com/mozilla-iot/gateway-wifi-setup/issues/60

**Comment by andrenatal** [comment]
So the user will never be able to turn the broadcast off?

I opened this here too because initially I thought that after the user manages to reach the gateway maybe he would want to turn it off, but honestly, I like it always on for marketing purposes and in case he forgets or etc.

**Comment by mrstegeman** [comment]
It'll be on until the gateway is rebooted. I don't see it being a huge issue, but it would be pretty easy for us to take the Bluetooth interface back down after the user sets up their domain and such.
