### ISSUE TITLE
Unable to dim Philips Hue from phone

### ISSUE THREAD

**Issue by nikolajsheller** [mozilla-iot/gateway#721]
When setting bulb color from my phone's browser, I can only choose between a few different, full intensity, colors.

I can select the full color range and intensity from at desktop browser.

![screenshot_20180228-233002](https://user-images.githubusercontent.com/875164/36816979-d7377072-1cdf-11e8-886c-e0af39998518.png)

**Comment by benfrancis** [comment]
Hi @nikolajsheller, this is actually intended behaviour. The web interface is using the standard HTML color input and this UI is actually provided by your browser. Different browsers provide different options.

Are you able to dim the bulb using the brightness slider, or does that not appear as an option for your bulb? Exactly which bulb are you using?

**Comment by nikolajsheller** [comment]
I do not see a brightness slider, please see the screenshot, and I only see about 16 colors. There is no slider outside the color picker. I can only control On/Off and color when selecting the thing. I am using firefox on android.
My bulb is a Philips Hue 806 lumen "White and color ambiance" with an E27 socket.

**Comment by nikolajsheller** [comment]
Googling around I found this:
https://blog.mozilla.org/ux/2013/12/a-new-colour-picker-on-firefox-for-android/
This is what I need. I am using Firefox 57.0.4 (Fennec). Oddly the advanced tab is not present and there is no way (that I can find) to switch to the color wheel.
I agree it would be a shame not to use the native implementation.

I will consider filing a bug with Mozilla's bugzilla.

Thank you for your input.
