### ISSUE TITLE
collecting data can be useful for project analytics and future research

### ISSUE THREAD

**Issue by kgiori** [mozilla-iot/gateway#730]
Firefox add-ons defines [four categories](https://wiki.mozilla.org/Firefox/Data_Collection#Data_Collection_Categories) to describe data collection. As a user, I'd be pleased to see a consistent use of these same categories to data collected by the Things Gateway add-ons. Future add-ons might be related to research, making the product better, 3rd party services, etc.

**Comment by mrstegeman** [comment]
Let's open individual issues if we decide there's something we want to collect.
