### ISSUE TITLE
ZWave controller should be reset at start of program?

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#74]
If the app crashes while the zwave dongle is inclusion mode, and you then restart the app, the dongle seems to still be in a state where many devices will timout. I observed that my Leviton devices all got timeouts.

Unplugging and replugging the dongle seemed to resolve this.

We might need to do a controller (dongle) reset. Ideally we'd detect the state that the controller is in and get it out of that state, and only reset the controller if absolutely required.

**Comment by mrstegeman** [comment]
@dhylands Is this still an issue?

**Comment by mrstegeman** [comment]
Moved: mozilla-iot/zwave-adapter#32
