### ISSUE TITLE
Feature request: debugability

### ISSUE THREAD

**Issue by Swaagie** [mozilla-iot/gateway#741]
Was trying to get a razberry working and found out it is a bit hard to debug installed adapters. For example adding `console.log/dir` messages to inspect some value in the adapter would result in the addon-controller complaining about a bad checksum. That in itself is obviously a good thing, but it would be nice if these checks could be turned off, for example in `NODE_ENV=development` those checks would be off. I ended up just deleting the file from the shasum list. Is there another way to do this more easily? 

Also some of the useful messages are being swallowed atm. For example, in my case the `ttyAMA0` port was not properly reporting the razberry module and it's details. However. the received error https://github.com/mozilla-iot/zwave-adapter/blob/master/zwave-adapter.js#L424-L428 is basically omitted and replaced with a more generic message `Unable to find ZWave adapter`. Which is not particularly helpful during debugging. I noticed an earlier removal of `Winston` as logger, but being able to set a `loglevel` and allowing the adapters to be really chatty when the `loglevel=verbose` would be helpful in this case.

Thoughts? I don't mind to put in the work to get it done

**Comment by mrstegeman** [comment]
The checksums are disabled if one of the following is true:
1. There is a `.git` directory within your add-on directory
2. `SHA256SUMS` is not included in the `files` array in `package.json`

You can also start the add-on yourself and debug it, i.e. through VS Code or something. This is what I typically do for debugging purposes. Not all functionality will work, such as enabling/disabling through the UI, but the add-on itself should still function properly. You could do something like this:
`$ node /path/to/gateway/src/addon-loader.js /path/to/gateway/build/addons/zwave-adapter`

**Comment by Swaagie** [comment]
Thanks for the pointers! I found number 2 by reading code, but 1. is easy as well. Simple git clone. Are these workarounds documented somewhere for future reference? 

Both are not ideal however, at least from my perspective. What are the current plans with respect to configurable debugability?

**Comment by rroopreddy** [comment]
What is the best way to start and debug an adapter by itself in `vscode`?. Trying to debug `example-adapter` in vscode using above command pattern

```
$ node /path/to/gateway/src/addon-loader.js /path/to/gateway/build/addons/example-adapter
```

results in 

```
WARNING: No configurations found in configuration directory:/path/to/gateway/build/addons/example-adapter/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
/Development/opensource/mozilla-iot/gateway/node_modules/config/lib/config.js:202
    throw new Error('Configuration property "' + property + '" is not defined');
    ^

Error: Configuration property "profileDir" is not defined
    at Config.get (/Development/opensource/mozilla-iot/gateway/node_modules/config/lib/config.js:202:11)
    at Object.open (/Development/opensource/mozilla-iot/gateway/src/db.js:53:35)
    at Object.<anonymous> (/Development/opensource/mozilla-iot/gateway/src/addon-loader.js:23:4)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
```

**Comment by mrstegeman** [comment]
I was a little bit off.

For the 0.3.X release series, you can do this:
```bash
cd /path/to/gateway
node src/addon-loader.js  /Users/mstegeman/workspace/adapters/example
```

For the current master branch of the gateway, you can do something like this:
```bash
cd /path/to/gateway
NODE_PATH=/Users/mstegeman/workspace/gateway/node_modules node src/addon-loader.js  /Users/mstegeman/workspace/adapters/example
```
