### ISSUE TITLE
Update Available but Not Reported

### ISSUE THREAD

**Issue by rei-vilo** [mozilla-iot/gateway#748]
On the menu **Settings > Updates** of the gateway, the version is said to be up-to-date at `0.3.0` when a new release `0.3.1` is available at https://github.com/mozilla-iot/gateway/releases/tag/0.3.1.

<img width="512" alt="capture 2018-03-08 a 21 17 00" src="https://user-images.githubusercontent.com/951776/37174279-548edd4e-2316-11e8-803d-c3d08c26caff.png">

Is the auto-update feature implemented?

**Comment by hobinjk** [comment]
We haven't tested the 0.3.1 release thoroughly enough to want it to be pushed out automatically so it's marked as a prerelease. If you want to test it out before we've signed off on it you can follow [these instructions](https://gist.github.com/hobinjk/e7c329bd2b7f6d16ae4e288d96d279c3).

**Comment by rei-vilo** [comment]
Thanks!
