### ISSUE TITLE
Time bases rule does not turn on bulb

### ISSUE THREAD

**Issue by gerritanne** [mozilla-iot/gateway#750]
Rule: when time is 17:00 turn on bulb x.

When I first setup the rule this worked. However, it does not seem to work any longer. I can still switch on and off the bulb manually. Just the rule (which is active) doesn’t trigger anything.

**Comment by hobinjk** [comment]
Sorry for the inconvenience! This issue is fixed in our upcoming 0.3.1 release which should be available this Tuesday. Your Gateway will automatically update within a day of when the release goes out.
