### ISSUE TITLE
Web Thing REST API - "GET"

### ISSUE THREAD

**Issue by aragnac** [mozilla-iot/gateway#753]
Good morning,

I tried to do a GET request on my gateway in order to retrieve thing resource. So first I used the
```json
GET http://mythingserver.com/things/mything
```
command alone, from my RESTClient module in mozilla and I obviously retrieve the html code of the web page. Then I add the
```json
Accept: application/json
```
in order to retrieve JSON data but I got a 401 unhautorized. I tried to add a "basic authentication" with one of the users created on my gateway but still got the same 401 code.
So, how can I retrieve JSON data from my gateway ?

Best regards,

Nicolas

**Comment by benfrancis** [comment]
You're doing the right thing with a GET request and the Accept header, it sounds like you might be missing the `authorization` header.

It looks like this:
`authorization: Bearer xyz`

Where `xyz` is the long JSON Web Token for your user. If you use the developer tools in your browser to look at the headers of the API requests while logged in, you should be able to copy and paste the token to use in your own requests.

That's the quickest way. If you're developing a third party application which you want to access the API you might want to consider having it request access using OAuth.

**Comment by aragnac** [comment]
Well,
first of all thanks for your quick answer Ben !
I tried with the Bearer web token but it still doesn't work as you can see on the screenshots underneath.

![bearer](https://user-images.githubusercontent.com/12186566/37343086-bc9b8afa-26c6-11e8-8ec3-d5ff133656f8.png)

![request](https://user-images.githubusercontent.com/12186566/37343065-aea7a488-26c6-11e8-997b-c423b61bf37c.png)

![response](https://user-images.githubusercontent.com/12186566/37343211-22a2ecee-26c7-11e8-86ea-12fc01252f14.png)

So, is there another thing I can add to the header to solve the problem ?

If not, considering using your second solution, which is to use OAuth. Can you tell me where can I find all the information needed to use OAuth such as Consumer key, Shared secret ? I guess the Shared secret is encrypted even if it travel on the network?

Thanks,

Nicolas

**Comment by sogaani** [comment]
@aragnac
It seems that you have missed ```Bearer ```.
```Bearer ``` is must required for the authorization header.

```
authorization: Bearer xyz
```

**Comment by aragnac** [comment]
@sogaani 
Oooh.. My fault ! You are right.
Too much hours spent in front of my screen.

Thanks !

**Comment by benfrancis** [comment]
(If you do want to look into OAuth then @hobinjk should be able to help)
