### ISSUE TITLE
OAuth:Appear authorization screen before login.

### ISSUE THREAD

**Issue by sogaani** [mozilla-iot/gateway#757]
Authorization screen is Temporarily shown  when using oauth with not logined client.
We could put ```class='hidden'``` on body same as gateway root to avoid it.

**Comment by ziransun** [comment]
I'd like to work on this if it's okay

**Comment by ziransun** [comment]
And if I can have steps on how to produce the bug, it would be much helpful.

**Comment by sogaani** [comment]
You can access authorization screen with following url.
```
https://[yourdomain].mozilla-iot.org/oauth/authorize?response_type=code&client_id=hello&redirect_uri=http%3A%2F%2F127.0.0.1%3A31338%2Fcallback&scope=readwrite&state=gfagrha
```
Replace ```[yourdomain]``` with your gateway domain.

Need to sign out your gateway to produce the bug.
You could use private browsing in Firefox or delete session.

**Comment by hobinjk** [comment]
Thanks for helping out! https://github.com/mozilla-iot/gateway/pull/629 fixed this issue on the main things page (so a similar change is needed here to the /oauth/authorize page)
