### ISSUE TITLE
can not find ikea tradfri bulb

### ISSUE THREAD

**Issue by MrKou47** [mozilla-iot/gateway#759]
Hello! Recently i bought an xstick(XU-Z11), Raspbery Pi3 and an [ikea tradfri bulb](http://www.ikea.com/gb/en/products/lighting/smart-lighting/tr%C3%A5dfri-dimming-kit-warm-white-yellow-art-80356911/).Today when i try to add tradfri bulb into gateway, i find that gateway can not find my bulb.

And my xstick always blink yellow light. Maybee something wrong with it?
![xstick](https://image.ibb.co/cEecPc/1301521046043_pic.jpg)

----

I try to factory reset tradfri. I follow the https://github.com/mozilla-iot/wiki/wiki/HOWTO:-Factory-reset-an-IKEA-bulb, switch the bulb six times,but after do this the bule doesn't flash...

----

And the tradfri instructions said that when connect to the bulb first time, the distance between wireless dimmer should less than 5cm, So do I need to put the raspberry pi close to the bulb?
![instruction](https://image.ibb.co/cyAyxx/WX20180315_010451_2x.png)

**Comment by mrstegeman** [comment]
Moved to the Zigbee adapter repo: https://github.com/mozilla-iot/zigbee-adapter/issues/16
