### ISSUE TITLE
Move Adapters into Settings

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#76]
As we want to use the Adapters section to configure which Adapters are enabled, the [latest UI mockups](https://docs.google.com/a/mozilla.com/presentation/d/1rMeg6hep8JQflqwbiNIbhSoK9StCeVZ2npphmQHKda4/edit?usp=sharing) put the Adapters section inside the Settings section of the UI

**Comment by benfrancis** [comment]
May not have time to do this before the first release, so could just hide the settings menu item for now instead.

**Comment by benfrancis** [comment]
UI Mockups:
![adapter_settings](https://user-images.githubusercontent.com/552417/32733477-409b1c42-c887-11e7-883c-cc45366ca4c2.png)

See also, #78 (Settings - Enable/disable adapter)

**Comment by benfrancis** [comment]
Do we actually need a list of adapters separate from the list of installed add-ons? The only use case I can think of is if you have multiple adapters of the same type. For example you install the Z-wave adapter add-on and plug in two Z-Wave adapters.

**Comment by dhylands** [comment]
I can see that eventually we'll want to have config/settings for each individual adapter. For example, to use door locks, you have to have a network key. For many users, having use generate a random network key would be perfectly acceptable, but for an existing newtork, we'd need a way to enter the current network key, otherwise we won't be able to talk to secure devices.

For a WebThing URL Adapter, we need a way to enter specific URLs.

**Comment by benfrancis** [comment]
> I can see that eventually we'll want to have config/settings for each individual adapter. For example, to use door locks, you have to have a network key. For many users, having use generate a random network key would be perfectly acceptable, but for an existing newtork, we'd need a way to enter the current network key, otherwise we won't be able to talk to secure devices.

Sorry, I don't understand this example, why does it require multiple adapters of the same type?

> For a WebThing URL Adapter, we need a way to enter specific URLs.

I imagine you'd just add a Thing by URL in the add thing dialog, you don't need an adapter per thing. In fact native web things are the one type of thing which probably don't need an "adapter" because they're already talking the Web Thing API.

**Comment by dhylands** [comment]
> I can see that eventually we'll want to have config/settings for each individual adapter. For example, to use door locks, you have to have a network key. For many users, having use generate a random network key would be perfectly acceptable, but for an existing newtork, we'd need a way to enter the current network key, otherwise we won't be able to talk to secure devices.
> Sorry, I don't understand this example, why does it require multiple adapters of the same type?

It requires settings at the adapter level as opposed to the adapter type level. If you have multiple zwave dongles, you might not be using the same network key on each dongle.
 
> For a WebThing URL Adapter, we need a way to enter specific URLs.
> I imagine you'd just add a Thing by URL in the add thing dialog, you don't need an adapter per thing. In fact native web things are the one type of thing which probably don't need an "adapter" because they're already talking the Web Thing API.

Where does the URL for the thing get stored? I thought that the UI gets it by querying the adapter.

**Comment by benfrancis** [comment]
Updated mockups:
![settings-addons](https://user-images.githubusercontent.com/552417/32958975-fa5176a8-cbb7-11e7-8b7d-39c493a31b9f.png)
![adapters](https://user-images.githubusercontent.com/552417/32958876-ab44dd48-cbb7-11e7-970a-59d58bc4ea66.png)

**Comment by benfrancis** [comment]
> Where does the URL for the thing get stored? I thought that the UI gets it by querying the adapter.

Presumably in the things table in the database. My assumption is that we shouldn't need an adapter to convert Web Thing API to Web Thing API so we can just point to URL endpoints in the Thing Description rather than have the gateway handle the API requests. That does depend a bit on the deployment and security model though (i.e. whether the gateway is acting as a proxy for a native web thing vs. the front end calling the Web Thing API on the thing directly.)
