### ISSUE TITLE
Reinstantiating things on startup

### ISSUE THREAD

**Issue by fiz1962** [mozilla-iot/gateway#764]
It seems Things that are saved in db.sqlite3 are not recreated when restarting the gateway.  They do show up on the web page, but then are not found if access is attempted unless they are reinstantiated when the adapter is loaded.  Unless there is some way I have missed to do this, perhaps a ".things" be added to newSettings in addon-loader.js and passed to the adapter, and let the adapter decide whether to recreate its Things when loaded?  A patch for a possible solution is attached.

[ThingsPatch.txt](https://github.com/mozilla-iot/gateway/files/1819457/ThingsPatch.txt)

**Comment by dhylands** [comment]
I'd like to get some more information about how the gateway was restarted? I've not seen this behaviour myself. Which adapter was being used?

**Comment by mrstegeman** [comment]
@dhylands I see this all the time. Sometimes, the discovery process is unreliable, so the adapters don't end up creating the things that they previously did. Typically, clicking the + on the things screen to start another discovery will fix it for me.

**Comment by dhylands** [comment]
I know with ZWave, it can take several minutes for the initial scan to complete, especially when there are "dead" devices. The adapter doesn't tell the gateway about the scanned devices until the scan has completed. Issue #624 might be related.

**Comment by fiz1962** [comment]
My ESP adapter code scans a range of IP addresses looking for "Things" that I make from ESP8266, Arduinos, etc when the "+" is clicked to start pairing.  If I had the adapter scan this range of addresses each time it was started I think all would be good, but in my case, my devices generally are not powered up all the time.  For example, they may only power up from an interrupt generated by a door switch long enough to report to the gateway that the door opened, then go back to sleep to conserve battery.  They would need to be powered up during the "pairing" process to be paired initially but I would then like to recreate any device stored in the db without it necessarily being powered up when the gateway started at some later time.  Ie, if the computer running the gateway rebooted I would like to be able to recreate any saved devices whether they are powered up or not.

**Comment by fiz1962** [comment]
Another wrinkle for pairing each time the gateway starts is just because a "Thing" responds at some IP address, I may not want to add it.

**Comment by mrstegeman** [comment]
This can now be done with `handleDeviceSaved()` in the adapter.
