### ISSUE TITLE
mozilla-iot-gateway.service not present

### ISSUE THREAD

**Issue by tebuch** [mozilla-iot/gateway#766]
I tried the `install.sh` script and at the end, it failed to find the `mozilla-iot-gateway.service` that's supposed to be in a non-existent `systemd/system/` directory. Thus, I cannot use systemctl to start it

**Comment by dhylands** [comment]
install.sh assumes that it's running in a previously prepared base image.

This wiki page describes how to create the base image:
https://github.com/mozilla-iot/wiki/wiki/Creating-the-base-image-file-for-the-Raspberry-Pi

The systemd stuff is done as part of the base image.

**Comment by tebuch** [comment]
Ahh okay. Thanks for the quick response
