### ISSUE TITLE
enable CORS for WEB thing API call

### ISSUE THREAD

**Issue by aragnac** [mozilla-iot/gateway#767]
Hi,
I'm currently developping an angular app using the WEB Thing API of the mozilla IoT gateway. My problem is that the "Cross-Origin Request" sharing option seems to be inactivated on the server side.  I got this king of errors with status code 503. Which file(s) do I have to modify in order to allow CORS on server side ? 

Best regards,

Nicolas

![203error](https://user-images.githubusercontent.com/12186566/37599583-605f8962-2b85-11e8-8383-308d66f9505c.png)

**Comment by sogaani** [comment]
If you want to allow "Cross-Origin Request" with all http request,  will be good to modify function:```configure```  in file:```src/router.js```.

You probably need to add the following code:
```
app.use(function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
  next();
});
```

**Comment by aragnac** [comment]
thanks for your quick answer @sogaani,

I tried to add the following lines but I still got the same errors. If I call the next();  I've got a "can't get/" error. 

Nicolas

![corserror](https://user-images.githubusercontent.com/12186566/37602937-c3515138-2b8d-11e8-9694-3b292e8f70c8.png)

**Comment by sogaani** [comment]
Sorry, I missed that we need to allow Authorization header at least.
```
      response.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept, Authorization");
```

**Comment by sogaani** [comment]
@aragnac
Do you need OPTIONS request?
I think that maybe OPTIONS method is not implemented.

Following code work in my browser.
```
fetch('https://[domain].mozilla-iot.org/things/virtual-things-0',{headers:{Authorization:'Bearer [TOKEN]'}}).then(res => {console.log(res),res.json()}).then((json) => {console.log(json)}).catch((err) => console.log(err));
```

**Comment by hobinjk** [comment]
@aragnac I'm sorry that you're encountering this issue! If you could provide the full list of request headers from the network tab it would be very helpful to understanding what's going on.

**Comment by mrstegeman** [comment]
@aragnac Can you see if #768 fixes your issue, please?

**Comment by aragnac** [comment]
@mrstegeman as mentioned upper in this issue, no it doens't fix it, unfortunetely.

**Comment by hobinjk** [comment]
Okay, after adding #768 the following code works which is what I think Angular is using under the hood:
```javascript
      function onLoad(event) {
        console.log(this.responseText, event);
      }
      
      let xhr = new XMLHttpRequest();
      xhr.addEventListener('load', onLoad);
      xhr.open('GET', 'https://hobinjk-laptop.mozilla-iot.org/things');
      xhr.setRequestHeader('Accept', 'application/json');
      xhr.setRequestHeader('Authorization', 'Bearer ' + jwt);
      
      xhr.send();
```

**Comment by hobinjk** [comment]
Although my browser appears to be sending the exact same OPTIONS as yours is. I'll try to set up angular to see if I can reproduce the issue there

**Comment by sogaani** [comment]
Preflighted requests section on [CORS specification](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) describes when browser request OPTIONS method.

We can use [CORS middleware](https://github.com/expressjs/cors) to deal OPTIONS request easy.

**Comment by aragnac** [comment]
hum, after added #768 it seems to be worst. I've got 
![cors](https://user-images.githubusercontent.com/12186566/37609041-5c828ed6-2b9c-11e8-830e-44e96b0aed43.png)

Then if I click on "open in new tab" I arrive on the /thing tab but no things appears. I suppose that the REST API call doens't work anymore..

**Comment by hobinjk** [comment]
If you add a security exception for 192.168.254.114 the request should work. That's the downside of working locally instead of pointing the request at the tunnel service (i.e. https://hobinjk-laptop.mozilla-iot.org, https://levelit.mozilla-iot.org, etc.)

I'm not sure why it's saying "www.example.com" has an invalid security certificate though. Are you sure everything in your code is pointed where it should be?

**Comment by aragnac** [comment]
Well, thanks a lot my dear @hobinjk it is working perfectly with your peace of code ! I used the XMLHttpRequest as you did and everything went well. 

Just one thing I want to notice. As you can see on this screenshot, I have two cncDevice-test request.
One with the "Request Method:GET" and the other one with the "Request Method:OPTIONS"

![cors](https://user-images.githubusercontent.com/12186566/37610716-9ee26a9a-2ba0-11e8-9d94-895af6ac3607.png)

**Comment by hobinjk** [comment]
@aragnac Glad to hear it! The OPTIONS request is the "preflight" request @sogaani is talking about which the browser uses to make sure CORS is enabled before sending the GET

**Comment by aragnac** [comment]
I've forgot to mention one important thing. 
It works ONLY because I use this plugin : [https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?utm_source=chrome-app-launcher-info-dialog](url)

Which add to response header the following rule : 
>  'Access-Control-Allow-Origin: *'

Nicolas.
