### ISSUE TITLE
AND statements for rules engine

### ISSUE THREAD

**Issue by gerritanne** [mozilla-iot/gateway#773]
The rules logic at this moment is quite basic (if this then that), and it's only possible to have 1 input device and connect it to 1 output device. It would be great to have multiple input devices connected to multiple output devices.

Some use cases:

IF time = 22:00 AND lamp 1 = on THEN turn off lamp 2 AND lamp 3

IF time = 24:00 THEN turn off ALL devices of type light bulb AND switch on smart plug

Kind regards,
Gerrit Haan

**Comment by benfrancis** [comment]
As a user I want to set multiple inputs and/or multiple outputs for rules, using an AND so that a rule can depend on multiple inputs or affect multiple outputs.

**Comment by hobinjk** [comment]
UI mockups:
![base](https://user-images.githubusercontent.com/2776089/40550439-13a48a02-6008-11e8-8179-b4e6c908c373.png)
![and-or detail](https://user-images.githubusercontent.com/2776089/40550438-1364f0e0-6008-11e8-9dad-ef35f9580a4d.png)

**Comment by mrstegeman** [comment]
@hobinjk This is done, right?

**Comment by mrstegeman** [comment]
Fixed by #1091
