### ISSUE TITLE
Enable/disable adapter

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#78]
As a user I want to see a list of adapters active on the gateway so I can choose which ones to enable.

**Comment by benfrancis** [comment]
UI Mockups:

![adapter_settings](https://user-images.githubusercontent.com/552417/32733362-fdfa895e-c886-11e7-9229-1f6b94a8a819.png)

**Comment by benfrancis** [comment]
See also: #76 (Move Adapters into Settings)

**Comment by benfrancis** [comment]
@mrstegeman Do we actually need this?

**Comment by mrstegeman** [comment]
I personally don't see a need to. I think enabling/disabling the add-on as a whole makes more sense, and if you're trying to disable an individual Z-Wave dongle or something, you could just unplug it.

**Comment by benfrancis** [comment]
OK thanks, let's close this.
