### ISSUE TITLE
separation of concerns (SoC) - Services concept (WEB Thing API)

### ISSUE THREAD

**Issue by aragnac** [mozilla-iot/gateway#788]
Hi,

I wonder something about the Mozilla IoT architecture. I guess that my question fit in the separation of concerns (SoC) concept but not sure.  

When issuing an API call, for example : 

> A PUT request on https://levelit.mozilla-iot.org/things/virtual-things-6/propertyname

The call goes to the server, crosses the adapter and finally arrived on the components on which we want to perform an action (very schematic representation).

But what I wonder is, that there is probably something between the API request recieved on the server side and the entry in the adapter. I mean that I suppose that the api call doens't go directy to the adapter. 
So my question is, is there any concept of service which already exist in the mozilla-iot gateway framework which involved the call of such a service before entering the correct adapter ?
Maybe a little diagram to better understand what I mean : 

![soc](https://user-images.githubusercontent.com/12186566/37769319-eda13134-2dd0-11e8-811a-9f59214ac14b.png)

And therefore, as a second question, is there a programaticaly way to tell "I want you (the initial API query) to go through this service before enterring in the right adapter" ?

I know, this question is a bit tricky. Hope someone can answer it.

Best regards,

Nicolas

**Comment by dhylands** [comment]
The handling of the put request is done by a controller. I'm not sure your example is valid. You would perhaps do a PUT on a property, in which case the handler is here:
https://github.com/mozilla-iot/gateway/blob/1c42f069913a5cdd045229b12931f83003c6a8e7/src/controllers/things_controller.js#L89-L110
That code takes the URL, extracts the thingId and propertyName and then calls the AddonManager to deal with the request.

**Comment by aragnac** [comment]
Hi @dhylands  thanks for your answer. 

In fact what I'm trying to establish is the complete sequence of calls, the complete architecture, from the API call to the things. So now I understand that the thing-controller handle the request (PUT, GET, ...) but as I can see it's only check if the query is well formated.

Is the thing directly link to a specific adapter or is there a way to decide ,from an upper layer (for example : the thing-controler) and based on information provide in the query, to redirect this query to a service (based on a service concept) which will achieve some operations before calling the right adapter which will then send the information to the right thing. 
What I want to achieve is to reduce/split the role of the adapter by giving some more stuff to do to a service, just to seperate a little bit more all the things. The adapter will be consider only as a driver if you want.

Another diagram to explain what I mean (green arrows): 

![architecture](https://user-images.githubusercontent.com/12186566/37824927-77cae496-2e8e-11e8-87df-4e862510a47b.png)

A concrete example : 

![example](https://user-images.githubusercontent.com/12186566/37825544-84c63bda-2e90-11e8-89ab-9800404f96f8.png)

In this example, I only use internal services to translate my action into gcode. But as you can see, services won't be call each time, it'll depends of the use case. 

We can imagine, for the same example, to have an external services (for example, call from the cloud) which take some video or pictures as input (corresponding to a human action, for example with is hand in front of the camera) and provide some data in output(in this case, also GCode) which can be understand by the right adapter. 
We can imagine to call services for whatever we want.

So, is there a concept of services (Cloud based, internal or external) already present in the mozilla iot architecture, is the service concept part of the pylosophy of the mozilla iot ? 

What I'm asking is probably a bit tricky. I tried to be as precise as possible.

Best regards, 

Nicolas
