### ISSUE TITLE
Firmware update support for Things

### ISSUE THREAD

**Issue by nithyanantham** [mozilla-iot/gateway#791]
Any plan to support OTA for connected Devices from Gateway?

**Comment by mrstegeman** [comment]
Are you referring to OTA firmware updates?

**Comment by nithyanantham** [comment]
Yes correct. I am referring to connected device firmware not the gateway firmware. I am looking for option to upload the firmware into gateway and from there i want to initiate OTA for all my connected devices.

**Comment by mrstegeman** [comment]
There is not currently support for that. We've had some initial discussions about it, but the OTA update mechanisms are all device-specific and are not always accessible by third party APIs.

**Comment by nithyanantham** [comment]
Ok, got it. I am working on some ESP8266 based custom device which is going support OTA. I am planning to use Mozilla Gateway to integrate all my wifi enabled devices. 

I thought of checking if there any specification already defined for OTA support so that i can adopt in my firmware.

**Comment by rzr** [comment]
Well for device management I would have a look at LWM2M:

https://en.wikipedia.org/wiki/OMA_LWM2M

**Comment by mrstegeman** [comment]
This should be handled by individual adapters, where possible.
