### ISSUE TITLE
OAuth: Change output of /things to reflect token's scope

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/gateway#793]
i.e. if the gateway has things test-1, test-2, and test-3 but a token grants `/things/test-1:read /things/test-2:read` a GET to /things authenticated by that token should list test-1 and test-2 instead of being blocked.

**Comment by ziransun** [comment]
I'd like to work on this. Thanks!

**Comment by mrstegeman** [comment]
Fixed by #929
