### ISSUE TITLE
building instructions seem to be outdated

### ISSUE THREAD

**Issue by skandragon** [mozilla-iot/gateway#800]
It seems the project has been split into a number of individual components, and there's no direction on how to build the gateway and (say) the zigbee adapter to have them work together, without having to build and install a full image.

This is for development use.

**Comment by mrstegeman** [comment]
The README isn't really outdated. The add-ons are no longer bundled, but are now installable in the UI via _Settings -> Add-ons_.

That said, the installable version of Zigbee/Z-Wave/GPIO will not currently work with master, they'd have to be built and installed manually. The other add-ons should work fine.
