### ISSUE TITLE
Device's actions news ?

### ISSUE THREAD

**Issue by aragnac** [mozilla-iot/gateway#807]
Refer to #717 

What about device's actions (and events) currently ? Is there any parent/super class you are working on from which we could heritate ? ( such as Adapter, Device and Property parent classes)
Any news about it ?

Nicolas

**Comment by mrstegeman** [comment]
Yes. You can follow these 2 issues, in addition to #717:
* https://github.com/mozilla-iot/gateway-addon-node/pull/4
* https://github.com/mozilla-iot/gateway-addon-python/pull/8

**Comment by aragnac** [comment]
Thanks @mrstegeman !
