### ISSUE TITLE
Start/end times of rules changed since summertime

### ISSUE THREAD

**Issue by gerritanne** [mozilla-iot/gateway#808]
Since summertime started here in The Netherlands, the rules end/start times unexpectedly changed with +1, which is not correct.

Original rule: 

If time is 22:00, turn on lamp

Same rule after summertime started:

If time is 23:00, turn on lamp

Rules should remain the same, regardless if it’s summertime or not

Kind regards,
Gerrit Haan

**Comment by benfrancis** [comment]
@hobinjk Do you know what's going on here?

**Comment by hobinjk** [comment]
The initial time implementation was based on the assumption that the raspberry pi's would all be properly localized to their own time zones. The time rules need to somehow know their time zone since the Pi doesn't.
