### ISSUE TITLE
binary node_modules are specific to NODE_MODULE_VERSION

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#810]
Steps to reproduce:
```
git clone https://github.com/mozilla-iot/serial-adapter.git
cd serial-adapter
nvm use v7.10.1
yarn
./list-ports.js
nvm use --lts
./list-ports.js
```
The second time I run list-ports.js using node v8.10.0 but node_modules generated via node v7.10.1 I get the following error:
```
/home/dhylands/Dropbox/moziot/serial-adapter/node_modules/bindings/bindings.js:88
        throw e
        ^

Error: The module '/home/dhylands/Dropbox/moziot/serial-adapter/node_modules/serialport/build/Release/serialport.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 51. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at bindings (/home/dhylands/Dropbox/moziot/serial-adapter/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/home/dhylands/Dropbox/moziot/serial-adapter/node_modules/serialport/lib/bindings/linux.js:2:36)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
```
This implies that node binary dependencies are not only platform specific but at least node major version number specific.

I found this table which shows NODE_MODULE_VERSION in relationship to node.js version.

**Comment by mrstegeman** [comment]
For reference, here's that table: https://nodejs.org/en/download/releases/

**Comment by mrstegeman** [comment]
It seems like we should just build against the current LTS version and distribute that.

**Comment by hobinjk** [comment]
This is basically why #814 (which installs the node lts as a default) is important

**Comment by dhylands** [comment]
That works for now, but when node v10 goes LTS we'll then run into the problem and need to install node v8 for version of the gateway still running that versus v10 for the newer gateway versions.

We can delay adding support for the time being, but we'll need to address it at some point.

**Comment by hobinjk** [comment]
This is true, I think the best way to address it is by pinning our LTS to node 8

**Comment by mrstegeman** [comment]
Duplicates #1122
