### ISSUE TITLE
No adapters present but Zigbee dongle is connected (and detected)

### ISSUE THREAD

**Issue by nrogelio** [mozilla-iot/gateway#811]
I have a Digi XStick2 ZB dongle connected to Raspberry Pi 3 running Things gateway 0.3.1 and I'm getting "No adapters present" message in Settings>Adapters section.

I was able to confirm the dongle is detected in /dev/ttyUSB0 running a script posted [here](https://unix.stackexchange.com/questions/144029/command-to-determine-ports-of-a-device-like-dev-ttyusb0).

Here is the [run-app.log](https://github.com/mozilla-iot/gateway/files/1858714/run-app.log) file with Debugging Zigbee enabled (this.debugFrames = true;).

And this is the dongle I'm using:
![zigbee_dongle](https://user-images.githubusercontent.com/37613459/38072179-14972290-32da-11e8-8657-a666729fe3db.PNG)

Thanks!

@dhylands

**Comment by nrogelio** [comment]
@dhylands here is the new [run-app.log](https://github.com/mozilla-iot/gateway/files/1862647/run-app.log) file.

Thanks!

**Comment by nrogelio** [comment]
I found what was the problem:

The PAN ID (ID) is 0 by default and this caused a conflict with [zb-at.js at line 141](https://github.com/mozilla-iot/zigbee-adapter/blob/master/zb-at.js#L141) which is expecting a string (hex number).

I installed [Digi XTCU software](https://www.digi.com/products/xbee-rf-solutions/xctu-software/xctu) and assigned a random hex number to ID and that solved the issue.

Here is the information about the PAN ID (ID) setting in XTCU:
![xtcu_pan_id](https://user-images.githubusercontent.com/37613459/38171866-7b755ac6-3556-11e8-86e5-f6f48ccec1a3.PNG)

Please feel free to close this issue, I don't do it since I think zb-at.js needs to be modified to accept 0 as a valid value for ID.

Thanks!

**Comment by dhylands** [comment]
Thanks. I've opened https://github.com/mozilla-iot/zigbee-adapter/issues/23 to have it properly recognize a configured PAN ID of 0
