### ISSUE TITLE
properties binding from JSON

### ISSUE THREAD

**Issue by aragnac** [mozilla-iot/gateway#828]
Hi, 

I encounter an issue when trying to parse JSON data from my adapter.
During the init phase everything goes well, the properties are well read with the JSON file and well created (see 1. ) but after this, when the property.as_dict() function is called and then the prop.update(self.description) (which expects a dict, see 2.) I have no longer a dict here but a string (see 3. ) . Any idea ? 

Thanks,

Nicolas

NB : My adapter is based on the mock Adapter.

![parseerror](https://user-images.githubusercontent.com/12186566/38300263-a8f4b21e-37fc-11e8-99ff-89c20739b3c0.png)

**Comment by aragnac** [comment]
Here it is : https://github.com/aragnac/gcode_adapterV3

**Comment by mrstegeman** [comment]
@aragnac Right here: https://github.com/aragnac/gcode_adapterV3/blob/master/pkg/property.py#L23

You're setting `description` to a string.

**Comment by aragnac** [comment]
Oh ! you're right, what a mistake..

Thanks,

Nicolas
