### ISSUE TITLE
Symbol mangling changes from declaring c++11 string to just referring to it as string

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/gateway#837]
openzwave-shared looks for `_ZN9OpenZWave7Options6CreateERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_S8_` but libopenzwave.so has `_ZN9OpenZWave7Options6CreateERKSsS2_S2_` 

The first demangles to 
```c++
OpenZWave::Options::Create(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
```
but the second demangles to
```c++
OpenZWave::Options::Create(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
```

This persists after rebuilding the library. I'm going to try a few more approaches but any help in debugging this would be greatly appreciated.

**Comment by dhylands** [comment]
Which platform is this happening on?

It perhaps suggests that the library is being built with different options than openzwave-shared

**Comment by hobinjk** [comment]
This is on the RPi 3 flashed with the 0.3.1 image

**Comment by hobinjk** [comment]
I tried rebuilding the openzwave-shared library with node 7.10.1 and it had the same error

**Comment by dhylands** [comment]
So you're building on the RPi3? Just trying to understand what I need to do to try and reproduce.

**Comment by dhylands** [comment]
It looks like the toolchain on the RPi3 is version 6, and the cross compiler toolchain is 4.8.3

So I'm going to guess that some default which relates to default level of C++ being used has changed.

Looking at: https://gcc.gnu.org/gcc-6/changes.html it says that -std=gnu++14 is now the default instead of -std=gnu++98

So we probably need to pass in -std=gnu++98 when building on the RPi3.

**Comment by hobinjk** [comment]
Yeah, this is part of the 0.3.0/0.3.1 -> master OTA testing I'm doing. The general behavior is that if I rebuild node_modules on the raspberry pi it does not work.

**Comment by hobinjk** [comment]
Oh, that's old enough that it's before the c++ ABI changes that are breaking things, wow. There's a compatibility flag -D_GLIBCXX_USE_CXX11_ABI=0 or 1, not sure which one is correct

**Comment by hobinjk** [comment]
(https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html)

**Comment by dhylands** [comment]
Looks like we need to build with -D_GLIBCXX_USE_CXX11_ABI=0 when using gcc 6 to maintain compatibility with binaries built using an older version of g++
