### ISSUE TITLE
Network device not being detected

### ISSUE THREAD

**Issue by mcprakash** [mozilla-iot/gateway#851]
Hi 
 I am getting an error which reads as follows

`
pi@raspberrypi  ~/gateway   master  npm start

> things-gateway@0.3.0 start /home/pi/gateway
> webpack && node build/gateway.js

sh: 1: webpack: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! things-gateway@0.3.0 start: `webpack && node build/gateway.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the things-gateway@0.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-04-07T00_56_13_692Z-debug.log
`

The debug.log is attached for reference. 
[2018-04-07T00_56_13_692Z-debug.log](https://github.com/mozilla-iot/gateway/files/1885918/2018-04-07T00_56_13_692Z-debug.log)

Best
Chandra

**Comment by sogaani** [comment]
Hi

You need to install related packages.
Exec ```yarn``` or ```npm install``` with shell to install packages.

More infomations for manual Installation is [here](https://github.com/mozilla-iot/gateway#prerequisites-for-building).

**Comment by rzr** [comment]
Shouldn't it started by systemd ?

**Comment by mrstegeman** [comment]
@rzr It seems like he's doing a manual build and install, so no systemd.

**Comment by mcprakash** [comment]
Yes, the gateway is working now. After installing additional modules. 

But, I am unable to detect the devices. 

I recently attended an event by Microchip (Mozilla IoT workshop by Kathy Giori). A ATSAM25WD device was used to demonstrate the ping example to add the device and then a simple blink LED. I tried to replicate the same. The device is connecting to my local internet but the RPi Gateway is unable to detect the device. 

Please help. 

Best
Chandra
