### ISSUE TITLE
Removed web thing appears in Add Thing screen

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#855]
STR:
* Add a web thing by its URL
* Remove the thing
* Click add button

Expected:
* Thing doesn't appear in add thing screen unless it is broadcasting via mDNS or Bluetooth

Actual:
* Removed thing appears in Add Thing screen

**Comment by mrstegeman** [comment]
Moved: https://github.com/mozilla-iot/thing-url-adapter/issues/25
