### ISSUE TITLE
Misaligned color input

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#856]
![screen shot 2018-04-09 at 17 03 11](https://user-images.githubusercontent.com/552417/38508845-2716d50e-3c18-11e8-9913-f7fc3837f957.png)

**Comment by benfrancis** [comment]
@hobinjk This looks an un-intended consequence of https://github.com/mozilla-iot/gateway/commit/d644bdeda516d0a6231ded007f2b9eddc73adafb

input[type="color"] selector from rule.css is applying to the thing detail view.

**Comment by benfrancis** [comment]
I'm not sure why though, because it actually looks better in both places without that rule! What's it for?

**Comment by hobinjk** [comment]
That rule is to align it better with the baselign which was more obvious when I was experimenting with different color input dimensions. I'll remove it since it does look okay without it
