### ISSUE TITLE
Platform "linux" is incompatible with module fsevents@1.1.2

### ISSUE THREAD

**Issue by jobhh** [mozilla-iot/gateway#868]
When running "yarn" the following info is shown:
    gateway@orangepipc:~/gateway$ yarn
    yarn install v1.5.1
    [1/4] Resolving packages...
    [2/4] Fetching packages...
    _info fsevents@1.1.2: The platform "linux" is incompatible with this module.
    info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation._
    [3/4] Linking dependencies...
    [4/4] Building fresh packages...
    success Saved lockfile.
    Done in 772.83s.

I searched around and this seems to be quite a common issue with yarn. Since it's optional I assume this shouldn't be a big issue?

Platform: Orange Pi PC running armbian, Debian server – mainline kernel image.
Kernel: Linux orangepipc 4.14.18-sunxi #24 SMP Fri Feb 9 16:24:32 CET 2018 armv7l GNU/Linux
OS: Debian GNU/Linux 9.4 (stretch)

All apt-get things were installed as root
Openzwave was build and installed as root.
nvm was installed as the user "gateway".
yarn was installed with apt-get from the "https://dl.yarnpkg.com/debian/ stable main" repo.

**Comment by mrstegeman** [comment]
Nope, this doesn't cause any problems.
