### ISSUE TITLE
Error reporting mechanism for add-ons

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#877]
As an add-on developer I want to report an error to the end user when something goes wrong

**Comment by nithyanantham** [comment]
I think we can link issue #889 as part of this story

**Comment by benfrancis** [comment]
Regarding UI: I'd suggest that any error which results from a user action (i.e. they are likely to be looking at the screen) and can be translated into something meaningful to the user should be displayed as a "toast" at the bottom of the screen.
