### ISSUE TITLE
login user name should not be case sensitive

### ISSUE THREAD

**Issue by nithyanantham** [mozilla-iot/gateway#888]
unable to login with different case user name

**Comment by nithyanantham** [comment]
I do not see any public domain user name with case sensitivity except Unix login.

If this behaviour is intended, I would expect warning message during user sign up process.

**Comment by dhylands** [comment]
I believe that the login is an email address and email addresses are not case sensitive. So we should probably convert the email to lower case and use the lower case version for everything internal in the program.
