### ISSUE TITLE
Release 0.4.0 Availability Through Settings > Updates

### ISSUE THREAD

**Issue by rei-vilo** [mozilla-iot/gateway#898]
When the release 0.4.0 is going to be available through **Settings > Updates**?

<img width="1268" alt="capture 2018-04-17 a 17 03 25" src="https://user-images.githubusercontent.com/951776/38878524-710e5d7c-4261-11e8-99d7-9610718bbc1a.png">

**Comment by hobinjk** [comment]
I'm currently tracking the issue #899 which was uncovered during my last round of OTA testing since it's an annoyingly subtle race. It will be available once that issue is fixed.

**Comment by rei-vilo** [comment]
Thanks!

**Comment by hobinjk** [comment]
The release should now be available

**Comment by rei-vilo** [comment]
Indeed, thanks!
