### ISSUE TITLE
Custom Thing UI

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#910]
As a thing developer I want to provide a custom web interface for my webthing so that I can provide a better user experience than the automatically generated default UI

**Comment by benfrancis** [comment]
UI specification [added](https://docs.google.com/presentation/d/1rMeg6hep8JQflqwbiNIbhSoK9StCeVZ2npphmQHKda4/edit#slide=id.g3b5aa6b68a_1_58).

UI mockup below:
![custom_web_interface](https://user-images.githubusercontent.com/552417/40546749-f23a6196-6027-11e8-860a-cec98116a836.png)

**Comment by mrstegeman** [comment]
@flatsiedatsie 

1. Add-ons can already have continuously running code. For example, the HomeKit adapter is constantly doing Bluetooth scans and communication in the background.
2. Add-ons can add a custom UI. If they run a web server, they can serve up whatever they want. The UI can be added to the thing by setting its `uiHref` property.
3. I assume you mean custom components for the stock UI. This would definitely be useful.

**Comment by benfrancis** [comment]
> Add custom UX (including JS) for creating thing displays. For example, Homegenie allows for gorgeous custom UX elements to be included.

I filed https://github.com/mozilla-iot/gateway/issues/1505 to discuss this.
