### ISSUE TITLE
Show thing status on floorplan

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#912]
As a user I would like to see the status of things in the floorplan view so that I can get an at-a-glance overview of the status of all my things

**Comment by benfrancis** [comment]
I'd ideally like to be able to show the current status summary of things on the floorplan, as we currently do in the Things view. The icons are smaller on the floorplan (and may be scaled down very small on mobile devices), so not as much information can be included, but I was thinking something along the lines of the mockup below:

![thing_status_on_floorplan](https://user-images.githubusercontent.com/552417/42183388-8e4d4452-7e39-11e8-804f-7875a05ed21d.png)

I can easily imagine how we could have two separate icons for on state and off state for each of these device types, but if we want to get any more complex than that (e.g. dynamically showing numbers, colors etc.) then the problem I see is that currently these thing icons are included in the SVG as a static image source.

@hobinjk @mrstegeman Can you imagine a way for us to dynamically generate these icons and update them in realtime? We could feasibly have .svg URLs for things and dynamically generate the SVG content based on current property values, but how would we update the SVG when the properties change?

If we generated them with HTML like is done in the Things view, I suspect they will be difficult to position on the SVG floorplan, in which currently all the icons scale with the SVG background.

What would be really nice would be if you could also turn the devices on and off directly in the floorplan view, as well as being able to navigate to the detail view, but I just don't think there's room for two touch targets as in the things screen. We could potentially explore other interaction designs like long-pressing the thing to expand out a detail view inside the floorplan view, where a simple click carries out the on/off action. And potentially modify the things view  as well to make it more consistent. We could also make the whole floorplan zoomable with pinch to zoom to zoom into finer details.

I wanted to get a sense of what you guys think is feasible, mostly with regards to showing property state in the thing icons.

**Comment by hobinjk** [comment]
Dynamically modifying SVG is a possibility although some of the mechanisms we'd have to use to get certain features (i.e. dynamically changing the color) would be a bit clunky.

However, I think the simplest way of doing this is to switch from the subtly-different floorplan icon view to the html view. We could then scale down the HTML view using a CSS transform. This would have the same nice scale-invariant properties of SVG while not being (as much of) a pain to manipulate.

**Comment by benfrancis** [comment]
It sounds like it's worth prototyping switching from SVG icons to HTML UI components, to see how easy it is to position them on the floorplan and how well they scale. @hobinjk Would you be interested in trying that? If it doesn't look good, the backup plan could be to try to dynamically modify the SVG.

I don't think directly using the existing UI components will work, because in many cases they're likely to be too small to fit 2-3 touch targets on a single icon. We probably need to create a compact variant of the components as in the mockup.

Eventually it would be nice if they could expand out inside the floorplan view when you tap them so you don't have to navigate to the separate detail view to interact with them, but just being able to display some basic status is a good starting point for making them more useful.

**Comment by hobinjk** [comment]
This might be difficult to get into 0.5 but I hope to have an initial implementation done by the end of tomorrow

**Comment by benfrancis** [comment]
Great, thank you. Let's see how it goes.
