### ISSUE TITLE
Expose multiple types of rule effects

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/gateway#913]
As a user I want fine-grained control over the side effects of rules. When I create a rule I don't want to be limited to rules which reset to their initial state after the trigger is deactivated.

The current exposed effects are all of type PulseEffect which means that after their deactivation they reset to the initial state. The engine already has support for SetEffect which is just a set and forget of the property. It would also be interesting to support a toggle for boolean proeprties which would allow implementing #694.

**Comment by hobinjk** [comment]
Mockups:
![base](https://user-images.githubusercontent.com/2776089/40550327-d033f9a6-6007-11e8-891a-8540a6d1a20e.png)
![set-pulse detail](https://user-images.githubusercontent.com/2776089/40550329-d098395c-6007-11e8-8d2b-4b2057b75ea8.png)

**Comment by benfrancis** [comment]
What do the symbols in the circles mean?

**Comment by hobinjk** [comment]
In this one the `_|‾` is meant to correspond to "set" and `_|‾|_` in the circle would correspond to "pulse". The /\ is part of the and/or (`/\`/`\/`) selection and could be replaced with `&`/`||`

For most users I think the symbols will end up meaning very little other than "you can click this circle to change the behavior" but advice on clearer iconography would be appreciated.

**Comment by hobinjk** [comment]
New thought on this: a "preview rule" button would go a long way to making this and #773 more logical. Calling the blob in the center with the and/or info a "join", the concept I have in mind would highlight each trigger-join connection one-by-one, highlighting the join-effect connections if the rule is active. To call attention to the difference between set/pulse it would also independently highlight the endcap or the effect block (this might not be clear enough)

**Comment by twobraids** [comment]
Instead of "pulse/set" visually situated between the predicate and the thing, consider allowing the user to select "if" or "while" as a prefix left of the predicate.  That reads from left to right like a sentence that describes the behavioral difference between the two cases.

**Comment by twobraids** [comment]
I just ran those two sentences by a disinterested third party.  The word "pulse" caused confusion.  Confusion was resolved with these changes:
    in the first sentence, s/pulse/set/
    in the second sentence s/pulse/temporarily set/

**Comment by hobinjk** [comment]
Here's what I'm suggesting: ![text-entry-in-context](https://user-images.githubusercontent.com/2776089/40803196-fd5667ec-64e5-11e8-80c4-12617f92d1fa.png)

**Comment by hobinjk** [comment]
The selector should actually be on "temporarily set", fixed:
![text-entry-in-context](https://user-images.githubusercontent.com/2776089/40991127-cc0b192e-68c0-11e8-99f6-2ef9624598c9.png)

**Comment by hobinjk** [comment]
Fixed by #1091
