### ISSUE TITLE
[Device] Can't connect to Paul Neuhaus Q Series

### ISSUE THREAD

**Issue by Vijabei** [mozilla-iot/gateway#921]
Hi,

I tried to connect to a color temp adjustable Paul Neuheus lamp (Q Series). The remote control will be recognized, but the lamp itself not.

I disconected all existing learned connections and started the "New Device" search withing the gateway. I hold the RasPi close to the lamps antenna as described in the lamps manual.

I updated to 0.4.0 but the ZigBee AddOn update doesn't work.

Any hints you can give me? Anything I can do from the console?

Thanks,
Vija

**Comment by mrstegeman** [comment]
Moved: https://github.com/mozilla-iot/zigbee-adapter/issues/24
