### ISSUE TITLE
Cannot connect to gateway.local or ip address

### ISSUE THREAD

**Issue by TonyCanning** [mozilla-iot/gateway#928]
Hi all,
I've followed this:
https://hacks.mozilla.org/2018/02/how-to-build-your-own-private-smart-home-with-a-raspberry-pi-and-mozillas-things-gateway/
and gotten to 
https://hacks.mozilla.org/files/2018/02/wifi_connecting.png
![image](https://user-images.githubusercontent.com/10809745/39128290-556708ce-46ff-11e8-9e4a-d938a1a7ab60.png)

when I navigate to gateway.local I get:
![image](https://user-images.githubusercontent.com/10809745/39128350-767b2018-46ff-11e8-8370-9cd7b76113f3.png)

So I put the pi on screen and checked for the ip address and tried connecting to it.
Same as above.

I haven't done anything other than the instructions (haven't changed gateway name or anything).

Anyone help?

**Comment by rzr** [comment]
I think I faced that issue couple of weeks ago, but I've been reported it has been fixed on maser

So is this reproductible on master  ? or 0.4.0 ? 

you can try by adding :8080 port

**Comment by mrstegeman** [comment]
Fixed by #1020
