### ISSUE TITLE
Smart Assistant - Set Level

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#954]
As a user I want to set the level of dimmable lights and level switches with natural language commands

- Set (the) \<device name\> to \<number\> percent
- Dim (the) \<device name\>
- Brighten (the) \<device name\>
- Dim the lights
- Brighten the lights
- Dim (the) \<device name\> by \<number\> percent
- Brighten (the) \<device name\> by \<number\> percent
- Dim the lights by \<number\> percent
- Brighten the lights by \<number\> percent

**Comment by mrstegeman** [comment]
Back-end done in #1185
