### ISSUE TITLE
Removing a thing from within the splat leaves the thing name at the top of the screen

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#961]
If you click on the splat for a device that has it, and then right click and remove the device, it leaves the name of the device at the top of the screen. It also says to Click + but no + is visible. And the top left is the back arrow rather than the menu,

**Comment by dhylands** [comment]
![screenshot from 2018-04-27 17-04-03](https://user-images.githubusercontent.com/127500/39389427-2c23b9ee-4a3d-11e8-91a8-4d68ddb9e8ff.png)

**Comment by dhylands** [comment]
This URL is also still on the removed thing.

**Comment by benfrancis** [comment]
Ah, I don't think it was intended that you can remove a thing from the thing detail view in this way, this code is just carried over from the things view. With the workaround in #966 this can probably stay as it is though.
