### ISSUE TITLE
Previously scanned Things are getting cached 

### ISSUE THREAD

**Issue by nithyanantham** [mozilla-iot/gateway#978]
Gateway Build : 0.4.0
Raspberry 2

I am using nodeMCU and i have flashed the same device multiple time with different things and different properties. During esp8266 web things scan it is still showing previously discovered items that is no longer exist in nodeMCU.

In this below screen shot. Led and Built-in Led both are no longer exist in current things endpoint and also for switch 1 and switch 2 is showing old values.

Expected Values : Gateway should discover only 4 things (switch1, switch2, switch3, switch4) with type as on/off switch.

![image](https://user-images.githubusercontent.com/5294240/39540537-89c7a03e-4e60-11e8-9279-f53c3c9de3e8.png)

**Comment by mrstegeman** [comment]
The issue with the thing description changing is covered by #1134.

There is a secondary issue, which is that things no longer present on the network are being displayed. That is covered by: mozilla-iot/thing-url-adapter#51
