### ISSUE TITLE
Features - standardization and native support for shutter/blinds devices

### ISSUE THREAD

**Issue by jarod68** [mozilla-iot/gateway#995]
This more a feature request than an issue, but would be great to natively support and standardize the shutters and/or blinds devices.
For a shutter we have the position and for the blinds we have in addition the slat angle in % (this could be in degres or radian too, but conversion would be easy)

Basically, the properties are:
- position % (mandatory)
- slat angle % (optional)

and the actions:
- UP, (optional)
- DOWN, (optional)
- STOP, (optional)
- STEP_UP, (optional)
- STEP_DOWN (optional)

As events : 
- bottom reached (optional)
- top reached (optional)

What do you think ?

**Comment by mrstegeman** [comment]
Moved: https://github.com/mozilla-iot/wot/issues/96
