### ISSUE TITLE
Addons list not loading due to SSL error

### ISSUE THREAD

**Issue by beniwtv** [mozilla-iot/gateway#999]
Hi,

Today I installed the latest IOT gateway as described on the README, but the gateway is unable to list addons due to an SSL error. When I manually visit the URL in Firefox I get:

![screenshot from 2018-05-11 16-32-08](https://user-images.githubusercontent.com/1401072/39929708-0fb2fee4-5539-11e8-8237-7407ad7dad31.png)

Seems something is wrongly configured.

**Comment by mrstegeman** [comment]
The SSL error is because you're using the staging server, instead of api.mozilla-iot.org.

**Comment by beniwtv** [comment]
Ah, I see that the release file has a different URL. It would be good perhaps to point this out in the README, to avoid confusions like this.

It does work now.
